Repository multiversx/mx-chain-go, pull requests merged in 2019-06, with the labels that each got.

#224 Recreate trie and request shard headers missing
  process/block/metablock.go
  process/block/shardblock.go
  process/sync/baseSync.go
  process/sync/shardblock_test.go
Labels: bug

#222 Bugs/en 2555 header resolvers storer nonce
  README.md
  dataRetriever/errors.go
  dataRetriever/factory/metachain/resolversContainerFactory.go
  dataRetriever/factory/metachain/resolversContainerFactory_test.go
  dataRetriever/factory/shard/resolversContainerFactory.go
  dataRetriever/resolvers/headerResolver.go
  dataRetriever/resolvers/headerResolverBase.go
  dataRetriever/resolvers/headerResolverBase_test.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/shardHeaderResolver.go
  dataRetriever/resolvers/shardHeaderResolver_test.go
  integrationTests/multiShard/block/testInitializer.go
  integrationTests/multiShard/metablock/testInitializer.go
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx_test.go
  integrationTests/multiShard/transaction/testInitializer.go
  integrationTests/singleShard/block/interceptedRequestHdr_test.go
  integrationTests/singleShard/block/interceptedRequestTxBlockBody_test.go
  integrationTests/singleShard/block/testInitializer.go
  integrationTests/singleShard/transaction/interceptedResolvedTx_test.go
  integrationTests/singleShard/transaction/testInitializer.go
  ntp/syncTime.go
Labels: bug, enhancement

#229 Bugs/en 2588 fix direct sender
  integrationTests/singleShard/block/interceptedRequestHdr_test.go
  p2p/libp2p/directSender.go
  p2p/libp2p/netMessenger.go
  p2p/p2p.go
Labels: bug

#230 changed the path of the .json files in config folder
  cmd/node/config/genesis.json
  cmd/node/config/nodesSetup.json
  cmd/node/main.go
Labels: enhancement

#234 core: fix filename trimming
  core/trimmers.go
  core/trimmers_test.go
Labels: bug

#228 Feat/en 2640 get values from vm
  api/api.go
  api/block/routes.go
  api/block/routes_test.go
  api/getValues/routes.go
  api/getValues/routes_test.go
  api/mock/facade.go
  api/transaction/routes_test.go
  cmd/node/main.go
  facade/elrondNodeFacade.go
  facade/elrondNodeFacade_test.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/mock/externalResolverStub.go
  integrationTests/mock/oneSCExecutorMockVM.go
  integrationTests/vm/mockVM/vmGet_test.go
  integrationTests/vm/testInitializer.go
  node/external/entities.go
  node/external/errors.go
  node/external/externalResolver.go
  node/external/externalResolver_test.go
  node/external/interface.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  node/external/recentBlock.go
  node/mock/proposerResolverStub.go
  node/mock/scDataGetterStub.go
  process/errors.go
  process/smartContract/scDataGetter.go
  process/smartContract/scDataGetter_test.go
Labels: enhancement

#226 Feat/en 2595 bootstrap from a given round
  cmd/node/main.go
  dataRetriever/requestHandlers/requestHandler.go
  node/defineOptions.go
  node/node.go
  process/block/metablock.go
  process/block/shardblock.go
  process/errors.go
  process/sync/baseSync.go
  process/sync/errors.go
  process/sync/export_test.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: enhancement
