Repository multiversx/mx-chain-go, pull requests merged in 2019-12, with the labels that each got.

#638 EN-4232 : refactor integration tests to work with GasPrice greater tha…
  go.sum
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/multiShard/block/executingMiniblocks_test.go
  integrationTests/multiShard/smartContract/executingSCCalls_test.go
  integrationTests/multiShard/smartContract/testInitializer.go
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx_test.go
  integrationTests/multiShard/transaction/sendBulkTransactions_test.go
  integrationTests/singleShard/block/executingMiniblocksSc_test.go
  integrationTests/testGameHelperFunctions.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/systemVM/systemVm_test.go
  node/nodeTesting.go
  process/block/preprocess/rewardsHandler.go
  process/economics/testEconomicsData.go
  process/smartContract/process.go
Labels: enhancement

#737 Fix termui app start no cursor on connection failed
  cmd/termui/main.go
Labels: bug

#736 EN-5231 : fix logger problem
  api/logs/logSender.go
Labels: bug

#700 En 5028 fix network flooding
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bn/subroundEndRound.go
  dataRetriever/errors.go
  dataRetriever/interface.go
  dataRetriever/mock/requestedItemsHandlerStub.go
  dataRetriever/requestHandlers/requestHandler.go
  dataRetriever/requestHandlers/requestHandler_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blackListHandleStub.go
  integrationTests/mock/requestedItemsHandlerStub.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/defineOptions.go
  node/defineOptions_test.go
  node/errors.go
  node/mock/requestedItemsHandlerStub.go
  node/node.go
  process/block/baseProcess.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/common.go
  process/interceptors/processor/hdrInterceptorProcessor.go
  process/interceptors/processor/hdrInterceptorProcessor_test.go
  process/interface.go
  process/mock/blackListHandlerStub.go
  process/mock/requestedItemsHandlerStub.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/baseSync.go
  process/sync/metaForkDetector_test.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardForkDetector_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
  storage/timecache/timeCache.go
  storage/timecache/timeCache_test.go
Labels: enhancement

#740 En 5237 check if nil reflect
  core/check/ifNil.go
  core/check/ifNil_test.go
Labels: enhancement

#751 Fix validator statistics root hash
  cmd/node/factory/structs.go
  core/genesis/genesisBlockCreator.go
  core/genesis/genesisBlockCreator_test.go
  integrationTests/testInitializer.go
  process/block/baseProcess.go
  process/sync/baseSync.go
Labels: bug, enhancement

#757 En 5276 added genesis time check in fork detector
  cmd/node/factory/structs.go
  integrationTests/consensus/testInitializer.go
  integrationTests/testSyncNode.go
  process/block/metablock.go
  process/block/shardblock.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/baseSync.go
  process/sync/errors.go
  process/sync/metaForkDetector.go
  process/sync/metaForkDetector_test.go
  process/sync/metablock_test.go
  process/sync/shardForkDetector.go
  process/sync/shardForkDetector_test.go
  process/sync/shardblock_test.go
Labels: bug, enhancement

#716 network sharding fixes
  consensus/interface.go
  consensus/mock/networkShardingCollectorStub.go
  consensus/spos/worker_test.go
  integrationTests/mock/networkShardingCollectorMock.go
  node/defineOptions.go
  node/heartbeat/interface.go
  node/heartbeat/messageProcessor.go
  node/heartbeat/messageProcessor_test.go
  node/interface.go
  node/mock/networkShardingCollectorStub.go
  sharding/networkSharding/peerShardMapper.go
  sharding/networkSharding/peerShardMapper_test.go
Labels: bug, enhancement

#735 Fix network sharding integration test
  integrationTests/p2p/networkSharding/networkSharding_test.go
Labels: bug

#766 Rc bon fix probable highest nonce
  consensus/spos/errors.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  process/sync/baseForkDetector.go
Labels: enhancement

#756 Edgecase when nothing proposed in the epoch
  epochStart/shardchain/trigger.go
  integrationTests/multiShard/endOfEpoch/executingEpochChange_test.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/errors.go
Labels: bug, enhancement

#749 Correct sync on metachain to resolve block body
  process/block/baseProcess_test.go
  process/block/metablock.go
  process/peer/process.go
  process/peer/process_test.go
  process/sync/baseSync.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
Labels: bug

#772 Rc bon fix probable highest nonce
  consensus/spos/errors.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  process/sync/baseForkDetector.go
Labels: enhancement

#583 En 4584 save metrics in storage
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/factory/structsStatusHandlers.go
  cmd/node/main.go
  config/config.go
  consensus/mock/blockProcessorMock.go
  core/statistics/machine/netStatistics.go
  dataRetriever/interface.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/storageBootstrapperMock.go
  integrationTests/testInitializer.go
  node/mock/blockProcessorStub.go
  process/block/baseProcess.go
  process/block/bootstrapStorage/bootstrapStorer.go
  process/block/bootstrapStorage/bootstrapStorer_test.go
  process/block/displayBlock.go
  process/block/displayBlock_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/metrics.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/interface.go
  process/mock/blockProcessorMock.go
  process/mock/storageBootstrapperMock.go
  process/sync/baseSync.go
  process/sync/loadPersistentMetrics.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
  statusHandler/mock/appStatusHandlerStub.go
  statusHandler/mock/marshalizerStub.go
  statusHandler/mock/storerStub.go
  statusHandler/mock/uint64ByteSliceConverterMock.go
  statusHandler/persister/common.go
  statusHandler/persister/persistentHandler.go
  statusHandler/persister/persistentHandler_test.go
  storage/storageUnit/nilStorer.go
Labels: enhancement

#776 fixed heartbeat integration test
  integrationTests/node/heartbeat_test.go
Labels: bug

#762 En 5272 fix computation of fee txs when gas limit is reached
  integrationTests/multiShard/block/executingRewardMiniblocks_test.go
  integrationTests/testProcessorNode.go
  process/block/preprocess/transactions.go
Labels: bug

#761 EN-5296 : add check for prev rand seed at consensus level
  cmd/node/factory/interface.go
  cmd/node/factory/structs.go
  cmd/node/main.go
  consensus/mock/headerSigVerifierStub.go
  consensus/spos/errors.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/headerSigVerifierStub.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/testSyncNode.go
  node/defineOptions.go
  node/defineOptions_test.go
  node/errors.go
  node/mock/headerSigVerifierStub.go
  node/node.go
  process/block/interceptedBlocks/argInterceptedBlockHeader.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/errors.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/metachain/interceptorsContainerFactory_test.go
  process/factory/shard/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory_test.go
  process/headerCheck/headerSignatureVerify.go
  process/interceptors/factory/argInterceptedDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory_test.go
  process/interceptors/factory/interceptedShardHeaderDataFactory.go
  process/interceptors/factory/interceptedShardHeaderDataFactory_test.go
  process/interface.go
  process/mock/headerSigVerifierStub.go
Labels: enhancement

#769 En 5129 anti flooding component
  consensus/mock/sposWorkerMock.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  dataRetriever/interface.go
  dataRetriever/mock/hashSliceResolverStub.go
  dataRetriever/mock/headerResolverStub.go
  dataRetriever/mock/resolverStub.go
  dataRetriever/resolvers/genericBlockBodyResolver.go
  dataRetriever/resolvers/genericBlockBodyResolver_test.go
  dataRetriever/resolvers/headerResolver.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/transactionResolver.go
  dataRetriever/resolvers/transactionResolver_test.go
  integrationTests/mock/headerResolverMock.go
  integrationTests/mock/miniBlocksResolverMock.go
  integrationTests/p2p/antiflood/antiflooding_test.go
  integrationTests/p2p/antiflood/messageProcessor.go
  integrationTests/p2p/peerDiscovery/messageProcessor.go
  integrationTests/p2p/pubsub/messageProcessor.go
  integrationTests/p2p/pubsub/peerReceivingMessages_test.go
  integrationTests/testInitializer.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/node_test.go
  p2p/example/libp2p/internalBroadcastSpeedMeasure/main.go
  p2p/libp2p/directSender.go
  p2p/libp2p/directSender_test.go
  p2p/libp2p/export_test.go
  p2p/libp2p/issues_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/memp2p/memp2p.go
  p2p/mock/messageProcessorStub.go
  p2p/mock/mockMessageProcessor.go
  p2p/mock/streamMock.go
  p2p/p2p.go
  process/errors.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/singleDataInterceptor_test.go
  process/interface.go
  process/mock/headerResolverMock.go
  process/mock/interceptorStub.go
  process/mock/miniBlocksResolverMock.go
  process/mock/resolverStub.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
  process/throttle/antiflood/quotaFloodPreventer.go
  process/throttle/antiflood/quotaFloodPreventer_test.go
Labels: enhancement

#748 En 4504 db pruning
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  core/constants.go
  dataRetriever/interface.go
  integrationTests/mock/DbMock.go
  integrationTests/mock/countingDB.go
  process/block/metrics.go
  process/block/shardblock.go
  statusHandler/presenter/blockInfoGetters.go
  statusHandler/view/interface.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
  storage/badgerdb/badgerdb.go
  storage/boltdb/boltdb.go
  storage/errors.go
  storage/factory/common.go
  storage/factory/persisterFactory.go
  storage/factory/pruningStorerFactory.go
  storage/interface.go
  storage/leveldb/leveldb.go
  storage/leveldb/leveldbSerial.go
  storage/memorydb/lruMemoryDB.go
  storage/memorydb/memorydb.go
  storage/mock/epochStartHandler.go
  storage/mock/persisterFactoryStub.go
  storage/pruning/export_test.go
  storage/pruning/fileHandling.go
  storage/pruning/interface.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorerArgs.go
  storage/pruning/pruningStorer_test.go
Labels: enhancement

#781 En 5315 prealloc process
  core/sliceUtil/sliceUtil.go
  data/common.go
  data/smartContractResult/smartContractResult.go
  data/transaction/transaction.go
  process/block/baseProcess.go
  process/block/bootstrapStorage/bootstrapStorer.go
  process/block/displayBlock.go
  process/block/displayMetaBlock.go
  process/block/metablock.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/intermediateResults.go
  process/block/preprocess/miniBlocksCompaction.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardsHandler.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/common.go
  process/interceptors/multiDataInterceptor.go
  process/peer/process.go
  process/scToProtocol/stakingToPeer.go
  process/smartContract/atArgumentParser.go
  process/smartContract/process.go
  process/sync/baseForkDetector.go
  process/sync/shardblock.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
Labels: enhancement

#791 Extra test, bad contract with stack overflow.
  integrationTests/vm/arwen/badcontracts_test.go
  integrationTests/vm/arwen/testdata/bad/bad.c
  integrationTests/vm/arwen/testdata/bad/bad.export
  integrationTests/vm/arwen/testdata/bad/bad.wasm
Labels: bug

#789 rc-fix-edge-case-in-bootstrap-from-storage-and-sync-state
  consensus/spos/bls/blsWorker.go
  consensus/spos/bn/bnWorker.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  process/block/baseProcess.go
  process/block/shardblock.go
  process/sync/baseSync.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
Labels: bug

#805 Fix gas computation and tx fee accumulation
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/gasComputation.go
  process/block/preprocess/gasConsumption_test.go
  process/block/preprocess/intermediateResults.go
  process/block/preprocess/miniBlocksCompaction.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardsHandler.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/factory/metachain/preProcessorsContainerFactory.go
  process/factory/shard/preProcessorsContainerFactory.go
  process/mock/gasHandlerMock.go
  process/smartContract/process.go
Labels: bug

#802 Move ArgumentParser into vmcommon
  cmd/node/factory/structs.go
  core/genesis/genesisBlockCreator.go
  go.mod
  integrationTests/testProcessorNode.go
  integrationTests/vm/testInitializer.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/block/interceptedBlocks/interceptedTxBlock_test.go
  process/errors.go
  process/headerCheck/headerSignatureVerify.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory_test.go
  process/interceptors/factory/interceptedRewardTxDataFactory.go
  process/interceptors/factory/interceptedRewardTxDataFactory_test.go
  process/interceptors/factory/interceptedShardHeaderDataFactory.go
  process/interceptors/factory/interceptedShardHeaderDataFactory_test.go
  process/interceptors/factory/interceptedTxBlockBodyDataFactory.go
  process/interceptors/factory/interceptedTxBlockBodyDataFactory_test.go
  process/interceptors/factory/interceptedTxDataFactory.go
  process/interceptors/factory/interceptedTxDataFactory_test.go
  process/interceptors/factory/interceptedUnsignedTxDataFactory.go
  process/interceptors/factory/interceptedUnsignedTxDataFactory_test.go
  process/interceptors/processor/hdrInterceptorProcessor.go
  process/interceptors/processor/hdrInterceptorProcessor_test.go
  process/interceptors/processor/txBodyInterceptorProcessor.go
  process/interceptors/processor/txBodyInterceptorProcessor_test.go
  process/interceptors/processor/txInterceptorProcessor.go
  process/interceptors/processor/txInterceptorProcessor_test.go
  process/smartContract/atArgumentParser.go
  process/smartContract/atArgumentParser_test.go
Labels: enhancement

#812 En 5348 validators statistics api route
  api/api.go
  api/mock/facade.go
  api/validator/routes.go
  api/validator/routes_test.go
  cmd/node/factory/structs.go
  cmd/node/main.go
  data/state/peerAccount.go
  facade/elrondNodeFacade.go
  facade/interface.go
  facade/mock/nodeMock.go
  integrationTests/mock/peerProcessorMock.go
  node/defineOptions.go
  node/defineOptions_test.go
  node/errors.go
  node/mock/peerProcessorMock.go
  node/node.go
  process/interface.go
  process/mock/peerProcessorMock.go
  process/peer/process.go
Labels: enhancement

#822 More linter fixes 2019.12.16
  consensus/spos/export_test.go
  consensus/spos/roundConsensus_test.go
  core/indexer/elasticsearch_test.go
  integrationTests/longTests/storage_test.go
  integrationTests/testStorage.go
  node/heartbeat/monitor.go
  p2p/libp2p/directSender.go
  storage/leveldb/leveldbSerial.go
Labels: bug

#827 Chain ID directory for databases
  cmd/node/main.go
Labels: enhancement

#828 Receipts optimization
  cmd/node/factory/structs.go
  consensus/mock/blockProcessorMock.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/commonSubround/subroundBlock.go
  consensus/spos/commonSubround/subroundBlock_test.go
  data/block/block.go
  data/block/metaBlock.go
  data/interface.go
  integrationTests/consensus/consensus_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/intermediateTransactionHandlerMock.go
  integrationTests/mock/transactionCoordinatorMock.go
  integrationTests/multiShard/block/executingMiniblocks_test.go
  integrationTests/testProcessorNode.go
  node/mock/blockProcessorStub.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/postprocess/basePostProcess.go
  process/block/postprocess/intermediateResults.go
  process/block/postprocess/oneMBPostProcessor.go
  process/block/postprocess/oneMBPostProcessor_test.go
  process/block/preprocess/rewardsHandler.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/errors.go
  process/interface.go
  process/mock/blockProcessorMock.go
  process/mock/headerHandlerStub.go
  process/mock/intermediateTransactionHandlerMock.go
  process/mock/transactionCoordinatorMock.go
Labels: enhancement

#819 Fix mem p2p
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  p2p/memp2p/export_test.go
  p2p/memp2p/memp2p_test.go
  p2p/memp2p/message.go
  p2p/memp2p/messenger.go
  p2p/memp2p/messenger_test.go
  p2p/memp2p/network.go
Labels: bug, enhancement

#722 En 5122 p2p connection authentication
  marshal/testing.go
  p2p/data/authMessage.go
  p2p/data/authMessage_test.go
  p2p/data/capnp/authMessage.capnp
  p2p/data/capnp/authMessage.capnp.go
  p2p/data/proto/authMessage.pb.go
  p2p/data/proto/authMessage.proto
  p2p/errors.go
  p2p/libp2p/export_test.go
  p2p/libp2p/identityProvider.go
  p2p/libp2p/identityProvider_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/options.go
  p2p/libp2p/options_test.go
  p2p/mock/marshalizerStub.go
  p2p/mock/networkShardingCollectorStub.go
  p2p/mock/signerVerifierStub.go
  p2p/p2p.go
Labels: enhancement

#795 EN-5328: path naming component
  cmd/node/factory/structs.go
  cmd/node/main.go
  core/constants.go
  core/converters.go
  storage/errors.go
  storage/factory/common.go
  storage/factory/pruningStorerFactory.go
  storage/interface.go
  storage/mock/pathManagerStub.go
  storage/mock/shardCoordinatorMock.go
  storage/pathmanager/pathManager.go
  storage/pathmanager/pathManager_test.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorerArgs.go
  storage/pruning/pruningStorer_test.go
Labels: enhancement

#833 fix termui bug when displaying num of shard headers processed
  process/block/displayMetaBlock.go
Labels: bug

#859 fix directories order for databases
  cmd/node/main.go
Labels: bug

#861 EN-5528 : fix bug with bootstrap from storage infinite loop
  core/statistics/softwareVersion/softwareVersion.go
  process/block/baseProcess.go
  process/block/bootstrapStorage/bootstrapStorer.go
  process/block/poolsCleaner/txPoolsCleaner_test.go
  process/sync/errors.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
Labels: bug

#899 removed ConsensusMessage.Timestamp unused field
  consensus/message.go
  consensus/message_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/bn/subroundBitmap.go
  consensus/spos/bn/subroundBitmap_test.go
  consensus/spos/bn/subroundCommitment.go
  consensus/spos/bn/subroundCommitmentHash.go
  consensus/spos/bn/subroundCommitmentHash_test.go
  consensus/spos/bn/subroundCommitment_test.go
  consensus/spos/bn/subroundSignature.go
  consensus/spos/bn/subroundSignature_test.go
  consensus/spos/commonSubround/subroundBlock.go
  consensus/spos/commonSubround/subroundBlock_test.go
  consensus/spos/worker_test.go
Labels: enhancement

#874 EN-5534: fix gosec issues
  api/api.go
  cmd/keygenerator/main.go
  cmd/node/config/server.toml
  cmd/node/factory/structsStatusHandlers.go
  cmd/node/main.go
  config/config.go
  consensus/mock/hasherMock.go
  core/constants.go
  core/file.go
  core/indexer/elasticsearch.go
  core/interface.go
  core/mock/hasherMock.go
  core/statistics/softwareVersion/softwareVersion.go
  core/statistics/softwareVersion/softwareVersion_test.go
  crypto/mock/hasherMock.go
  crypto/mock/hasherSpongeMock.go
  data/mock/addressMock.go
  data/mock/hasherMock.go
  data/mock/hasherMock127.go
  data/mock/keccakMock.go
  dataRetriever/mock/hasherMock.go
  display/tablePrinter.go
  epochStart/mock/hasherMock.go
  facade/elrondNodeFacade.go
  go.mod
  go.sum
  hashing/blake2b/blake2b.go
  hashing/fnv/fnv.go
  hashing/keccak/keccak.go
  hashing/sha256/sha256.go
  integrationTests/mock/countingDB.go
  integrationTests/mock/hasherSpongeMock.go
  integrationTests/vm/arwen/utils.go
  node/mock/hasherFake.go
  node/mock/hasherMock.go
  node/node_test.go
  process/block/postprocess/basePostProcess.go
  process/mock/hasherMock.go
  sharding/mock/hasherMock.go
  statusHandler/export_test.go
  statusHandler/prometheusHandler.go
  statusHandler/prometheusHandler_test.go
  storage/pruning/fileHandling.go
Labels: enhancement

#867 fixed a bug that caused delayed recovery to a shard when a forkdetect…
  consensus/spos/worker.go
  consensus/spos/worker_test.go
Labels: bug

#825 En 5376 antiflooding metrics
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  core/errors.go
  core/p2pConstants.go
  integrationTests/p2p/antiflood/antiflooding_test.go
  integrationTests/p2p/antiflood/nilQuotaStatusHandler.go
  p2p/antiflood/p2pAntiflood.go
  p2p/antiflood/p2pAntiflood_test.go
  p2p/mock/floodPreventerStub.go
  p2p/p2p.go
  process/interface.go
  process/mock/quotaStatusHandlerStub.go
  process/throttle/antiflood/export_test.go
  process/throttle/antiflood/interface.go
  process/throttle/antiflood/quotaFloodPreventer.go
  process/throttle/antiflood/quotaFloodPreventer_test.go
  statusHandler/errors.go
  statusHandler/mock/appStatusHandlerMock.go
  statusHandler/p2pQuota/export_test.go
  statusHandler/p2pQuota/p2pQuotaProcessor.go
  statusHandler/p2pQuota/p2pQuotaProcessor_test.go
  statusHandler/quotaStatusHandler/printQuotaStatusHandler.go
Labels: enhancement

#803 Gas computation for tx data
  cmd/node/config/economics.toml
  config/economicsConfig.go
  core/address.go
  data/block/block.go
  data/block/block_test.go
  go.mod
  go.sum
  integrationTests/longTests/executingSCTransactions_test.go
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/singleShard/block/executingMiniblocksSc_test.go
  integrationTests/singleShard/block/wrc20_arwen_01.wasm
  integrationTests/testGameHelperFunctions.go
  integrationTests/testProcessorNode.go
  process/block/postprocess/basePostProcess.go
  process/block/postprocess/intermediateResults.go
  process/block/postprocess/oneMBPostProcessor.go
  process/block/preprocess/rewardsHandler.go
  process/coordinator/process.go
  process/economics/economicsData.go
  process/economics/economicsData_test.go
  process/economics/testEconomicsData.go
  process/errors.go
  process/factory/metachain/vmContainerFactory_test.go
  process/interface.go
  process/peer/process_test.go
Labels: bug

#916 Fix minrating economics config
  cmd/node/config/economics.toml
Labels: bug

#915 updated libp2p's libraries to latest releases
  go.mod
  go.sum
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  p2p/libp2p/discovery/nullDiscoverer.go
  p2p/libp2p/libp2pConnectionMonitor.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/libp2p/networksharding/kadSharder_test.go
  p2p/libp2p/networksharding/noSharder.go
  p2p/libp2p/networksharding/sharder.go
Labels: enhancement
