Repository multiversx/mx-chain-go, pull requests merged in 2019-10, with the labels that each got.

#504 EN-4215: bug fixing related to consensus group size for shards and meta
  cmd/node/main.go
Labels: bug

#500 EN-4198 : add new metric in termui for final highest block nonce
  cmd/node/main.go
  core/constants.go
  process/block/shardblock.go
  statusHandler/presenter/blockInfoGetters.go
  statusHandler/presenter/blockInfoGetters_test.go
  statusHandler/view/interface.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#487 En 4158 metablocks refactor
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/block/interceptedMetaBlockHeader.go
  process/block/interceptedMetaBlockHeader_test.go
  process/block/interceptors/metachainHeaderInterceptor.go
  process/block/interceptors/metachainHeaderInterceptor_test.go
  process/block/interceptors/peerBlockBodyInterceptor.go
  process/block/interceptors/peerBlockBodyInterceptors_test.go
  process/block/interceptors/txBlockBodyInterceptors_test.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory_test.go
  process/interceptors/factory/constants.go
  process/interceptors/factory/metaInterceptedDataFactory.go
  process/interceptors/factory/metaInterceptedDataFactory_test.go
  process/interceptors/factory/shardInterceptedDataFactory.go
  process/interceptors/factory/shardInterceptedDataFactory_test.go
  process/mock/headerHandlerStub.go
Labels: enhancement

#494 En 4184 fix print info and throttle size
  cmd/node/config/config.toml
  core/computers.go
  core/computers_test.go
  core/constants.go
  integrationTests/mock/intermediateTransactionHandlerMock.go
  process/block/displayBlock.go
  process/block/metablock.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock.go
  process/constants.go
  process/errors.go
  process/mock/intermediateTransactionHandlerMock.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/export_test.go
  process/sync/shardForkDetector.go
  process/throttle/block.go
  process/throttle/block_test.go
Labels: bug, enhancement

#495 En 4170 economics parameters
  cmd/node/config/config.toml
  cmd/node/config/economics.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  config/economicsConfig.go
  config/tomlConfig_test.go
  integrationTests/mock/feeHandlerMock.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/testInitializer.go
  process/block/preprocess/rewardsHandler.go
  process/block/preprocess/rewardsHandler_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock_test.go
  process/coordinator/process_test.go
  process/economics/economicsData.go
  process/economics/economicsData_test.go
  process/errors.go
  process/factory/shard/intermediateProcessorsContainerFactory.go
  process/factory/shard/intermediateProcessorsContainerFactory_test.go
  process/factory/shard/preProcessorsContainerFactory.go
  process/factory/shard/preProcessorsContainerFactory_test.go
  process/interface.go
  process/mock/feeHandlerMock.go
  process/mock/rewardsHandlerMock.go
  process/transaction/export_test.go
  process/transaction/process.go
  process/transaction/process_test.go
Labels: enhancement

#499 EN-4207 : fix tests that fail with race condition
  p2p/libp2p/issues_test.go
  process/common_test.go
Labels: bug

#498 EN-4203-Remove-old-block-tracker-from-elrond-go
  cmd/node/factory/structs.go
  cmd/node/main.go
  consensus/mock/blocksTrackerMock.go
  consensus/mock/consensusDataContainerMock.go
  consensus/mock/mockTestInitializer.go
  consensus/mock/sposWorkerMock.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bn/bnSubroundsFactory.go
  consensus/spos/bn/subroundEndRound.go
  consensus/spos/commonSubround/base_test.go
  consensus/spos/commonSubround/subroundStartRound.go
  consensus/spos/commonSubround/subroundStartRound_test.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/consensusCore_test.go
  consensus/spos/constants.go
  consensus/spos/errors.go
  consensus/spos/export_test.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blocksTrackerMock.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/defineOptions.go
  node/errors.go
  node/node.go
  process/block/argProcessor.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/interface.go
  process/mock/blocksTrackerMock.go
  process/track/metaBlock.go
  process/track/metaBlock_test.go
  process/track/shardBlock.go
  process/track/shardBlock_test.go
Labels: enhancement

#507 En 4217 bugfixing tx flood
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  core/errors.go
  core/throttler/numGoRoutineThrottler.go
  core/throttler/numGoRoutineThrottler_test.go
  integrationTests/frontend/wallet/txInterception_test.go
  integrationTests/mock/feeHandlerMock.go
  integrationTests/mock/feeHandlerStub.go
  integrationTests/multiShard/block/executingMiniblocks_test.go
  integrationTests/multiShard/smartContract/testInitializer.go
  integrationTests/singleShard/transaction/interceptedResolvedTx_test.go
  integrationTests/testGameHelperFunctions.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  integrationTests/vm/testInitializer.go
  p2p/libp2p/netMessenger.go
  process/block/interceptors/headerInterceptor_test.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/coordinator/process_test.go
  process/dataValidators/txValidator.go
  process/dataValidators/txValidator_test.go
  process/errors.go
  process/factory/shard/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory_test.go
  process/factory/shard/preProcessorsContainerFactory_test.go
  process/interface.go
  process/mock/feeHandlerMock.go
  process/mock/feeHandlerStub.go
  process/mock/interceptorThrottlerStub.go
  process/sync/shardblock_test.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  process/transaction/interceptor.go
  process/transaction/interceptor_test.go
  process/transaction/process_test.go
Labels: bug

#513 En 4212 fix bug when meta blocks are evicted
  core/computers.go
  core/computers_test.go
  integrationTests/multiShard/block/executingRewardMiniblocks_test.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/common.go
  process/common_test.go
  process/interface.go
  process/mock/headerHandlerStub.go
  process/throttle/block.go
  process/throttle/block_test.go
Labels: enhancement

#511 Fix development tests race
  p2p/libp2p/netMessenger_test.go
Labels: bug

#508 En 4164 heartbeat refactor
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  dataRetriever/interface.go
  integrationTests/node/heartbeat_test.go
  node/heartbeat/errors.go
  node/heartbeat/export_test.go
  node/heartbeat/hearbeatMessageInfo.go
  node/heartbeat/hearbeatMessageInfo_test.go
  node/heartbeat/heartbeat.go
  node/heartbeat/interface.go
  node/heartbeat/messageProcessor.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/heartbeat/realTimer.go
  node/heartbeat/storage/heartbeatStorer.go
  node/mock/heartbeatStorerStub.go
  node/mock/messageHandlerStub.go
  node/mock/mockTimer.go
  node/mock/storerMock.go
  node/mock/storerStub.go
  node/node.go
  node/node_test.go
Labels: enhancement

#516 Fix update heartbeat counters
  node/heartbeat/monitor.go
Labels: bug

#517 removed heartbeat storage when serving a rest API request
  cmd/node/config/config.toml
  node/heartbeat/monitor.go
Labels: bug

#509 En 4174 miniblocks interceptor refactor
  process/block/interceptedBlocks/argInterceptedTxBlockBody.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/block/interceptedBlocks/interceptedTxBlock.go
  process/block/interceptedBlocks/interceptedTxBlock_test.go
  process/block/interceptedPeerBlock.go
  process/block/interceptedPeerBlock_test.go
  process/block/interceptedTxBlock.go
  process/block/interceptedTxBlock_test.go
  process/block/interceptors/messageChecker.go
  process/block/interceptors/txBlockBodyInterceptor.go
  process/block/interceptors/txBlockBodyInterceptors_test.go
  process/errors.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory.go
  process/interceptors/factory/constants.go
  process/interceptors/factory/shardInterceptedDataFactory.go
  process/interceptors/factory/shardInterceptedDataFactory_test.go
  process/interceptors/processor/argTxBodyInterceptorProcessor.go
  process/interceptors/processor/txBodyInterceptorProcessor.go
  process/interceptors/processor/txBodyInterceptorProcessor_test.go
  process/transaction/interceptedTransaction.go
  process/unsigned/interceptedUnsignedTransaction.go
Labels: enhancement

#524 removed concurrent issue on rewardTxProcessor.goL245
  process/block/preprocess/rewardTxPreProcessor.go
Labels: bug

#484 En 4138 sync it block too old
  integrationTests/interface.go
  integrationTests/sync/basicSync_test.go
  integrationTests/sync/common.go
  integrationTests/sync/edgeCases_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  process/sync/testMetaBootstrap.go
  process/sync/testShardBootstrap.go
Labels: bug

#525 EN-4291-Refactor-mini-blocks-request-from-sync
  core/computers.go
  core/computers_test.go
  dataRetriever/errors.go
  dataRetriever/interface.go
  dataRetriever/resolvers/genericBlockBodyResolver.go
  integrationTests/mock/miniBlocksResolverMock.go
  process/block/baseProcess.go
  process/mock/miniBlocksResolverMock.go
  process/sync/baseSync.go
  process/sync/export_test.go
  process/sync/metablock.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug, enhancement

#496 En 3782/system vm and smart contracts
  core/genesis/genesisBlockCreator.go
  integrationTests/mock/intermediateTransactionHandlerMock.go
  integrationTests/multiShard/smartContract/executingSCCalls_test.go
  integrationTests/vm/mockVM/vmDeploy_test.go
  integrationTests/vm/mockVM/vmGet_test.go
  integrationTests/vm/mockVM/vmRunContract_test.go
  process/factory/factory.go
  process/factory/shard/vmContainerFactory_test.go
  process/transaction/process.go
  vm/errors.go
  vm/factory/factory.go
  vm/factory/systemSCContainer.go
  vm/factory/systemSCContainer_test.go
  vm/factory/systemSCFactory.go
  vm/factory/systemSCFactory_test.go
  vm/interface.go
  vm/mock/blockChainHookStub.go
  vm/mock/cryptoHookStub.go
  vm/mock/systemEIStub.go
  vm/mock/systemSCContainerStub.go
  vm/mock/systemSCStub.go
  vm/process/systemVM.go
  vm/process/systemVM_test.go
  vm/systemSmartContracts/common.go
  vm/systemSmartContracts/common_test.go
  vm/systemSmartContracts/eei.go
  vm/systemSmartContracts/eei_test.go
  vm/systemSmartContracts/staking.go
  vm/systemSmartContracts/staking_test.go
Labels: enhancement

#543 transaction fee calculation refactor:
  data/rewardTx/rewardTx.go
  data/transaction/transaction.go
  integrationTests/mock/feeHandlerStub.go
  integrationTests/multiShard/block/executingRewardMiniblocks_test.go
  integrationTests/multiShard/smartContract/testInitializer.go
  integrationTests/singleShard/transaction/interceptedResolvedTx_test.go
  integrationTests/state/stateExecTransaction_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock_test.go
  process/coordinator/process_test.go
  process/economics/economicsData.go
  process/economics/economicsData_test.go
  process/economics/testEconomicsData.go
  process/errors.go
  process/interface.go
  process/mock/feeHandlerStub.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  process/transaction/process.go
  process/transaction/process_test.go
Labels: bug, enhancement

#545 Fixed probable highest nonce set by a proposed block
  consensus/spos/worker.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/export_test.go
Labels: bug, enhancement

#527 En 4225 termui new metrics rewards
  cmd/node/main.go
  consensus/mock/appStatusHandlerStub.go
  consensus/mock/nodesCoordinatorMock.go
  consensus/mock/statusHandlerMock.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bn/subroundEndRound.go
  core/constants.go
  core/interface.go
  core/mock/appStatusHandlerStub.go
  core/statistics/machine/cpuStatistics.go
  data/address/specialAddresses.go
  data/consensusRewardData.go
  data/mock/nodesCoordinatorMock.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/nodesCoordinatorMock.go
  integrationTests/mock/specialAddressHandlerMock.go
  integrationTests/multiShard/smartContract/testInitializer.go
  integrationTests/testProcessorNodeWithMultisigner.go
  node/mock/appStatusHandlerStub.go
  node/mock/nodesCoordinatorMock.go
  process/block/metablock.go
  process/block/metrics.go
  process/block/shardblock.go
  process/interface.go
  process/mock/appStatusHandlerStub.go
  process/mock/nodesCoordinatorMock.go
  process/mock/specialAddressHandlerMock.go
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/interface.go
  sharding/shardingArgs.go
  statusHandler/appStatusFacade.go
  statusHandler/mock/appStatusHandlerStub.go
  statusHandler/nilHandler.go
  statusHandler/presenter/common.go
  statusHandler/presenter/instanceInfoGetters.go
  statusHandler/presenter/instanceInfoGetters_test.go
  statusHandler/presenter/presenterStatusHandler.go
  statusHandler/prometheusHandler.go
  statusHandler/statusMetricsProvider.go
  statusHandler/view/interface.go
  statusHandler/view/termuic/processCloser.go
  statusHandler/view/termuic/termuiConsole.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#530 EN-4313-Fix-bug-on-request-missing-headers-by-nonce
  dataRetriever/dataPool/metaDataPool.go
  dataRetriever/dataPool/metaDataPool_test.go
  dataRetriever/dataPool/nonceSyncMapCacher.go
  dataRetriever/dataPool/nonceSyncMapCacher_test.go
  dataRetriever/factory/metachain/resolversContainerFactory.go
  dataRetriever/factory/metachain/resolversContainerFactory_test.go
  dataRetriever/interface.go
  dataRetriever/mock/metaPoolsHolderStub.go
  integrationTests/multiShard/block/interceptedBlocks_test.go
  integrationTests/multiShard/block/interceptedHeadersSigVerification_test.go
  integrationTests/multiShard/metablock/blocksDissemination_test.go
  integrationTests/multiShard/smartContract/testInitializer.go
  integrationTests/sync/common.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  node/mock/metaPoolsHolderStub.go
  process/block/baseProcess_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/metachain/interceptorsContainerFactory_test.go
  process/mock/metaPoolsHolderFake.go
  process/mock/metaPoolsHolderStub.go
  process/sync/baseSync.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
Labels: bug, enhancement

#442 En 3794/wasm vm integration
  core/libLocator/vmLocator_darwin.go
  core/libLocator/vmLocator_linux.go
  core/libLocator/vmLocator_windows.go
  go.mod
  go.sum
  integrationTests/agar_v1_min.hex
  integrationTests/longTests/executingSCTransactions_test.go
  integrationTests/vm/testInitializer.go
  integrationTests/vm/wasm/agar_v1_min_ewasmified.wasm
  integrationTests/vm/wasm/cpucalculate_ewasmified.wasm
  integrationTests/vm/wasm/fibonacci_ewasmified.wasm
  integrationTests/vm/wasm/store.wasm
  integrationTests/vm/wasm/stringconcat_ewasmified.wasm
  integrationTests/vm/wasm/wasmVM_test.go
  integrationTests/vm/wasm/wrc20_ewasmified.wasm
  process/factory/factory.go
  process/factory/shard/vmContainerFactory.go
Labels: enhancement

#548 En 4195 integration tests trie pruning
  data/interface.go
  data/mock/evictionWaitingListMock.go
  data/mock/trieStub.go
  data/state/accountsDB.go
  data/state/accountsDBWrapperForSync.go
  data/trie/branchNode.go
  data/trie/errors.go
  data/trie/extensionNode.go
  data/trie/leafNode.go
  data/trie/node.go
  data/trie/node_test.go
  data/trie/patriciaMerkleTrie.go
  data/trie/patriciaMerkleTrie_test.go
  integrationTests/state/stateTrie_test.go
  integrationTests/sync/basicSync_test.go
  integrationTests/sync/common.go
  integrationTests/sync/edgeCases_test.go
  integrationTests/testGameHelperFunctions.go
  integrationTests/testInitializer.go
  integrationTests/testSyncNode.go
  node/node.go
  process/block/shardblock.go
  process/sync/shardblock.go
Labels: enhancement

#556 Improved probable highest nonce reset and sync status for all nodes
  consensus/mock/forkDetectorMock.go
  consensus/spos/commonSubround/subroundStartRound.go
  integrationTests/mock/forkDetectorMock.go
  node/mock/forkDetectorMock.go
  process/block/preprocess/transactions.go
  process/common.go
  process/constants.go
  process/interface.go
  process/mock/forkDetectorMock.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/baseSync.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
  sharding/multiShardCoordinator.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#566 En 4565 fix problem with pool capacity
  api/mock/cacherStub.go
  data/mock/cacherStub.go
  dataRetriever/mock/cacherMock.go
  dataRetriever/mock/cacherStub.go
  integrationTests/mock/cacherStub.go
  node/mock/cacherStub.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardTxPreProcessor_test.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock.go
  process/constants.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interface.go
  process/mock/cacherMock.go
  process/mock/cacherStub.go
  process/mock/preprocessorMock.go
  storage/fifocache/fifocacheSharded.go
  storage/interface.go
  storage/lrucache/lrucache.go
Labels: bug, enhancement

#546 EN-4321 : add in termui warning when node needs to be updated
  cmd/node/factory/structs.go
  cmd/node/main.go
  cmd/node/metrics/machineStatistics.go
  cmd/node/metrics/metrics.go
  core/constants.go
  core/errors.go
  core/statistics/softwareVersion/factory/softwareVersionFactory.go
  core/statistics/softwareVersion/factory/softwareVersionFactory_test.go
  core/statistics/softwareVersion/softwareVersion.go
  core/statistics/softwareVersion/softwareVersion_test.go
  statusHandler/presenter/instanceInfoGetters.go
  statusHandler/presenter/instanceInfoGetters_test.go
  statusHandler/view/interface.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#531 EN-4317: preferences config file
  cmd/node/config/config.toml
  cmd/node/config/prefs.toml
  cmd/node/main.go
  config/prefsConfig.go
  config/tomlConfig_test.go
Labels: enhancement

#550 En 4379-Cross-build
  .gitignore
  Makefile
  cmd/node/main.go
  cross_build.sh
Labels: enhancement

#536 En 4248 compact miniblocks
  cmd/node/factory/structs.go
  data/interface.go
  data/rewardTx/rewardTx.go
  data/smartContractResult/smartContractResult.go
  data/transaction/transaction.go
  integrationTests/multiShard/block/executingRewardMiniblocks_test.go
  integrationTests/multiShard/smartContract/testInitializer.go
  integrationTests/testProcessorNode.go
  process/block/preprocess/miniBlocksCompaction.go
  process/block/preprocess/miniBlocksCompaction_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock_test.go
  process/coordinator/process_test.go
  process/errors.go
  process/factory/shard/preProcessorsContainerFactory.go
  process/factory/shard/preProcessorsContainerFactory_test.go
  process/interface.go
  process/mock/miniBlocksCompacterMock.go
Labels: enhancement

#589 En 4641 fix bugs in testnet battle of nodes phase 1 wave 3
  consensus/broadcast/metaChainMessenger.go
  consensus/broadcast/metaChainMessenger_test.go
  consensus/broadcast/shardChainMessenger.go
  consensus/broadcast/shardChainMessenger_test.go
  consensus/interface.go
  consensus/mock/broadcastMessangerMock.go
  consensus/mock/forkDetectorMock.go
  consensus/spos/bls/blsWorker.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bn/bnWorker.go
  consensus/spos/bn/subroundEndRound.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  core/converters.go
  core/converters_test.go
  integrationTests/interface.go
  integrationTests/mock/forkDetectorMock.go
  integrationTests/sync/common.go
  integrationTests/sync/edgeCases_test.go
  integrationTests/testProcessorNode.go
  node/mock/forkDetectorMock.go
  node/node.go
  process/block/metablock.go
  process/block/preprocess/miniBlocksCompaction_test.go
  process/block/shardblock.go
  process/constants.go
  process/errors.go
  process/interface.go
  process/mock/forkDetectorMock.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/baseSync.go
  process/sync/export_test.go
  process/sync/interface.go
  process/sync/metaForkDetector.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardForkDetector.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
  process/sync/testMetaBootstrap.go
  process/sync/testShardBootstrap.go
Labels: bug, enhancement

#608 En 3655 smart contract handling peers unit tests
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
Labels: enhancement
