Repository multiversx/mx-chain-go, pull requests merged in 2019-07, with the labels that each got.

#238 changed get-values route to vm-values
  api/api.go
  api/mock/facade.go
  api/vmValues/routes.go
  api/vmValues/routes_test.go
  facade/elrondNodeFacade.go
  facade/elrondNodeFacade_test.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
Labels: enhancement

#250 Feat/en 2678 data and execution module
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  core/logger/redirectStderrWindows.go
  dataRetriever/dataPool/shardDataPool.go
  dataRetriever/dataPool/shardDataPool_test.go
  dataRetriever/errors.go
  dataRetriever/factory/shard/resolversContainerFactory.go
  dataRetriever/factory/shard/resolversContainerFactory_test.go
  dataRetriever/interface.go
  dataRetriever/mock/poolsHolderStub.go
  dataRetriever/requestHandlers/requestHandler.go
  dataRetriever/requestHandlers/requestHandler_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/frontend/wallet/testInitializer.go
  integrationTests/multiShard/block/testInitializer.go
  integrationTests/multiShard/metablock/testInitializer.go
  integrationTests/multiShard/transaction/testInitializer.go
  integrationTests/singleShard/block/testInitializer.go
  integrationTests/singleShard/transaction/testInitializer.go
  node/mock/poolsHolderStub.go
  process/block/baseProcess_test.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions_test.go
  process/coordinator/process_test.go
  process/errors.go
  process/factory/factory.go
  process/factory/shard/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory_test.go
  process/factory/shard/preProcessorsContainerFactory.go
  process/factory/shard/preProcessorsContainerFactory_test.go
  process/interface.go
  process/mock/poolsHolderFake.go
  process/mock/poolsHolderStub.go
  process/mock/requestHandlerMock.go
  process/smartContract/interceptedSmartContractResult.go
  process/smartContract/interceptor.go
  process/unsigned/interceptedUnsignedTransaction.go
  process/unsigned/interceptedUnsignedTransaction_test.go
  process/unsigned/interceptor.go
  process/unsigned/interceptor_test.go
Labels: enhancement

#251 Bug/en 2838 delete from branch node correctly
  data/trie/branchNode.go
  data/trie/branchNode_test.go
  data/trie/patriciaMerkleTrie.go
Labels: bug

#253 Bug/fix windows redirect
  core/logger/errors.go
  core/logger/redirectStderrWindows.go
Labels: bug

#252 Fixed stream reset and peer is not directly connected errors
  dataRetriever/resolvers/topicResolverSender/export_test.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go
  p2p/libp2p/directSender.go
  p2p/libp2p/export_test.go
  p2p/libp2p/mutexHolder.go
  p2p/libp2p/mutexHolder_test.go
  p2p/libp2p/netMessenger.go
  p2p/p2p.go
Labels: bug

#259 Merged feat/vm and economics update 07072019
  data/trie/branchNode.go
  data/trie/branchNode_test.go
  data/trie/patriciaMerkleTrie.go
  dataRetriever/resolvers/topicResolverSender/export_test.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go
  p2p/libp2p/directSender.go
  p2p/libp2p/export_test.go
  p2p/libp2p/mutexHolder.go
  p2p/libp2p/mutexHolder_test.go
  p2p/libp2p/netMessenger.go
  p2p/p2p.go
Labels: enhancement

#255 enabled iele vm to be used by the node
  api/transaction/routes_test.go
  api/vmValues/routes.go
  api/vmValues/routes_test.go
  cmd/node/factory/structs.go
  cmd/node/main.go
  core/indexer/elasticsearch.go
  core/indexer/elasticsearch_test.go
  data/interface.go
  data/smartContractResult/smartContractResult.go
  data/smartContractResult/smartContractResult_test.go
  data/transaction/capnp/schema.capnp
  data/transaction/capnp/schema.capnp.go
  data/transaction/transaction.go
  data/transaction/transaction_test.go
  facade/elrondNodeFacade_test.go
  go.mod
  go.sum
  integrationTests/frontend/wallet/txInterception_test.go
  integrationTests/multiShard/block/executingMiniblocks_test.go
  integrationTests/singleShard/transaction/interceptedResolvedTx_test.go
  integrationTests/vm/iele/vmDeploy_test.go
  integrationTests/vm/iele/vmRunContract_test.go
  integrationTests/vm/mockVM/vmDeploy_test.go
  integrationTests/vm/mockVM/vmGet_test.go
  integrationTests/vm/mockVM/vmRunContract_test.go
  integrationTests/vm/testInitializer.go
  marshal/capnpMarshalizer_test.go
  node/node.go
  node/nodeTesting.go
  node/node_test.go
  process/block/shardblock_test.go
  process/coordinator/process_test.go
  process/interface.go
  process/mock/argumentsParserMock.go
  process/smartContract/atArgumentParser.go
  process/smartContract/atArgumentParser_test.go
  process/smartContract/export_test.go
  process/smartContract/hooks/vmCrypto.go
  process/smartContract/hooks/vmCrypto_test.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/sync/shardblock_test.go
  process/transaction/interceptedTransaction_test.go
  process/transaction/interceptor_test.go
  process/transaction/process_test.go
  process/unsigned/interceptedUnsignedTransaction_test.go
  process/unsigned/interceptor_test.go
Labels: enhancement

#264 Feat/en 2864 agar io sc integration tests
  go.mod
  go.sum
  integrationTests/vm/iele/agarioV2.hex
  integrationTests/vm/iele/vmAgar_test.go
  integrationTests/vm/iele/vmDeploy_test.go
  integrationTests/vm/iele/vmRunContract_test.go
  integrationTests/vm/mockVM/vmDeploy_test.go
  integrationTests/vm/mockVM/vmGet_test.go
  integrationTests/vm/mockVM/vmRunContract_test.go
  integrationTests/vm/testInitializer.go
Labels: enhancement

#254 Added session.info and -working-directory
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/path.go
Labels: bug

#263 Issue/#248 wrong nonce in block
  cmd/node/main.go
  consensus/mock/bootstrapMock.go
  consensus/mock/consensusDataContainerMock.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/export_test.go
  consensus/spos/bn/bnSubroundsFactory_test.go
  consensus/spos/bn/export_test.go
  consensus/spos/commonSubround/subroundStartRound_test.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/consensusCore_test.go
  consensus/spos/errors.go
  consensus/spos/export_test.go
  consensus/spos/subround_test.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  node/defineOptions.go
  node/node.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/constants.go
  process/errors.go
  process/sync/baseSync.go
  process/sync/basicForkDetector.go
  process/sync/basicForkDetector_test.go
  process/sync/errors.go
  process/sync/export_test.go
  process/sync/interface.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug

#261 Unit tests
  process/block/export_test.go
  process/block/metablock_test.go
  process/block/shardblock_test.go
Labels: enhancement

#272 fixed bug in trie.extensionNode when splitting into a branch
  data/interface.go
  data/mock/trieStub.go
  data/trie/branchNode.go
  data/trie/extensionNode.go
  data/trie/leafNode.go
  data/trie/node.go
  data/trie/patriciaMerkleTrie.go
  integrationTests/state/genesisEdgeCase.json
  integrationTests/state/genesisState_test.go
  integrationTests/state/stateTrie_test.go
Labels: P0, bug

#282 bug/EN-2910-Fix-bug-when-nil-hash-is-return-from-sync-map
  process/sync/baseSync.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug

#288 bug/EN-3146-Request header by hash when fork is detected
  cmd/node/main.go
  consensus/mock/forkDetectorMock.go
  integrationTests/mock/forkDetectorMock.go
  node/mock/forkDetectorMock.go
  process/interface.go
  process/mock/forkDetectorMock.go
  process/sync/baseSync.go
  process/sync/baseSync_test.go
  process/sync/basicForkDetector.go
  process/sync/basicForkDetector_test.go
  process/sync/export_test.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug

#293 Added deepClone functionality to trie
  data/interface.go
  data/mock/crypto.go
  data/mock/crypto_test.go
  data/mock/sha3/LICENSE
  data/mock/sha3/PATENTS
  data/mock/sha3/doc.go
  data/mock/sha3/hashes.go
  data/mock/sha3/keccakf.go
  data/mock/sha3/register.go
  data/mock/sha3/sha3.go
  data/mock/sha3/sha3_test.go
  data/mock/sha3/shake.go
  data/mock/sha3/testdata/keccakKats.json.deflate
  data/mock/sha3/xor.go
  data/mock/sha3/xor_generic.go
  data/mock/sha3/xor_unaligned.go
  data/mock/trieStub.go
  data/trie/branchNode.go
  data/trie/branchNode_test.go
  data/trie/extensionNode.go
  data/trie/extensionNode_test.go
  data/trie/leafNode.go
  data/trie/leafNode_test.go
  data/trie/node.go
  data/trie/patriciaMerkleTrie.go
  data/trie/patriciaMerkleTrie_test.go
Labels: enhancement

#292 Feat/en 3093 tx limit adaptivity on propose block
  cmd/node/factory/structs.go
  cmd/node/main.go
  consensus/spos/commonSubround/subroundBlock.go
  consensus/spos/commonSubround/subroundStartRound.go
  core/computers.go
  core/computers_test.go
  data/block/block.go
  data/block/metaBlock.go
  data/interface.go
  go.mod
  go.sum
  integrationTests/multiShard/block/testInitializer.go
  integrationTests/multiShard/metablock/testInitializer.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  node/errors.go
  process/block/baseProcess.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interface.go
  process/mock/blockSizeThrottlerStub.go
  process/mock/headerHandlerStub.go
  process/mock/transactionCoordinatorMock.go
  process/sync/metablock.go
  process/sync/shardblock.go
  process/throttle/block.go
  process/throttle/block_test.go
  process/throttle/export_test.go
Labels: enhancement

#301 Bug/en 3192 fix bug when a wrong/unused fork requested header is received
  cmd/node/main.go
  process/sync/metablock.go
  process/sync/shardblock.go
Labels: bug

#302 Bug/en 3205 fix bug out of memory
  cmd/node/config/config.toml
Labels: bug

#300 En 3107 test 1mil accounts
  data/trie/branchNode.go
  data/trie/extensionNode.go
  integrationTests/mock/DbMock.go
  integrationTests/mock/countingDB.go
  integrationTests/state/stateTrie_test.go
Labels: enhancement

#298 Bugs/en 3179 data trie loading bugfix
  data/mock/accountWrapperMock.go
  data/state/account.go
  data/state/accountsDB.go
  data/state/baseJournalEntries.go
  data/state/baseJournalEntries_test.go
  data/state/export_test.go
  data/state/interface.go
  data/state/journalEntries_test.go
  data/state/metaAccount.go
  integrationTests/state/stateTrie_test.go
  integrationTests/vm/iele/agarioV2.hex
  integrationTests/vm/iele/vmAgar_test.go
  integrationTests/vm/iele/vmDeploy_test.go
  integrationTests/vm/iele/vmRunContract_test.go
  integrationTests/vm/testInitializer.go
  node/mock/accountsStub.go
  process/mock/accountWrapperFake.go
  process/mock/accountsStub.go
Labels: P1, bug

#306 Bug/en 3214 fix bug in "Has" method from nonceSyncMapCacher
  dataRetriever/dataPool/nonceSyncMapCacher.go
  dataRetriever/dataPool/nonceSyncMapCacher_test.go
  dataRetriever/interface.go
  dataRetriever/mock/uint64SyncMapCacherStub.go
  integrationTests/consensus/consensus_test.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/coordinator/process_test.go
  process/errors.go
  process/mock/uint64SyncMapCacherStub.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug

#311 Bug/en 3214 fix bug in "Has" method from nonceSyncMapCacher
  cmd/node/config/config.toml
  dataRetriever/dataPool/nonceSyncMapCacher.go
  dataRetriever/dataPool/nonceSyncMapCacher_test.go
  dataRetriever/interface.go
  dataRetriever/mock/uint64SyncMapCacherStub.go
  integrationTests/consensus/consensus_test.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/coordinator/process_test.go
  process/errors.go
  process/mock/uint64SyncMapCacherStub.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug

#309 Bug/en 3206 tps benchmark update concurrency problem
  core/statistics/tpsBenchmark.go
  core/statistics/tpsBenchmark_test.go
Labels: bug

#291 Feat/en 3155 heartbeat refactor
  api/node/routes_test.go
  facade/elrondNodeFacade_test.go
  node/heartbeat/hearbeatMessageInfo.go
  node/heartbeat/hearbeatMessageInfo_test.go
  node/heartbeat/heartbeat.go
  node/heartbeat/interface.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/heartbeat/sender.go
  node/heartbeat/sender_test.go
  node/node.go
  node/node_test.go
Labels: enhancement

#315 refactor displayBlock.go
  process/block/displayBlock.go
  process/block/export_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
Labels: enhancement

#308 Bugs/en 3188 sc deploy tx dispatching
  core/computers_test.go
  go.mod
  go.sum
  integrationTests/multiShard/block/agarioV2.hex
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/multiShard/block/executingMiniblocks_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  process/coordinator/process.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
Labels: P1, bug, enhancement

#318 Marshalize intermediate result and for SCR only when needed
  consensus/broadcast/metaChainMessenger.go
  consensus/broadcast/shardChainMessenger.go
  consensus/broadcast/shardChainMessenger_test.go
  consensus/interface.go
  consensus/mock/blockProcessorMock.go
  consensus/mock/broadcastMessangerMock.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bn/subroundEndRound_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/intermediateTransactionHandlerMock.go
  node/mock/blockProcessorStub.go
  process/block/metablock.go
  process/block/preprocess/intermediateResults.go
  process/block/preprocess/intermediateResults_test.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/shardblock.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/errors.go
  process/interface.go
  process/mock/blockProcessorMock.go
  process/mock/intermediateTransactionHandlerMock.go
  process/mock/transactionCoordinatorMock.go
Labels: enhancement

#320 Bug/en 3249 fix bug when node resolves requests with bad unused headers
  cmd/node/config/config.toml
  dataRetriever/resolvers/headerResolver.go
  dataRetriever/resolvers/headerResolver_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/common.go
  process/common_test.go
  process/errors.go
  process/mock/shardIdHashMapMock.go
  process/sync/export_test.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
  process/track/shardBlock.go
Labels: bug

#321 Bugs/en 3228 sc processor refund gas
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/singleShard/block/agarioV2.hex
  integrationTests/singleShard/block/executingMiniblocksSc_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  process/smartContract/process.go
  process/smartContract/process_test.go
Labels: P1, bug

#326 Bugs/en 3233 test scrs are processed intra shard
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/singleShard/block/executingMiniblocksSc_test.go
  integrationTests/testProcessorNode.go
Labels: enhancement
