Repository multiversx/mx-chain-go, pull requests merged in 2019-09, with the labels that each got.

#411 En 3834 observers out of mem add stats
  core/statistics/resourceMonitor.go
Labels: enhancement

#409 Bugfix/en 3696 nodes blocked in forkchoice
  data/block/block.go
  process/block/baseProcess.go
  process/block/export_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/sync/baseSync.go
  process/sync/basicForkDetector.go
  process/sync/basicForkDetector_test.go
  process/sync/export_test.go
  process/sync/interface.go
  process/sync/metablock.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug

#403 EN-3755: bulk transactions sender
  api/mock/facade.go
  api/transaction/routes.go
  facade/elrondNodeFacade.go
  facade/interface.go
  facade/mock/nodeMock.go
  integrationTests/multiShard/transaction/sendBulkTransactions_test.go
  node/errors.go
  node/mock/multipleShardsCoordinatorMock.go
  node/node.go
  node/nodeTesting.go
  node/node_test.go
Labels: enhancement

#393 En 3603 refactor tx interceptor
  core/check/ifNil.go
  core/check/ifNil_test.go
  core/check/interface.go
  core/errors.go
  core/throttler/numGoRoutineThrottler.go
  core/throttler/numGoRoutineThrottler_test.go
  data/transaction/transaction.go
  process/dataValidators/nilTxValidator.go
  process/dataValidators/nilTxValidator_test.go
  process/errors.go
  process/factory/shard/interceptorsContainerFactory.go
  process/interceptors/factory/argInterceptedDataFactory.go
  process/interceptors/factory/interceptedDataFactory.go
  process/interceptors/factory/interceptedDataFactory_test.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/processor/argTxInterceptorProcessor.go
  process/interceptors/processor/interface.go
  process/interceptors/processor/txInterceptorProcessor.go
  process/interceptors/processor/txInterceptorProcessor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interface.go
  process/mock/interceptedTxHandlerStub.go
  process/mock/txValidatorStub.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  process/transaction/interceptor.go
  process/transaction/interceptor_test.go
  process/transaction/process.go
Labels: enhancement

#415 En 3828/index scrs to elastic search
  integrationTests/mock/intermediateTransactionHandlerMock.go
  process/block/preprocess/intermediateResults.go
  process/block/preprocess/intermediateResults_test.go
  process/coordinator/process.go
  process/interface.go
  process/mock/intermediateTransactionHandlerMock.go
Labels: enhancement

#417 En 3833 observers get out of mem
  cmd/node/factory/structs.go
  consensus/broadcast/shardChainMessenger.go
  core/partitioning/simpleDataPacker.go
  core/partitioning/simpleDataPacker_test.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/singleShard/transaction/interceptedBulkUnsignedTx_test.go
  integrationTests/testProcessorNode.go
  node/node.go
  node/nodeTesting.go
Labels: bug

#421 generate bulk transaction func does not care about the tx pool size
  node/nodeTesting.go
  node/nodeTesting_test.go
Labels: bug

#418 En 3698 termui update new metrics
  cmd/node/main.go
  consensus/chronology/chronology.go
  consensus/chronology/chronology_test.go
  core/constants.go
  core/converters.go
  core/converters_test.go
  process/block/metablock.go
  process/block/metrics.go
  process/block/shardblock.go
  statusHandler/presenter/blockInfoGetters.go
  statusHandler/presenter/blockInfoGetters_test.go
  statusHandler/presenter/chainInfoGetters.go
  statusHandler/presenter/chainInfoGetters_test.go
  statusHandler/presenter/presenterStatusHandler.go
  statusHandler/view/interface.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#427 updated test for prometheusHandler in order to support go1.13
  statusHandler/appStatusFacade_test.go
  statusHandler/prometheusHandler_test.go
Labels: enhancement

#420 EN-3346: mdns removal and p2p integration tests refactor
  cmd/node/config/p2p.toml
  cmd/seednode/config/p2p.toml
  config/config.go
  go.mod
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/p2p/peerDiscovery/kadDht/peerDiscovery_test.go
  integrationTests/p2p/peerDiscovery/mdns/peerDiscovery_test.go
  integrationTests/p2p/peerDiscovery/testRunnner.go
  integrationTests/p2p/pubsub/peerReceivingMessages_test.go
  integrationTests/testInitializer.go
  p2p/errors.go
  p2p/libp2p/discovery/export_test.go
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  p2p/libp2p/discovery/kadDhtDiscoverer_test.go
  p2p/libp2p/discovery/mdnsDiscoverer.go
  p2p/libp2p/discovery/mdnsDiscoverer_test.go
  p2p/libp2p/discovery/nullDiscoverer.go
  p2p/libp2p/factory/peerDiscovererCreator.go
  p2p/libp2p/factory/peerDiscovererCreator_test.go
Labels: enhancement

#423 En 3880 integration tests create test sync node
  integrationTests/mock/rounderMock.go
  integrationTests/singleShard/transaction/interceptedBulkTx_test.go
  integrationTests/sync/basicSync_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/node.go
Labels: enhancement

#430 updated libp2p's libraries to the latest version
  go.mod
  go.sum
  p2p/mock/connectableHostStub.go
  storage/badgerdb/badgerdb.go
Labels: enhancement

#416 EN-3344: integration test for bls multi sign
  integrationTests/multisig/blsMultisig_test.go
Labels: enhancement

#437 Update feat interceptors 02
  cmd/node/config/p2p.toml
  cmd/node/main.go
  cmd/seednode/config/p2p.toml
  config/config.go
  consensus/chronology/chronology.go
  consensus/chronology/chronology_test.go
  consensus/mock/sposWorkerMock.go
  consensus/spos/commonSubround/subroundBlock_test.go
  core/constants.go
  core/converters.go
  core/converters_test.go
  core/statistics/resourceMonitor.go
  crypto/signing/key.go
  facade/interface.go
  go.mod
  go.sum
  integrationTests/mock/rounderMock.go
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/p2p/peerDiscovery/kadDht/peerDiscovery_test.go
  integrationTests/p2p/peerDiscovery/mdns/peerDiscovery_test.go
  integrationTests/p2p/peerDiscovery/testRunnner.go
  integrationTests/p2p/pubsub/peerReceivingMessages_test.go
  integrationTests/singleShard/transaction/interceptedBulkTx_test.go
  integrationTests/sync/basicSync_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/node.go
  p2p/errors.go
  p2p/libp2p/discovery/export_test.go
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  p2p/libp2p/discovery/kadDhtDiscoverer_test.go
  p2p/libp2p/discovery/mdnsDiscoverer.go
  p2p/libp2p/discovery/mdnsDiscoverer_test.go
  p2p/libp2p/discovery/nullDiscoverer.go
  p2p/libp2p/factory/peerDiscovererCreator.go
  p2p/libp2p/factory/peerDiscovererCreator_test.go
  p2p/mock/connectableHostStub.go
  process/block/metablock.go
  process/block/metrics.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  statusHandler/appStatusFacade_test.go
  statusHandler/presenter/blockInfoGetters.go
  statusHandler/presenter/blockInfoGetters_test.go
  statusHandler/presenter/chainInfoGetters.go
  statusHandler/presenter/chainInfoGetters_test.go
  statusHandler/presenter/presenterStatusHandler.go
  statusHandler/prometheusHandler_test.go
  statusHandler/view/interface.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
  storage/badgerdb/badgerdb.go
Labels: enhancement

#434 EN-3887: new tx interceptor, refactor tests that are falling
  cmd/node/factory/structs.go
  go.sum
  integrationTests/frontend/wallet/txInterception_test.go
  integrationTests/multiShard/block/executingMiniblocks_test.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx_test.go
  integrationTests/multiShard/transaction/sendBulkTransactions_test.go
  integrationTests/singleShard/transaction/interceptedBulkTx_test.go
  integrationTests/singleShard/transaction/interceptedResolvedTx_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  process/dataValidators/txValidator.go
  process/dataValidators/txValidator_test.go
  process/factory/shard/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory_test.go
  process/interface.go
  process/mock/txValidatorHandlerStub.go
  process/mock/txValidatorStub.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  process/transaction/interceptor.go
  process/transaction/interceptor_test.go
Labels: enhancement

#436 Fixed bug with fork choice and negative txs
  process/block/displayBlock.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/common.go
  process/common_test.go
  process/constants.go
  process/sync/metablock.go
  process/sync/shardblock.go
  process/throttle/block.go
  process/throttle/block_test.go
Labels: bug

#441 EN-3909: node endpoint for exporting status handler's metrics
  api/mock/facade.go
  api/node/routes.go
  api/node/routes_test.go
  cmd/node/main.go
  consensus/mock/bootstrapMock.go
  core/constants.go
  facade/elrondNodeFacade.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  node/external/errors.go
  node/external/interface.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  node/mock/statusMetricsStub.go
  node/node.go
  process/interface.go
  process/sync/baseSync.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
  statusHandler/statusMetricsProvider.go
  statusHandler/statusMetricsProvider_test.go
Labels: enhancement

#443 En 3924 fix bug when nil notarized header is added and displayed
  consensus/mock/forkDetectorMock.go
  consensus/spos/worker_test.go
  integrationTests/mock/forkDetectorMock.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/testProcessorNode.go
  node/mock/forkDetectorMock.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/displayBlock.go
  process/block/export_test.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/interface.go
  process/mock/forkDetectorMock.go
  process/sync/basicForkDetector.go
  process/sync/basicForkDetector_test.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug

#455 EN-3069: integration test for invalid sc code + refactoring
  integrationTests/vm/iele/vmAgar_test.go
  integrationTests/vm/iele/vmDeploy_test.go
  integrationTests/vm/iele/vmRunContract_test.go
  integrationTests/vm/testInitializer.go
  process/smartContract/process.go
Labels: enhancement

#457 En 4077 refactor shard processor constructor
  cmd/node/factory/structs.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  process/block/argProcessor.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
Labels: enhancement

#456 En 3996 implement db eviction cache
  data/interface.go
  data/trie/errors.go
  data/trie/evictionWaitingList/evictionWaitingList.go
  data/trie/evictionWaitingList/evictionWaitingList_test.go
  marshal/jsonMarshalizer.go
Labels: enhancement

#460 Remove default initial sk files from config
  cmd/node/config/initialBalancesSk.pem
  cmd/node/config/initialNodesSk.pem
Labels: enhancement

#459 En 3930 seednode does not advertise peer public ip
  p2p/libp2p/netMessenger.go
Labels: bug

#454 En 4061 fix bug in set final block notarized by meta
  cmd/node/factory/structs.go
  dataRetriever/errors.go
  dataRetriever/requestHandlers/requestHandler.go
  dataRetriever/requestHandlers/requestHandler_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/node.go
  process/block/baseProcess.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/baseSync.go
  process/sync/errors.go
  process/sync/export_test.go
  process/sync/metaForkDetector.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardForkDetector.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug

#458 En 4088 integration test block double sign
  integrationTests/sync/basicSync_test.go
  integrationTests/testInitializer.go
Labels: enhancement

#450 En 3887 cleanup txs pools
  cmd/node/factory/structs.go
  go.sum
  integrationTests/mock/poolscleanerMock.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  process/block/argProcessor.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/poolsCleaner/txPoolsCleaner.go
  process/block/poolsCleaner/txPoolsCleaner_test.go
  process/block/shardblock.go
  process/errors.go
  process/interface.go
  process/mock/poolscleanerMock.go
Labels: enhancement

#472 EN-4120: unit tests for rewards
  process/block/preprocess/rewardsHandler_test.go
  process/block/preprocess/smartContractResults_test.go
  process/rewardTransaction/export_test.go
  process/rewardTransaction/interceptedRewardTransaction_test.go
  process/rewardTransaction/interceptor_test.go
  process/rewardTransaction/process.go
  process/rewardTransaction/process_test.go
Labels: enhancement

#465 Arwen WASM VM integration.
  cmd/node/main.go
  go.mod
  go.sum
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/arwen/arwenVM_test.go
  integrationTests/vm/arwen/cpucalculate_arwen.wasm
  integrationTests/vm/arwen/fib_arwen.wasm
  integrationTests/vm/arwen/stringconcat_arwen.wasm
  integrationTests/vm/arwen/wrc20_arwen.wasm
  integrationTests/vm/iele/vmAgar_test.go
  integrationTests/vm/iele/vmDeploy_test.go
  integrationTests/vm/iele/vmRunContract_test.go
  integrationTests/vm/mockVM/vmGet_test.go
  integrationTests/vm/testInitializer.go
  process/factory/factory.go
  process/factory/shard/vmContainerFactory.go
  process/smartContract/hooks/vmAccountsDB.go
  process/smartContract/process.go
  process/smartContract/scDataGetter.go
  process/smartContract/scDataGetter_test.go
Labels: enhancement

#473 En 4003 sc results interceptors refactor
  process/factory/shard/interceptorsContainerFactory.go
  process/interceptors/factory/interceptedDataFactory.go
  process/interceptors/factory/interceptedDataFactory_test.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/processor/interface.go
  process/interceptors/processor/txInterceptorProcessor.go
  process/interceptors/processor/txInterceptorProcessor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/singleDataInterceptor_test.go
  process/interface.go
  process/mock/interceptedDataStub.go
  process/mock/interceptedTxHandlerStub.go
  process/mock/nilTxValidator.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  process/unsigned/interceptedUnsignedTransaction.go
  process/unsigned/interceptedUnsignedTransaction_test.go
  process/unsigned/interceptor.go
  process/unsigned/interceptor_test.go
Labels: enhancement

#480 En 4102 improve fork detector
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/errors.go
  process/interface.go
  process/mock/preprocessorMock.go
  process/mock/transactionCoordinatorMock.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/export_test.go
  process/sync/metaForkDetector.go
  process/sync/shardForkDetector.go
Labels: bug, enhancement

#479 En 4126 headers interceptors refactor
  process/block/interceptedBlockHeader.go
  process/block/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/argInterceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedMetaBlockHeader.go
  process/block/interceptedMetaBlockHeader_test.go
  process/block/interceptors/headerInterceptor.go
  process/block/interceptors/headerInterceptor_test.go
  process/block/interceptors/metachainHeaderInterceptor.go
  process/block/interceptors/metachainHeaderInterceptor_test.go
  process/block/interceptors/peerBlockBodyInterceptors_test.go
  process/block/interceptors/txBlockBodyInterceptors_test.go
  process/dataValidators/nilHeaderValidator.go
  process/dataValidators/nilHeaderValidator_test.go
  process/errors.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory.go
  process/interceptors/factory/argInterceptedDataFactory.go
  process/interceptors/factory/constants.go
  process/interceptors/factory/interceptedDataFactory_test.go
  process/interceptors/factory/metaInterceptedDataFactory.go
  process/interceptors/factory/metaInterceptedDataFactory_test.go
  process/interceptors/factory/shardInterceptedDataFactory.go
  process/interceptors/factory/shardInterceptedDataFactory_test.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/processor/argHdrInterceptorProcessor.go
  process/interceptors/processor/argTxInterceptorProcessor.go
  process/interceptors/processor/hdrInterceptorProcessor.go
  process/interceptors/processor/hdrInterceptorProcessor_test.go
  process/interceptors/processor/txInterceptorProcessor.go
  process/interceptors/processor/txInterceptorProcessor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/singleDataInterceptor_test.go
  process/interface.go
  process/mock/getHdrHandlerStub.go
  process/mock/headerValidatorStub.go
Labels: enhancement

#486 EN-4155-Fix-bug-with-processed-mini-blocks-from-meta-blocks
  core/computers.go
  data/block/block.go
  data/block/metaBlock.go
  data/interface.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interface.go
  process/mock/transactionCoordinatorMock.go
  process/sync/shardForkDetector.go
Labels: bug
