Repository multiversx/mx-chain-go, pull requests merged in 2019-08, with the labels that each got.

#317 EN-3218: AppStatusHandler integration and some prometheus custom metrics
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  consensus/chronology/chronology.go
  consensus/chronology/chronology_test.go
  consensus/chronology/errors.go
  consensus/mock/appStatusHandlerStub.go
  consensus/mock/statusHandlerMock.go
  core/appStatusPolling/appStatusPolling.go
  core/appStatusPolling/appStatusPolling_test.go
  core/appStatusPolling/errors.go
  core/constants.go
  core/interface.go
  core/mock/appStatusHandlerStub.go
  core/mock/connectedAddressesHandlerMock.go
  data/blockchain/blockchain.go
  data/blockchain/blockchain_test.go
  data/blockchain/errors.go
  integrationTests/consensus/consensus_test.go
  integrationTests/multiShard/block/testInitializer.go
  integrationTests/multiShard/metablock/testInitializer.go
  node/defineOptions.go
  node/defineOptions_test.go
  node/errors.go
  node/mock/appStatusFacadeStub.go
  node/mock/appStatusHandlerStub.go
  node/node.go
  node/node_test.go
  process/block/shardblock_test.go
  process/mock/appStatusHandlerStub.go
  process/sync/shardblock_test.go
  statusHandler/appStatusFacade.go
  statusHandler/appStatusFacade_test.go
  statusHandler/errors.go
  statusHandler/export_test.go
  statusHandler/mock/appStatusHandlerStub.go
  statusHandler/nilHandler.go
  statusHandler/prometheusHandler.go
  statusHandler/prometheusHandler_test.go
Labels: enhancement

#345 En 3350/implement vm factory
  cmd/node/factory/structs.go
  integrationTests/mock/vmContainerMock.go
  integrationTests/mock/vmExecutionHandlerStub.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/testInitializer.go
  process/factory/containers/export_test.go
  process/factory/containers/preProcessorsContainer.go
  process/factory/containers/preProcessorsContainer_test.go
  process/factory/containers/vmContainer.go
  process/factory/containers/vmContainer_test.go
  process/factory/factory.go
  process/factory/shard/vmContainerFactory.go
  process/factory/shard/vmContainerFactory_test.go
  process/interface.go
  process/mock/vmContainerMock.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/transaction/process_test.go
Labels: enhancement

#352 changed version to 1.0.12, appended runtime version, goos and goarch
  cmd/node/main.go
Labels: enhancement

#343 modified shard meta headers resolvers to query only metachain nodes
  dataRetriever/errors.go
  dataRetriever/factory/metachain/resolversContainerFactory.go
  dataRetriever/factory/shard/resolversContainerFactory.go
  dataRetriever/interface.go
  dataRetriever/mock/peerListCreatorStub.go
  dataRetriever/resolvers/topicResolverSender/diffPeerListCreator.go
  dataRetriever/resolvers/topicResolverSender/diffPeerListCreator_test.go
  dataRetriever/resolvers/topicResolverSender/export_test.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go
  integrationTests/mock/cacherStub.go
  integrationTests/mock/poolsHolderStub.go
  integrationTests/multiShard/block/interceptedBlocks_test.go
Labels: bug, enhancement

#358 bugfix/make transaction coordinator call processors in strict order when processing miniblocks
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/errors.go
Labels: bug

#357 EN 3274 reactivated tx nonce check on transactions
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/multiShard/block/executingMiniblocks_test.go
  integrationTests/multiShard/smartContract/executingSCCalls_test.go
  integrationTests/testWalletAccount.go
  process/block/interceptors/headerInterceptor.go
  process/block/interceptors/headerInterceptorBase.go
  process/block/interceptors/headerInterceptorBase_test.go
  process/block/interceptors/headerInterceptor_test.go
  process/block/interceptors/metachainHeaderInterceptor.go
  process/block/interceptors/metachainHeaderInterceptor_test.go
  process/block/preprocess/transactions.go
  process/dataValidators/nilHeaderValidator.go
  process/dataValidators/nilHeaderValidator_test.go
  process/dataValidators/nilTxValidator.go
  process/dataValidators/nilTxValidator_test.go
  process/errors.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory.go
  process/interface.go
  process/metablock/shardHeaderInterceptor.go
  process/metablock/shardHeaderInterceptor_test.go
  process/mock/headerValidatorStub.go
  process/mock/txValidatorStub.go
  process/transaction/interceptor.go
  process/transaction/interceptor_test.go
  process/transaction/process.go
  process/transaction/process_test.go
Labels: enhancement

#365 added a new appVersion var in main to be populated at build time
  cmd/node/main.go
Labels: enhancement

#350 Bugfix/added gasLimit check when creating cross shard miniBlocks
  integrationTests/longTests/executingSCTransactions_test.go
  integrationTests/singleShard/block/executingMiniblocksSc_test.go
  integrationTests/testGameHelperFunctions.go
  integrationTests/testInitializer.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/constants.go
Labels: enhancement

#354 Feat/en 2674 add account pk in nodesSetup.json
  cmd/node/config/nodesSetup.json
  cmd/node/factory/structs.go
  cmd/node/main.go
  consensus/mock/nodesCoordinatorMock.go
  consensus/mock/validatorMock.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/nodesCoordinatorMock.go
  integrationTests/multiShard/block/testInitializer.go
  integrationTests/multiShard/metablock/testInitializer.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/singleShard/block/testInitializer.go
  integrationTests/testInitializer.go
  node/mock/nodesCoordinatorMock.go
  node/mock/validatorMock.go
  process/block/interceptors/headerInterceptorBase_test.go
  process/block/interceptors/headerInterceptor_test.go
  process/mock/nodesCoordinatorMock.go
  sharding/errors.go
  sharding/export_test.go
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/interface.go
  sharding/mock/invalidNodesSetupMock.json
  sharding/mock/nodesCoordinatorMock.go
  sharding/mock/nodesSetupMock.json
  sharding/mock/validatorMock.go
  sharding/nodesSetup.go
  sharding/nodesSetup_test.go
  sharding/validator.go
  sharding/validator_test.go
Labels: enhancement

#367 fixed failing TestTpsBenchmark_Concurrent test
  core/statistics/tpsBenchmark.go
  core/statistics/tpsBenchmark_test.go
Labels: bug

#361 Feat/en 3280 improve set of last check point in fork detector
  consensus/mock/blockProcessorMock.go
  consensus/mock/forkDetectorMock.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  core/constants.go
  dataRetriever/dataPool/nonceSyncMapCacher.go
  dataRetriever/dataPool/nonceSyncMapCacher_test.go
  dataRetriever/interface.go
  dataRetriever/mock/uint64SyncMapCacherStub.go
  go.sum
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/forkDetectorMock.go
  integrationTests/multiShard/block/testInitializer.go
  integrationTests/multiShard/metablock/testInitializer.go
  integrationTests/multiShard/smartContract/testInitilalizer.go
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx_test.go
  integrationTests/multiShard/transaction/testInitializer.go
  integrationTests/testProcessorNode.go
  node/mock/blockProcessorStub.go
  node/mock/forkDetectorMock.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/displayBlock.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/interface.go
  process/mock/blockProcessorMock.go
  process/mock/forkDetectorMock.go
  process/mock/uint64SyncMapCacherStub.go
  process/sync/baseSync.go
  process/sync/basicForkDetector.go
  process/sync/basicForkDetector_test.go
  process/sync/export_test.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: bug, enhancement

#368 En 3542 fix heartbeat is active
  integrationTests/node/heartbeat_test.go
  integrationTests/testInitializer.go
  node/heartbeat/hearbeatMessageInfo.go
  node/heartbeat/heartbeat.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/heartbeat/sender.go
Labels: bug

#344 feat/EN-3483-merge-header-interceptors
  process/block/interceptors/headerInterceptor.go
  process/block/interceptors/headerInterceptorBase.go
  process/block/interceptors/headerInterceptorBase_test.go
  process/block/interceptors/headerInterceptor_test.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/metablock/shardHeaderInterceptor.go
  process/metablock/shardHeaderInterceptor_test.go
Labels: enhancement

#373 En 3563 update term ui
  api/api.go
  cmd/node/main.go
  core/constants.go
  facade/elrondNodeFacade.go
  facade/elrondNodeFacade_test.go
  statusHandler/termuiStatusHandler.go
  statusHandler/termuiStatusHandler_test.go
  statusHandler/termuic/termuiConsole.go
  statusHandler/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#374 Bugs/fix hb shard
  integrationTests/node/heartbeat_test.go
  node/heartbeat/errors.go
  node/heartbeat/heartbeat.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/heartbeat/sender.go
  node/node.go
Labels: bug

#381 added new interceptor implementations
  process/errors.go
  process/interceptors/common.go
  process/interceptors/common_test.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/singleDataInterceptor_test.go
  process/interface.go
  process/mock/interceptedDataFactoryStub.go
  process/mock/interceptedDataStub.go
  process/mock/interceptorProcessorStub.go
  process/mock/interceptorThrottlerStub.go
Labels: enhancement

#387 En 3609 bugfix interceptors should not broadcast when a direct msg has been received
  consensus/mock/sposWorkerMock.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  dataRetriever/interface.go
  dataRetriever/mock/hashSliceResolverStub.go
  dataRetriever/mock/headerResolverStub.go
  dataRetriever/mock/resolverStub.go
  dataRetriever/resolvers/genericBlockBodyResolver.go
  dataRetriever/resolvers/genericBlockBodyResolver_test.go
  dataRetriever/resolvers/headerResolver.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/transactionResolver.go
  dataRetriever/resolvers/transactionResolver_test.go
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/headerResolverMock.go
  integrationTests/mock/miniBlocksResolverMock.go
  integrationTests/p2p/peerDiscovery/messageProcessor.go
  integrationTests/p2p/pubsub/peerReceivingMessages_test.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/node_test.go
  p2p/example/libp2p/chatAdvertiser/main.go
  p2p/example/libp2p/internalBroadcastSpeedMeasure/main.go
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  p2p/libp2p/discovery/kadDhtDiscoverer_test.go
  p2p/libp2p/discovery/mdnsDiscoverer_test.go
  p2p/libp2p/issues_test.go
  p2p/libp2p/libp2pConnectionMonitor.go
  p2p/libp2p/libp2pConnectionMonitor_test.go
  p2p/libp2p/memMessenger.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/loadBalancer/outgoingChannelLoadBalancer_test.go
  p2p/memp2p/memp2p.go
  p2p/memp2p/memp2p_test.go
  p2p/mock/messageProcessorStub.go
  p2p/mock/mockMessageProcessor.go
  p2p/p2p.go
  process/block/interceptors/headerInterceptor.go
  process/block/interceptors/headerInterceptor_test.go
  process/block/interceptors/metachainHeaderInterceptor.go
  process/block/interceptors/metachainHeaderInterceptor_test.go
  process/block/interceptors/peerBlockBodyInterceptor.go
  process/block/interceptors/peerBlockBodyInterceptors_test.go
  process/block/interceptors/txBlockBodyInterceptor.go
  process/block/interceptors/txBlockBodyInterceptors_test.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/singleDataInterceptor_test.go
  process/interface.go
  process/mock/headerResolverMock.go
  process/mock/interceptorStub.go
  process/mock/miniBlocksResolverMock.go
  process/mock/resolverStub.go
  process/transaction/interceptor.go
  process/transaction/interceptor_test.go
  process/unsigned/interceptor.go
  process/unsigned/interceptor_test.go
Labels: bug

#389 EN-3576 - working on termui console, add a new table in grid with Blo…
  cmd/node/main.go
  core/constants.go
  statusHandler/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#392 integrationTests: add integration tests for signature verification on…
  cmd/node/main.go
  integrationTests/mock/keyMock.go
  integrationTests/multiShard/block/interceptedHeadersSigVerification_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/testWalletAccount.go
Labels: enhancement

#385 EN-3605 - heartbeat shard ID split into received and computed
  api/node/routes_test.go
  core/constants.go
  facade/elrondNodeFacade_test.go
  node/heartbeat/hearbeatMessageInfo.go
  node/heartbeat/hearbeatMessageInfo_test.go
  node/heartbeat/heartbeat.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/heartbeat/sender.go
  node/heartbeat/sender_test.go
Labels: enhancement

#397 Added startTimeStamp to session.info
  cmd/node/main.go
Labels: enhancement

#399 EN-2890 : remove second generation of the genesis block
  cmd/node/factory/structs.go
  cmd/node/main.go
  core/genesis/genesisBlockCreator.go
  node/node.go
  node/node_test.go
Labels: enhancement

#406 fixed bug that could not generate bulk transactions
  cmd/node/factory/structs.go
  cmd/node/main.go
  node/defineOptions.go
  node/node.go
  sharding/nodesSetup.go
  sharding/nodesSetup_test.go
Labels: bug
