Repository multiversx/mx-chain-go, pull requests merged in 2020-07, with the labels that each got.

#2024 fix destination shard as observer (dev branch)
  cmd/node/config/prefs.toml
  cmd/node/main.go
  core/constants.go
  epochStart/bootstrap/fromLocalStorage.go
  epochStart/bootstrap/process.go
Labels: enhancement

#1823 generic API responses
  api/address/routes.go
  api/address/routes_test.go
  api/hardfork/routes.go
  api/hardfork/routes_test.go
  api/network/routes.go
  api/node/routes.go
  api/node/routes_test.go
  api/shared/shared.go
  api/transaction/routes.go
  api/transaction/routes_test.go
  api/validator/routes.go
  api/validator/routes_test.go
  api/vmValues/routes.go
  api/vmValues/routes_test.go
  cmd/termui/provider/metricsProvider.go
  vm/systemSmartContracts/esdt_test.go
Labels: enhancement

#2082 EN-7054: Rest API endpoints throttlers
  api/errors/errors.go
  api/middleware/globalThrottler.go
  api/mock/facade.go
  api/mock/throttlerStub.go
  api/shared/shared.go
  api/transaction/routes.go
  api/transaction/routes_test.go
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
  core/interface.go
  debug/antiflood/debugger.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  node/node.go
  node/nodeTransactions.go
  node/nodeTransactions_test.go
  node/options.go
Labels: enhancement

#2086 EN-7056: GolangCI fixes
  cmd/node/main.go
  consensus/mock/broadcastMessangerMock.go
  core/alarm/alarm_test.go
  core/converters.go
  core/converters_test.go
  crypto/signing/mcl/multisig/bls_test.go
  dataRetriever/txpool/memorytests/memory_test.go
  debug/antiflood/debugger.go
  debug/p2p/p2pDebugger.go
  epochStart/bootstrap/process.go
  facade/nodeFacade.go
  genesis/data/initialAccount.go
  genesis/process/intermediate/deployProcessor.go
  integrationTests/longTests/antiflooding/messageProcessor.go
  integrationTests/longTests/storage/storagePutRemove_test.go
  integrationTests/testInitializer.go
  integrationTests/vm/systemVM/stakingSC_test.go
  node/node.go
  node/nodeMemoryConfig_test.go
  process/block/preprocess/rewardTxPreProcessor_test.go
  process/factory/interceptorscontainer/args.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory.go
  process/interceptors/factory/interceptedShardHeaderDataFactory.go
  process/peer/validatorsProvider.go
  process/scToProtocol/stakingToPeer_test.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/sync/baseForkDetector.go
  process/throttle/antiflood/floodPreventers/quotaFloodPreventer.go
  process/transaction/interceptedTransaction.go
  sharding/hashValidatorShuffler.go
  sharding/hashValidatorShuffler_test.go
  storage/factory/pruningStorerFactory.go
  storage/immunitycache/chunk.go
  storage/pruning/pruningStorer.go
  storage/txcache/monitoring.go
  storage/txcache/txListForSender.go
  update/trigger/trigger.go
  vm/systemSmartContracts/eei_test.go
Labels: enhancement

#2084 renamed fullArchive to cleanOldEpochsData
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
  epochStart/bootstrap/process_test.go
  storage/factory/pruningStorerFactory.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorerArgs.go
  storage/pruning/pruningStorer_test.go
  testscommon/generalConfig.go
Labels: enhancement

#2096 Avoid whitelisting out of range block data
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/export_test.go
Labels: bug, enhancement

#2092 Api middlewares refactor
  api/address/routes_test.go
  api/api.go
  api/errors/errors.go
  api/hardfork/routes.go
  api/hardfork/routes_test.go
  api/middleware/errors.go
  api/middleware/export_test.go
  api/middleware/globalThrottler.go
  api/middleware/globalThrottler_test.go
  api/middleware/middleware.go
  api/middleware/middleware_test.go
  api/middleware/sourceThrottler.go
  api/middleware/sourceThrottler_test.go
  api/middleware/testing.go
  api/mock/hardforkFacade.go
  api/network/routes_test.go
  api/transaction/routes_test.go
  api/validator/routes_test.go
  cmd/node/config/genesis.json
  cmd/node/config/nodesSetup.json
  facade/nodeFacade.go
Labels: bug

#2105 Fix whitelisting in advance for miniblocks
  epochStart/bootstrap/disabled/disabledValidityAttester.go
  epochStart/metachain/epochStartData.go
  epochStart/metachain/epochStartData_test.go
  integrationTests/mock/blockTrackerStub.go
  node/mock/blockTrackerStub.go
  process/block/baseProcess.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader.go
  process/block/metablock.go
  process/block/shardblock.go
  process/constants.go
  process/interface.go
  process/mock/blockTrackerMock.go
  process/mock/finalityAttesterStub.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
Labels: bug

#2112 Fix sync speed problem with attesting finality headers which are not requested in advance
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/shardblock.go
  process/block/shardblock_test.go
Labels: bug

#2089 Refactor multi file system in hardfork
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
  data/mock/memDbMock.go
  data/mock/storerStub.go
  dataRetriever/mock/storerStub.go
  epochStart/mock/storerMock.go
  epochStart/mock/storerStub.go
  genesis/mock/storerMock.go
  genesis/process/genesisBlockCreator.go
  heartbeat/mock/storerMock.go
  heartbeat/mock/storerStub.go
  integrationTests/mock/countingDB.go
  integrationTests/mock/dbMock.go
  integrationTests/mock/storerMock.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  node/mock/storerStub.go
  process/mock/storerMock.go
  process/mock/storerStub.go
  sharding/mock/storerMock.go
  statusHandler/mock/storerStub.go
  storage/interface.go
  storage/leveldb/common.go
  storage/leveldb/leveldb_test.go
  storage/memorydb/lruMemoryDB.go
  storage/memorydb/lruMemoryDB_test.go
  storage/memorydb/memorydb.go
  storage/memorydb/memorydb_test.go
  storage/mock/storerStub.go
  storage/pruning/pruningStorer.go
  storage/storageUnit/nilStorer.go
  storage/storageUnit/storageunit.go
  update/errors.go
  update/factory/exportHandlerFactory.go
  update/files/multiFileReader.go
  update/files/multiFileReader_test.go
  update/files/multiFileWriter.go
  update/files/multiFileWriter_test.go
  update/genesis/base.go
  update/genesis/export.go
  update/genesis/export_test.go
  update/genesis/import.go
  update/genesis/import_test.go
  update/interface.go
  update/mock/hardforkStorerStub.go
  update/mock/multiFileReaderStub.go
  update/mock/multiFileWriterStub.go
  update/mock/storerMock.go
  update/mock/storerStub.go
  update/storing/hardforkStorer.go
  update/storing/hardforkStorer_test.go
Labels: enhancement

#2120 Fix mbs and txs requests in advance when node is syncing
  cmd/node/factory/structs.go
  cmd/node/main.go
  core/constants.go
  epochStart/shardchain/trigger.go
  epochStart/shardchain/triggerRegistry_test.go
  epochStart/shardchain/trigger_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testProcessorNode.go
  process/block/baseProcess.go
  process/coordinator/process.go
  update/errors.go
  update/factory/exportHandlerFactory.go
Labels: bug, enhancement

#2116 Refactored API (again)
  api/address/routes.go
  api/address/routes_test.go
  api/api.go
  api/errors/errors.go
  api/hardfork/routes.go
  api/hardfork/routes_test.go
  api/middleware/endpointThrottler.go
  api/middleware/endpointThrottler_test.go
  api/middleware/errors.go
  api/middleware/export_test.go
  api/middleware/globalThrottler.go
  api/middleware/globalThrottler_test.go
  api/middleware/middleware.go
  api/middleware/middleware_test.go
  api/middleware/sourceThrottler.go
  api/middleware/sourceThrottler_test.go
  api/middleware/testing.go
  api/network/routes.go
  api/network/routes_test.go
  api/node/routes.go
  api/node/routes_test.go
  api/shared/shared.go
  api/transaction/routes.go
  api/transaction/routes_test.go
  api/validator/routes.go
  api/validator/routes_test.go
  api/vmValues/routes.go
  api/vmValues/routes_test.go
  facade/nodeFacade.go
Labels: bug

#2130 Fix number of shard headers included in one meta block
  process/block/metablock.go
  process/constants.go
Labels: bug, enhancement

#2131 Tuned up some constants to improve catch up speed
  cmd/node/config/config.toml
  process/block/baseProcess_test.go
  process/block/metablock.go
  process/constants.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockProcessor_test.go
Labels: enhancement

#2128 Add validator stats root hash to genesis block
  cmd/node/factory/structs.go
Labels: bug

#2134 Add display for current and peak TPS in meta nodes
  integrationTests/mock/rounderMock.go
  process/block/displayMetaBlock.go
  process/block/metablock.go
  process/block/metablock_test.go
Labels: enhancement

#2136 Payable / non-payable contracts, Arwen update, upgrade fixes
  Makefile
  cmd/node/factory/structs.go
  data/smartContractResult/proto/smartContractResult.proto
  data/smartContractResult/smartContractResult.pb.go
  genesis/mock/blockChainHookHandlerMock.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  go.mod
  go.sum
  integrationTests/mock/blockChainHookHandlerMock.go
  integrationTests/mock/oneSCExecutorMockVM.go
  integrationTests/mock/scProcessorMock.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/oneNodeNetwork.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/arwen/arwenVM/arwenVM_test.go
  integrationTests/vm/arwen/testdata/delegation/delegation.wasm
  integrationTests/vm/arwen/testdata/hello-v1/answer.c
  integrationTests/vm/arwen/testdata/hello-v1/answer.export
  integrationTests/vm/arwen/testdata/hello-v1/answer.wasm
  integrationTests/vm/arwen/testdata/hello-v1/output/answer.wasm
  integrationTests/vm/arwen/testdata/hello-v2/output/answer.wasm
  integrationTests/vm/arwen/testdata/hello-v3/output/answer.wasm
  integrationTests/vm/arwen/testdata/upgrades-parent/output/parent.wasm
  integrationTests/vm/arwen/testdata/upgrades-parent/parent.cpp
  integrationTests/vm/arwen/testdata/upgrades-parent/parent.wasm
  integrationTests/vm/arwen/upgrades/upgrades_test.go
  integrationTests/vm/arwen/utils.go
  integrationTests/vm/testInitializer.go
  process/errors.go
  process/interface.go
  process/mock/blockChainHookHandlerMock.go
  process/mock/scProcessorMock.go
  process/mock/temporaryAccountsHandlerMock.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/blockChainHook_test.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/transaction/baseProcess.go
  process/transaction/export_test.go
  process/transaction/metaProcess.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
  vm/mock/blockChainHookStub.go
Labels: bug, enhancement

#2152 Fix txPoolsCleaner component for rewards transactions received by metachain nodes
  process/block/poolsCleaner/miniBlocksPoolsCleaner.go
  process/block/poolsCleaner/txsPoolsCleaner.go
  process/block/poolsCleaner/txsPoolsCleaner_test.go
  process/rewardTransaction/interceptedRewardTransaction.go
Labels: bug

#2171 Bug fix/waiting list unstake edge case
  cmd/node/config/systemSmartContractsConfig.toml
  integrationTests/multiShard/relayedTx/relayedTx_test.go
  integrationTests/vm/esdt/esdtProcess_test.go
  process/smartContract/builtInFunctions/esdtTransfer.go
  process/smartContract/builtInFunctions/esdtTransfer_test.go
  sharding/indexHashedNodesCoordinator_test.go
  update/genesis/import.go
  update/process/shardBlock.go
  update/sync/coordinator_test.go
  vm/interface.go
  vm/mock/systemEIStub.go
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/auction.pb.go
  vm/systemSmartContracts/auction_test.go
  vm/systemSmartContracts/eei.go
  vm/systemSmartContracts/esdt.go
  vm/systemSmartContracts/governance.go
  vm/systemSmartContracts/governance_test.go
  vm/systemSmartContracts/proto/auction.proto
  vm/systemSmartContracts/staking.go
  vm/systemSmartContracts/stakingWithWaiting_test.go
Labels: bug
