Repository multiversx/mx-chain-go, pull requests merged in 2020-02, with the labels that each got.

#1042 En-5688: disabled option for antiflood
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  consensus/spos/worker.go
  p2p/antiflood/factory/disabledAntiFlood.go
  p2p/antiflood/factory/disabledAntiFlood_test.go
  p2p/antiflood/factory/disabledBlacklist.go
  p2p/antiflood/factory/disabledBlacklist_test.go
  p2p/antiflood/factory/p2pAntifloodAndBlacklistFactory.go
  p2p/antiflood/factory/p2pAntifloodAndBlacklistFactory_test.go
  p2p/errors.go
  p2p/mock/appStatusHandlerMock.go
Labels: enhancement

#1047 Fixed unnecessary requests of mini blocks
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/shardblock.go
Labels: bug

#1057 Intercepted tx changed trace print
  integrationTests/multiShard/block/executingMiniblocks_test.go
  p2p/libp2p/netMessenger.go
  p2p/p2p.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/rewardsHandler.go
  process/block/preprocess/rewardsHandler_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interceptors/common.go
  process/interceptors/common_test.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/processor/txInterceptorProcessor.go
  process/interceptors/singleDataInterceptor.go
  process/interface.go
Labels: bug

#1062 Fix rewards txs collision
  data/rewardTx/rewardTx.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardsHandler.go
  process/block/preprocess/rewardsHandler_test.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
Labels: bug

#1065 added the possibility to log to file directly from the node
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
  config/tomlConfig_test.go
  logger/redirects/redirectStderrDarwin.go
  logger/redirects/redirectStderrLinux.go
  logger/redirects/redirectStderrWindows.go
  scripts/testnet/include/nodes.sh
Labels: enhancement

#1069 Changed log level for display calculated rewards txs
  process/block/preprocess/rewardsHandler.go
Labels: enhancement

#1079 Fix edge case in sync state
  process/sync/baseSync.go
  process/sync/export_test.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
Labels: bug

#1045 En 5459/hard fork interceptors data trie container
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  dataRetriever/errors.go
  dataRetriever/interface.go
  dataRetriever/mock/whiteListHandlerStub.go
  dataRetriever/requestHandlers/requestHandler.go
  dataRetriever/requestHandlers/requestHandler_test.go
  integrationTests/testProcessorNode.go
  node/mock/interceptorContainerStub.go
  process/errors.go
  process/factory/containers/interceptorsContainer.go
  process/factory/containers/interceptorsContainer_test.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/metachain/interceptorsContainerFactory_test.go
  process/factory/shard/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory_test.go
  process/interceptors/defaultDataVerifier.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/singleDataInterceptor_test.go
  process/interceptors/whiteListDataVerifier.go
  process/interface.go
  process/mock/interceptedDataVerifierMock.go
  process/mock/interceptorStub.go
  process/mock/whiteListHandlerStub.go
  update/errors.go
  update/factory/dataTrieFactory.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncInterceptorsContainerFactory.go
  update/factory/fullSyncResolversContainerFactory.go
  update/factory/trieSyncersContainerFactory.go
Labels: enhancement

#1085 autoclosing persisters when GC tries to collect the persister instance
  storage/leveldb/leveldb.go
  storage/leveldb/leveldbSerial.go
Labels: bug

#1075 Fix commit with longer time
  cmd/node/config/config.toml
  consensus/spos/bls/subroundEndRound.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/postprocess/intermediateResults.go
  process/block/postprocess/oneMBPostProcessor.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  storage/errors.go
  storage/factory/pruningStorerFactory.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorerArgs.go
  storage/pruning/pruningStorer_test.go
  storage/storageUnit/storageunit.go
  storage/storageUnit/storageunit_test.go
Labels: enhancement

#1084 Integration test for out of order tx execution between proposer and validator
  integrationTests/multiShard/block/edgecases_test.go
  integrationTests/testProcessorNodeWithCoordinator.go
  process/block/shardblock.go
Labels: bug

#1096 Fix-block-tracker-cleaning-problem
  integrationTests/mock/blockTrackerStub.go
  integrationTests/multiShard/block/edgecases_test.go
  node/mock/blockTrackerStub.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/common.go
  process/interface.go
  process/mock/blockTrackerMock.go
  process/rewardTransaction/process.go
  process/smartContract/process.go
  process/throttle/block.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/export_test.go
  process/transaction/metaProcess.go
  process/transaction/shardProcess.go
Labels: bug

#1102 removed the dependency between the node and cmd package, removed some…
  cmd/node/factory/structs.go
  core/constants.go
  node/node.go
Labels: bug

#1073 En 5722 tsc fix blake empty value hash size
  cmd/node/factory/structs.go
  hashing/blake2b/blake2b.go
  hashing/blake2b/blake2b_test.go
  hashing/hasher_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/multisig/blsMultisig_test.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  storage/bloom/bloom.go
  storage/bloom/bloom_test.go
  storage/storageUnit/storageunit.go
  storage/storageUnit/storageunit_test.go
Labels: bug

#1089 Optimised validator statistics - bulk trie write for missed blocks
  process/mock/peerAccountHandlerMock.go
  process/peer/export_test.go
  process/peer/process.go
  process/peer/process_test.go
  process/peer/validatorCounters.go
  process/peer/validatorsCounters_test.go
Labels: bug, enhancement

#1080 Hard fork export all unfinished metablocks and miniblocks
  epochStart/metachain/trigger.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/systemVM/systemVm_test.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/processor/txBodyInterceptorProcessor.go
  process/interceptors/processor/txBodyInterceptorProcessor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/whiteListDataVerifier.go
  update/errors.go
  update/factory/dataTrieFactory.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncResolversContainerFactory.go
  update/files/multiFileWriter.go
  update/genesis/base.go
  update/genesis/export.go
  update/genesis/import.go
  update/interface.go
  update/mock/epochMiniBlocksSyncHandlerMock.go
  update/mock/headerSyncHandlerMock.go
  update/mock/headerSyncHandlerStub.go
  update/mock/uint64ByteSliceConverterStub.go
  update/sync/base.go
  update/sync/coordinator.go
  update/sync/coordinator_test.go
  update/sync/nilSyncTries.go
  update/sync/syncHeaders.go
  update/sync/syncHeaders_test.go
  update/sync/syncMiniBlocks.go
  update/sync/syncMiniBlocks_test.go
  update/sync/syncTransactions.go
Labels: enhancement

#1099 Eb 5748/accumulated fee to header
  cmd/node/factory/structs.go
  consensus/mock/headerHandlerStub.go
  data/address/specialAddresses.go
  data/address/specialAddresses_test.go
  data/block/block.go
  data/block/metaBlock.go
  data/interface.go
  epochStart/genesis/genesisBlockCreator.go
  epochStart/genesis/genesisFeeHandler.go
  integrationTests/mock/specialAddressHandlerMock.go
  integrationTests/mock/unsignedTxHandlerMock.go
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/multiShard/block/executingRewardMiniblocks_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/testSyncNode.go
  process/block/argProcessor.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/metrics.go
  process/block/postprocess/feeHandler.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/export_test.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardTxPreProcessor_test.go
  process/block/preprocess/rewardsHandler.go
  process/block/preprocess/rewardsHandler_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/errors.go
  process/factory/metachain/feeHandler.go
  process/factory/shard/intermediateProcessorsContainerFactory.go
  process/factory/shard/intermediateProcessorsContainerFactory_test.go
  process/factory/shard/preProcessorsContainerFactory.go
  process/factory/shard/preProcessorsContainerFactory_test.go
  process/interface.go
  process/mock/feeAccumulatorStub.go
  process/mock/headerHandlerStub.go
  process/mock/specialAddressHandlerMock.go
  process/mock/unsignedTxHandlerMock.go
  process/rewardTransaction/process.go
  process/rewardTransaction/process_test.go
  process/smartContract/process_test.go
  process/transaction/shardProcess_test.go
Labels: enhancement

#1107 added more info to existing prints
  process/interceptors/multiDataInterceptor.go
  process/interceptors/singleDataInterceptor.go
Labels: enhancement

#1095 En 5747/implement reward to sc developer
  cmd/node/config/economics.toml
  config/economicsConfig.go
  core/computers.go
  data/state/account.go
  data/state/errors.go
  data/state/interface.go
  data/state/journalEntries.go
  epochStart/genesis/genesisFeeHandler.go
  integrationTests/longTests/executingSCTransactions_test.go
  integrationTests/mock/feeHandlerStub.go
  integrationTests/mock/scProcessorMock.go
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/singleShard/block/executingMiniblocksSc_test.go
  node/mock/txFeeHandlerStub.go
  process/coordinator/transactionType.go
  process/coordinator/transactionType_test.go
  process/economics/economicsData.go
  process/errors.go
  process/interface.go
  process/mock/accountWrapperFake.go
  process/mock/dataTrieTrackerStub.go
  process/mock/feeHandlerStub.go
  process/mock/scProcessorMock.go
  process/mock/trieStub.go
  process/mock/userAccountStub.go
  process/smartContract/changeOwnerAddress.go
  process/smartContract/claimDeveloperRewards.go
  process/smartContract/export_test.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/transaction/baseProcess.go
  process/transaction/export_test.go
  process/transaction/metaProcess_test.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
Labels: enhancement

#1106 configuration and flags refactoring
  cmd/node/config/config.toml
  cmd/node/config/external.toml
  cmd/node/config/prefs.toml
  cmd/node/config/server.toml
  cmd/node/factory/structsStatusHandlers.go
  cmd/node/main.go
  config/config.go
  config/externalConfig.go
  config/prefsConfig.go
  config/tomlConfig_test.go
  core/configParser.go
  core/configParser_test.go
  scripts/testnet/include/config.sh
Labels: enhancement

#1112 made seednode work on network-sharding branch
  cmd/seednode/config/p2p.toml
  cmd/seednode/main.go
Labels: bug

#1087 En 5699 tx packing
  api/mock/facade.go
  api/transaction/routes.go
  api/transaction/routes_test.go
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  cmd/seednode/config/p2p.toml
  config/config.go
  core/accumulator/export_test.go
  core/accumulator/timeAccumulator.go
  core/accumulator/timeAccumulator_test.go
  core/constants.go
  core/errors.go
  facade/elrondNodeFacade.go
  facade/elrondNodeFacade_test.go
  facade/interface.go
  facade/mock/nodeMock.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  node/errors.go
  node/interface.go
  node/mock/accumulatorMock.go
  node/node.go
  node/node_test.go
  node/options.go
  node/options_test.go
Labels: enhancement

#1113 remove num-of-nodes option
  cmd/node/main.go
  sharding/nodesSetup.go
  sharding/nodesSetup_test.go
Labels: bug

#1122 changed refresh topic peers interval values
  p2p/libp2p/netMessenger.go
  p2p/libp2p/peersOnChannel.go
  scripts/testnet/include/nodes.sh
Labels: bug

#1078 EN-5729: new consensus group selection algorithm
  core/converters.go
  core/converters_test.go
  integrationTests/multiShard/block/interceptedHeadersSigVerification_test.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/testWalletAccount.go
  sharding/common.go
  sharding/common_test.go
  sharding/consensusGroupProviderBench_test.go
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/mock/nodesCoordinatorMock.go
  sharding/selectionBasedProvider.go
  sharding/selectionBasedProvider_test.go
Labels: enhancement

#1064 EN-5714: refactor duplicated code
  cmd/node/factory/structs.go
  dataRetriever/factory/metachain/resolversContainerFactory.go
  dataRetriever/factory/metachain/resolversContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/args.go
  dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go
  dataRetriever/factory/shard/resolversContainerFactory.go
  dataRetriever/factory/shard/resolversContainerFactory_test.go
  integrationTests/testProcessorNode.go
  process/factory/interceptorscontainer/args.go
  process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/metachain/interceptorsContainerFactory_test.go
  process/factory/shard/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory_test.go
  process/factory/shard/intermediateProcessorsContainerFactory_test.go
Labels: enhancement

#1125 En 5752/rewards per block end of epoch
  cmd/node/config/economics.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  cmd/node/metrics/metrics.go
  config/economicsConfig.go
  config/tomlConfig_test.go
  consensus/mock/blockProcessorMock.go
  consensus/mock/mockTestInitializer.go
  consensus/mock/nodesCoordinatorMock.go
  consensus/round/round.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlock_test.go
  data/block/metaBlock.go
  data/mock/nodesCoordinatorMock.go
  epochStart/genesis/genesisBlockCreator.go
  integrationTests/consensus/consensus_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/epochEconomicsStub.go
  integrationTests/mock/epochStartDataCreatorStub.go
  integrationTests/mock/nodesCoordinatorMock.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/singleShard/block/consensusNotAchieved_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  integrationTests/vm/systemVM/systemVm_test.go
  node/mock/blockProcessorStub.go
  node/mock/nodesCoordinatorMock.go
  process/block/argProcessor.go
  process/block/epochStartData.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/economics/economicsData.go
  process/economics/economicsData_test.go
  process/economics/rewardsPerBlock.go
  process/errors.go
  process/factory/metachain/vmContainerFactory_test.go
  process/interface.go
  process/mock/blockProcessorMock.go
  process/mock/epochEconomicsStub.go
  process/mock/epochStartDataCreatorStub.go
  process/mock/nodesCoordinatorMock.go
  process/mock/validatorSettingsStub.go
  process/peer/process_test.go
  sharding/indexHashedNodesCoordinator.go
  sharding/interface.go
  vm/factory/systemSCFactory.go
  vm/mock/validatorSettingsStub.go
  vm/systemSmartContracts/staking.go
Labels: enhancement

#1135 Fix try sync trigger condition
  process/sync/baseSync.go
Labels: bug

#1128 En 5800 added harmonic mean in ntp synchronization
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
  core/computers.go
  core/computers_test.go
  integrationTests/consensus/testInitializer.go
  ntp/errors.go
  ntp/export_test.go
  ntp/syncTime.go
  ntp/syncTime_test.go
Labels: enhancement

#1117 added new host wrapper, sharder aware
  cmd/node/config/p2p.toml
  consensus/spos/worker.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/testP2PNode.go
  p2p/errors.go
  p2p/libp2p/connectionMonitor/factory/connectionMonitorFactory.go
  p2p/libp2p/connectionMonitor/factory/connectionMonitorFactory_test.go
  p2p/libp2p/connectionMonitor/factory/interface.go
  p2p/libp2p/connectionMonitor/interface.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitor.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple_test.go
  p2p/libp2p/connectionMonitor/nilConnectionMonitor.go
  p2p/libp2p/discovery/continuousKadDhtDiscoverer.go
  p2p/libp2p/discovery/hostWithConnectionManagement.go
  p2p/libp2p/discovery/hostWithConnectionManagement_test.go
  p2p/libp2p/discovery/interface.go
  p2p/libp2p/interface.go
  p2p/libp2p/metrics/connections.go
  p2p/libp2p/metrics/connections_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/networksharding/factory/sharderFactory.go
  p2p/libp2p/networksharding/factory/sharderFactory_test.go
  p2p/libp2p/networksharding/listKadSharder.go
  p2p/libp2p/networksharding/listKadSharder_test.go
  p2p/mock/sharderStub.go
  p2p/p2p.go
Labels: enhancement

#1140 En 5754/rewards interceptors
  core/indexer/elasticsearch.go
  data/rewardTx/rewardTx.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go
  epochStart/metachain/rewards.go
  integrationTests/mock/nodesCoordinatorMock.go
  integrationTests/multiShard/endOfEpoch/executingEpochChange_test.go
  integrationTests/resolvers/rewards_test.go
  integrationTests/resolvers/testInitializer.go
  integrationTests/singleShard/transaction/interceptedResolvedTx_test.go
  integrationTests/state/stateTrie_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  process/block/baseProcess_test.go
  process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  process/peer/process.go
  process/rewardTransaction/interceptedRewardTransaction.go
  process/rewardTransaction/interceptedRewardTransaction_test.go
  process/rewardTransaction/process_test.go
Labels: enhancement

#1154 Fixed an edge case when node not requests next cross header
  cmd/node/factory/structs.go
  process/constants.go
  process/interface.go
  process/track/argBlockProcessor.go
  process/track/argBlockTrack.go
  process/track/baseBlockTrack.go
  process/track/blockProcessor.go
  process/track/blockProcessor_test.go
  process/track/errors.go
  process/track/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: bug

#1158 Fix sync problem on epoch change
  process/block/metablock.go
  process/block/shardblock.go
  process/sync/baseSync.go
Labels: bug

#1056 En 5464 peer rating chance computer
  cmd/node/config/economics.toml
  cmd/node/main.go
  config/economicsConfig.go
  consensus/mock/nodesCoordinatorMock.go
  data/mock/nodesCoordinatorMock.go
  integrationTests/interface.go
  integrationTests/mock/nodesCoordinatorMock.go
  integrationTests/mock/raterMock.go
  integrationTests/mock/ratingReaderMock.go
  integrationTests/multiShard/endOfEpoch/executingEpochChange_test.go
  integrationTests/nodesCoordinatorFactory.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  node/mock/nodesCoordinatorMock.go
  process/economics/interface.go
  process/economics/ratingsData.go
  process/economics/selectionData.go
  process/errors.go
  process/interface.go
  process/mock/nodesCoordinatorMock.go
  process/mock/raterMock.go
  process/mock/ratingReaderMock.go
  process/mock/ratingsInfoMock.go
  process/peer/process.go
  process/peer/ratingReader.go
  process/rating/blockSigningRater.go
  process/rating/blockSigningRater_test.go
  process/rating/chance.go
  process/rating/nilRatingReader.go
  sharding/errors.go
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinatorWithRater.go
  sharding/indexHashedNodesCoordinatorWithRater_test.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/interface.go
  sharding/mock/raterMock.go
Labels: bug, enhancement

#1162 fixed evictionDB creation parameter passing
  data/trie/factory/trieCreator.go
  data/trie/trieStorageManager.go
  storage/storageUnit/storageunit.go
  storage/storageUnit/storageunit_test.go
Labels: bug
