Repository multiversx/mx-chain-go, pull requests merged in 2020-05, with the labels that each got.

#1497 fixed closing the bootstrap storage
  storage/factory/bootstrapDataProvider.go
  storage/leveldb/common.go
  storage/leveldb/leveldb.go
  storage/leveldb/leveldbSerial.go
  storage/leveldb/leveldb_test.go
Labels: bug

#1503 fixed cleaning of header cache after the block tracker initialization
  dataRetriever/requestHandlers/requestHandler.go
  debug/resolver/interceptorResolver.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  process/interceptors/processor/miniblockInterceptorProcessor.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
  sharding/nodesSetup.go
Labels: bug

#1512 Fix sync speed problem
  core/computers.go
  core/computers_test.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/shardblock.go
Labels: bug

#1510 En 6169 system tests
  cmd/node/main.go
  genesis/checking/nodesSetupChecker.go
  genesis/data/initialAccount.go
  genesis/data/initialSmartContract_test.go
  genesis/errors.go
  genesis/interface.go
  genesis/mock/deployProcessorStub.go
  genesis/mock/initialNodesHandlerStub.go
  genesis/mock/nodeInfoMock.go
  genesis/mock/nodesListSplitterStub.go
  genesis/mock/shardCoordinatorMock.go
  genesis/mock/smartContractParserStub.go
  genesis/mock/txExecutionProcessorStub.go
  genesis/parsing/accountsParser.go
  genesis/parsing/accountsParser_test.go
  genesis/process/interface.go
  genesis/process/intermediate/delegationDeployProcessor.go
  genesis/process/intermediate/delegationDeployProcessor_test.go
  genesis/process/intermediate/delegationProcessor.go
  genesis/process/intermediate/delegationProcessor_test.go
  genesis/process/intermediate/deployProcessor.go
  genesis/process/intermediate/deployProcessor_test.go
  genesis/process/intermediate/nodesListSplitter.go
  genesis/process/intermediate/nodesListSplitter_test.go
  genesis/process/intermediate/testdata/dummy.txt
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/mock/nodesHandlerMock.go
  scripts/testnet/include/config.sh
  scripts/testnet/variables.sh
Labels: enhancement

#1518 Fix edge case on reset probable highest nonce
  process/constants.go
  process/sync/baseSync.go
  process/sync/export_test.go
  process/sync/shardblock_test.go
Labels: bug

#1462 EN-6261: new Rest API routes
  api/api.go
  api/network/routes.go
  api/network/routes_test.go
  api/node/routes.go
  cmd/node/main.go
  cmd/node/metrics/metrics.go
  core/constants.go
  node/external/interface.go
  node/mock/statusMetricsStub.go
  process/economics/economicsData.go
  statusHandler/statusMetricsProvider.go
Labels: enhancement

#1447 EN-6253: api routes config file
  api/address/routes.go
  api/address/routes_test.go
  api/api.go
  api/hardfork/routes.go
  api/hardfork/routes_test.go
  api/middleware/globalThrottler_test.go
  api/middleware/sourceThrottler_test.go
  api/network/routes.go
  api/network/routes_test.go
  api/node/routes.go
  api/node/routes_test.go
  api/transaction/routes.go
  api/transaction/routes_test.go
  api/validator/routes.go
  api/validator/routes_test.go
  api/vmValues/routes.go
  api/vmValues/routes_test.go
  api/wrapper/errors.go
  api/wrapper/routerWrapper.go
  cmd/node/config/api.toml
  cmd/node/main.go
  config/config.go
  config/tomlConfig_test.go
  facade/errors.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
Labels: enhancement

#1513 EN-6290: change tx data field back to string
  api/mock/facade.go
  api/transaction/routes.go
  api/transaction/routes_test.go
  cmd/node/config/config.toml
  data/transaction/transaction.go
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  integrationTests/frontend/wallet/txInterception_test.go
  integrationTests/testProcessorNode.go
  marshal/factory/marshalizerFactory.go
  marshal/txJsonMarshalizer.go
  marshal/txJsonMarshalizer_test.go
  node/node.go
  node/node_test.go
Labels: enhancement

#1526 sync should be critical error in bootstrap
  epochStart/bootstrap/epochStartMetaBlockProcessor.go
  epochStart/bootstrap/process.go
Labels: bug

#1712 EN-6400: fix golangci issues
  api/node/routes.go
  cmd/node/main.go
  config/config.go
  epochStart/bootstrap/epochStartMetaBlockProcessor_test.go
  epochStart/bootstrap/process.go
  factory/coreComponents.go
  integrationTests/vm/arwen/arwenVM/arwenVM_test.go
  integrationTests/vm/esdt/esdtProcess_test.go
  integrationTests/vm/iele/vmRunContract/vmRunContract_test.go
  marshal/txJsonMarshalizer_test.go
  process/block/shardblock.go
  process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  process/scToProtocol/stakingToPeer_test.go
  process/smartContract/builtInFunctions/claimDeveloperRewards_test.go
  process/smartContract/process_test.go
  process/throttle/antiflood/floodPreventers/topicFloodPreventer.go
  storage/pruning/pruningStorer.go
  storage/txcache/maps/bucketSortedMap_test.go
  storage/txcache/testutils_test.go
  storage/txcache/txListForSenderAsSortedMapItem.go
  vm/factory/systemSCFactory.go
Labels: enhancement

#1721 p2p fixes
  cmd/node/config/p2p.toml
  cmd/seednode/config/p2p.toml
  factory/networkComponents_test.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/testInitializer.go
  p2p/example/libp2p/autodiscovery/main.go
  p2p/libp2p/discovery/continuousKadDhtDiscoverer.go
  p2p/libp2p/discovery/factory/peerDiscovererFactory.go
  p2p/libp2p/discovery/factory/peerDiscovererFactory_test.go
  p2p/libp2p/netMessenger_test.go
Labels: bug

#1718 En 6314/no rating change in first epoch after hardfork
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  data/state/interface.go
  data/state/peerAccount.go
  data/state/peerAccountData.pb.go
  data/state/peerAccount_test.go
  data/state/proto/peerAccountData.proto
  epochStart/bootstrap/common.go
  epochStart/errors.go
  genesis/errors.go
  genesis/mock/memDbMock.go
  genesis/mock/storageManagerStub.go
  genesis/process/argGenesisBlockCreator.go
  genesis/process/genesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/memoryComponents.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/mock/validatorStatisticsProcessorStub.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/node/getAccount/getAccount_test.go
  integrationTests/state/genesisState/genesisState_test.go
  integrationTests/state/stateExecTransaction/stateExecTransaction_test.go
  integrationTests/state/stateTrie/stateTrie_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  node/mock/peerProcessorMock.go
  node/mock/validatorStatisticsProcessorStub.go
  process/block/metablock.go
  process/interface.go
  process/mock/validatorStatisticsProcessorStub.go
  process/peer/process.go
  process/peer/process_test.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
  update/errors.go
  update/files/multiFileReader.go
  update/files/multiFileWriter.go
  update/files/multiFileWriter_test.go
  update/genesis/export.go
  update/genesis/import.go
  update/genesis/import_test.go
Labels: enhancement

#1553 New libp2p libs
  cmd/seednode/main.go
  factory/networkComponents.go
  go.mod
  go.sum
  integrationTests/consensus/consensus_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/longTests/executingSCTransactions/executingSCTransactions_test.go
  integrationTests/multiShard/block/edgecases/edgecases_test.go
  integrationTests/multiShard/block/executingMiniblocks/executingMiniblocks_test.go
  integrationTests/multiShard/block/executingMiniblocksSc/executingMiniblocksSc_test.go
  integrationTests/multiShard/block/executingRewardMiniblocks/executingRewardMiniblocks_test.go
  integrationTests/multiShard/block/interceptedBlocks/interceptedBlocks_test.go
  integrationTests/multiShard/block/interceptedHeadersSigVerification/interceptedHeadersSigVerification_test.go
  integrationTests/multiShard/endOfEpoch/epochChangeWithNodesShuffling/epochChangeWithNodesShuffling_test.go
  integrationTests/multiShard/endOfEpoch/epochChangeWithNodesShufflingAndRater/epochChangeWithNodesShufflingAndRater_test.go
  integrationTests/multiShard/endOfEpoch/epochStartChangeWithContinuousTransactionsInMultiShardedEnvironment/epochStartChangeWithContinuousTransactionsInMultiShardedEnvironment_test.go
  integrationTests/multiShard/endOfEpoch/epochStartChangeWithoutTransactionInMultiShardedEnvironment/epochStartChangeWithoutTransactionInMultiShardedEnvironment_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/multiShard/metablock/blocksDissemination_test.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx/interceptedResolvedBulkTx_test.go
  integrationTests/multiShard/transaction/txRouting/txRouting_test.go
  integrationTests/node/heartbeat/heartbeat_test.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/p2p/peerDiscovery/kadDht/peerDiscovery_test.go
  integrationTests/p2p/peerDiscovery/simpleMessageProcessor.go
  integrationTests/p2p/pubsub/peerReceivingMessages_test.go
  integrationTests/singleShard/block/consensusNotAchieved/consensusNotAchieved_test.go
  integrationTests/singleShard/block/executingMiniblocks/executingMiniblocks_test.go
  integrationTests/singleShard/block/executingMiniblocksSc/executingMiniblocksSc_test.go
  integrationTests/state/stateTrie/stateTrie_test.go
  integrationTests/sync/basicSync/basicSync_test.go
  integrationTests/sync/edgeCases/edgeCases_test.go
  integrationTests/testInitializer.go
  integrationTests/testP2PNode.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/testSyncNode.go
  integrationTests/vm/esdt/esdtProcess_test.go
  integrationTests/vm/systemVM/stakingSC_test.go
  p2p/example/libp2p/autodiscovery/main.go
  p2p/example/libp2p/internalBroadcastSpeedMeasure/main.go
  p2p/libp2p/discovery/continuousKadDhtDiscoverer.go
  p2p/libp2p/discovery/continuousKadDhtDiscoverer_test.go
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  p2p/libp2p/discovery/kadDhtDiscoverer_test.go
  p2p/libp2p/issues_test.go
  p2p/libp2p/mockMessenger.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/loadBalancer/outgoingChannelLoadBalancer.go
  p2p/mock/channelLoadBalancerStub.go
  p2p/mock/connectableHostStub.go
  p2p/mock/eventBusStub.go
  p2p/mock/eventSubscriptionStub.go
  p2p/p2p.go
Labels: bug, enhancement

#1728 Add checks for epoch start config when init bootstrap
  cmd/node/config/config.toml
  epochStart/bootstrap/common.go
  epochStart/bootstrap/epochStartMetaBlockProcessor.go
  epochStart/bootstrap/export_test.go
  epochStart/bootstrap/process_test.go
Labels: bug

#1720 EN-6411: unit tests epoch start bootstrap and update
  epochStart/bootstrap/export_test.go
  epochStart/bootstrap/interface.go
  epochStart/bootstrap/syncEpochStartMeta.go
  epochStart/bootstrap/syncEpochStartMeta_test.go
  epochStart/bootstrap/syncValidatorStatus_test.go
  epochStart/mock/messengerStub.go
  epochStart/mock/metaBlockInterceptorProcessorStub.go
  update/container/accountDBSyncers_test.go
  update/container/trieSyncers_test.go
  update/sync/base_test.go
  update/sync/concurrentTriesMap_test.go
  update/sync/syncHeadersByHash.go
  update/sync/syncHeadersByHash_test.go
  update/sync/syncMiniBlocks_test.go
Labels: enhancement

#1742 Implement go routines closing mechanism
  cmd/node/factory/structs.go
  cmd/node/main.go
  consensus/chronology/chronology.go
  consensus/interface.go
  consensus/mock/bootstrapMock.go
  consensus/mock/chronologyHandlerMock.go
  consensus/mock/sposWorkerMock.go
  consensus/mock/syncTimerMock.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  core/close/interface.go
  epochStart/interface.go
  epochStart/metachain/trigger.go
  epochStart/mock/syncTimerStub.go
  epochStart/shardchain/trigger.go
  epochStart/shardchain/triggerRegistry_test.go
  facade/mock/syncTimerMock.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/endOfEpochTriggerStub.go
  integrationTests/mock/syncTimerMock.go
  integrationTests/testProcessorNode.go
  node/mock/endOfEpochTriggerStub.go
  node/mock/syncStub.go
  node/mock/syncTimerStub.go
  node/node.go
  node/node_test.go
  node/options_test.go
  ntp/interface.go
  ntp/syncTime.go
  ntp/syncTime_test.go
  process/block/poolsCleaner/miniBlocksPoolsCleaner.go
  process/block/poolsCleaner/txsPoolsCleaner.go
  process/interface.go
  process/mock/endOfEpochTriggerStub.go
  process/mock/syncTimerMock.go
  process/sync/baseSync.go
  process/sync/baseSync_test.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: enhancement

#1749 bugFix/change reward address
  integrationTests/multiShard/endOfEpoch/epochChangeWithNodesShufflingAndRater/epochChangeWithNodesShufflingAndRater_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/vm/systemVM/stakingSC_test.go
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/auction_test.go
  vm/systemSmartContracts/staking.go
Labels: bug

#1735 termui fixes
  cmd/node/main.go
  consensus/epoch/epoch.go
  consensus/epoch/epoch_test.go
  consensus/spos/bls/subroundStartRound.go
  process/block/metrics.go
  process/block/metrics_test.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#1758 arwen v0.3.19 integration
  cmd/node/config/genesisContracts/delegation.wasm
  genesis/process/testdata/delegation.wasm
  go.mod
  go.sum
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multiShard/smartContract/testdata/delegate/delegation.wasm
  process/factory/shard/vmContainerFactory.go
Labels: bug, enhancement

#1772 Remove txs from pool after each commit
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/shardblock.go
Labels: enhancement

#1755 En 6436 process components handler
  core/constants.go
  core/statistics/interface.go
  core/statistics/softwareVersion/softwareVersion.go
  data/mock/multipleShardsCoordinatorMock.go
  factory/blockProcessorCreator.go
  factory/errors.go
  factory/interface.go
  factory/mock/accountsParserStub.go
  factory/mock/nodesCoordinatorMock.go
  factory/mock/rounderMock.go
  factory/mock/smartContractParserStub.go
  factory/networkComponents.go
  factory/networkComponentsHandler.go
  factory/processComponents.go
  factory/processComponentsHandler.go
  factory/processComponents_test.go
  factory/statusComponents.go
  factory/statusComponentsHandler.go
  factory/statusComponents_test.go
  node/nodeTesting.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/singleDataInterceptor.go
  process/throttle/antiflood/factory/disabledFloodPreventer.go
  process/throttle/antiflood/factory/disabledFloodPreventer_test.go
  process/throttle/antiflood/factory/disabledTopicFloodPreventer.go
  process/throttle/antiflood/factory/disabledTopicFloodPreventer_test.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory_test.go
  process/throttle/antiflood/factory/p2pOutputAntiflood.go
  process/throttle/antiflood/factory/p2pOutputAntiflood_test.go
  update/sync/coordinator.go
  update/sync/syncAccountsDBs.go
Labels: enhancement

#1781 Fix checker genesis
  genesis/checking/nodesSetupChecker.go
  genesis/checking/nodesSetupChecker_test.go
Labels: bug

#1796 Merge node epoch endpoint to network status
  api/node/routes.go
  api/node/routes_test.go
  cmd/node/config/api.toml
  node/external/interface.go
  node/external/nodeApiResolver_test.go
  node/mock/statusMetricsStub.go
  statusHandler/statusMetricsProvider.go
Labels: enhancement

#1800 Track whitelisted cross mini blocks to whitelist cross txs
  cmd/node/factory/structs.go
  process/track/export_test.go
  process/track/miniBlockTrack.go
  process/track/miniBlockTrack_test.go
Labels: enhancement

#1809 En 6508 fix logger in main
  cmd/node/main.go
Labels: bug

#1813 En 6494 fix tx routing
  integrationTests/multiShard/transaction/txRouting/txRouting_test.go
  node/node.go
Labels: bug

#1801 Antiflood fixes slow preventer
  cmd/node/config/config.toml
  config/config.go
  core/p2pConstants.go
  core/p2pCore.go
  factory/networkComponents.go
  integrationTests/longTests/antiflooding/antiflooding_test.go
  integrationTests/longTests/antiflooding/messageProcessor.go
  integrationTests/mock/blackListHandleStub.go
  integrationTests/p2p/antiflood/antiflooding/antiflooding_test.go
  integrationTests/p2p/antiflood/blacklist/blacklist_test.go
  integrationTests/p2p/antiflood/common.go
  integrationTests/p2p/antiflood/messageProcessor.go
  integrationTests/p2p/antiflood/nilQuotaStatusHandler.go
  node/mock/blackListHandlerStub.go
  node/mock/requestedItemsHandlerStub.go
  p2p/errors.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/networksharding/listsSharder.go
  p2p/libp2p/networksharding/listsSharder_test.go
  p2p/p2p.go
  process/errors.go
  process/interface.go
  process/mock/blackListHandlerStub.go
  process/mock/floodPreventerStub.go
  process/mock/quotaStatusHandlerStub.go
  process/mock/topicFloodPreventerStub.go
  process/throttle/antiflood/blackList/p2pBlackListProcessor.go
  process/throttle/antiflood/blackList/p2pBlackListProcessor_test.go
  process/throttle/antiflood/disabled/antiflood.go
  process/throttle/antiflood/disabled/antiflood_test.go
  process/throttle/antiflood/disabled/blacklistHandler.go
  process/throttle/antiflood/disabled/blacklistHandler_test.go
  process/throttle/antiflood/factory/disabledAntiFlood.go
  process/throttle/antiflood/factory/disabledBlacklist.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory_test.go
  process/throttle/antiflood/factory/p2pOutputAntiflood.go
  process/throttle/antiflood/factory/p2pOutputAntiflood_test.go
  process/throttle/antiflood/floodPreventers/export_test.go
  process/throttle/antiflood/floodPreventers/interface.go
  process/throttle/antiflood/floodPreventers/quotaFloodPreventer.go
  process/throttle/antiflood/floodPreventers/quotaFloodPreventer_test.go
  process/throttle/antiflood/p2pAntiflood.go
  process/throttle/antiflood/p2pAntiflood_test.go
  sharding/networksharding/peerShardMapper.go
  sharding/networksharding/peerShardMapper_test.go
  statusHandler/p2pQuota/p2pQuotaProcessor.go
  statusHandler/p2pQuota/p2pQuotaProcessor_test.go
  storage/timecache/export_test.go
  storage/timecache/timeCache.go
  storage/timecache/timeCache_test.go
Labels: bug, enhancement

#1807 Removed miniblocks requests in advance
  consensus/broadcast/shardChainMessenger.go
  consensus/broadcast/shardChainMessenger_test.go
  consensus/spos/bls/subroundEndRound.go
  core/constants.go
  dataRetriever/requestHandlers/requestHandler.go
  epochStart/metachain/rewards.go
  epochStart/shardchain/trigger.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testProcessorNode.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/postprocess/basePostProcess.go
  process/block/preprocess/basePreProcess.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/coordinator/process.go
Labels: enhancement

#1787 EN-6461: made tps benchmarks persistent
  cmd/node/factory/structsStatusHandlers.go
  cmd/node/main.go
  core/constants.go
  core/statistics/errors.go
  core/statistics/tpsBenchmark.go
  statusHandler/persister/common.go
  statusHandler/persister/common_test.go
  statusHandler/persister/persistentHandler.go
Labels: enhancement
