Repository multiversx/mx-chain-go, pull requests merged in 2020-11, with the labels that each got.

#2374 Fix bad tx behavior through tx pool cleaning
  integrationTests/mock/transactionCoordinatorMock.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardTxPreProcessor_test.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/preprocess/validatorInfoPreProcessor.go
  process/block/preprocess/validatorInfoPreProcessor_test.go
  process/block/shardblock.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interface.go
  process/mock/preprocessorMock.go
  process/mock/transactionCoordinatorMock.go
  update/mock/transactionCoordinatorMock.go
Labels: enhancement

#2376 Import DB further speed improvements
  cmd/node/main.go
  config/config.go
  data/trie/trieStorageManager.go
Labels: enhancement

#2425 Fixed elastic search errors
  cmd/node/main.go
  core/indexer/common.go
  core/indexer/errors.go
  core/indexer/factory/indexerFactory.go
  core/indexer/factory/indexerFactory_test.go
  core/indexer/testdata/accounts.json
  core/indexer/testdata/accountshistory.json
  core/indexer/testdata/accountshistory_policy.json
  core/indexer/testdata/miniblocks_policy.json
  core/indexer/testdata/rating.json
  core/indexer/testdata/rating_policy.json
  core/indexer/testdata/rounds.json
  core/indexer/testdata/rounds_policy.json
  core/indexer/testdata/validators.json
  core/indexer/testdata/validators_policy.json
  integrationTests/multiShard/smartContract/scCallingSC_test.go
Labels: bug

#2368 Fix multiple broadcast for cross txs
  consensus/broadcast/commonMessenger.go
  consensus/broadcast/delayedBroadcast.go
  consensus/broadcast/metaChainMessenger.go
  consensus/broadcast/shardChainMessenger.go
Labels: enhancement

#2440 Delegation system SC - Audit
  vm/systemSmartContracts/delegation.go
  vm/systemSmartContracts/delegationManager.go
  vm/systemSmartContracts/delegationManager_test.go
  vm/systemSmartContracts/delegation_test.go
Labels: needs investigation

#2433 bugfix/unjail-from-inactive
  process/peer/process.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
Labels: bug

#2458 Fix waiting all signatures edge case after NTP sync
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/consensusState.go
  consensus/spos/consensusState_test.go
  go.mod
  go.sum
  ntp/syncTime.go
Labels: bug

#2466 Top up rewards optimizations
  epochStart/metachain/stakingDataProvider.go
  epochStart/metachain/stakingDataProvider_test.go
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/auction_test.go
Labels: enhancement

#2471 Hardfork: execute pending txs in correct order
  update/common.go
  update/errors.go
  update/genesis/base.go
  update/genesis/export.go
  update/genesis/export_test.go
  update/genesis/import.go
  update/genesis/import_test.go
  update/interface.go
  update/mock/headerSyncHandlerStub.go
  update/mock/importHandlerStub.go
  update/mock/pendingTransactionProcessorStub.go
  update/mock/syncStateStub.go
  update/process/processPending.go
  update/process/processPending_test.go
  update/process/shardBlock.go
  update/process/shardBlock_test.go
  update/sync/coordinator.go
  update/sync/syncHeaders.go
  update/sync/syncMiniBlocks.go
  update/sync/syncMiniBlocks_test.go
Labels: bug, enhancement

#2482 small refactoring on esdt api
  api/address/routes.go
  api/address/routes_test.go
  cmd/node/config/api.toml
Labels: enhancement

#2390 Enable transactions signed with hash
  api/mock/facade.go
  api/transaction/routes.go
  api/transaction/routes_test.go
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  core/errors.go
  core/versioning/txVersionChecker.go
  core/versioning/txVersionChecker_test.go
  data/transaction/frontendTransaction.go
  data/transaction/proto/transaction.proto
  data/transaction/transaction.go
  data/transaction/transaction.pb.go
  epochStart/bootstrap/common.go
  epochStart/bootstrap/factory/epochStartInterceptorsContainerFactory.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/errors.go
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  factory/coreComponents.go
  factory/coreComponents_test.go
  factory/dtos.go
  hashing/factory/hasherFactory.go
  hashing/hasher_test.go
  integrationTests/frontend/wallet/txInterception_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testProcessorNode.go
  node/errors.go
  node/node.go
  node/node_test.go
  node/options.go
  node/options_test.go
  process/errors.go
  process/factory/interceptorscontainer/args.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  process/interceptors/factory/argInterceptedDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory_test.go
  process/interceptors/factory/interceptedTxDataFactory.go
  process/interceptors/factory/interceptedTxDataFactory_test.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/singleDataInterceptor.go
  process/interface.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  update/errors.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncInterceptors.go
Labels: enhancement

#2495 EN 8232 new storage bootstrap component
  cmd/node/flags.go
  epochStart/bootstrap/epochStartMetaBlockProcessor.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/storageEpochStartMetaBlockProcessor.go
  epochStart/bootstrap/storageEpochStartMetaBlockProcessor_test.go
  epochStart/bootstrap/storageProcess.go
  epochStart/bootstrap/storageProcess_test.go
  epochStart/bootstrap/syncValidatorStatus.go
  errors/errors.go
  factory/bootstrapComponents.go
  factory/processComponents.go
  process/block/shardblock.go
  storage/leveldb/leveldb.go
  storage/leveldb/leveldbSerial.go
Labels: enhancement

#2520 fix epoch-root hash storer config
  cmd/node/config/config.toml
Labels: bug

#2503 EN 8164 new kad dht peer discoverer implementation
  cmd/node/config/p2p.toml
  cmd/seednode/config/p2p.toml
  config/p2pConfig.go
  factory/networkComponents_test.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/p2p/peerDisconnecting/seedersDisconnecting_test.go
  integrationTests/testInitializer.go
  integrationTests/testP2PNode.go
  p2p/errors.go
  p2p/example/libp2p/autodiscovery/main.go
  p2p/libp2p/connectableHost.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple_test.go
  p2p/libp2p/discovery/continuousKadDhtDiscoverer.go
  p2p/libp2p/discovery/continuousKadDhtDiscoverer_test.go
  p2p/libp2p/discovery/export_test.go
  p2p/libp2p/discovery/factory/peerDiscovererFactory.go
  p2p/libp2p/discovery/factory/peerDiscovererFactory_test.go
  p2p/libp2p/discovery/interface.go
  p2p/libp2p/discovery/nilDiscoverer.go
  p2p/libp2p/discovery/nilDiscoverer_test.go
  p2p/libp2p/discovery/optimizedKadDhtDiscoverer.go
  p2p/libp2p/discovery/optimizedKadDhtDiscoverer_test.go
  p2p/libp2p/netMessenger_test.go
  p2p/mock/connectableHostStub.go
  p2p/mock/kadDhtHandlerStub.go
  p2p/mock/reconnecterStub.go
  p2p/p2p.go
Labels: enhancement

#2525 En 8336/rename auction sc
  cmd/node/config/genesisSmartContracts.json
  cmd/node/config/systemSmartContractsConfig.toml
  config/systemSmartContractsConfig.go
  epochStart/metachain/economics.go
  epochStart/metachain/stakingDataProvider.go
  epochStart/metachain/stakingDataProvider_test.go
  epochStart/metachain/systemSCs.go
  epochStart/metachain/systemSCs_test.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/intermediate/deployProcessor.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/testdata/smartcontracts.json
  integrationTests/frontend/staking/staking_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/multiShard/hardFork/testdata/smartcontracts.json
  integrationTests/multiShard/smartContract/dns/smartcontracts.json
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multiShard/smartContract/testdata/smartcontracts.json
  integrationTests/multiShard/txScenarios/moveBalance_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/arwen/delegation/delegation_test.go
  integrationTests/vm/delegation/delegation_test.go
  integrationTests/vm/systemVM/stakingSC_test.go
  process/factory/metachain/vmContainerFactory_test.go
  vm/address.go
  vm/errors.go
  vm/factory/systemSCFactory.go
  vm/factory/systemSCFactory_test.go
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/auctionSaveLoad.go
  vm/systemSmartContracts/auction_test.go
  vm/systemSmartContracts/common.go
  vm/systemSmartContracts/delegation.go
  vm/systemSmartContracts/delegationManager.go
  vm/systemSmartContracts/delegationManager_test.go
  vm/systemSmartContracts/delegation_test.go
  vm/systemSmartContracts/governance.go
  vm/systemSmartContracts/governance_test.go
  vm/systemSmartContracts/proto/validator.proto
  vm/systemSmartContracts/stakingWithWaiting_test.go
  vm/systemSmartContracts/staking_test.go
  vm/systemSmartContracts/validator.pb.go
Labels: enhancement

#2522 Full history lru persisters
  cmd/node/flags.go
  cmd/storer2elastic/dataprocessor/ratingsProcessor.go
  config/contextFlagsConfig.go
  dataRetriever/mock/nilCurrentNetworkEpochProviderHandler.go
  factory/mock/peerHonestyHandlerStub.go
  node/nodeRunner.go
  storage/errors.go
  storage/lrucache/lrucache.go
  storage/pruning/export_test.go
  storage/pruning/fullHistoryPruningStorer.go
  storage/pruning/fullHistoryPruningStorer_test.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorerArgs.go
Labels: enhancement

#2489 fixed bug with mainnet config on soft restart
  epochStart/bootstrap/process.go
Labels: bug

#2527 Keygenerator refactor
  cmd/keygenerator/main.go
Labels: enhancement
