Repository multiversx/mx-chain-go, pull requests merged in 2020-03, with the labels that each got.

#1180 Fix sync requests on startup
  api/mock/facade.go
  api/node/routes.go
  cmd/node/main.go
  dataRetriever/requestHandlers/requestHandler.go
  facade/elrondNodeFacade.go
  facade/elrondNodeFacade_test.go
  facade/interface.go
  facade/mock/nodeMock.go
  integrationTests/consensus/consensus_test.go
  node/node.go
  node/node_test.go
  p2p/libp2p/netMessenger.go
  process/block/metablock.go
  process/block/shardblock.go
  process/sync/baseSync.go
  process/track/blockProcessor.go
  process/track/blockProcessor_test.go
  process/track/export_test.go
  sharding/indexHashedNodesCoordinator.go
Labels: bug

#1187 En 5778/hard fork tries
  core/converters.go
  core/converters_test.go
  data/mock/requestHandlerStub.go
  data/trie/branchNode_test.go
  data/trie/errors.go
  data/trie/extensionNode_test.go
  data/trie/interface.go
  data/trie/leafNode_test.go
  data/trie/sync.go
  data/trie/sync_test.go
  dataRetriever/factory/containers/resolversFinder.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go
  dataRetriever/interface.go
  dataRetriever/mock/resolversFinderStub.go
  dataRetriever/requestHandlers/requestHandler.go
  dataRetriever/requestHandlers/requestHandler_test.go
  epochStart/shardchain/trigger.go
  integrationTests/mock/resolversFinderStub.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/state/stateTrieSync_test.go
  node/mock/resolversFinderStub.go
  process/block/baseProcess.go
  process/block/export_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  sharding/errors.go
  sharding/multiShardCoordinator.go
  sharding/multiShardCoordinator_test.go
  sharding/oneShardCoordinator.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncInterceptors.go
  update/factory/fullSyncResolversContainerFactory.go
  update/factory/trieSyncersContainerFactory.go
  update/genesis/base.go
  update/genesis/export.go
  update/interface.go
  update/sync/syncTries.go
Labels: enhancement

#1171 Fix main error msgs
  cmd/node/main.go
Labels: bug

#1185 Fix update peer on meta
  README.md
  cmd/node/factory/structs.go
  consensus/mock/blockProcessorMock.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  data/block/metaBlock.pb.go
  data/block/proto/metaBlock.proto
  epochStart/genesis/genesisBlockCreator.go
  epochStart/interface.go
  epochStart/metachain/economics.go
  epochStart/metachain/trigger.go
  epochStart/metachain/triggerRegistry.go
  epochStart/metachain/triggerRegistry_test.go
  epochStart/metachain/trigger_test.go
  epochStart/shardchain/trigger.go
  epochStart/shardchain/trigger_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/endOfEpochTriggerStub.go
  integrationTests/mock/validatorStatisticsProcessorStub.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  node/mock/blockProcessorStub.go
  node/mock/endOfEpochTriggerStub.go
  node/mock/validatorStatisticsProcessorStub.go
  process/block/baseProcess.go
  process/block/hdrForBlock.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/interface.go
  process/mock/blockProcessorMock.go
  process/mock/endOfEpochTriggerStub.go
  process/mock/validatorStatisticsProcessorStub.go
  process/peer/process.go
  process/peer/process_test.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
Labels: bug

#1196 marshalizer fixes
  api/api.go
  cmd/logviewer/main.go
  cmd/logviewer/testing/main.go
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  cmd/termui/provider/logProvider.go
  integrationTests/consensus/testInitializer.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  logger/logLine.go
  logger/logLineMessage.pb.go
  logger/logLine_test.go
  logger/proto/logLineMessage.proto
  logger/proto/schema.pb.go
  logger/proto/schema.proto
  marshal/errors.go
  marshal/factory/marshalizerFactory.go
  marshal/factory/marshalizerFactory_test.go
  marshal/protobufMarshalizer.go
  marshal/protobufMarshalizer_test.go
  node/node.go
  node/nodeTesting.go
  node/nodeTesting_test.go
  node/node_test.go
  node/options.go
  node/options_test.go
Labels: enhancement

#1186 Fix-block-tracker-cleanup-and-possible-out-of-memory
  process/block/metablock.go
  process/block/shardblock.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockBalancer_test.go
  process/track/blockNotarizer.go
  process/track/blockNotarizer_test.go
  process/track/blockNotifier_test.go
  process/track/blockProcessor_test.go
  process/track/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: bug, enhancement

#1201 Fix network sharding eclipse attack
  cmd/node/config/config.toml
  integrationTests/interface.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/networksharding/listsSharder.go
  p2p/libp2p/networksharding/listsSharder_test.go
  p2p/libp2p/networksharding/prioBitsSharder.go
  p2p/libp2p/networksharding/prioBitsSharder_test.go
  p2p/libp2p/unknownPeerShardResolver.go
  p2p/libp2p/unknownPeerShardResolver_test.go
  p2p/mock/peerShardResolverStub.go
  p2p/p2p.go
  sharding/networksharding/export_test.go
  sharding/networksharding/peerShardMapper.go
  sharding/networksharding/peerShardMapper_test.go
  sharding/networksharding/pidQueue.go
  sharding/networksharding/pidQueue_test.go
Labels: bug, enhancement

#1205 Fix is epoch start set reset
  consensus/mock/headerHandlerStub.go
  data/block/metaBlock.go
  data/interface.go
  epochStart/errors.go
  epochStart/interface.go
  epochStart/metachain/trigger.go
  epochStart/metachain/trigger_test.go
  epochStart/shardchain/trigger.go
  epochStart/shardchain/triggerRegistry.go
  epochStart/shardchain/triggerRegistry_test.go
  epochStart/shardchain/trigger_test.go
  integrationTests/mock/endOfEpochTriggerStub.go
  node/mock/endOfEpochTriggerStub.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/metablock.go
  process/block/shardblock.go
  process/interface.go
  process/mock/endOfEpochTriggerStub.go
  process/mock/headerHandlerStub.go
  process/sync/baseSync.go
  sharding/mock/headerHandlerStub.go
Labels: bug

#1207 Fix epoch 1 change
  epochStart/metachain/trigger.go
  epochStart/shardchain/trigger.go
Labels: bug

#1209 fix elastic search bug - close response body
  core/indexer/elasticsearchDatabase.go
  core/indexer/elasticsearchDatabaseWriter.go
  core/indexer/elasticsearchDatabase_test.go
  core/indexer/interface.go
  core/mock/databaseWriterMock.go
Labels: bug

#1188 En 5789 from kyber to go ed25519
  cmd/keygenerator/main.go
  cmd/node/factory/structs.go
  crypto/errors.go
  crypto/interface.go
  crypto/mock/point.go
  crypto/mock/scalar.go
  crypto/mock/suite.go
  crypto/signing/ed25519/point.go
  crypto/signing/ed25519/point_test.go
  crypto/signing/ed25519/scalar.go
  crypto/signing/ed25519/scalar_test.go
  crypto/signing/ed25519/singlesig/ed25519.go
  crypto/signing/ed25519/singlesig/ed25519_test.go
  crypto/signing/ed25519/suite.go
  crypto/signing/ed25519/suite_test.go
  crypto/signing/key.go
  crypto/signing/key_test.go
  crypto/signing/kyber/suiteEd25519.go
  crypto/signing/kyber/suitePairingBn256.go
  crypto/signing/mcl/suiteBLS12_381.go
  crypto/signing/mcl/suiteBLS12_381_test.go
  go.sum
  integrationTests/consensus/testInitializer.go
  integrationTests/longTests/executingSCTransactions_test.go
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/multiShard/transaction/sendBulkTransactions_test.go
  integrationTests/node/heartbeat_test.go
  integrationTests/singleShard/block/executingMiniblocksSc_test.go
  integrationTests/singleShard/transaction/interceptedResolvedTx_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testWalletAccount.go
Labels: enhancement

#1211 Fixed set of sync state mechanism
  process/sync/baseSync.go
  process/sync/export_test.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
Labels: bug

#1219 Correlation of header tracker and cacher pools
  integrationTests/mock/blockTrackerStub.go
  node/mock/blockTrackerStub.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/shardblock.go
  process/constants.go
  process/interface.go
  process/mock/blockTrackerMock.go
  process/sync/baseSync.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockNotarizer.go
  process/track/blockNotarizer_test.go
  process/track/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: enhancement

#1225 Fix counting of pending miniblocks
  cmd/node/factory/structs.go
  epochStart/interface.go
  epochStart/metachain/pendingMiniBlocks.go
  epochStart/metachain/pendingMiniBlocks_test.go
  integrationTests/mock/pendingMiniBlocksHandlerStub.go
  node/mock/pendingMiniBlocksHandlerStub.go
  process/block/pendingMb/pendingMiniBlocks.go
  process/block/pendingMb/pendingMiniBlocks_test.go
  process/interface.go
  process/mock/pendingMiniBlocksHandlerStub.go
Labels: bug

#1227 pk checks when starting node
  cmd/node/factory/errors.go
  cmd/node/factory/structs.go
  cmd/node/main.go
  core/file.go
  core/file_test.go
Labels: enhancement

#1189 En 5464 peer rating process in shard
  cmd/node/config/config.toml
  cmd/node/config/economics.toml
  cmd/node/factory/structs.go
  consensus/mock/nodesCoordinatorMock.go
  data/block/metaBlock.go
  data/interface.go
  data/mock/nodesCoordinatorMock.go
  data/state/interface.go
  data/state/peerAccountData.pb.go
  data/state/proto/peerAccountData.proto
  data/state/validatorInfo.go
  epochStart/errors.go
  epochStart/interface.go
  epochStart/mock/requestHandlerStub.go
  epochStart/mock/validatorInfoProcessorStub.go
  epochStart/shardchain/trigger.go
  epochStart/shardchain/triggerRegistry_test.go
  epochStart/shardchain/trigger_test.go
  epochStart/shardchain/validatorInfoProcessor.go
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/nodesCoordinatorMock.go
  integrationTests/mock/validatorInfoProcessorStub.go
  integrationTests/mock/validatorStatisticsProcessorStub.go
  integrationTests/state/stateTrie_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/mock/nodesCoordinatorMock.go
  node/mock/peerProcessorMock.go
  node/mock/validatorStatisticsProcessorStub.go
  node/node.go
  node/node_test.go
  process/block/argProcessor.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/interceptedBlocks/common.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/preprocess/validatorInfoPreProcessor.go
  process/block/shardblock.go
  process/errors.go
  process/interface.go
  process/mock/nodesCoordinatorMock.go
  process/mock/validatorStatisticsProcessorStub.go
  process/peer/process.go
  process/rating/blockSigningRater.go
  scripts/testnet/variables.sh
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinatorWithRater.go
  sharding/indexHashedNodesCoordinatorWithRater_test.go
  sharding/interface.go
  sharding/xorValidatorShuffler.go
Labels: enhancement

#1236 Fix-sync-problem-on-forced-roll-back
  consensus/mock/bootstrapMock.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/bls/subroundStartRound_test.go
  consensus/spos/worker_test.go
  core/constants.go
  process/constants.go
  process/interface.go
  process/sync/baseSync.go
  process/sync/export_test.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
Labels: bug, enhancement

#1241 Removed unused block throttle
  consensus/spos/worker.go
  process/block/baseProcess.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/coordinator/process.go
  process/interface.go
  process/mock/blockSizeThrottlerStub.go
  process/throttle/block.go
  process/throttle/block_test.go
  process/throttle/export_test.go
  process/track/shardBlockTrack.go
Labels: enhancement

#1246 remove parallel from tests
  crypto/signing/mcl/multisig/bls_test.go
Labels: bug

#1224 Fix tx routing
  integrationTests/multiShard/transaction/sendBulkTransactions_test.go
  integrationTests/multiShard/transaction/txRouting_test.go
  integrationTests/testProcessorNode.go
  node/node.go
  process/dataValidators/txValidator.go
  process/dataValidators/txValidator_test.go
  process/errors.go
  process/interceptors/processor/txInterceptorProcessor.go
  process/interface.go
  process/mock/txValidatorHandlerStub.go
Labels: bug

#1245 Fixed sender and receiver shard used to process txs
  process/block/export_test.go
  process/block/preprocess/export_test.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/smartContract/process.go
Labels: bug

#1251 Add pending miniblocks in bootstrap storer
  integrationTests/mock/pendingMiniBlocksHandlerStub.go
  node/mock/pendingMiniBlocksHandlerStub.go
  process/block/baseProcess.go
  process/block/bootstrapStorage/bootstrapData.pb.go
  process/block/bootstrapStorage/proto/bootstrapData.proto
  process/block/metablock.go
  process/block/pendingMb/pendingMiniBlocks.go
  process/block/pendingMb/pendingMiniBlocks_test.go
  process/interface.go
  process/mock/pendingMiniBlocksHandlerStub.go
  process/sync/storageBootstrap/interface.go
  process/sync/storageBootstrap/metaStorageBootstrapper.go
  process/sync/storageBootstrap/shardStorageBootstrapper.go
  process/track/shardBlockTrack.go
Labels: bug, enhancement

#1134 EN-5814: update flags description
  cmd/node/main.go
Labels: enhancement

#1202 simplified heartbeat storage DTO
  node/heartbeat/heartbeat.pb.go
  node/heartbeat/monitor.go
  node/heartbeat/proto/heartbeat.proto
  node/heartbeat/storage/heartbeatStorer.go
  node/heartbeat/storage/heartbeatStorer_test.go
Labels: enhancement

#1261 bugfix/Revert accumulated fees when necessary
  cmd/node/factory/structs.go
  data/mock/unsignedTxHandlerMock.go
  epochStart/genesis/genesisFeeHandler.go
  integrationTests/mock/unsignedTxHandlerMock.go
  integrationTests/testProcessorNode.go
  process/block/postprocess/feeHandler.go
  process/block/preprocess/transactions.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interface.go
  process/mock/feeAccumulatorStub.go
  process/mock/unsignedTxHandlerMock.go
  process/smartContract/export_test.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/transaction/shardProcess.go
Labels: bug

#1263 Adaptive block size throttle
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  data/block/block.go
  data/block/metaBlock.go
  data/interface.go
  integrationTests/mock/blockSizeThrottlerStub.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  process/block/argProcessor.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/pendingMb/pendingMiniBlocks.go
  process/block/preprocess/adapterTxCacheToSortedTransactionsProvider.go
  process/block/preprocess/blockSizeComputation.go
  process/block/preprocess/blockSizeComputation_test.go
  process/block/preprocess/interfaces.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/errors.go
  process/interface.go
  process/mock/blockSizeThrottlerStub.go
  process/throttle/block.go
  process/throttle/block_test.go
  process/throttle/export_test.go
Labels: enhancement

#1254 Fix observers network sharding
  cmd/node/config/config.toml
  cmd/node/config/p2p.toml
  cmd/node/metrics/metrics.go
  config/p2pConfig.go
  core/constants.go
  core/errors.go
  core/p2pCore.go
  integrationTests/interface.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/testP2PNode.go
  p2p/example/libp2p/internalBroadcastSpeedMeasure/main.go
  p2p/libp2p/issues_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/libp2p/networksharding/factory/sharderFactory.go
  p2p/libp2p/networksharding/factory/sharderFactory_test.go
  p2p/libp2p/networksharding/listsSharder.go
  p2p/libp2p/networksharding/listsSharder_test.go
  p2p/libp2p/networksharding/oneListSharder.go
  p2p/libp2p/networksharding/oneListSharder_test.go
  p2p/libp2p/networksharding/prioBitsSharder.go
  p2p/libp2p/networksharding/prioBitsSharder_test.go
  p2p/libp2p/unknownPeerShardResolver.go
  p2p/libp2p/unknownPeerShardResolver_test.go
  p2p/memp2p/messenger_test.go
  p2p/mock/messageProcessorStub.go
  p2p/mock/mockMessageProcessor.go
  p2p/mock/networkShardingCollectorStub.go
  p2p/mock/p2pMessageMock.go
  p2p/mock/peerShardResolverStub.go
  p2p/p2p.go
  process/block/shardblock.go
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinatorRegistry.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/networksharding/peerShardMapper.go
  sharding/networksharding/peerShardMapper_test.go
Labels: bug, enhancement

#1271 epoch trigger - sort metaheaders according to nonce.
  epochStart/interface.go
  epochStart/metachain/trigger.go
  epochStart/shardchain/trigger.go
  epochStart/shardchain/trigger_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader.go
  process/block/metablock.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock.go
  process/interface.go
Labels: bug

#1277 Fix observer shardid on restart
  cmd/node/main.go
  integrationTests/nodesCoordinatorFactory.go
  integrationTests/testP2PNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  scripts/testnet/variables.sh
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinatorRegistry.go
  sharding/indexHashedNodesCoordinatorRegistry_test.go
  sharding/indexHashedNodesCoordinatorWithRater.go
  sharding/indexHashedNodesCoordinatorWithRater_test.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/shardingArgs.go
Labels: bug

#1274 Fix requesters
  core/random/concurrentSafeIntRandomizer.go
  core/random/concurrentSafeIntRandomizer_test.go
  dataRetriever/errors.go
  dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go
  dataRetriever/interface.go
  dataRetriever/mock/intRandomizerMock.go
  dataRetriever/mock/intRandomizerStub.go
  dataRetriever/mock/peerListCreatorStub.go
  dataRetriever/resolvers/topicResolverSender/diffPeerListCreator.go
  dataRetriever/resolvers/topicResolverSender/diffPeerListCreator_test.go
  dataRetriever/resolvers/topicResolverSender/export_test.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go
Labels: bug, enhancement

#1282 Fixed dead lock in process block
  process/block/shardblock.go
  process/sync/baseSync.go
Labels: bug

#1210 blockchain refactor
  cmd/node/factory/structs.go
  consensus/broadcast/metaChainMessenger.go
  consensus/mock/blockChainMock.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/worker.go
  data/block/block.go
  data/blockchain/baseBlockchain.go
  data/blockchain/blockchain.go
  data/blockchain/blockchain_test.go
  data/blockchain/metachain.go
  data/blockchain/metachain_test.go
  data/interface.go
  data/mock/appStatusHandlerStub.go
  data/mock/cacherStub.go
  dataRetriever/mock/blockChainMock.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blockChainMock.go
  integrationTests/multiShard/block/executingMiniblocks/executingMiniblocks_test.go
  integrationTests/testInitializer.go
  node/mock/blockChainMock.go
  node/mock/chainHandlerStub.go
  node/options_test.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/mock/blockChainMock.go
  process/sync/baseSync.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
Labels: enhancement

#1276 Fix-misleading-prints-for-headers-pool-info
  dataRetriever/interface.go
  dataRetriever/mock/headersCacherStub.go
  epochStart/mock/headersCacherStub.go
  node/mock/headersCacherStub.go
  process/block/baseProcess.go
  process/block/bootstrapStorage/bootstrapStorer.go
  process/block/bootstrapStorage/bootstrapStorer_test.go
  process/block/displayMetaBlock.go
  process/block/metablock.go
  process/block/metrics.go
  process/block/processedMb/processedMiniBlocks.go
  process/block/shardblock.go
  process/constants.go
  process/mock/headersCacherStub.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: enhancement

#1287 Fix fork detection on final checkpoint nonce
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
Labels: bug

#1294 EN-6013: heartbeat update for peer list
  core/constants.go
  integrationTests/node/heartbeat/heartbeat_test.go
  integrationTests/testP2PNode.go
  node/heartbeat/errors.go
  node/heartbeat/export_test.go
  node/heartbeat/heartbeat.pb.go
  node/heartbeat/heartbeatMessageInfo.go
  node/heartbeat/heartbeatMessageInfo_test.go
  node/heartbeat/heartbeatdata.go
  node/heartbeat/interface.go
  node/heartbeat/monitor.go
  node/heartbeat/monitorEdgeCases_test.go
  node/heartbeat/monitor_test.go
  node/heartbeat/proto/heartbeat.proto
  node/heartbeat/sender.go
  node/heartbeat/sender_test.go
  node/mock/appStatusHandlerStub.go
  node/mock/nodesCoordinatorMock.go
  node/mock/peerProcessorMock.go
  node/mock/peerTypeProviderStub.go
  node/node.go
  node/node_test.go
  process/block/metrics.go
  process/block/shardblock.go
  sharding/peerTypeProvider.go
  statusHandler/presenter/instanceInfoGetters.go
  statusHandler/view/interface.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#1304 Fix save of epoch start identifier in correct storer
  cmd/node/config/config.toml
  dataRetriever/requestHandlers/requestHandler.go
  epochStart/metachain/trigger.go
  epochStart/shardchain/trigger.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/common.go
  process/common_test.go
  process/peer/process.go
  process/peer/process_test.go
  sharding/indexHashedNodesCoordinator.go
Labels: bug

#1306 fixed counter for termui
  process/block/metrics.go
Labels: bug

#1309 replaced github.com/cornelk/hashmap implementation with an internal, …
  core/container/mutexMap.go
  core/container/mutexMap_test.go
  dataRetriever/factory/containers/resolversContainer.go
  go.mod
  go.sum
  process/factory/containers/export_test.go
  process/factory/containers/interceptorsContainer.go
  process/factory/containers/intermediateTransactionHandlersContainer.go
  process/factory/containers/preProcessorsContainer.go
  process/factory/containers/vmContainer.go
  vm/factory/systemSCContainer.go
Labels: bug

#1302 En 5895 rating signed blocks threshold and consecutive blocks penalty
  api/validator/routes_test.go
  cmd/node/config/ratings.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/ratingsConfig.go
  data/interface.go
  data/state/interface.go
  data/state/peerAccount.go
  data/state/peerAccountData.pb.go
  data/state/proto/peerAccountData.proto
  data/state/proto/validatorInfo.proto
  data/state/validatorInfo.go
  data/state/validatorInfo.pb.go
  epochStart/interface.go
  epochStart/metachain/validators.go
  epochStart/metachain/validators_test.go
  epochStart/mock/validatorStatisticsProcessorStub.go
  epochStart/shardchain/validatorInfoProcessor.go
  epochStart/shardchain/validatorInfoProcessor_test.go
  facade/elrondNodeFacade_test.go
  integrationTests/mock/raterMock.go
  integrationTests/mock/validatorStatisticsProcessorStub.go
  integrationTests/testProcessorNode.go
  node/mock/peerProcessorMock.go
  node/mock/validatorStatisticsProcessorStub.go
  node/mock/validatorsProviderStub.go
  node/node.go
  node/node_test.go
  node/options.go
  process/block/metablock.go
  process/errors.go
  process/interface.go
  process/mock/accountWrapperMock.go
  process/mock/peerAccountHandlerMock.go
  process/mock/raterMock.go
  process/mock/ratingStepMock.go
  process/mock/ratingsInfoMock.go
  process/mock/validatorStatisticsProcessorStub.go
  process/peer/process.go
  process/peer/process_test.go
  process/peer/validatorsProvider.go
  process/peer/validatorsProvider_test.go
  process/rating/blockSigningRater.go
  process/rating/blockSigningRater_test.go
  process/rating/chance_test.go
  process/rating/ratingStepData.go
  process/rating/ratingStepData_test.go
  process/rating/ratingsData.go
  process/rating/ratingsData_test.go
  sharding/interface.go
Labels: enhancement
