Repository multiversx/mx-chain-go, pull requests merged in 2020-04, with the labels that each got.

#1318 updated travis.yml so it will build the termui and logviewer binaries
  .travis.yml
Labels: enhancement

#1315 EN-6030: epoch data endpoint
  api/node/routes.go
  api/node/routes_test.go
  cmd/node/factory/structs.go
  cmd/node/main.go
  cmd/node/metrics/metrics.go
  core/constants.go
  epochStart/errors.go
  epochStart/interface.go
  epochStart/metachain/trigger.go
  epochStart/metachain/triggerRegistry_test.go
  epochStart/shardchain/trigger.go
  epochStart/shardchain/triggerRegistry_test.go
  integrationTests/mock/endOfEpochTriggerStub.go
  node/external/interface.go
  node/external/nodeApiResolver_test.go
  node/mock/endOfEpochTriggerStub.go
  node/mock/statusMetricsStub.go
  process/mock/endOfEpochTriggerStub.go
  statusHandler/presenter/chainInfoGetters.go
  statusHandler/statusMetricsProvider.go
Labels: enhancement

#1233 fixed edge case when starting in a round of an epoch change.
  cmd/node/factory/structs.go
  consensus/mock/blockProcessorMock.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/bls/subroundBlock.go
  epochStart/interface.go
  epochStart/metachain/epochStartData.go
  epochStart/metachain/trigger.go
  epochStart/metachain/trigger_test.go
  epochStart/shardchain/trigger.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/endOfEpochTriggerStub.go
  integrationTests/multiShard/block/edgecases/edgecases_test.go
  integrationTests/singleShard/block/consensusNotAchieved/consensusNotAchieved_test.go
  integrationTests/testProcessorNode.go
  node/mock/blockProcessorStub.go
  node/mock/endOfEpochTriggerStub.go
  node/node.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/common.go
  process/interface.go
  process/mock/blockProcessorMock.go
  process/mock/endOfEpochTriggerStub.go
  scripts/testnet/start.sh
  scripts/testnet/variables.sh
  storage/leveldb/leveldb.go
  storage/leveldb/leveldbSerial.go
Labels: bug

#1333 Fix trigger for shards on missed peer miniblocks
  epochStart/mock/validatorInfoProcessorStub.go
  epochStart/shardchain/trigger.go
  epochStart/shardchain/triggerRegistry_test.go
  epochStart/shardchain/validatorInfoProcessor.go
  epochStart/shardchain/validatorInfoProcessor_test.go
  integrationTests/mock/validatorInfoProcessorStub.go
  process/interface.go
Labels: bug

#1321 changed epoch source in peer shard mapper
  cmd/node/factory/structs.go
  cmd/node/main.go
  core/constants.go
  integrationTests/testP2PNode.go
  sharding/networksharding/export_test.go
  sharding/networksharding/peerShardMapper.go
  sharding/networksharding/peerShardMapper_test.go
Labels: bug

#1300 Removed unused cleaning mechanism from block tracker
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockNotarizer.go
  process/track/blockNotarizer_test.go
  process/track/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: enhancement

#1351 Fixed wrong type assertion for received transactions
  cmd/node/factory/structs.go
  consensus/spos/bls/blsWorker.go
  consensus/spos/bls/blsWorker_test.go
  consensus/spos/errors.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  core/constants.go
  integrationTests/consensus/testInitializer.go
  process/block/poolsCleaner/crossTxsPoolsCleaner.go
  process/block/poolsCleaner/miniBlocksCleaner.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
Labels: bug

#1360 fix out of range case
  process/block/metrics.go
  process/block/metrics_test.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: bug

#1356 En 6064 index rewards txs metachain calc block size
  core/indexer/common.go
  core/indexer/common_test.go
  core/indexer/data.go
  core/indexer/elasticsearch.go
  core/indexer/elasticsearchDatabase.go
  core/indexer/elasticsearchDatabase_test.go
  core/indexer/interface.go
  epochStart/metachain/rewards.go
  integrationTests/mock/epochRewardsCreatorStub.go
  process/block/metablock.go
  process/interface.go
  process/mock/epochRewardsCreatorStub.go
Labels: enhancement

#1372 fixed golang ci bots issues
  data/trie/sync.go
  epochStart/bootstrap/disabled/disabledAccountsAdapter.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/syncEpochStartMeta.go
  sharding/indexHashedNodesCoordinator.go
  storage/factory/openStorage.go
  update/sync/syncHeadersByHash.go
  update/sync/syncMiniBlocks.go
Labels: bug

#1374 Add consensus messages validity checks
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
  config/tomlConfig_test.go
  consensus/spos/bls/blsWorker.go
  consensus/spos/bls/blsWorker_test.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusMessageValidator.go
  consensus/spos/consensusMessageValidator_test.go
  consensus/spos/errors.go
  consensus/spos/interface.go
  consensus/spos/subround_test.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  core/constants.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/multiSigMock.go
  node/node.go
  node/options.go
  node/options_test.go
Labels: enhancement

#1273 EN-5897: shuffled out handler and notifier
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
  epochStart/bootstrap/disabled/disabledShuffledOutHandler.go
  epochStart/bootstrap/syncValidatorStatus.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/shuffledOutHandlerStub.go
  integrationTests/nodesCoordinatorFactory.go
  integrationTests/testP2PNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  node/errors.go
  node/node.go
  node/options.go
  node/options_test.go
  sharding/errors.go
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinatorWithRater_test.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/interface.go
  sharding/mock/shuffledOutHandlerStub.go
  sharding/shardingArgs.go
  sharding/shuffledOutTrigger.go
  sharding/shuffledOutTrigger_test.go
Labels: enhancement

#1378 Fix block size throttle edge case for cross mbs dest me
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  integrationTests/testProcessorNode.go
  process/block/poolsCleaner/crossTxsPoolsCleaner.go
  process/block/preprocess/blockSizeComputation.go
  process/block/preprocess/blockSizeComputation_test.go
  process/block/preprocess/interfaces.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/transactions.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/mock/blockSizeComputationStub.go
Labels: bug, enhancement

#1390 add display table for epoch start meta block
  process/block/baseProcess.go
  process/block/displayMetaBlock.go
Labels: enhancement

#1392 Add and restore last self notarized headers from bootstorer
  cmd/node/config/config.toml
  config/config.go
  consensus/spos/bls/subroundEndRound.go
  dataRetriever/interface.go
  integrationTests/mock/blockTrackerStub.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  node/mock/blockTrackerStub.go
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/poolsCleaner/interface.go
  process/interface.go
  process/mock/blockTrackerHandlerMock.go
  process/mock/blockTrackerMock.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
  process/sync/storageBootstrap/interface.go
  process/sync/storageBootstrap/metaStorageBootstrapper.go
  process/sync/storageBootstrap/shardStorageBootstrapper.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockBalancer.go
  process/track/blockBalancer_test.go
  process/track/blockProcessor.go
  process/track/export_test.go
  process/track/interface.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
  storage/factory/pruningStorerFactory.go
Labels: bug, enhancement

#1403 return metablock if at least num of peers send it
  epochStart/bootstrap/epochStartMetaBlockProcessor.go
  epochStart/bootstrap/epochStartMetaBlockProcessor_test.go
  epochStart/bootstrap/export_test.go
Labels: enhancement

#1400 Fix edge case when forced fork and reset probable highest nonce are prevented
  consensus/mock/headerHandlerStub.go
  consensus/spos/worker.go
  p2p/libp2p/netMessenger.go
  process/dataValidators/txValidator.go
  process/dataValidators/txValidator_test.go
  process/interceptors/common.go
  process/sync/baseSync.go
  process/sync/export_test.go
  process/sync/shardblock_test.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
Labels: bug, enhancement

#1398 Node structure cleanup
  api/mock/facade.go
  api/node/routes.go
  api/node/routes_test.go
  cmd/node/main.go
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  integrationTests/consensus/consensus_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/multiShard/block/edgecases/edgecases_test.go
  integrationTests/multiShard/block/executingMiniblocks/executingMiniblocks_test.go
  integrationTests/multiShard/block/executingMiniblocksSc/executingMiniblocksSc_test.go
  integrationTests/multiShard/block/executingRewardMiniblocks/executingRewardMiniblocks_test.go
  integrationTests/multiShard/block/interceptedBlocks/interceptedBlocks_test.go
  integrationTests/multiShard/block/interceptedHeadersSigVerification/interceptedHeadersSigVerification_test.go
  integrationTests/multiShard/endOfEpoch/epochChangeWithNodesShuffling/epochChangeWithNodesShuffling_test.go
  integrationTests/multiShard/endOfEpoch/epochChangeWithNodesShufflingAndRater/epochChangeWithNodesShufflingAndRater_test.go
  integrationTests/multiShard/endOfEpoch/epochStartChangeWithContinuousTransactionsInMultiShardedEnvironment/epochStartChangeWithContinuousTransactionsInMultiShardedEnvironment_test.go
  integrationTests/multiShard/endOfEpoch/epochStartChangeWithoutTransactionInMultiShardedEnvironment/epochStartChangeWithoutTransactionInMultiShardedEnvironment_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/multiShard/metablock/blocksDissemination_test.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx/interceptedResolvedBulkTx_test.go
  integrationTests/multiShard/transaction/txRouting/txRouting_test.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/resolvers/headers/headers_test.go
  integrationTests/resolvers/metablock/metablock_test.go
  integrationTests/resolvers/miniblocks/miniblocks_test.go
  integrationTests/resolvers/rewards/rewards_test.go
  integrationTests/resolvers/testInitializer.go
  integrationTests/singleShard/block/consensusNotAchieved/consensusNotAchieved_test.go
  integrationTests/singleShard/block/interceptedRequestHdr/interceptedRequestHdr_test.go
  integrationTests/singleShard/block/interceptedRequestTxBlockBody/interceptedRequestTxBlockBody_test.go
  integrationTests/singleShard/transaction/interceptedBulkTx/interceptedBulkTx_test.go
  integrationTests/singleShard/transaction/interceptedBulkUnsignedTx/interceptedBulkUnsignedTx_test.go
  integrationTests/singleShard/transaction/interceptedResolvedTx/interceptedResolvedTx_test.go
  integrationTests/singleShard/transaction/interceptedResolvedUnsignedTx/interceptedResolvedUnsignedTx_test.go
  integrationTests/state/stateTrie/stateTrie_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/testInitializer.go
  integrationTests/vm/systemVM/systemVm_test.go
  node/node.go
  node/node_test.go
Labels: bug

#1411 Fix integration tests
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
Labels: bug

#1381 Logs and events
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  core/address.go
  core/constants.go
  data/interface.go
  data/transaction/log.go
  data/transaction/log.pb.go
  data/transaction/log_test.go
  data/transaction/proto/log.proto
  dataRetriever/interface.go
  epochStart/bootstrap/export_test.go
  epochStart/genesis/genesisBlockCreator.go
  go.mod
  go.sum
  integrationTests/mock/txLogsProcessorStub.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/vm/arwen/badcontracts/badcontracts_test.go
  integrationTests/vm/arwen/testdata/bad-reservedFunctions/function-ChangeOwnerAddress.wasm
  integrationTests/vm/arwen/testdata/bad-reservedFunctions/function-ClaimDeveloperRewards.wasm
  integrationTests/vm/arwen/testdata/bad-reservedFunctions/function-asyncCall.wasm
  integrationTests/vm/arwen/testdata/bad-reservedFunctions/function-foobar.wasm
  integrationTests/vm/arwen/testdata/bad-reservedFunctions/function_ClaimDeveloperRewards.wasm
  integrationTests/vm/arwen/testdata/bad-reservedFunctions/reservedFunctions.c
  integrationTests/vm/arwen/testdata/bad-reservedFunctions/reservedFunctions.export
  integrationTests/vm/arwen/testdata/bad-reservedFunctions/reservedFunctions.wasm
  integrationTests/vm/arwen/upgrades/upgrades_test.go
  integrationTests/vm/arwen/utils.go
  integrationTests/vm/arwen/wasmer/wasmer_test.go
  integrationTests/vm/testInitializer.go
  process/errors.go
  process/factory/shard/vmContainerFactory.go
  process/interface.go
  process/mock/txLogsProcessorStub.go
  process/smartContract/builtInFunctions/factory.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/transactionLog/process.go
  process/transactionLog/process_test.go
  storage/factory/pruningStorerFactory.go
  vm/mock/blockChainHookStub.go
Labels: enhancement

#1418 bugFix/check epoch cross correctness
  epochStart/shardchain/trigger.go
  process/block/shardblock.go
  process/track/baseBlockTrack.go
Labels: bug

#1415 Fixed creation of interceptors when starting the bootstrap from storage
  cmd/node/main.go
  epochStart/bootstrap/fromLocalStorage.go
  epochStart/bootstrap/fromLocalStorage_test.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/syncEpochStartMeta.go
Labels: bug

#1425 Automatic recover of corrupted DB file
  storage/leveldb/common.go
  storage/leveldb/leveldb.go
  storage/leveldb/leveldbSerial.go
  storage/leveldb/leveldb_test.go
Labels: bug

#1416 Fix processing txs from me using initial balances
  cmd/node/factory/structs.go
  data/errors.go
  epochStart/genesis/genesisBlockCreator_test.go
  epochStart/metachain/rewards_test.go
  integrationTests/testProcessorNode.go
  node/nodeTesting_test.go
  node/node_test.go
  process/block/postprocess/intermediateResults_test.go
  process/block/preprocess/balanceComputation.go
  process/block/preprocess/balanceComputation_test.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/export_test.go
  process/block/preprocess/interfaces.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardTxPreProcessor_test.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/dataValidators/txValidator.go
  process/dataValidators/txValidator_test.go
  process/errors.go
  process/factory/metachain/preProcessorsContainerFactory.go
  process/factory/metachain/preProcessorsContainerFactory_test.go
  process/factory/shard/preProcessorsContainerFactory.go
  process/factory/shard/preProcessorsContainerFactory_test.go
  process/mock/balanceComputationStub.go
  process/peer/process_test.go
  process/rewardTransaction/interceptedRewardTransaction_test.go
  process/rewardTransaction/process_test.go
  process/smartContract/hooks/blockChainHook_test.go
  process/transaction/interceptedTransaction_test.go
  process/transaction/metaProcess_test.go
  process/transaction/shardProcess_test.go
  process/unsigned/interceptedUnsignedTransaction_test.go
Labels: bug, enhancement

#1301 Fix antiflood num messages counting on multidata interceptor
  cmd/node/config/config.toml
  cmd/node/factory/interface.go
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  consensus/interface.go
  consensus/mock/p2pAntifloodHandlerStub.go
  consensus/spos/sposFactory/sposFactory_test.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  core/constants.go
  core/p2pCore.go
  dataRetriever/interface.go
  dataRetriever/mock/p2pAntifloodHandlerStub.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/messageProcessor.go
  dataRetriever/resolvers/messageProcessor_test.go
  dataRetriever/resolvers/transactionResolver_test.go
  dataRetriever/resolvers/trieNodeResolver.go
  dataRetriever/resolvers/trieNodeResolver_test.go
  epochStart/bootstrap/disabled/disabledAntiFloodHandler.go
  integrationTests/mock/nilAntifloodHandler.go
  integrationTests/mock/topicAntifloodStub.go
  node/heartbeat/interface.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/interface.go
  node/mock/p2pAntifloodHandlerStub.go
  node/node.go
  node/node_test.go
  node/options.go
  p2p/errors.go
  process/block/interceptedBlocks/interceptedMiniblock.go
  process/interceptors/common.go
  process/interceptors/common_test.go
  process/interceptors/multiDataInterceptor.go
  process/interface.go
  process/mock/floodPreventerStub.go
  process/mock/p2pAntifloodHandlerStub.go
  process/mock/topicFloodPreventerStub.go
  process/throttle/antiflood/factory/disabledAntiFlood.go
  process/throttle/antiflood/factory/disabledAntiFlood_test.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory_test.go
  process/throttle/antiflood/factory/p2pOutputAntiflood.go
  process/throttle/antiflood/factory/p2pOutputAntiflood_test.go
  process/throttle/antiflood/floodPreventers/nilTopicFloodPreventer.go
  process/throttle/antiflood/floodPreventers/nilTopicFloodPreventer_test.go
  process/throttle/antiflood/floodPreventers/quotaFloodPreventer.go
  process/throttle/antiflood/floodPreventers/quotaFloodPreventer_test.go
  process/throttle/antiflood/floodPreventers/topicFloodPreventer.go
  process/throttle/antiflood/floodPreventers/topicFloodPreventer_test.go
  process/throttle/antiflood/p2pAntiflood.go
  process/throttle/antiflood/p2pAntiflood_test.go
  sharding/networksharding/peerShardMapper.go
Labels: bug

#1428 Cleanup storage on bootstrap for higher nonce if exists
  process/sync/storageBootstrap/baseStorageBootstrapper.go
  process/sync/storageBootstrap/interface.go
  process/sync/storageBootstrap/metaStorageBootstrapper.go
  process/sync/storageBootstrap/shardStorageBootstrapper.go
Labels: bug

#1433 Fix requested received missing txs
  process/block/baseProcess.go
  process/block/metablock.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/track/shardBlockTrack.go
Labels: bug

#1434 TxCache Trace to Debug
  cmd/node/factory/structs.go
  integrationTests/mock/poolscleanerMock.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  process/block/argProcessor.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/poolsCleaner/txPoolsCleaner.go
  process/block/poolsCleaner/txPoolsCleaner_test.go
  process/block/shardblock.go
  process/interface.go
  process/mock/poolscleanerMock.go
  storage/txcache/monitoring.go
  storage/txcache/txCache.go
Labels: enhancement

#1440 Fixed key-value range problem and append to slice with predefined len
  epochStart/shardchain/trigger.go
Labels: bug

#1401 En 6078 genesis file format
  genesis/delegationData.go
  genesis/delegationData_test.go
  genesis/errors.go
  genesis/export_test.go
  genesis/genesis.go
  genesis/genesis_test.go
  genesis/initialAccount.go
  genesis/initialAccount_test.go
  genesis/mock/addressConverterStub.go
  genesis/mock/addressMock.go
  genesis/mock/pubkeyConverterStub.go
  genesis/mock/shardCoordinatorMock.go
  genesis/testdata/genesis_bad.json
  genesis/testdata/genesis_ok.json
Labels: enhancement

#1450 Bug fix/revert state to block if no block inepoch
  epochStart/shardchain/trigger.go
  epochStart/shardchain/trigger_test.go
Labels: bug

#1383 keep oldest epoch in metablock pruning storer
  data/block/metaBlock.pb.go
  data/block/proto/metaBlock.proto
  dataRetriever/chainStorer.go
  dataRetriever/interface.go
  dataRetriever/mock/chainStorerMock.go
  epochStart/bootstrap/disabled/disabledChainStorer.go
  epochStart/bootstrap/epochStartMetaBlockProcessor.go
  epochStart/metachain/epochStartData.go
  epochStart/mock/chainStorerStub.go
  integrationTests/mock/chainStorerMock.go
  node/mock/chainStorerMock.go
  process/block/metablock.go
  process/block/shardblock.go
  process/mock/chainStorerMock.go
  storage/errors.go
  storage/interface.go
  storage/pruning/export_test.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorer_test.go
  update/mock/chainStorerMock.go
Labels: enhancement

#1452 Fix bech32 warn
  process/common.go
Labels: bug

#1453 Added num of shards in node/status route
  cmd/node/main.go
  cmd/node/metrics/machineStatistics.go
  cmd/node/metrics/metrics.go
  core/constants.go
Labels: enhancement

#1451 Staking/Unstaking/Reactivate after jail
  cmd/node/config/economics.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/economicsConfig.go
  data/state/accountsDB.go
  data/state/interface.go
  data/state/peerAccount.go
  data/state/peerAccountData.pb.go
  data/state/peerAccount_test.go
  data/state/proto/peerAccountData.proto
  epochStart/errors.go
  epochStart/genesis/genesisBlockCreator.go
  epochStart/interface.go
  epochStart/metachain/economics.go
  epochStart/metachain/economics_test.go
  epochStart/mock/nodesSetupStub.go
  epochStart/mock/raterStub.go
  integrationTests/mock/nodesSetupStub.go
  integrationTests/mock/raterMock.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/vm/systemVM/systemVm_test.go
  process/block/metablock.go
  process/economics/economicsData.go
  process/economics/economicsData_test.go
  process/errors.go
  process/factory/metachain/vmContainerFactory.go
  process/factory/metachain/vmContainerFactory_test.go
  process/interface.go
  process/mock/nodesConfigProviderStub.go
  process/mock/nodesSetupStub.go
  process/mock/peerAccountHandlerMock.go
  process/mock/raterMock.go
  process/mock/ratingsInfoMock.go
  process/peer/process.go
  process/peer/process_test.go
  process/rating/blockSigningRater.go
  process/rating/ratingsData.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
  sharding/indexHashedNodesCoordinator.go
  sharding/interface.go
  sharding/nodesSetup.go
  update/genesis/base.go
  vm/errors.go
  vm/factory/systemSCFactory.go
  vm/factory/systemSCFactory_test.go
  vm/interface.go
  vm/mock/nodesConfigProviderStub.go
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/auction_test.go
  vm/systemSmartContracts/proto/staking.proto
  vm/systemSmartContracts/staking.go
  vm/systemSmartContracts/staking.pb.go
  vm/systemSmartContracts/staking_test.go
Labels: enhancement

#1457 Extended cross tx cleaner for all txs
  cmd/node/factory/structs.go
  process/block/poolsCleaner/crossTxsPoolsCleaner.go
  process/block/poolsCleaner/crossTxsPoolsCleaner_test.go
  process/constants.go
Labels: enhancement

#1459 En 6079 genesis refactor
  cmd/node/factory/structs.go
  cmd/node/main.go
  epochStart/bootstrap/factory/epochStartInterceptorsContainerFactory.go
  epochStart/genesis/genesisBlockCreator.go
  epochStart/genesis/genesisBlockCreator_test.go
  epochStart/genesis/genesisFeeHandler.go
  epochStart/genesis/nilMessageSignVerifier.go
  genesis/delegationData.go
  genesis/errors.go
  genesis/initialAccount.go
  genesis/interface.go
  genesis/mock/accountsStub.go
  genesis/mock/blockChainStub.go
  genesis/mock/chainStorerMock.go
  genesis/mock/coordinatorStub.go
  genesis/mock/genesisParserStub.go
  genesis/mock/hasherMock.go
  genesis/mock/initialNodesSetupHandlerStub.go
  genesis/mock/marshalizerMock.go
  genesis/mock/poolsHolderMock.go
  genesis/mock/pubkeyConverterMock.go
  genesis/mock/storerMock.go
  genesis/mock/txLogProcessorMock.go
  genesis/mock/uint64ByteSliceConverterMock.go
  genesis/parser/export_test.go
  genesis/parser/genesis.go
  genesis/parser/genesis_test.go
  genesis/parser/testdata/genesis_bad.json
  genesis/parser/testdata/genesis_ok.json
  genesis/process/argGenesisBlockCreator.go
  genesis/process/disabled/disabledFeeHandler.go
  genesis/process/disabled/disabledMessageSignVerifier.go
  genesis/process/genesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/memoryComponents.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  genesis/process/testdata/genesis.json
  integrationTests/state/genesisState/genesisEdgeCase.json
  integrationTests/state/genesisState/genesisState_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/testInitializer.go
  process/economics/testEconomicsData.go
  sharding/common.go
  sharding/genesis.go
  sharding/genesis_test.go
  update/factory/exportHandlerFactory.go
  vm/factory/systemSCFactory_test.go
  vm/systemSmartContracts/defaults/gasMap.go
Labels: enhancement

#1454 add whitelist for already verified (sig) txs
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  epochStart/bootstrap/export_test.go
  epochStart/bootstrap/factory/epochStartInterceptorsContainerFactory.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testProcessorNode.go
  node/node.go
  node/options.go
  node/options_test.go
  process/factory/interceptorscontainer/args.go
  process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  process/interceptors/disabledWhiteListDataVerifier.go
  process/interceptors/factory/argInterceptedDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory_test.go
  process/interceptors/factory/interceptedTxDataFactory.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/whiteListDataVerifier.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncInterceptors.go
Labels: enhancement

#1422 Changed key filename
  README.md
  cmd/keygenerator/main.go
  cmd/node/config/config.toml
  cmd/node/config/genesis.json
  cmd/node/config/nodesSetup.json
  cmd/node/main.go
  scripts/testnet/include/config.sh
Labels: bug, enhancement

#1469 added check for initial nodes against the genesis file
  cmd/node/config/genesis.json
  cmd/node/config/nodesSetup.json
  cmd/node/factory/structs.go
  cmd/node/main.go
  epochStart/mock/nodeInfoMock.go
  genesis/checking/nodesSetupChecker.go
  genesis/checking/nodesSetupChecker_test.go
  genesis/data/delegationData.go
  genesis/data/delegationData_test.go
  genesis/data/initialAccount.go
  genesis/data/initialAccount_test.go
  genesis/errors.go
  genesis/interface.go
  genesis/mock/genesisNodeInfoHandlerMock.go
  genesis/mock/genesisParserStub.go
  genesis/parsing/export_test.go
  genesis/parsing/genesis.go
  genesis/parsing/genesis_test.go
  genesis/parsing/testdata/genesis_bad.json
  genesis/parsing/testdata/genesis_ok.json
  genesis/process/argGenesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/mock/nodeInfoMock.go
  integrationTests/state/genesisState/genesisState_test.go
  integrationTests/testProcessorNodeWithCoordinator.go
  process/mock/nodeInfoMock.go
  process/peer/process.go
  scripts/testnet/include/config.sh
  scripts/testnet/variables.sh
  sharding/indexHashedNodesCoordinatorRegistry.go
  sharding/interface.go
  sharding/nodesSetup.go
Labels: enhancement

#1470 Collect more sigs if possible
  consensus/interface.go
  consensus/mock/subroundHandlerMock.go
  consensus/spos/bls/constants.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/subround.go
  dataRetriever/provider/miniBlocks.go
  dataRetriever/provider/miniBlocks_test.go
  process/block/poolsCleaner/txsPoolsCleaner.go
  process/block/poolsCleaner/txsPoolsCleaner_test.go
  process/block/preprocess/basePreProcess.go
  process/block/shardblock.go
  process/constants.go
  process/interface.go
  process/mock/miniBlocksProviderStub.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/baseSync.go
  process/sync/baseSync_test.go
  process/sync/export_test.go
  process/sync/interface.go
  process/sync/metaForkDetector.go
  process/sync/metablock.go
  process/sync/shardForkDetector.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
Labels: enhancement

#1475 Resolver debugger fixes
  configP2P.json
  dataRetriever/interface.go
  dataRetriever/mock/resolverDebugHandlerStub.go
  dataRetriever/resolvers/headerResolver.go
  dataRetriever/resolvers/miniblockResolver.go
  dataRetriever/resolvers/transactionResolver.go
  dataRetriever/resolvers/trieNodeResolver.go
  debug/factory/interface.go
  debug/resolver/disabledInterceptorResolver.go
  debug/resolver/disabledInterceptorResolver_test.go
  debug/resolver/export_test.go
  debug/resolver/interceptorResolver.go
  debug/resolver/interceptorResolver_test.go
  web-server.json
Labels: enhancement

#1479 EN-6272: heartbeat identity field
  cmd/node/config/prefs.toml
  cmd/node/main.go
  config/prefsConfig.go
  integrationTests/testP2PNode.go
  node/heartbeat/heartbeat.pb.go
  node/heartbeat/heartbeatMessageInfo.go
  node/heartbeat/heartbeatMessageInfo_test.go
  node/heartbeat/heartbeatMessageValidator.go
  node/heartbeat/heartbeatdata.go
  node/heartbeat/monitor.go
  node/heartbeat/proto/heartbeat.proto
  node/heartbeat/sender.go
  node/node.go
  node/node_test.go
Labels: enhancement

#1483 Fix edge case on forced roll back cleaning pool
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/baseSync.go
  sharding/indexHashedNodesCoordinator.go
  sharding/interface.go
  sharding/mock/nodesCoordinatorCacheMock.go
Labels: bug
