Repository multiversx/mx-chain-go, pull requests merged in 2020-08, with the labels that each got.

#2198 adapted testnet's script to new filegen
  scripts/testnet/include/config.sh
  scripts/testnet/variables.sh
Labels: enhancement

#2191 Fix wrong genesis block save
  cmd/node/factory/structs.go
Labels: P2, bug

#2208 En 7301 fix boostrap from storage
  epochStart/bootstrap/process.go
Labels: bug

#2205 Exchanges integration - additions
  api/block/routes.go
  cmd/node/metrics/metrics.go
  core/constants.go
  node/blockAPI/metaBlock.go
  node/blockAPI/shardBlock.go
  process/block/metablock.go
  process/block/metrics.go
  process/block/shardblock.go
  statusHandler/presenter/blockInfoGetters.go
  statusHandler/presenter/blockInfoGetters_test.go
  statusHandler/statusMetricsProvider.go
  statusHandler/view/interface.go
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: enhancement

#2192 Fix log inside pruning storer
  storage/pruning/pruningStorer.go
Labels: enhancement

#2203 En 7295 get username route
  api/address/routes.go
  api/address/routes_test.go
  api/errors/errors.go
  api/mock/facade.go
  cmd/node/config/api.toml
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  node/errors.go
  node/node.go
  node/node_test.go
Labels: enhancement

#2221 Use block tracker alongside headers pool
  process/track/baseBlockTrack_test.go
  process/track/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: bug, enhancement

#2217 Exchanges integration - additions
  api/block/routes.go
  data/transaction/apiTransactionResult.go
  node/blockAPI/metaBlock.go
  node/blockAPI/shardBlock.go
  node/nodeBlocks_test.go
  node/nodeTransactions.go
  node/nodeTransactions_test.go
  scripts/testnet/include/config.sh
Labels: enhancement

#2223 En 7316 add call value sc query
  api/vmValues/routes.go
  process/interface.go
  process/smartContract/scQueryService.go
  process/smartContract/scQueryService_test.go
Labels: enhancement

#2199 Soft-fork boilerplate
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/config.go
  core/forking/export_test.go
  core/forking/genericEpochNotifier.go
  core/forking/genericEpochNotifier_test.go
  core/interface.go
  core/mock/epochSubscriberHandlerStub.go
  genesis/errors.go
  genesis/process/argGenesisBlockCreator.go
  genesis/process/genesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/multiShard/softfork/scDeploy_test.go
  integrationTests/multiShard/softfork/testdata/answer.wasm
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/testSyncNode.go
  integrationTests/vm/arwen/arwenVM/arwenVM_test.go
  integrationTests/vm/arwen/utils.go
  integrationTests/vm/testInitializer.go
  process/block/argProcessor.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/errors.go
  process/interface.go
  process/mock/epochNotifierStub.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
Labels: enhancement

#2232 Fix-failing-integration-tests
  integrationTests/multiShard/relayedTx/relayedTx_test.go
Labels: enhancement

#2235 Add receipts hash storer
  cmd/node/config/config.toml
  config/config.go
  config/tomlConfig_test.go
  dataRetriever/interface.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/transactionCoordinatorMock.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/testInitializer.go
  node/nodeMemoryConfig_test.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/metablock.go
  process/block/shardblock.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interface.go
  process/mock/intermediateTransactionHandlerMock.go
  process/mock/transactionCoordinatorMock.go
  process/sync/shardblock_test.go
  process/track/baseBlockTrack_test.go
  storage/factory/pruningStorerFactory.go
  testscommon/generalConfig.go
  update/mock/transactionCoordinatorMock.go
  update/process/shardBlock.go
  update/process/shardBlock_test.go
  update/sync/syncHeaders_test.go
Labels: enhancement

#2238 fixed the situation when empty receipts would have been saved
  process/block/baseProcess.go
  process/coordinator/process.go
  update/process/shardBlock.go
Labels: bug

#2240 Fix save genesis meta to storage
  epochStart/bootstrap/fromLocalStorage.go
  genesis/process/metaGenesisBlockCreator.go
Labels: bug

#2242 Add marshalized receipts in storer
  process/block/baseProcess.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  update/process/shardBlock.go
Labels: enhancement

#2243 Fixed the delegation SC deploy at genesis after hardfork
  genesis/process/genesisBlockCreator.go
Labels: bug

#2253 Changed log level in scope of debugging
  process/block/preprocess/transactions.go
  process/smartContract/process.go
  process/transaction/shardProcess.go
Labels: enhancement

#2250 Adapt prerequisites.sh for Arch based distributions.
  scripts/testnet/prerequisites.sh
Labels: enhancement

#2249 EN-7479: storer 2 elastic bug fixes
  cmd/storer2elastic/config.toml
  cmd/storer2elastic/config/configParser.go
  cmd/storer2elastic/data/dtos.go
  cmd/storer2elastic/dataprocessor/dataProcessor.go
  cmd/storer2elastic/dataprocessor/dataReplayer.go
  cmd/storer2elastic/dataprocessor/ratingsProcessor.go
  cmd/storer2elastic/dataprocessor/tpsBenchmarkUpdater.go
  cmd/storer2elastic/main.go
Labels: bug

#2256 Handle transactions towards metachain in DbLookupExtensions
  core/dblookupext/historyRepository.go
  core/dblookupext/historyRepository_test.go
  data/transaction/apiTransactionResult.go
  data/transaction/status.go
  data/transaction/status_test.go
  node/nodeTransactions.go
  node/nodeTransactions_test.go
Labels: enhancement

#2258 Fix epoch set in manual epoch notifier
  cmd/node/factory/structs.go
  cmd/node/main.go
  epochStart/notifier/manualEpochStartNotifier.go
Labels: bug
