Repository multiversx/mx-chain-go, pull requests merged in 2020-09, with the labels that each got.

#2257 Fix backwards compatibility for tx fee
  cmd/node/main.go
  epochStart/metachain/systemSCs_test.go
  epochStart/mock/epochNotifierStub.go
  genesis/process/disabled/feeHandler.go
  integrationTests/mock/epochNotifierStub.go
  integrationTests/mock/feeHandlerStub.go
  integrationTests/testProcessorNode.go
  node/mock/txFeeHandlerStub.go
  process/economics/economicsData.go
  process/economics/economicsData_test.go
  process/factory/metachain/vmContainerFactory_test.go
  process/interface.go
  process/mock/feeHandlerStub.go
  process/peer/process_test.go
  process/transaction/baseProcess.go
  process/transaction/interceptedTransaction.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
Labels: enhancement

#2259 Fix block data cleaning from pools
  core/constants.go
  integrationTests/mock/intermediateTransactionHandlerMock.go
  node/mock/intermProcessorStub.go
  p2p/libp2p/directSender.go
  p2p/libp2p/directSender_test.go
  p2p/libp2p/netMessenger.go
  process/block/metablock.go
  process/block/postprocess/intermediateResults.go
  process/block/postprocess/intermediateResults_test.go
  process/block/postprocess/oneMBPostProcessor.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/blockSizeComputation_test.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardTxPreProcessor_test.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/validatorInfoPreProcessor.go
  process/block/preprocess/validatorInfoPreProcessor_test.go
  process/block/shardblock.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/factory/shard/preProcessorsContainerFactory.go
  process/interface.go
  process/mock/intermediateTransactionHandlerMock.go
  process/mock/preprocessorMock.go
  process/smartContract/process.go
  process/transaction/shardProcess.go
Labels: bug, enhancement

#2264 EN-7221: extra unit tests for factory package
  factory/blockProcessorCreator_test.go
  factory/consensusComponents.go
  factory/consensusComponents_test.go
  factory/cryptoComponentsHandler_test.go
  factory/export_test.go
  factory/mock/bootstrapStorerStub.go
  factory/mock/epochStartTriggerStub.go
  factory/mock/forkDetectorStub.go
  factory/mock/stateComponentsHolderStub.go
  factory/processComponents_test.go
  factory/stateComponentsHandler_test.go
  factory/statusComponentsHandler_test.go
Labels: enhancement

#2268 Fix set of final block after restart in epoch
  consensus/mock/forkDetectorMock.go
  integrationTests/mock/forkDetectorStub.go
  node/mock/forkDetectorMock.go
  process/interface.go
  process/mock/forkDetectorMock.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
Labels: bug

#2260 EN-7433: storer to elastic - fix miniblock not found
  cmd/storer2elastic/config.toml
  cmd/storer2elastic/config/configParser.go
  cmd/storer2elastic/databasereader/databaseReader.go
  cmd/storer2elastic/databasereader/persistersReader.go
  cmd/storer2elastic/dataprocessor/dataProcessor.go
  cmd/storer2elastic/dataprocessor/dataReplayer.go
  cmd/storer2elastic/dataprocessor/ratingsProcessor.go
  cmd/storer2elastic/main.go
Labels: bug

#2277 Fixed meta smart contract processor arguments
  cmd/node/factory/structs.go
Labels: bug

#2276 Fix execution order of cross mini blocks
  consensus/mock/headerHandlerStub.go
  data/block/block.go
  data/block/block_test.go
  data/block/metaBlock.go
  data/block/metaBlock_test.go
  data/interface.go
  integrationTests/multiShard/relayedTx/edgecases/edgecases_test.go
  integrationTests/multiShard/relayedTx/relayedTx_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/mock/headerHandlerStub.go
  sharding/mock/headerHandlerStub.go
Labels: bug, enhancement

#2269 Optimize db lookup extensions while sync & fast-reply-database
  cmd/node/main.go
  core/dblookupext/historyRepository.go
  core/dblookupext/historyRepository_test.go
  core/dblookupext/interface.go
  core/dblookupext/nilHistoryRepository.go
  process/block/metablock.go
  process/block/shardblock.go
  testscommon/genericmocks/storerMock.go
  testscommon/historyRepositoryStub.go
Labels: enhancement

#2213 Unit tests for storer2elastic tool
  cmd/storer2elastic/databasereader/databaseReader_test.go
  cmd/storer2elastic/databasereader/headerMarshalizer_test.go
  cmd/storer2elastic/databasereader/persistersReader_test.go
  cmd/storer2elastic/dataprocessor/dataProcessor.go
  cmd/storer2elastic/dataprocessor/dataProcessor_test.go
  cmd/storer2elastic/dataprocessor/dataReplayer.go
  cmd/storer2elastic/dataprocessor/dataReplayer_test.go
  cmd/storer2elastic/dataprocessor/errors.go
  cmd/storer2elastic/dataprocessor/export_test.go
  cmd/storer2elastic/dataprocessor/interface.go
  cmd/storer2elastic/dataprocessor/ratingsProcessor.go
  cmd/storer2elastic/dataprocessor/ratingsProcessor_test.go
  cmd/storer2elastic/main.go
  cmd/storer2elastic/mock/accountsAdapterStub.go
  cmd/storer2elastic/mock/dataReplayerStub.go
  cmd/storer2elastic/mock/databaseReaderStub.go
  cmd/storer2elastic/mock/directoryReaderStub.go
  cmd/storer2elastic/mock/elasticIndexerStub.go
  cmd/storer2elastic/mock/genesisNodesSetupHandlerStub.go
  cmd/storer2elastic/mock/hasherMock.go
  cmd/storer2elastic/mock/headerMarshalizerStub.go
  cmd/storer2elastic/mock/marshalizerMock.go
  cmd/storer2elastic/mock/nodeInfoMock.go
  cmd/storer2elastic/mock/persisterFactoryStub.go
  cmd/storer2elastic/mock/persisterStub.go
  cmd/storer2elastic/mock/pubKeyConverterMock.go
  cmd/storer2elastic/mock/ratingsProcessorStub.go
  cmd/storer2elastic/mock/shardCoordinatorMock.go
  cmd/storer2elastic/mock/tpsBenchmarkUpdaterStub.go
  cmd/storer2elastic/mock/uint64ByteSliceConverterMock.go
Labels: enhancement

#2280 Improve block tracker computation time
  core/dblookupext/interface.go
  integrationTests/mock/blockTrackerStub.go
  node/mock/blockTrackerStub.go
  process/interface.go
  process/mock/blockNotifierHandlerMock.go
  process/mock/blockNotifierHandlerStub.go
  process/mock/blockTrackerMock.go
  process/sync/baseForkDetector_test.go
  process/sync/shardForkDetector.go
  process/track/argBlockProcessor.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockNotifier.go
  process/track/blockNotifier_test.go
  process/track/blockProcessor.go
  process/track/blockProcessor_test.go
  process/track/errors.go
  process/track/export_test.go
  process/track/interface.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: enhancement

#2285 Signal double key usage in the network
  heartbeat/componentHandler/heartbeatHandler.go
  heartbeat/data/heartbeat.pb.go
  heartbeat/data/heartbeatdata.go
  heartbeat/data/proto/heartbeat.proto
  heartbeat/mock/timerMock.go
  heartbeat/process/export_test.go
  heartbeat/process/heartbeatMessageInfo.go
  heartbeat/process/heartbeatMessageInfo_test.go
  heartbeat/process/monitor.go
  heartbeat/process/monitor_test.go
  integrationTests/mock/timeCacherStub.go
  node/mock/timeCacheStub.go
  process/interface.go
  process/mock/blackListHandlerStub.go
  process/mock/timeCacheStub.go
  process/throttle/antiflood/disabled/timeCacher.go
  storage/timecache/timeCache.go
Labels: enhancement

#2287 wrapped vm output api response
  api/mock/facade.go
  api/vmValues/routes.go
  api/vmValues/routes_test.go
  data/vm/vmOutputApi.go
  data/vm/vmOutputApi_test.go
  facade/nodeFacade.go
Labels: enhancement

#2292 EN-6936: log route on seednode
  cmd/seednode/api/api.go
  cmd/seednode/main.go
Labels: enhancement

#2301 Limit the number of the same consensus message type from the same pk
  consensus/mock/sposWorkerMock.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/bls/subroundStartRound_test.go
  consensus/spos/consensusMessageValidator.go
  consensus/spos/consensusMessageValidator_test.go
  consensus/spos/constants.go
  consensus/spos/errors.go
  consensus/spos/export_test.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
Labels: enhancement

#2310 Sync tracker pool with headers pool
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/mock/blockTrackerHandlerMock.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockProcessor.go
  process/track/blockProcessor_test.go
  process/track/export_test.go
  process/track/interface.go
Labels: bug, enhancement

#2297 added FullArchive setting in config.toml
  cmd/node/main.go
  cmd/node/metrics/metrics.go
  config/config.go
  config/p2pConfig.go
  consensus/interface.go
  consensus/mock/networkShardingCollectorStub.go
  consensus/spos/worker_test.go
  core/constants.go
  core/p2pCore.go
  data/state/peerTypeInfo.go
  factory/networkComponents_test.go
  heartbeat/componentHandler/heartbeatHandler.go
  heartbeat/componentHandler/heartbeatHandler_test.go
  heartbeat/data/heartbeat.pb.go
  heartbeat/data/heartbeatdata.go
  heartbeat/data/proto/heartbeat.proto
  heartbeat/interface.go
  heartbeat/mock/networkShardingCollectorStub.go
  heartbeat/process/export_test.go
  heartbeat/process/heartbeatMessageInfo.go
  heartbeat/process/heartbeatMessageInfo_test.go
  heartbeat/process/heartbeatMessageValidator.go
  heartbeat/process/messageProcessor.go
  heartbeat/process/messageProcessor_test.go
  heartbeat/process/monitor.go
  heartbeat/process/sender.go
  integrationTests/interface.go
  integrationTests/mock/networkShardingCollectorMock.go
  integrationTests/mock/networkShardingCollectorStub.go
  integrationTests/node/heartbeat/heartbeat_test.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/testP2PNode.go
  node/interface.go
  node/mock/networkShardingCollectorStub.go
  node/node.go
  node/node_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/networksharding/factory/sharderFactory.go
  p2p/libp2p/networksharding/factory/sharderFactory_test.go
  p2p/libp2p/networksharding/listsSharder.go
  p2p/libp2p/networksharding/listsSharder_test.go
  p2p/p2p.go
  process/peer/peerTypeProvider.go
  sharding/networksharding/peerShardMapper.go
  sharding/networksharding/peerShardMapper_test.go
  statusHandler/presenter/instanceInfoGetters.go
  statusHandler/view/interface.go
Labels: enhancement

#2321 Resize termui gauge label
  cmd/node/config/ratings.toml
  statusHandler/view/termuic/termuiRenders/widgetsRender.go
Labels: bug

#2323 Improved subround EndRound and fixed some mocks/linter warns
  cmd/node/factory/interface.go
  consensus/interface.go
  consensus/mock/consensusDataContainerMock.go
  consensus/mock/headerSigVerifierStub.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/consensusCore_test.go
  consensus/spos/interface.go
  consensus/spos/worker_test.go
  integrationTests/mock/headerSigVerifierStub.go
  node/mock/headerSigVerifierStub.go
  node/node.go
  node/options.go
  process/headerCheck/headerSignatureVerify.go
  process/headerCheck/headerSignatureVerify_test.go
Labels: enhancement

#2333 Fixed configs for a better testing process
  cmd/node/config/economics.toml
  cmd/node/config/genesis.json
  cmd/node/config/genesisContracts/dns.wasm
  cmd/node/config/genesisSmartContracts.json
  cmd/node/config/nodesSetup.json
  cmd/node/config/systemSmartContractsConfig.toml
  cmd/node/config/testKeys/delegationWalletKey.pem
  cmd/node/config/testKeys/dnsWalletKey.pem
  cmd/node/config/testKeys/esdtWalletKey.pem
  cmd/node/config/testKeys/protocolSustainabilityWalletKey.pem
  cmd/node/config/upgradeContracts/dns/v3.0/deploy.json
  cmd/node/config/upgradeContracts/dns/v3.0/dns.wasm
  scripts/testnet/include/config.sh
Labels: bug
