Repository multiversx/mx-chain-go, pull requests merged in 2020-01, with the labels that each got.

#941 Hack nodes coordinator without rating
  cmd/node/main.go
Labels: bug

#824 En 4571 new cache for headers
  dataRetriever/dataPool/headersCache/errors.go
  dataRetriever/dataPool/headersCache/headersByHashMap.go
  dataRetriever/dataPool/headersCache/headersCache.go
  dataRetriever/dataPool/headersCache/headersCounter.go
  dataRetriever/dataPool/headersCache/headersPool.go
  dataRetriever/dataPool/headersCache/headersPool_test.go
  dataRetriever/dataPool/headersCache/listOfHeadersByNonces.go
  dataRetriever/dataPool/headersCache/structs.go
  dataRetriever/interface.go
Labels: enhancement

#846 EN-5525 - Block tracker component
  process/constants.go
  process/errors.go
  process/track/argBlockTrack.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockNotarizer.go
  process/track/blockNotarizer_test.go
  process/track/blockNotifier.go
  process/track/blockNotifier_test.go
  process/track/blockProcessor.go
  process/track/blockProcessor_test.go
  process/track/errors.go
  process/track/export_test.go
  process/track/interface.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: enhancement

#937 En 5556 antiflood feedback loop conn mngr
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  consensus/spos/worker_test.go
  core/p2pConstants.go
  dataRetriever/resolvers/genericBlockBodyResolver_test.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/transactionResolver_test.go
  integrationTests/p2p/antiflood/antiflooding_test.go
  integrationTests/p2p/antiflood/blacklist_test.go
  integrationTests/p2p/antiflood/messageProcessor.go
  integrationTests/sync/basicSync_test.go
  integrationTests/sync/common.go
  integrationTests/sync/edgeCases_test.go
  integrationTests/testInitializer.go
  node/heartbeat/interface.go
  node/heartbeat/messageProcessor.go
  node/heartbeat/messageProcessor_test.go
  node/heartbeat/monitor.go
  node/heartbeat/monitorEdgeCases_test.go
  node/heartbeat/monitor_test.go
  node/heartbeat/sender_test.go
  node/mock/messageHandlerStub.go
  p2p/antiflood/p2pAntiflood.go
  p2p/antiflood/p2pAntiflood_test.go
  p2p/errors.go
  p2p/libp2p/connectionMonitor.go
  p2p/libp2p/connectionMonitorNotifier.go
  p2p/libp2p/connectionMonitorNotifier_test.go
  p2p/libp2p/connectionMonitor_test.go
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  p2p/libp2p/issues_test.go
  p2p/libp2p/libp2pConnectionMonitor.go
  p2p/libp2p/libp2pConnectionMonitor_test.go
  p2p/libp2p/libp2pContext.go
  p2p/libp2p/libp2pContext_test.go
  p2p/libp2p/memMessenger.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/libp2p/options.go
  p2p/libp2p/options_test.go
  p2p/memp2p/errors.go
  p2p/memp2p/messenger.go
  p2p/mock/blacklistHandlerStub.go
  p2p/mock/connectionMonitorStub.go
  p2p/mock/nilBlacklistHandler.go
  p2p/mock/reconnecterStub.go
  p2p/p2p.go
  process/errors.go
  process/throttle/antiflood/p2pBlackListProcessor.go
  process/throttle/antiflood/p2pBlackListProcessor_test.go
  process/throttle/antiflood/quotaFloodPreventer.go
  process/throttle/antiflood/quotaFloodPreventer_test.go
  statusHandler/p2pQuota/interface.go
  statusHandler/p2pQuota/p2pQuotaProcessor.go
  statusHandler/p2pQuota/p2pQuotaProcessor_test.go
Labels: enhancement

#939 small optimization in nodes coordinator
  core/export_test.go
  core/stopWatch.go
  core/stopWatch_test.go
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  process/block/metablock.go
  process/block/shardblock.go
  process/peer/export_test.go
  process/peer/mediators.go
  process/peer/process.go
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinator_test.go
Labels: enhancement

#946 fixed display of bad params error when prioBits is 0
  p2p/libp2p/networksharding/kadSharder.go
Labels: bug

#945 En 5550 validator statistics integration test
  data/block/metaBlock.go
  data/block/metaBlock_test.go
  data/state/accountsDB.go
  data/state/peerAccount.go
  data/state/peerAccount_test.go
  data/state/peerJournalEntries.go
  data/state/peerJournalEntries_test.go
  data/trie/branchNode.go
  epochStart/metachain/pendingMiniBlocks.go
  go.mod
  go.sum
  integrationTests/multiShard/block/executingMiniblocksSc_test.go
  integrationTests/multiShard/block/interceptedHeadersSigVerification_test.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/singleShard/block/executingMiniblocksSc_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/vm/iele/vmAgar_test.go
  integrationTests/vm/systemVM/systemVm_test.go
  process/block/metablock.go
  process/peer/process.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/process.go
  sharding/indexHashedNodesCoordinator.go
Labels: bug

#744 EN-5153 : extract processed mini blocks map to a struct
  consensus/mock/blockProcessorMock.go
  integrationTests/mock/blockProcessorMock.go
  node/mock/blockProcessorStub.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/processedMb/processedMiniBlocks.go
  process/block/processedMb/processedMiniBlocks_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/common.go
  process/interface.go
  process/mock/blockProcessorMock.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
Labels: enhancement

#900 fix pruning on rollback
  data/trie/patriciaMerkleTrie.go
  data/trie/trieStorageManager.go
  data/trie/trieStorageManager_test.go
  integrationTests/state/stateTrie_test.go
  process/sync/baseSync.go
  scripts/testnet/include/nodes.sh
Labels: bug

#958 Api middleware
  api/api.go
  api/errors/errors.go
  api/middleware/errors.go
  api/middleware/globalThrottler.go
  api/middleware/globalThrottler_test.go
  api/middleware/sourceThrottler.go
  api/middleware/sourceThrottler_test.go
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
  facade/elrondNodeFacade.go
  facade/elrondNodeFacade_test.go
  facade/errors.go
  facade/mock/apiResolverStub.go
  facade/mock/nodeMock.go
  facade/mock/syncTimerMock.go
Labels: enhancement

#870 En 5433/staking sc auction continues
  cmd/node/config/economics.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  config/economicsConfig.go
  epochStart/genesis/genesisBlockCreator.go
  epochStart/metachain/pendingMiniBlocks_test.go
  epochStart/mock/cacherStub.go
  epochStart/mock/marshalizerMock.go
  epochStart/shardchain/trigger.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multiShard/smartContract/testdata/build-cToWasm.sh
  integrationTests/multiShard/smartContract/testdata/delegate/delegate.c
  integrationTests/multiShard/smartContract/testdata/delegate/delegate.wasm
  integrationTests/multiShard/smartContract/testdata/main.syms
  integrationTests/testProcessorNode.go
  integrationTests/vm/systemVM/systemVm_test.go
  p2p/memp2p/export_test.go
  p2p/memp2p/messenger.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/economics/economicsData.go
  process/economics/economicsData_test.go
  process/errors.go
  process/factory/metachain/vmContainerFactory.go
  process/factory/metachain/vmContainerFactory_test.go
  process/interface.go
  process/mock/messageSignVerifierMock.go
  process/mock/validatorSettingsStub.go
  process/peer/process_test.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
  vm/errors.go
  vm/factory/factory.go
  vm/factory/systemSCFactory.go
  vm/factory/systemSCFactory_test.go
  vm/interface.go
  vm/mock/argumentsParserMock.go
  vm/mock/keyGenMock.go
  vm/mock/keyMock.go
  vm/mock/messageSignVerifierMock.go
  vm/mock/signerMock.go
  vm/mock/systemEIStub.go
  vm/mock/validatorSettingsStub.go
  vm/process/messageSigVerifier.go
  vm/process/messageSigVerifier_test.go
  vm/process/systemVM.go
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/auction_test.go
  vm/systemSmartContracts/eei.go
  vm/systemSmartContracts/eei_test.go
  vm/systemSmartContracts/staking.go
  vm/systemSmartContracts/staking_test.go
Labels: bug, enhancement

#960 EN-5593: add option to disable the storage pruning
  cmd/node/config/config.toml
  config/config.go
  storage/factory/pruningStorerFactory.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorerArgs.go
  storage/pruning/pruningStorer_test.go
Labels: enhancement

#962 remove network ID config and flag
  cmd/node/config/config.toml
  cmd/node/main.go
  config/config.go
Labels: enhancement

#949 En 4945 block tracker integration
  cmd/node/factory/structs.go
  cmd/node/main.go
  consensus/mock/forkDetectorMock.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/blockTrackerStub.go
  integrationTests/mock/forkDetectorMock.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/testSyncNode.go
  node/errors.go
  node/mock/blockTrackerStub.go
  node/mock/forkDetectorMock.go
  node/node.go
  node/options.go
  node/options_test.go
  process/block/argProcessor.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/bootstrapStorage/bootstrapStorer.go
  process/block/bootstrapStorage/bootstrapStorer_test.go
  process/block/displayBlock.go
  process/block/displayMetaBlock.go
  process/block/export_test.go
  process/block/headerValidator.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/constants.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/errors.go
  process/interface.go
  process/mock/blockTrackerMock.go
  process/mock/forkDetectorMock.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
  process/sync/baseSync.go
  process/sync/export_test.go
  process/sync/metaForkDetector.go
  process/sync/metaForkDetector_test.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardForkDetector.go
  process/sync/shardForkDetector_test.go
  process/sync/shardblock_test.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
  process/sync/storageBootstrap/interface.go
  process/sync/storageBootstrap/metaStorageBootstrapper.go
  process/sync/storageBootstrap/shardStorageBootstrapper.go
  process/track/argBlockTrack.go
  process/track/baseBlockTrack.go
  process/track/blockProcessor.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: bug, enhancement

#950 EN-5579: add close method for all store units
  cmd/node/main.go
  data/interface.go
  data/mock/storerStub.go
  data/mock/trieStub.go
  data/state/accountsDB.go
  data/state/interface.go
  data/trie/patriciaMerkleTrie.go
  dataRetriever/chainStorer.go
  dataRetriever/interface.go
  dataRetriever/mock/chainStorerMock.go
  dataRetriever/mock/storerStub.go
  epochStart/mock/chainStorerStub.go
  epochStart/mock/storerStub.go
  integrationTests/mock/chainStorerMock.go
  node/mock/accountsStub.go
  node/mock/chainStorerMock.go
  node/mock/storerMock.go
  node/mock/storerStub.go
  process/mock/accountsStub.go
  process/mock/chainStorerMock.go
  process/mock/storerMock.go
  process/mock/storerStub.go
  statusHandler/mock/storerStub.go
  storage/errors.go
  storage/interface.go
  storage/pruning/pruningStorer.go
  storage/storageUnit/nilStorer.go
  storage/storageUnit/storageunit.go
Labels: enhancement

#957 En 5589 fix missing invalid transactions
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  core/stopWatch.go
  data/trie/interceptedNode.go
  epochStart/genesis/genesisBlockCreator.go
  integrationTests/singleShard/block/executingMiniblocks_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  process/block/baseProcess.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader.go
  process/block/interceptedBlocks/interceptedTxBlock.go
  process/block/metablock.go
  process/block/poolsCleaner/txPoolsCleaner.go
  process/block/poolsCleaner/txPoolsCleaner_test.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/transactions.go
  process/block/shardblock.go
  process/dataValidators/txValidator.go
  process/dataValidators/txValidator_test.go
  process/errors.go
  process/factory/metachain/feeHandler.go
  process/interceptors/common.go
  process/interceptors/processor/interface.go
  process/interceptors/processor/txInterceptorProcessor.go
  process/interface.go
  process/mock/interceptedDataStub.go
  process/mock/interceptedTxHandlerStub.go
  process/mock/txValidatorHandlerStub.go
  process/rating/nilRatingReader.go
  process/rewardTransaction/interceptedRewardTransaction.go
  process/rewardTransaction/interceptedRewardTransaction_test.go
  process/transaction/baseProcess.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  process/transaction/metaProcess.go
  process/transaction/metaProcess_test.go
  process/transaction/shardProcess.go
  process/unsigned/interceptedUnsignedTransaction.go
  process/unsigned/interceptedUnsignedTransaction_test.go
Labels: bug

#984 En 5614 kad dht parameters
  cmd/node/config/p2p.toml
  cmd/node/factory/structs.go
  cmd/seednode/config/p2p.toml
  cmd/seednode/main.go
  config/config.go
  integrationTests/consensus/testInitializer.go
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/testInitializer.go
  p2p/errors.go
  p2p/example/libp2p/autodiscovery/main.go
  p2p/libp2p/discovery/export_test.go
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  p2p/libp2p/discovery/kadDhtDiscoverer_test.go
  p2p/libp2p/factory/peerDiscovererCreator.go
  p2p/libp2p/factory/peerDiscovererFactory.go
  p2p/libp2p/factory/peerDiscovererFactory_test.go
Labels: bug, enhancement

#987 * Fixed multiple requests/prints in block tracker when a node is syncing
  process/constants.go
  process/track/baseBlockTrack.go
  process/track/blockProcessor.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: bug, enhancement

#989 fixed some calls to Lock and Unlock
  data/trie/trieStorageManager.go
  epochStart/metachain/pendingMiniBlocks.go
Labels: bug

#994 Fixed pending minblocks test
  epochStart/metachain/pendingMiniBlocks_test.go
Labels: bug

#998 take out context timeout when publishing messages on pubsub
  p2p/libp2p/netMessenger.go
Labels: bug

#999 En 5624 improve bls consensus process commit block
  consensus/mock/sposWorkerMock.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/constants.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/commonSubround/subroundBlock.go
  consensus/spos/commonSubround/subroundStartRound.go
  consensus/spos/commonSubround/subroundStartRound_test.go
  consensus/spos/consensusState.go
  consensus/spos/consensusState_test.go
  consensus/spos/constants.go
  consensus/spos/interface.go
  consensus/spos/subround.go
  consensus/spos/worker.go
  node/node.go
  process/block/metablock.go
  process/block/shardblock.go
Labels: enhancement

#1006 Added sleep between p2p sends
  p2p/libp2p/netMessenger.go
Labels: bug

#976 En 5596 new kad sharder implementation
  cmd/node/config/p2p.toml
  cmd/node/factory/structs.go
  cmd/node/main.go
  cmd/seednode/main.go
  config/config.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go
  integrationTests/testInitializer.go
  integrationTests/testP2PNode.go
  p2p/errors.go
  p2p/libp2p/connectionMonitor/factory/connectionMonitorFactory.go
  p2p/libp2p/connectionMonitor/factory/connectionMonitorFactory_test.go
  p2p/libp2p/connectionMonitor/factory/interface.go
  p2p/libp2p/connectionMonitor/interface.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitor.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple_test.go
  p2p/libp2p/connectionMonitor/libp2pConnectionMonitor_test.go
  p2p/libp2p/connectionMonitor/nilConnectionMonitor.go
  p2p/libp2p/connectionMonitor/nilConnectionMonitor_test.go
  p2p/libp2p/discovery/continuousKadDhtDiscoverer.go
  p2p/libp2p/discovery/continuousKadDhtDiscoverer_test.go
  p2p/libp2p/discovery/export_test.go
  p2p/libp2p/discovery/factory/peerDiscovererFactory.go
  p2p/libp2p/discovery/factory/peerDiscovererFactory_test.go
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  p2p/libp2p/discovery/kadDhtDiscoverer_test.go
  p2p/libp2p/factory/peerDiscovererFactory_test.go
  p2p/libp2p/interface.go
  p2p/libp2p/memMessenger.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/libp2p/networksharding/factory/sharderFactory.go
  p2p/libp2p/networksharding/factory/sharderFactory_test.go
  p2p/libp2p/networksharding/listKadSharder.go
  p2p/libp2p/networksharding/listKadSharder_test.go
  p2p/libp2p/networksharding/peerDistances.go
  p2p/libp2p/networksharding/peerDistances_test.go
  p2p/libp2p/unknownPeerShardResolver.go
  p2p/libp2p/unknownPeerShardResolver_test.go
  p2p/memp2p/messenger.go
  p2p/mock/nilConnectionMonitor.go
  p2p/mock/peerDiscovererStub.go
  p2p/mock/reconnecterStub.go
  p2p/mock/reconnecterWithPauseAndResumeStub.go
  p2p/mock/sharderStub.go
  p2p/p2p.go
Labels: enhancement

#1011 Fix sync state on rollback edge case
  consensus/mock/forkDetectorMock.go
  integrationTests/mock/forkDetectorMock.go
  node/mock/forkDetectorMock.go
  process/constants.go
  process/interface.go
  process/mock/forkDetectorMock.go
  process/sync/baseForkDetector.go
  process/sync/baseSync.go
Labels: bug

#1012 En 5621 maligned fixes
  api/node/routes.go
  cmd/logviewer/main.go
  cmd/node/factory/structs.go
  config/config.go
  core/indexer/data.go
  data/block/block.go
  data/block/metaBlock.go
  data/mock/multipleShardsCoordinatorMock.go
  data/rewardTx/rewardTx.go
  dataRetriever/mock/multipleShardsCoordinatorMock.go
  dataRetriever/requestData.go
  epochStart/shardchain/trigger.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/multipleShardsCoordinatorMock.go
  node/heartbeat/export_test.go
  node/heartbeat/hearbeatMessageInfo.go
  node/heartbeat/heartbeat.go
  node/mock/multipleShardsCoordinatorMock.go
  node/node.go
  p2p/libp2p/discovery/kadDhtDiscoverer.go
  process/mock/multipleShardsCoordinatorMock.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorerArgs.go
  storage/storageUnit/storageunit.go
Labels: enhancement

#1013 - updated libp2p to latest releases
  go.mod
  go.sum
  p2p/libp2p/netMessenger_test.go
Labels: bug

#1002 En 5459 hardfork impl unit tests
  update/interface.go
  update/mock/accountsHandlerStub.go
  update/mock/cacherMock.go
  update/mock/cacherStub.go
  update/mock/chainStorerMock.go
  update/mock/endOfEpochTriggerStub.go
  update/mock/epochMiniBlocksSyncHandlerMock.go
  update/mock/epochStartTriesSyncHandlerMock.go
  update/mock/hasherStub.go
  update/mock/headerSyncHandlerMock.go
  update/mock/headerValidatorStub.go
  update/mock/marshalizerFake.go
  update/mock/oneShardCoordinatorMock.go
  update/mock/pendingTransactionsSyncHandlerMock.go
  update/mock/poolsHolderMock.go
  update/mock/requestHandlerStub.go
  update/mock/storerStub.go
  update/mock/trieStub.go
  update/mock/trieSyncersStub.go
  update/mock/triesHolderMock.go
  update/sync/base.go
  update/sync/concurrentTriesMap.go
  update/sync/coordinator.go
  update/sync/coordinator_test.go
  update/sync/syncHeaders.go
  update/sync/syncHeaders_test.go
  update/sync/syncMiniBlocks.go
  update/sync/syncMiniBlocks_test.go
  update/sync/syncTransactions.go
  update/sync/syncTransactions_test.go
  update/sync/syncTries.go
  update/sync/syncTries_test.go
Labels: enhancement

#1010 En 5642 add stats for consensus
  consensus/mock/sposWorkerMock.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bn/bnSubroundsFactory.go
  consensus/spos/commonSubround/export_test.go
  consensus/spos/commonSubround/subroundBlock.go
  consensus/spos/commonSubround/subroundBlock_test.go
  consensus/spos/commonSubround/subroundStartRound.go
  consensus/spos/export_test.go
  consensus/spos/interface.go
  consensus/spos/subround.go
  consensus/spos/subround_test.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  core/constants.go
Labels: enhancement

#1018 Missing header 2020
  cmd/node/factory/structs.go
  dataRetriever/dataPool/headersCache/headersCache.go
  dataRetriever/dataPool/headersCache/headersPool.go
  epochStart/metachain/trigger.go
  epochStart/shardchain/trigger.go
  integrationTests/resolvers/metablock_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/testSyncNode.go
  process/block/interceptedBlocks/argInterceptedBlockHeader.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/block/metablock.go
  process/factory/metachain/interceptorsContainerFactory.go
  process/factory/metachain/interceptorsContainerFactory_test.go
  process/factory/shard/interceptorsContainerFactory.go
  process/factory/shard/interceptorsContainerFactory_test.go
  process/interceptors/factory/argInterceptedDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory_test.go
  process/interceptors/factory/interceptedShardHeaderDataFactory.go
  process/interceptors/factory/nilEpochTrigger.go
  process/peer/process.go
Labels: bug

#974 EN-5599: topic antiflood
  api/transaction/routes_test.go
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  consensus/interface.go
  consensus/mock/consensusDataContainerMock.go
  consensus/mock/mockTestInitializer.go
  consensus/mock/p2pAntifloodHandlerStub.go
  consensus/spos/bls/blsWorker.go
  consensus/spos/bn/bnWorker.go
  consensus/spos/common.go
  consensus/spos/commonSubround/subroundStartRound.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCore_test.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  dataRetriever/common.go
  dataRetriever/factory/metachain/resolversContainerFactory.go
  dataRetriever/factory/shard/resolversContainerFactory.go
  dataRetriever/interface.go
  dataRetriever/mock/p2pAntifloodHandlerStub.go
  dataRetriever/resolvers/headerResolver.go
  dataRetriever/resolvers/headerResolver_test.go
  integrationTests/mock/nilAntifloodHandler.go
  integrationTests/mock/topicAntifloodStub.go
  integrationTests/p2p/antiflood/messageProcessor.go
  node/heartbeat/interface.go
  node/heartbeat/messageProcessor.go
  node/heartbeat/messageProcessor_test.go
  node/heartbeat/monitor.go
  node/heartbeat/monitor_test.go
  node/interface.go
  node/mock/p2pAntifloodHandlerStub.go
  node/node.go
  node/node_test.go
  p2p/antiflood/p2pAntiflood.go
  p2p/antiflood/p2pAntiflood_test.go
  p2p/errors.go
  p2p/mock/topicFloodPreventerStub.go
  p2p/p2p.go
  process/throttle/antiflood/export_test.go
  process/throttle/antiflood/topicFloodPreventer.go
  process/throttle/antiflood/topicFloodPreventer_test.go
Labels: enhancement

#1035 removed accumulator from project
  crypto/accumulator/accumulator.go
  crypto/accumulator/rsa/rsaAcc.go
  crypto/accumulator/rsa/rsaAcc_test.go
Labels: enhancement
