Repository multiversx/mx-chain-go, pull requests merged in 2020-12, with the labels that each got.

#2511 Execute postprocessor after hard fork
  core/converters.go
  genesis/process/disabled/rewardTxProcessor.go
  genesis/process/genesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/testInitializer.go
  scripts/testnet/include/tools.sh
  update/common.go
  update/common_test.go
  update/errors.go
  update/interface.go
  update/mock/addressMock.go
  update/mock/hardForkBlockProcessor.go
  update/mock/hasherMock.go
  update/mock/pendingTransactionProcessorStub.go
  update/process/afterHardFork.go
  update/process/afterHardFork_test.go
  update/process/baseProcess.go
  update/process/metaBlock.go
  update/process/metaBlock_test.go
  update/process/processPending.go
  update/process/processPending_test.go
  update/process/shardBlock.go
  update/process/shardBlock_test.go
Labels: bug, enhancement

#2513 EN-7818 hardfork resolver fixes
  debug/resolver/interceptorResolver.go
  update/constants.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncResolversContainerFactory.go
  update/sync/coordinator.go
  update/sync/coordinator_test.go
  update/sync/syncAccountsDBs.go
Labels: bug

#2534 Fix epoch start trigger when epoch start previous header is missing
  epochStart/shardchain/trigger.go
  process/track/baseBlockTrack.go
Labels: bug

#2533 Resolver fixes
  cmd/node/main.go
  dataRetriever/resolvers/miniblockResolver.go
  dataRetriever/resolvers/miniblockResolver_test.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender.go
  dataRetriever/resolvers/transactionResolver.go
  integrationTests/resolvers/metablock/metablock_test.go
Labels: bug

#2539 Hardfork fixes 2020.12.02
  cmd/node/main.go
  debug/resolver/interceptorResolver.go
  epochStart/interface.go
  epochStart/metachain/economics_test.go
  epochStart/metachain/trigger.go
  epochStart/metachain/trigger_test.go
  epochStart/shardchain/trigger.go
  integrationTests/mock/endOfEpochTriggerStub.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testP2PNode.go
  integrationTests/testProcessorNode.go
  node/mock/endOfEpochTriggerStub.go
  update/errors.go
  update/factory/exportHandlerFactory.go
  update/interface.go
  update/mock/epochHandlerStub.go
  update/mock/roundHandlerStub.go
  update/trigger/export_test.go
  update/trigger/trigger.go
  update/trigger/trigger_test.go
Labels: bug

#2517 EN-8343-optimize-trie-sync
  data/trie/sync.go
Labels: bug, enhancement

#2538 Feat/hardfork fixes01
  cmd/node/main.go
  core/converters.go
  data/interface.go
  data/syncer/baseAccountsSyncer.go
  data/syncer/userAccountsSyncer.go
  data/syncer/validatorAccountsSyncer.go
  data/trie/errors.go
  data/trie/statistics/trieSyncStatistics.go
  data/trie/statistics/trieSyncStatistics_test.go
  data/trie/sync.go
  data/trie/sync_test.go
  debug/resolver/interceptorResolver.go
  epochStart/interface.go
  epochStart/metachain/economics_test.go
  epochStart/metachain/trigger.go
  epochStart/metachain/trigger_test.go
  epochStart/shardchain/trigger.go
  genesis/process/disabled/rewardTxProcessor.go
  genesis/process/genesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/mock/endOfEpochTriggerStub.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/testInitializer.go
  integrationTests/testP2PNode.go
  integrationTests/testProcessorNode.go
  node/mock/endOfEpochTriggerStub.go
  scripts/testnet/include/tools.sh
  update/common.go
  update/common_test.go
  update/constants.go
  update/errors.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncResolversContainerFactory.go
  update/interface.go
  update/mock/addressMock.go
  update/mock/epochHandlerStub.go
  update/mock/hardForkBlockProcessor.go
  update/mock/hasherMock.go
  update/mock/pendingTransactionProcessorStub.go
  update/mock/roundHandlerStub.go
  update/process/afterHardFork.go
  update/process/afterHardFork_test.go
  update/process/baseProcess.go
  update/process/metaBlock.go
  update/process/metaBlock_test.go
  update/process/processPending.go
  update/process/processPending_test.go
  update/process/shardBlock.go
  update/process/shardBlock_test.go
  update/sync/coordinator.go
  update/sync/coordinator_test.go
  update/sync/syncAccountsDBs.go
  update/trigger/export_test.go
  update/trigger/trigger.go
  update/trigger/trigger_test.go
Labels: enhancement

#2521 max number of shards for genesis config
  cmd/node/config/config.toml
  cmd/node/main.go
  cmd/storer2elastic/main.go
  config/config.go
  sharding/errors.go
  sharding/nodesSetup.go
  sharding/nodesSetup_test.go
  testscommon/generalConfig.go
Labels: enhancement

#2548 En 8341/protection agains mass unstake
  epochStart/errors.go
  epochStart/metachain/systemSCs.go
  epochStart/metachain/systemSCs_test.go
  integrationTests/mock/epochStartSystemSCStub.go
  integrationTests/mock/validatorStatisticsProcessorStub.go
  node/mock/peerProcessorMock.go
  node/mock/validatorStatisticsProcessorStub.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/interface.go
  process/mock/epochStartSystemSCStub.go
  process/mock/validatorStatisticsProcessorStub.go
  process/peer/process.go
  process/peer/process_test.go
  process/peer/validatorsProvider_test.go
  vm/factory/systemSCFactory.go
  vm/systemSmartContracts/validator.go
  vm/systemSmartContracts/validator_test.go
Labels: enhancement

#2563 Hardfork storers closing on soft restart
  factory/processComponents.go
  genesis/process/genesisBlockCreator.go
  update/factory/exportHandlerFactory.go
  update/genesis/export.go
  update/genesis/import.go
  update/interface.go
  update/mock/importHandlerStub.go
  update/storing/hardforkStorer.go
Labels: enhancement

#2570 Trie sync fixes
  data/syncer/baseAccountsSyncer.go
  data/syncer/userAccountsSyncer.go
  data/syncer/validatorAccountsSyncer.go
  data/trie/branchNode_test.go
  data/trie/errors.go
  data/trie/export_test.go
  data/trie/extensionNode_test.go
  data/trie/leafNode_test.go
  data/trie/node_test.go
  data/trie/sync.go
  data/trie/sync_test.go
  data/trie/trieStorageManager_test.go
  epochStart/bootstrap/process.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  update/constants.go
  update/factory/accountDBSyncerContainerFactory.go
  update/factory/exportHandlerFactory.go
  update/interface.go
  update/mock/epochStartTriesSyncHandlerMock.go
  update/sync/coordinator.go
  update/sync/syncAccountsDBs.go
  update/sync/syncAccountsDBs_test.go
Labels: bug, enhancement

#2454 EN-8058: hashers refactoring
  core/indexer/dataIndexer_test.go
  crypto/signing/mcl/singlesig/bls_bench_test.go
  data/trie/patriciaMerkleTrie_test.go
  epochStart/metachain/systemSCs_test.go
  factory/cryptoComponents.go
  hashing/blake2b/blake2b.go
  hashing/blake2b/blake2b_test.go
  hashing/blake2b/errors.go
  hashing/factory/hasherFactory.go
  hashing/factory/hasherFactory_test.go
  hashing/fnv/fnv.go
  hashing/hasher.go
  hashing/hasher_test.go
  hashing/keccak/keccak.go
  hashing/sha256/sha256.go
  integrationTests/consensus/testInitializer.go
  integrationTests/longTests/storage/storage_test.go
  integrationTests/mock/keyMock.go
  integrationTests/multiShard/smartContract/dns/dns_test.go
  integrationTests/multisig/blsMultisig_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/vm/arwen/arwenVM/arwenVM_test.go
  integrationTests/vm/arwen/utils.go
  integrationTests/vm/testInitializer.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/vmCrypto.go
  process/smartContract/hooks/vmCrypto_test.go
  sharding/expandedListSampling_test.go
  sharding/hashValidatorShuffler.go
  sharding/indexHashedNodesCoordinatorWithRater_test.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/weightedRandomSampling_test.go
  storage/bloom/bloom.go
  storage/bloom/bloom_test.go
  storage/storageUnit/storageunit.go
  storage/storageUnit/storageunit_test.go
  vm/systemSmartContracts/esdt.go
Labels: enhancement

#2582 added example tests for addresses and bls signing
  examples/address_test.go
  examples/blsSigning_test.go
Labels: enhancement

#2588 EN-8500: ESDT fixes
  core/indexer/elasticProcessor.go
  integrationTests/multiShard/relayedTx/relayedTx_test.go
  integrationTests/vm/esdt/esdtProcess_test.go
  process/errors.go
  process/factory/metachain/vmContainerFactory.go
  process/smartContract/builtInFunctions/esdtFreezeWipe.go
  process/smartContract/builtInFunctions/esdtFreezeWipe_test.go
  vm/errors.go
  vm/factory/systemSCFactory.go
  vm/factory/systemSCFactory_test.go
  vm/mock/pubKeyConverterMock.go
  vm/systemSmartContracts/esdt.go
  vm/systemSmartContracts/esdt.pb.go
  vm/systemSmartContracts/esdt_test.go
  vm/systemSmartContracts/proto/esdt.proto
Labels: enhancement

#2607 Fixed the OriginalSender encoding in nodeTransactions.go
  node/nodeTransactions.go
  node/nodeTransactions_test.go
Labels: bug

#2605 Arithmetic difference economics useful print
  epochStart/metachain/rewards.go
Labels: enhancement, low prio

#2608 Optimize set owner in system sc
  epochStart/metachain/epochStartData.go
  epochStart/metachain/stakingDataProvider_test.go
  epochStart/metachain/systemSCs.go
  epochStart/metachain/systemSCs_test.go
  vm/systemSmartContracts/staking.go
  vm/systemSmartContracts/staking_test.go
  vm/systemSmartContracts/validator.go
  vm/systemSmartContracts/validator_test.go
Labels: bug, enhancement

#2617 Fixed backwards compatibility new issue
  integrationTests/vm/arwen/arwenVM/arwenVM_test.go
  integrationTests/vm/arwen/arwenVM/gasSchedule_test.go
  integrationTests/vm/arwen/delegation/delegation_test.go
  integrationTests/vm/arwen/wasmer/wasmer_test.go
  integrationTests/vm/mockVM/vmDeploy/vmDeploy_test.go
  integrationTests/vm/mockVM/vmGet/vmGet_test.go
  integrationTests/vm/mockVM/vmRunContract/vmRunContract_test.go
  integrationTests/vm/testInitializer.go
  integrationTests/vm/txsFee/backwardsCompatibility_test.go
  integrationTests/vm/txsFee/builtInFunctions_test.go
  integrationTests/vm/txsFee/moveBalance_test.go
  integrationTests/vm/txsFee/multiShard/builtInFunctions_test.go
  integrationTests/vm/txsFee/multiShard/moveBalance_test.go
  integrationTests/vm/txsFee/multiShard/relayedBuiltInFunctions_test.go
  integrationTests/vm/txsFee/multiShard/relayedMoveBalance_test.go
  integrationTests/vm/txsFee/multiShard/relayedScDeploy_test.go
  integrationTests/vm/txsFee/multiShard/relayedTxScCalls_test.go
  integrationTests/vm/txsFee/multiShard/scCalls_test.go
  integrationTests/vm/txsFee/relayedBuiltInFunctions_test.go
  integrationTests/vm/txsFee/relayedMoveBalance_test.go
  integrationTests/vm/txsFee/relayedScCalls_test.go
  integrationTests/vm/txsFee/relayedScDeploy_test.go
  integrationTests/vm/txsFee/scCalls_test.go
  integrationTests/vm/txsFee/scDeploy_test.go
  integrationTests/vm/txsFee/utils/utils.go
  process/smartContract/testUtils.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
Labels: bug

#2618 Fix token name length condition
  vm/systemSmartContracts/esdt.go
Labels: bug

#2627 System delegation SC scenarios
  integrationTests/vm/delegation/delegationScenarios_test.go
Labels: enhancement

#2628 Staking fixes
  epochStart/metachain/systemSCs.go
  epochStart/metachain/systemSCs_test.go
  sharding/common.go
  vm/systemSmartContracts/staking.go
Labels: bug
