Repository multiversx/mx-chain-go, pull requests merged in 2020-06, with the labels that each got.

#1830 Fix whitelist problem
  dataRetriever/requestHandlers/requestHandler.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/errors.go
  process/interceptors/processor/miniblockInterceptorProcessor.go
Labels: bug, enhancement

#1837 Fix bootstrap from storage edge case for shard nodes
  process/block/shardblock.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
Labels: bug

#1834 bugFix/validator-empty-at-restart
  process/interceptors/disabledWhiteListDataVerifier.go
  process/peer/validatorsProvider.go
  process/peer/validatorsProvider_test.go
Labels: bug

#1833 bugFix/stake-stake-claim-auction-sc
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/auction_test.go
Labels: bug

#1842 [Minor bug / minor fix] TxPool - fix inconsistent counters (estimators)
  storage/immunitycache/cache_test.go
  storage/immunitycache/chunk.go
  storage/txcache/maps/bucketSortedMap.go
  storage/txcache/maps/bucketSortedMap_test.go
  storage/txcache/maps/concurrentMap.go
  storage/txcache/maps/concurrentMap_test.go
  storage/txcache/txByHashMap.go
  storage/txcache/txListBySenderMap.go
Labels: bug

#1835 bugFix/account-wrap-is-nil
  data/state/accountsDB.go
  data/state/accountsDB_test.go
  data/state/journalEntries.go
  data/state/journalEntries_test.go
  data/trie/patriciaMerkleTrie.go
  process/coordinator/process.go
  process/scToProtocol/stakingToPeer.go
  process/smartContract/process.go
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/staking.go
Labels: bug

#1838 Optimize cross headers requests when is not really needed
  process/block/metablock.go
  process/block/shardblock.go
  process/sync/metablock.go
  process/sync/shardblock.go
Labels: enhancement

#1848 Fix consensus group is null
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/worker.go
Labels: bug

#1847 added nonce metrics in network status
  cmd/node/metrics/metrics.go
  core/constants.go
  epochStart/metachain/trigger.go
  epochStart/shardchain/trigger.go
  statusHandler/statusMetricsProvider.go
Labels: enhancement

#1852 Hotfix antiflood
  p2p/libp2p/netMessenger.go
  process/throttle/antiflood/blackList/p2pBlackListProcessor.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory.go
  storage/errors.go
  storage/timecache/export_test.go
  storage/timecache/timeCache.go
  storage/timecache/timeCache_test.go
Labels: bug

#1855 added software version metric to network config endpoint
  api/network/routes.go
  statusHandler/statusMetricsProvider.go
Labels: enhancement

#1859 Commit block measurement time
  consensus/spos/bls/subroundEndRound.go
  core/constants.go
  process/block/baseProcess.go
  process/sync/baseSync.go
Labels: enhancement

#1864 Bug fix/sync multiple tries
  api/mock/cacherStub.go
  cmd/node/config/config.toml
  consensus/mock/cacherMock.go
  core/common.go
  data/errors.go
  data/interface.go
  data/mock/cacherMock.go
  data/mock/uint64CacherStub.go
  data/syncer/userAccountsSyncer.go
  data/trie/sync.go
  dataRetriever/mock/cacherStub.go
  dataRetriever/requestHandlers/requestHandler.go
  epochStart/bootstrap/process.go
  epochStart/mock/cacherStub.go
  epochStart/shardchain/peerMiniBlocksSyncer.go
  integrationTests/mock/cacherStub.go
  integrationTests/resolvers/miniblocks/miniblocks_test.go
  integrationTests/singleShard/block/interceptedRequestTxBlockBody/interceptedRequestTxBlockBody_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/testProcessorNode.go
  node/mock/cacherStub.go
  process/block/poolsCleaner/miniBlocksPoolsCleaner.go
  process/mock/cacherMock.go
  process/mock/cacherStub.go
  process/mock/uint64SyncMapCacherStub.go
  process/sync/baseSync.go
  process/track/miniBlockTrack.go
  sharding/mock/cacherMock.go
  storage/fifocache/export_test.go
  storage/fifocache/fifocacheSharded.go
  storage/fifocache/fifocacheSharded_test.go
  storage/immunitycache/cache.go
  storage/interface.go
  storage/lrucache/export_test.go
  storage/lrucache/lrucache.go
  storage/lrucache/lrucache_test.go
  storage/txcache/disabledCache.go
  storage/txcache/disabledCache_test.go
  storage/txcache/txCache.go
  storage/txcache/txCache_test.go
  update/factory/accountDBSyncerContainerFactory.go
  update/mock/cacherMock.go
  update/mock/cacherStub.go
  update/sync/syncMiniBlocks.go
Labels: bug

#1876 bug fix get transaction api route
  node/nodeTransactions.go
  node/nodeTransactions_test.go
Labels: bug

#1868 EN-6612 added ports range capability on network messenger
  cmd/node/config/p2p.toml
  cmd/node/main.go
  cmd/seednode/config/p2p.toml
  cmd/seednode/main.go
  config/p2pConfig.go
  core/mock/intRandomizerStub.go
  core/random/concurrentSafeIntRandomizer.go
  core/random/fisherYates.go
  core/random/fisherYates_test.go
  dataRetriever/resolvers/topicResolverSender/export_test.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go
  factory/networkComponents_test.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/testInitializer.go
  p2p/errors.go
  p2p/example/libp2p/autodiscovery/main.go
  p2p/example/libp2p/internalBroadcastSpeedMeasure/main.go
  p2p/libp2p/issues_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/libp2p/ports.go
  p2p/libp2p/ports_test.go
  scripts/testnet/include/config.sh
Labels: enhancement

#1872 made epoch start metrics persistent and/or fetch from epoch bootstrapper
  cmd/node/main.go
  epochStart/bootstrap/common.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/mock/appStatusHandlerStub.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  process/sync/loadPersistentMetrics.go
  statusHandler/persister/persistentHandler.go
Labels: bug

#1870 En 6618 p2p rebroadcast message
  cmd/node/config/config.toml
  cmd/seednode/config/p2p.toml
  config/config.go
  factory/networkComponents.go
  factory/networkComponents_test.go
  p2p/errors.go
  p2p/libp2p/disabled/cacher.go
  p2p/libp2p/export_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/mock/cacherStub.go
  p2p/p2p.go
Labels: enhancement

#1898 Fix fork detector after double sign
  consensus/spos/bls/constants.go
  process/sync/baseForkDetector.go
  process/sync/baseForkDetector_test.go
Labels: bug

#1894 TermUI issues fix
  cmd/node/factory/structsStatusHandlers.go
  cmd/node/main.go
  cmd/node/metrics/metrics.go
  cmd/termui/main.go
  cmd/termui/provider/logProvider.go
  process/block/metrics.go
  statusHandler/errors.go
  statusHandler/factory/interface.go
  statusHandler/view/termuic/termuiConsole.go
Labels: bug

#1895 EN-6710 antiflood blocks consensus fix
  cmd/node/config/config.toml
  consensus/interface.go
  consensus/mock/p2pAntifloodHandlerStub.go
  consensus/spos/bls/blsWorker.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  dataRetriever/interface.go
  dataRetriever/mock/p2pAntifloodHandlerStub.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/messageProcessor.go
  dataRetriever/resolvers/messageProcessor_test.go
  dataRetriever/resolvers/transactionResolver_test.go
  dataRetriever/resolvers/trieNodeResolver_test.go
  debug/antiflood/debugger.go
  debug/antiflood/debugger_test.go
  epochStart/bootstrap/disabled/disabledAntiFloodHandler.go
  factory/interface.go
  heartbeat/interface.go
  heartbeat/mock/p2pAntifloodHandlerStub.go
  heartbeat/process/monitor.go
  heartbeat/process/monitor_test.go
  integrationTests/mock/nilAntifloodHandler.go
  integrationTests/mock/p2pAntifloodHandlerStub.go
  node/interface.go
  node/mock/p2pAntifloodHandlerStub.go
  process/interceptors/common.go
  process/interceptors/common_test.go
  process/interceptors/multiDataInterceptor.go
  process/interface.go
  process/mock/p2pAntifloodHandlerStub.go
  process/throttle/antiflood/disabled/antiflood.go
  process/throttle/antiflood/disabled/antifloodDebugger.go
  process/throttle/antiflood/disabled/antiflood_test.go
  process/throttle/antiflood/p2pAntiflood.go
  process/throttle/antiflood/p2pAntiflood_test.go
Labels: bug

#1918 Add peer info route
  api/errors/errors.go
  api/mock/facade.go
  api/node/routes.go
  api/node/routes_test.go
  cmd/node/config/api.toml
  consensus/interface.go
  consensus/mock/networkShardingCollectorStub.go
  core/p2pCore.go
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  heartbeat/interface.go
  heartbeat/mock/messengerStub.go
  integrationTests/mock/networkShardingCollectorMock.go
  node/errors.go
  node/interface.go
  node/mock/messengerStub.go
  node/mock/networkShardingCollectorStub.go
  node/node.go
  node/node_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/memp2p/messenger.go
  p2p/p2p.go
  sharding/networksharding/peerShardMapper.go
  sharding/networksharding/peerShardMapper_test.go
Labels: enhancement

#1931 Confirmation-of-epoch-start-block-too-fast
  core/constants.go
  process/block/baseProcess.go
Labels: bug, enhancement

#1942 Fix antiflood self blacklisted
  factory/networkComponents.go
  integrationTests/longTests/antiflooding/antiflooding_test.go
  integrationTests/mock/peerBlackListHandlerStub.go
  integrationTests/p2p/antiflood/blacklist/blacklist_test.go
  node/mock/peerBlackListHandler.go
  process/interface.go
  process/mock/peerBlackListHandlerStub.go
  process/throttle/antiflood/blackList/p2pBlackListProcessor.go
  process/throttle/antiflood/blackList/p2pBlackListProcessor_test.go
  process/throttle/antiflood/disabled/peerBlacklistHandler.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory.go
  process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory_test.go
  storage/interface.go
  storage/mock/timeCacheStub.go
  storage/timecache/export_test.go
  storage/timecache/peerTimeCache.go
  storage/timecache/peerTimeCache_test.go
  storage/timecache/timeCache.go
  storage/timecache/timeCache_test.go
Labels: bug

#1935 fix termui app when shuffled out or node stops
  cmd/termui/main.go
  cmd/termui/provider/logProvider.go
Labels: bug

#1914 Check if txs and mbs exists in es
  core/indexer/common.go
  core/indexer/elasticsearchDatabase.go
  core/indexer/elasticsearchDatabaseClient.go
  core/indexer/elasticsearchDatabase_test.go
  core/indexer/interface.go
  core/indexer/queries.go
  core/mock/databaseWriterMock.go
Labels: bug

#1952 Fix trie snapshot concurrency
  data/interface.go
  data/mock/storageManagerStub.go
  data/trie/patriciaMerkleTrie.go
  data/trie/patriciaMerkleTrie_test.go
  data/trie/snapshotDb.go
  data/trie/trieStorageManager.go
  data/trie/trieStorageManager_test.go
  epochStart/mock/storageManagerStub.go
  genesis/mock/storageManagerStub.go
  update/mock/storageManagerStub.go
Labels: bug

#1950 Elastic search new bug steam err
  core/indexer/common.go
  core/indexer/constants.go
  core/indexer/elasticsearchDatabase.go
  core/indexer/elasticsearchDatabaseClient.go
  core/indexer/elasticsearchDatabase_test.go
  core/indexer/queries.go
Labels: bug

#1957 bugFix/rewards-to-meta
  epochStart/errors.go
  epochStart/metachain/rewards.go
  epochStart/metachain/rewards_test.go
Labels: bug

#1925 Drop connection from peers if invalid data was sent
  cmd/node/config/config.toml
  consensus/interface.go
  consensus/mock/p2pAntifloodHandlerStub.go
  consensus/spos/worker.go
  core/constants.go
  dataRetriever/interface.go
  dataRetriever/mock/p2pAntifloodHandlerStub.go
  dataRetriever/resolvers/headerResolver.go
  dataRetriever/resolvers/messageProcessor.go
  dataRetriever/resolvers/messageProcessor_test.go
  dataRetriever/resolvers/miniblockResolver.go
  dataRetriever/resolvers/transactionResolver.go
  dataRetriever/resolvers/trieNodeResolver.go
  epochStart/bootstrap/disabled/disabledAntiFloodHandler.go
  epochStart/bootstrap/interface.go
  epochStart/bootstrap/process.go
  epochStart/mock/messengerStub.go
  factory/interface.go
  go.mod
  go.sum
  heartbeat/componentHandler/heartbeatHandler.go
  heartbeat/componentHandler/heartbeatHandler_test.go
  heartbeat/errors.go
  heartbeat/interface.go
  heartbeat/mock/p2pAntifloodHandlerStub.go
  heartbeat/process/monitor.go
  heartbeat/process/monitorEdgeCases_test.go
  heartbeat/process/monitor_test.go
  integrationTests/mock/nilAntifloodHandler.go
  integrationTests/mock/p2pAntifloodHandlerStub.go
  integrationTests/node/heartbeat/heartbeat_test.go
  integrationTests/p2p/pubsub/messageProcessor.go
  integrationTests/p2p/pubsub/unjoin_test.go
  node/interface.go
  node/mock/p2pAntifloodHandlerStub.go
  node/node.go
  p2p/errors.go
  p2p/issues/pubsub_349/main.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/loadBalancer/outgoingChannelLoadBalancer.go
  p2p/loadBalancer/outgoingChannelLoadBalancer_test.go
  p2p/mock/eventBusStub.go
  p2p/p2p.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/singleDataInterceptor_test.go
  process/interface.go
  process/mock/antifloodDebuggerStub.go
  process/mock/p2pAntifloodHandlerStub.go
  process/throttle/antiflood/disabled/antiflood.go
  process/throttle/antiflood/p2pAntiflood.go
  process/throttle/antiflood/p2pAntiflood_test.go
Labels: bug, enhancement

#1954 bugFix/close-app-always
  cmd/node/main.go
Labels: bug

#1816 En 6314/voting smart contract
  cmd/node/config/gasSchedule.toml
  cmd/node/config/systemSmartContractsConfig.toml
  cmd/node/factory/structs.go
  config/systemSmartContractsConfig.go
  genesis/process/genesisBlockCreator_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  process/factory/metachain/vmContainerFactory_test.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
  vm/errors.go
  vm/factory/factory.go
  vm/factory/systemSCFactory.go
  vm/factory/systemSCFactory_test.go
  vm/gasCost.go
  vm/systemSmartContracts/auction.go
  vm/systemSmartContracts/auction_test.go
  vm/systemSmartContracts/defaults/gasMap.go
  vm/systemSmartContracts/governance.go
  vm/systemSmartContracts/governance.pb.go
  vm/systemSmartContracts/governance_test.go
  vm/systemSmartContracts/proto/governance.proto
  vm/systemSmartContracts/staking.go
  vm/systemSmartContracts/staking_test.go
Labels: enhancement

#1956 load snapshots in order
  data/trie/trieStorageManager.go
  data/trie/trieStorageManager_test.go
Labels: bug

#1901 Delegation contract v0.3.0
  cmd/node/config/genesisContracts/delegation.wasm
  genesis/errors.go
  genesis/process/intermediate/standardDelegationProcessor.go
  genesis/process/intermediate/standardDelegationProcessor_test.go
  genesis/process/testdata/delegation.wasm
  genesis/process/testdata/smartcontracts.json
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multiShard/smartContract/testdata/delegate/delegation.wasm
  process/smartContract/process.go
  process/smartContract/vmInput.go
  vm/systemSmartContracts/auction.go
Labels: enhancement

#1965 Fix state of meta is stuck
  process/block/shardblock.go
Labels: bug

#1980 changed the message displayed when a key is not available in termui
  statusHandler/presenter/blockInfoGetters_test.go
  statusHandler/presenter/common.go
Labels: enhancement

#1985 Fix p2p debugger unit tests
  debug/p2p/export_test.go
  debug/p2p/p2pDebugger_test.go
Labels: bug

#1979 Add feedback for peer honesty in consensus
  cmd/node/main.go
  consensus/interface.go
  consensus/mock/consensusDataContainerMock.go
  consensus/mock/mockTestInitializer.go
  consensus/mock/peerHonestyHandlerStub.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/common.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCore_test.go
  consensus/spos/constants.go
  consensus/spos/errors.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/peerHonestyHandlerStub.go
  integrationTests/testP2PNode.go
  node/errors.go
  node/mock/peerHonestyHandlerStub.go
  node/node.go
  node/node_test.go
  node/options.go
  node/options_test.go
Labels: enhancement

#2006 added denomination in network config
  cmd/node/config/economics.toml
  cmd/node/metrics/metrics.go
  config/economicsConfig.go
  config/tomlConfig_test.go
  core/constants.go
  statusHandler/presenter/common.go
  statusHandler/presenter/instanceInfoGetters_test.go
  statusHandler/statusMetricsProvider.go
Labels: enhancement

#2012 Fixed intercepted txs test
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx/interceptedResolvedBulkTx_test.go
Labels: bug

#1988 Prune state only behind finalized
  integrationTests/testProcessorNode.go
  process/block/shardblock.go
Labels: bug

#1996 Add machine ID in version string
  cmd/node/main.go
  go.mod
  go.sum
Labels: enhancement

#2011 Hotfix p2p unjoin mutex
  p2p/libp2p/netMessenger.go
Labels: bug

#2010 removed process start function when shuffled out
  cmd/node/main.go
Labels: enhancement

#2013 Whitelist cross miniblocks to metachain
  cmd/node/factory/structs.go
  consensus/broadcast/metaChainMessenger.go
  consensus/broadcast/shardChainMessenger.go
  process/interceptors/processor/miniblockInterceptorProcessor.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/export_test.go
Labels: enhancement

#2021 Reject miniblocks which are not whitelisted
  integrationTests/resolvers/miniblocks/miniblocks_test.go
  integrationTests/singleShard/block/interceptedRequestTxBlockBody/interceptedRequestTxBlockBody_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/processor/miniblockInterceptorProcessor.go
Labels: enhancement

#2007 En 6833/antiflood observers
  cmd/node/factory/structs.go
  cmd/node/main.go
  consensus/mock/nodesCoordinatorMock.go
  core/mock/nodesCoordinatorMock.go
  dataRetriever/requestHandlers/requestHandler.go
  epochStart/bootstrap/disabled/disabledAntiFloodHandler.go
  epochStart/bootstrap/disabled/disabledNodesCoordinator.go
  epochStart/bootstrap/factory/epochStartInterceptorsContainerFactory.go
  epochStart/bootstrap/syncEpochStartMeta.go
  epochStart/mock/nodesCoordinatorStub.go
  factory/interface.go
  heartbeat/mock/nodesCoordinatorMock.go
  integrationTests/mock/nilAntifloodHandler.go
  integrationTests/mock/nodesCoordinatorMock.go
  integrationTests/testProcessorNode.go
  node/mock/nodesCoordinatorMock.go
  process/block/interceptedBlocks/argInterceptedBlockHeader.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/errors.go
  process/factory/interceptorscontainer/args.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  process/interceptors/factory/argInterceptedDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory.go
  process/interceptors/factory/interceptedMetaHeaderDataFactory_test.go
  process/interceptors/factory/interceptedShardHeaderDataFactory.go
  process/interceptors/factory/interceptedShardHeaderDataFactory_test.go
  process/interceptors/multiDataInterceptor.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/singleDataInterceptor.go
  process/interceptors/singleDataInterceptor_test.go
  process/interceptors/whiteListDataVerifier.go
  process/interceptors/whiteListDataVerifier_test.go
  process/interface.go
  process/mock/nodesCoordinatorMock.go
  process/mock/p2pAntifloodHandlerStub.go
  process/mock/peerShardResolverStub.go
  process/peer/process_test.go
  process/throttle/antiflood/disabled/antiflood.go
  process/throttle/antiflood/disabled/peerValidatorMapper.go
  process/throttle/antiflood/p2pAntiflood.go
  process/throttle/antiflood/p2pAntiflood_test.go
  sharding/indexHashedNodesCoordinator.go
  sharding/indexHashedNodesCoordinatorWithRater_test.go
  sharding/indexHashedNodesCoordinator_test.go
  sharding/interface.go
  sharding/networksharding/mock_test.go
  sharding/networksharding/peerShardMapper.go
  sharding/networksharding/peerShardMapper_test.go
  update/factory/fullSyncInterceptors.go
Labels: enhancement

#2023 En 6847 timestamp in p2p message
  cmd/node/config/config.toml
  cmd/node/main.go
  cmd/seednode/config/config.toml
  cmd/seednode/main.go
  config/config.go
  consensus/mock/p2pMessageMock.go
  core/constants.go
  dataRetriever/mock/p2pMessageMock.go
  factory/errors.go
  factory/networkComponents.go
  factory/networkComponents_test.go
  heartbeat/mock/p2pMessageStub.go
  integrationTests/mock/peerDenialEvaluatorStub.go
  integrationTests/testInitializer.go
  node/mock/peerDenialEvaluatorStub.go
  p2p/data/authMessage.go
  p2p/data/proto/topicMessage.proto
  p2p/data/topicMessage.pb.go
  p2p/errors.go
  p2p/example/libp2p/autodiscovery/main.go
  p2p/example/libp2p/internalBroadcastSpeedMeasure/main.go
  p2p/libp2p/connectionMonitorWrapper.go
  p2p/libp2p/connectionMonitorWrapper_test.go
  p2p/libp2p/directSender.go
  p2p/libp2p/directSender_test.go
  p2p/libp2p/disabled/cacher.go
  p2p/libp2p/disabled/nilPeerDenialEvaluator.go
  p2p/libp2p/disabled/nilPeerDenialEvaluator_test.go
  p2p/libp2p/export_test.go
  p2p/libp2p/issues_test.go
  p2p/libp2p/message.go
  p2p/libp2p/message_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/memp2p/message.go
  p2p/message/message.go
  p2p/mock/p2pMessageMock.go
  p2p/mock/peerDenialEvaluatorStub.go
  p2p/p2p.go
  process/mock/p2pMessageMock.go
  process/throttle/antiflood/blackList/peerDenialEvaluator.go
  process/throttle/antiflood/blackList/peerDenialEvaluator_test.go
  testscommon/protoMarshalizerMock.go
Labels: enhancement

#2031 Reject not whitelisted cross txs dest me
  cmd/node/factory/structs.go
  consensus/broadcast/commonMessenger.go
  consensus/broadcast/delayedBroadcast.go
  consensus/broadcast/delayedBroadcast_test.go
  consensus/broadcast/metaChainMessenger_test.go
  consensus/spos/bls/subroundEndRound.go
  core/constants.go
  epochStart/bootstrap/epochStartMetaBlockProcessor.go
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx/interceptedResolvedBulkTx_test.go
  integrationTests/multiShard/transaction/txRouting/txRouting_test.go
  integrationTests/singleShard/transaction/interceptedBulkTx/interceptedBulkTx_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  node/nodeTesting.go
  node/nodeTesting_test.go
  process/dataValidators/txValidator.go
  process/errors.go
  process/interceptors/processor/miniblockInterceptorProcessor.go
  process/interceptors/processor/miniblockInterceptorProcessor_test.go
  process/interceptors/processor/txInterceptorProcessor.go
  process/interface.go
  process/mock/nilTxValidator.go
  process/mock/txValidatorStub.go
  process/track/miniBlockTrack.go
  process/track/miniBlockTrack_test.go
Labels: enhancement

#2044 Fix pools cleaner lock-unlock and start from storage edge case
  consensus/broadcast/metaChainMessenger.go
  consensus/broadcast/shardChainMessenger.go
  consensus/broadcast/shardChainMessenger_test.go
  consensus/interface.go
  consensus/mock/broadcastMessangerMock.go
  consensus/spos/bls/subroundEndRound.go
  process/block/export_test.go
  process/block/poolsCleaner/miniBlocksPoolsCleaner.go
  process/block/poolsCleaner/txsPoolsCleaner.go
  process/block/shardblock.go
  process/block/shardblock_test.go
Labels: bug, enhancement

#2038 Refactored p2p blacklist prints
  dataRetriever/requestData.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  process/block/poolsCleaner/txsPoolsCleaner.go
  process/interceptors/whiteListDataVerifier.go
  process/track/miniBlockTrack.go
  scripts/testnet/include/config.sh
  scripts/testnet/variables.sh
Labels: bug
