Repository multiversx/mx-chain-go, pull requests merged in 2021-01, with the labels that each got.

#2638 EN-8537: unit tests for new view functions
  node/node.go
  vm/systemSmartContracts/delegation_test.go
  vm/systemSmartContracts/validator_test.go
Labels: enhancement

#2659 added trace log for invalid transaction
  process/transaction/shardProcess.go
Labels: enhancement

#2653 added /network/total-staked API route
  api/mock/facade.go
  api/network/routes.go
  api/network/routes_test.go
  cmd/node/config/api.toml
  cmd/node/main.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/nodeFacade.go
  node/external/errors.go
  node/external/interface.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  node/totalStakedAPI/disabledTotalStakedValueProcessor.go
  node/totalStakedAPI/errors..go
  node/totalStakedAPI/totalStakedValueHandlerFactory.go
  node/totalStakedAPI/totalStakedValueHandlerFactory_test.go
  node/totalStakedAPI/totalStakedValueProcessor.go
  node/totalStakedAPI/totalStakedValueProcessor_test.go
  testscommon/poolsHolderMock.go
Labels: enhancement

#2667 p2p/libp2p: fix leak
  p2p/libp2p/netMessenger.go
Labels: bug

#2668 p2p/libp2p: fix potential denial of service
  p2p/libp2p/directSender.go
  p2p/libp2p/directSender_test.go
Labels: bug

#2672 External/bugfixes
  data/trie/trieStorageManager.go
  p2p/libp2p/directSender.go
  p2p/libp2p/directSender_test.go
  p2p/libp2p/netMessenger.go
  update/sync/syncHeadersByHash.go
  update/sync/syncMiniBlocks.go
Labels: bug

#2689 Fixed misleading info about cross-shard miniblocks processing
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardTxPreProcessor_test.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/validatorInfoPreProcessor.go
  process/block/preprocess/validatorInfoPreProcessor_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interface.go
  process/mock/preprocessorMock.go
Labels: enhancement

#2701 Assessment tool binary preparation
  cmd/assessment/hostParameters/hostParametersGetter.go
  cmd/assessment/hostParameters/hostParametersGetter_test.go
  cmd/assessment/main.go
Labels: enhancement

#2702 added protection for maximum tx value length
  cmd/node/config/config.toml
  cmd/node/main.go
  genesis/process/disabled/feeHandler.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/feeHandlerStub.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  node/errors.go
  node/mock/txFeeHandlerStub.go
  node/node.go
  node/node_test.go
  node/options.go
  node/options_test.go
  process/errors.go
  process/interface.go
  process/mock/feeHandlerStub.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
Labels: enhancement

#2715 Fixed LogIfError usage
  process/smartContract/process.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
  vm/systemSmartContracts/governance.go
Labels: bug, enhancement

#2718 Fixed block size reached for txs with user name
  core/constants.go
  core/indexer/data.go
  data/interface.go
  data/receipt/receipt.go
  data/rewardTx/rewardTx.go
  data/smartContractResult/smartContractResult.go
  process/block/preprocess/transactions.go
  process/coordinator/process.go
  process/coordinator/process_test.go
Labels: bug, enhancement

#2720 Fix max block size reached when more than one scr is generated
  core/constants.go
  process/block/preprocess/transactions.go
  process/coordinator/process.go
Labels: bug, enhancement

#2747 EN-8693: economics persistent metrics
  cmd/node/factory/structsStatusHandlers.go
  process/sync/loadPersistentMetrics.go
  statusHandler/persister/persistentHandler.go
Labels: enhancement
