Repository multiversx/mx-chain-go, pull requests merged in 2021-02, with the labels that each got.

#2763 EN-8728: gas price modifier metric update
  cmd/node/main.go
  process/economics/economicsData.go
Labels: bug

#2762 Block execution invariant
  cmd/node/config/config.toml
  cmd/node/factory/structs.go
  config/config.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/mock/transactionCoordinatorMock.go
  integrationTests/testProcessorNode.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/errors.go
  process/interface.go
  process/mock/transactionCoordinatorMock.go
  update/mock/transactionCoordinatorMock.go
Labels: enhancement

#2766 Test bridge burn
  integrationTests/multiShard/smartContract/polynetworkbridge/bridge_test.go
  integrationTests/multiShard/smartContract/testdata/polynetworkbridge/esdt_token_manager.wasm
  integrationTests/vm/esdt/esdtProcess_test.go
Labels: bug, enhancement

#2769 Fix hardfork integration tests
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/testSyncNode.go
Labels: bug

#2815 EN-8854: get all key-value pairs for an account API endpoint
  api/address/routes.go
  api/address/routes_test.go
  api/errors/errors.go
  api/mock/facade.go
  cmd/node/config/api.toml
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  node/node.go
  node/node_test.go
Labels: enhancement

#2816 [soft restart] fixed issue when checking core subcomponents
  factory/coreComponents.go
  factory/coreComponentsHandler.go
Labels: bug

#2817 Implement redundancy for elrond nodes
  cmd/node/config/prefs.toml
  cmd/node/main.go
  config/prefsConfig.go
  config/tomlConfig_test.go
  consensus/interface.go
  consensus/mock/consensusDataContainerMock.go
  consensus/mock/mockTestInitializer.go
  consensus/mock/nodeRedundancyHandlerStub.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/bls/subroundStartRound_test.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/consensusCore_test.go
  consensus/spos/errors.go
  consensus/spos/export_test.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/nodeRedundancyHandlerStub.go
  node/errors.go
  node/mock/nodeRedundancyHandlerStub.go
  node/node.go
  node/node_test.go
  node/options.go
  node/options_test.go
  redundancy/errors.go
  redundancy/export_test.go
  redundancy/interface.go
  redundancy/mock/messengerStub.go
  redundancy/redundancy.go
  redundancy/redundnacy_test.go
Labels: enhancement

#2808 Refactor transaction coordinator with arguments
  consensus/spos/bls/subroundEndRound.go
  factory/blockProcessorCreator.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/testProcessorNode.go
  process/block/baseProcess_test.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
Labels: enhancement

#2833 Redundancy and heartbeat integration
  cmd/node/main.go
  consensus/interface.go
  consensus/mock/keyGenMock.go
  consensus/mock/nodeRedundancyHandlerStub.go
  heartbeat/componentHandler/heartbeatHandler.go
  heartbeat/componentHandler/heartbeatHandler_test.go
  heartbeat/errors.go
  heartbeat/interface.go
  heartbeat/mock/keyMock.go
  heartbeat/mock/redundancyHandlerStub.go
  heartbeat/process/sender.go
  heartbeat/process/sender_test.go
  integrationTests/consensus/testInitializer.go
  integrationTests/mock/nodeRedundancyHandlerStub.go
  integrationTests/mock/redundancyHandlerStub.go
  integrationTests/node/heartbeat/heartbeat_test.go
  integrationTests/testP2PNode.go
  integrationTests/testProcessorNode.go
  node/mock/keyMock.go
  node/mock/messengerStub.go
  node/mock/nodeRedundancyHandlerStub.go
  node/mock/storerStub.go
  node/node.go
  node/node_test.go
  redundancy/errors.go
  redundancy/mock/privateKeyStub.go
  redundancy/redundancy.go
  redundancy/redundnacy_test.go
Labels: enhancement

#2840 reference new elastic-indexer-go
  cmd/node/factory/structs.go
  cmd/storer2elastic/mock/elasticIndexerStub.go
  consensus/mock/indexer.go
  genesis/mock/indexerMock.go
  go.mod
  go.sum
  node/mock/indexerMock.go
  process/interface.go
  process/mock/indexerMock.go
Labels: enhancement
