Repository multiversx/mx-chain-go, pull requests merged in 2022-10, with the labels that each got.

#4535 Remove unnecessary gasComputation.Reset call
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/basePreProcess_test.go
Labels: type:bug, area:processing, impact:high, interested:protocol, size:small, priority:1-I&U, complexity:medium

#4542 Integrate vm-common: v1.3.18
  go.mod
  go.sum
Labels: area:indexer, type:improvement, interested:rosetta, area:import-db, area:logs-events-VM

#4549 Fix old database cleaner
  storage/clean/oldDatabaseCleaner.go
  storage/disabled/storer.go
  storage/disabled/storer_test.go
Labels: area:storage, complexity:trivial, impact:medium, interested:protocol

#4518 refactor interceptor resolver: use mutex in event struct
  debug/resolver/export_test.go
  debug/resolver/interceptorResolver.go
Labels: interested:protocol, type:refactoring

#4552 Upgrade indexer
  go.mod
  go.sum
Labels: type:bug, area:indexer, impact:low, interested:api-elrond-com, priority:1-I&U, complexity:medium

#4548 Fix old nft liquidity
  cmd/node/config/enableEpochs.toml
  config/epochConfig.go
  config/tomlConfig_test.go
  factory/apiResolverFactory.go
  factory/blockProcessorCreator.go
  genesis/process/shardGenesisBlockCreator.go
  go.mod
  go.sum
  node/nodeRunner.go
  process/smartContract/builtInFunctions/factory.go
Labels: type:bug, area:processing, complexity:high, impact:high, interested:wallet, interested:web, interested:dex-frontend, interested:maiar, interested:sc, interested:protocol, size:small, priority:1-I&U

#4544 Reference vm-common v1.3.15-rosetta1.
  go.mod
  go.sum
Labels: ignore-for-release-notes

#4529 Fixed preferred peers loading
  node/nodeRunner.go
Labels: type:bug, complexity:trivial, config, impact:low, interested:protocol, interested:validator, size:small

#4557 Merge optimize consensus sig into pseudo slashing
  consensus/spos/bls/subroundSignature.go
  factory/consensus/consensusComponents.go
  factory/crypto/cryptoComponents.go
  factory/crypto/cryptoComponentsHandler.go
  factory/crypto/errors.go
  factory/crypto/signatureHolder.go
  factory/crypto/signatureHolder_test.go
  factory/interface.go
  factory/mock/cryptoComponentsMock.go
  integrationTests/consensus/consensusSigning_test.go
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/cryptoComponentsStub.go
  integrationTests/testConsensusNode.go
  node/mock/factory/cryptoComponentsStub.go
  testscommon/components/default.go
Labels: ignore-for-release-notes

#4534 Workaround: get logs on a best-effort basis (handle epoch-change edge-case)
  node/external/logs/logsRepository.go
  node/external/logs/logsRepository_test.go
Labels: area:node-api, interested:rosetta

#4545 Status metrics on node start
  common/statistics/disabled/netStatistics.go
  common/statistics/disabled/netStatistics_test.go
  common/statistics/errors.go
  common/statistics/interface.go
  common/statistics/machine/export_test.go
  common/statistics/machine/netStatistics.go
  common/statistics/machine/netStatistics_test.go
  common/statistics/resourceMonitor.go
  common/statistics/resourceMonitor_test.go
  errors/errors.go
  factory/bootstrap/bootstrapComponentsHandler.go
  factory/consensus/consensusComponentsHandler.go
  factory/constants.go
  factory/core/coreComponentsHandler.go
  factory/crypto/cryptoComponentsHandler.go
  factory/data/dataComponentsHandler.go
  factory/heartbeat/heartbeatComponentsHandler.go
  factory/interface.go
  factory/network/networkComponentsHandler.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/processComponentsHandler.go
  factory/state/stateComponentsHandler.go
  factory/status/statusComponents.go
  factory/status/statusComponentsHandler.go
  factory/status/statusComponents_test.go
  factory/statusCore/statusCoreComponents.go
  factory/statusCore/statusCoreComponentsHandler.go
  factory/statusCore/statusCoreComponentsHandler_test.go
  factory/statusCore/statusCoreComponents_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/factory/statusCoreComponents/statusCoreComponents_test.go
  node/errors.go
  node/nodeHelper.go
  node/nodeRunner.go
  node/options.go
  state/syncer/baseAccountsSyncer.go
  testscommon/components/components.go
  testscommon/components/configs.go
Labels: area:logs, impact:low, interested:protocol, size:medium, type:improvement, complexity:medium

#4408 Move WASM-VM legacy branches into separate repos
  cmd/assessment/benchmarks/arwenBenchmark.go
  epochStart/metachain/systemSCs_test.go
  genesis/process/genesisBlockCreator_test.go
  go.mod
  go.sum
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithTestWebServer.go
  integrationTests/vm/arwen/arwenvm/mandosConverter/mandosConverter.go
  integrationTests/vm/arwen/arwenvm/mandosConverter/mandosConverterUtils.go
  integrationTests/vm/testInitializer.go
  integrationTests/vm/txsFee/scCalls_test.go
  process/factory/metachain/vmContainerFactory_test.go
  process/factory/shard/vmContainerFactory.go
  process/factory/shard/vmContainerFactory_test.go
  testscommon/components/components.go
  vm/factory/systemSCFactory_test.go
Labels: area:vm

#4569 Added cross shard peer topic notifier
  common/constants.go
  factory/heartbeatV2Components.go
  heartbeat/interface.go
  heartbeat/monitor/crossShardPeerTopicNotifier.go
  heartbeat/monitor/crossShardPeerTopicNotifier_test.go
  integrationTests/testHeartbeatNode.go
  p2p/errors.go
  p2p/libp2p/export_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/mock/peerTopicNotifierStub.go
  p2p/p2p.go
  testscommon/p2pmocks/messengerStub.go
Labels: ignore-for-release-notes

#4526 Merge feat rosetta into rc v1 4 0
  api/errors/errors.go
  api/groups/nodeGroup.go
  api/groups/nodeGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  cmd/node/config/api.toml
  common/dtos.go
  epochStart/bootstrap/metaStorageHandler.go
  epochStart/bootstrap/metaStorageHandler_test.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/shardStorageHandler.go
  facade/initial/initialNodeFacade.go
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  factory/data/dataComponents.go
  factory/processing/processComponents.go
  integrationTests/interface.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/testInitializer.go
  node/node.go
  node/node_test.go
  storage/databaseremover/factory/customDatabaseRemoverCreator.go
  storage/databaseremover/factory/customDatabaseRemoverCreator_test.go
  storage/errors.go
  storage/factory/pruningStorerFactory.go
Labels: ignore-for-release-notes

#4556 Trie statistics
  common/interface.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/peerAccountsDB.go
  state/peerAccountsDB_test.go
  state/snapshotStatistics.go
  state/snapshotStatistics_test.go
  testscommon/storageManagerStub.go
  testscommon/trie/statisticsMock.go
  trie/branchNode.go
  trie/branchNode_test.go
  trie/extensionNode.go
  trie/extensionNode_test.go
  trie/interface.go
  trie/leafNode.go
  trie/leafNode_test.go
  trie/node.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
  trie/statistics/trieStatistics.go
  trie/statistics/trieStatisticsCollector.go
  trie/statistics/trieStatisticsCollector_test.go
  trie/statistics/trieStatistics_test.go
  trie/sync_test.go
  trie/trieStorageManager.go
  trie/trieStorageManagerFactory_test.go
  trie/trieStorageManagerWithoutSnapshot.go
  trie/trieStorageManagerWithoutSnapshot_test.go
  trie/trieStorageManager_test.go
Labels: area:trie, impact:low, interested:protocol, size:large, type:improvement, complexity:medium

#4581 Reference vm-common v1.3.20
  go.mod
  go.sum
Labels: ignore-for-release-notes

#4568 HeartbeatV2 connections improvements
  cmd/node/config/config.toml
  common/constants.go
  config/config.go
  factory/heartbeatV2Components.go
  factory/heartbeatV2Components_test.go
  heartbeat/interface.go
  heartbeat/monitor/crossShardPeerTopicNotifier.go
  heartbeat/monitor/crossShardPeerTopicNotifier_test.go
  heartbeat/processor/directConnectionsProcessor.go
  heartbeat/processor/directConnectionsProcessor_test.go
  heartbeat/processor/export_test.go
  heartbeat/sender/peerShardSender.go
  heartbeat/sender/peerShardSender_test.go
  integrationTests/p2p/networkSharding-hbv2/networkSharding_test.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNode.go
  p2p/errors.go
  p2p/libp2p/export_test.go
  p2p/libp2p/netMessenger.go
  p2p/libp2p/netMessenger_test.go
  p2p/message/generate.go
  p2p/message/peerShardMessage.pb.go
  p2p/message/peerShardMessage.proto
  p2p/mock/peerTopicNotifierStub.go
  p2p/p2p.go
  process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/interceptors/factory/interceptedPeerShardFactory.go
  process/interceptors/factory/interceptedPeerShardFactory_test.go
  process/interceptors/processor/directConnectionInfoInterceptorProcessor.go
  process/interceptors/processor/peerShardInterceptorProcessor.go
  process/interceptors/processor/peerShardInterceptorProcessor_test.go
  process/p2p/interceptedDirectConnectionInfo.go
  process/p2p/interceptedPeerShard.go
  process/p2p/interceptedPeerShard_test.go
  sharding/networksharding/peerShardMapper.go
  testscommon/generalConfig.go
  testscommon/p2pmocks/messengerStub.go
Labels: type:bug, area:heartbeat, impact:medium, interested:protocol, complexity:medium

#4579 Fix the heartbeat v2 monitor when the redundancy feature was activated
  factory/heartbeatV2Components.go
  heartbeat/monitor/monitor.go
  heartbeat/monitor/monitor_test.go
Labels: type:bug, area:heartbeat, impact:medium, interested:explorer, interested:protocol, interested:validator, size:small, complexity:medium

#4589 Merge refactor get all leaves into unit tests
  state/accountsDB.go
Labels: ignore-for-release-notes

#4578 Unit tests for GetAllLeavesOnChannel refactorings
  node/node_test.go
  process/block/baseProcess_test.go
  process/peer/process_test.go
  update/genesis/export_test.go
Labels: ignore-for-release-notes

#4574 Fix `closeAllComponents did not finish on time` problem at the pruning storer level
  common/goroutines/dump.go
  common/goroutines/dump_test.go
  node/node.go
  node/nodeRunner.go
  storage/pruning/pruningStorer.go
  storage/pruning/pruningStorer_test.go
  testscommon/goroutines/counter.go
Labels: type:bug, area:storage, impact:low, interested:protocol, size:small, complexity:medium

#4586 EN-13280: added endpoint for bulk accounts request
  api/groups/addressGroup.go
  api/groups/addressGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  cmd/node/config/api.toml
  cmd/node/config/config.toml
  config/config.go
  facade/errors.go
  facade/initial/initialNodeFacade.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  integrationTests/interface.go
  storage/interface.go
Labels: area:node-api, interested:api-elrond-com, complexity:medium

#4512 Save genesis body and txs pool data into node storage
  common/constants.go
  factory/processing/processComponents.go
  node/external/blockAPI/baseBlock.go
  node/external/blockAPI/metaBlock.go
  node/external/blockAPI/metaBlock_test.go
  node/external/blockAPI/shardBlock.go
  node/external/blockAPI/shardBlock_test.go
Labels: area:consensus, complexity:trivial, impact:low, interested:protocol

#4564 Trie refactoring for get all leaves
  common/channels.go
  common/channels_test.go
  common/interface.go
  epochStart/bootstrap/disabled/disabledAccountsAdapter.go
  epochStart/metachain/systemSCs.go
  factory/processing/processComponents.go
  integrationTests/state/stateTrieClose/stateTrieClose_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/testProcessorNode.go
  node/node.go
  node/node_test.go
  node/trieIterators/delegatedListProcessor.go
  node/trieIterators/delegatedListProcessor_test.go
  node/trieIterators/directStakedListProcessor.go
  node/trieIterators/directStakedListProcessor_test.go
  node/trieIterators/stakeValuesProcessor.go
  node/trieIterators/stakeValuesProcessor_test.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/peer/process.go
  process/peer/process_test.go
  process/txsimulator/wrappedAccountsDB.go
  process/txsimulator/wrappedAccountsDB_test.go
  state/accountsDB.go
  state/accountsDBApi.go
  state/accountsDBApiWithHistory.go
  state/accountsDBApiWithHistory_test.go
  state/accountsDBApi_test.go
  state/accountsDB_test.go
  state/interface.go
  state/peerAccountsDB.go
  state/peerAccountsDB_test.go
  state/syncer/userAccountsSyncer.go
  testscommon/state/accountsAdapterStub.go
  testscommon/storageManagerStub.go
  testscommon/trie/trieStub.go
  trie/errors.go
  trie/mock/keyBuilderStub.go
  trie/node_test.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
  trie/trieStorageManager.go
  trie/trieStorageManagerFactory_test.go
  trie/trieStorageManagerWithoutCheckpoints.go
  trie/trieStorageManagerWithoutCheckpoints_test.go
  trie/trieStorageManagerWithoutSnapshot.go
  trie/trieStorageManagerWithoutSnapshot_test.go
  trie/trieStorageManager_test.go
  update/genesis/common.go
  update/genesis/export.go
  update/genesis/export_test.go
Labels: area:trie, interested:protocol, type:refactoring

#4592 Bootstrap heartbeat sender
  dataRetriever/blockchain/bootstrapBlockchain.go
  dataRetriever/blockchain/bootstrapBlockchain_test.go
  epochStart/bootstrap/epochStartMetaBlockProcessor_test.go
  epochStart/bootstrap/interface.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/storageEpochStartMetaBlockProcessor_test.go
  epochStart/bootstrap/storageProcess.go
  epochStart/bootstrap/syncEpochStartMeta_test.go
  epochStart/mock/cryptoComponentsMock.go
  epochStart/mock/messengerStub.go
  factory/heartbeat/heartbeatV2Components.go
  factory/heartbeat/heartbeatV2Components_test.go
  factory/status/statusComponents.go
  heartbeat/interface.go
  heartbeat/mock/currentBlockProviderStub.go
  heartbeat/sender/bootstrapSender.go
  heartbeat/sender/bootstrapSender_test.go
  heartbeat/sender/disabled/hardforkHandler.go
  heartbeat/sender/disabled/senderHandler.go
  heartbeat/sender/heartbeatSender_test.go
  heartbeat/sender/peerAuthenticationSender_test.go
  heartbeat/sender/sender_test.go
  integrationTests/testProcessorNode.go
  node/nodeRunner.go
  process/interface.go
  process/mock/cryptoComponentsMock.go
  process/peer/bootstrapPeerTypeProvider.go
  process/peer/bootstrapPeerTypeProvider_test.go
  redundancy/bootstrapRedundancy.go
  redundancy/bootstrapRedundancy_test.go
  testscommon/p2pmocks/messengerStub.go
  testscommon/trie/statisticsMock.go
Labels: type:feature, area:heartbeat, impact:low, interested:protocol, complexity:medium

#4604 Remove HeartbeatDisableEpoch
  cmd/node/config/enableEpochs.toml
  common/constants.go
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  factory/heartbeat/heartbeatV2Components.go
  genesis/process/shardGenesisBlockCreator.go
  heartbeat/status/export_test.go
  heartbeat/status/metricsUpdater.go
  heartbeat/status/metricsUpdater_test.go
  integrationTests/constants.go
  integrationTests/p2p/networkSharding/networkSharding_test.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testP2PNode.go
  integrationTests/testProcessorNode.go
  node/metrics/metrics.go
  node/metrics/metrics_test.go
  node/nodeRunner.go
  sharding/mock/enableEpochsHandlerMock.go
  statusHandler/statusMetricsProvider.go
  statusHandler/statusMetricsProvider_test.go
  testscommon/enableEpochsHandlerStub.go
Labels: low prio, area:heartbeat, complexity:trivial, impact:low, interested:protocol, type:refactoring

#4590 EN-13278: move webserver antiflood configuration
  api/gin/webServer.go
  cmd/node/config/config.toml
  config/config.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  node/nodeRunner.go
Labels: area:node-api, impact:low, interested:api-elrond-com, complexity:medium

#4608 Fix revert to snapshot warn
  process/block/preprocess/transactions.go
  process/block/preprocess/transactionsV2.go
  process/smartContract/process.go
Labels: area:logs, complexity:trivial, impact:low, size:small, type:refactoring

#4599 Sync statistics on status core comp
  common/statistics/disabled/netStatistics.go
  epochStart/bootstrap/common.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/errors.go
  errors/errors.go
  factory/bootstrap/bootstrapComponents.go
  factory/consensus/consensusComponents.go
  factory/interface.go
  factory/statusCore/statusCoreComponents.go
  factory/statusCore/statusCoreComponentsHandler.go
  heartbeat/data/heartbeatdata.go
  heartbeat/errors.go
  heartbeat/heartbeat.pb.go
  heartbeat/interface.go
  heartbeat/monitor/monitor.go
  heartbeat/monitor/monitor_test.go
  heartbeat/proto/heartbeat.proto
  heartbeat/sender/bootstrapSender.go
  heartbeat/sender/bootstrapSender_test.go
  heartbeat/sender/disabled/trieSyncStatisticsProvider.go
  heartbeat/sender/heartbeatSender.go
  heartbeat/sender/heartbeatSender_test.go
  heartbeat/sender/sender.go
  integrationTests/factory/bootstrapComponents/bootstrapComponents_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/dataComponents/dataComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/stateComponents/stateComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  node/nodeRunner.go
  state/errors.go
  state/syncer/baseAccountsSyncer.go
  state/syncer/userAccountsSyncer.go
  state/syncer/validatorAccountsSyncer.go
  testscommon/components/components.go
  testscommon/sizeSyncStatisticsHandlerStub.go
  update/factory/accountDBSyncerContainerFactory.go
Labels: low prio, area:heartbeat, impact:low, interested:protocol, type:refactoring, complexity:medium

#4538 altered accounts endpoints
  api/errors/errors.go
  api/groups/blockGroup.go
  api/groups/blockGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  cmd/node/config/api.toml
  common/dtos.go
  facade/initial/initialNodeFacade.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/nodeFacade.go
  factory/api/apiResolverFactory.go
  factory/processing/processComponentsHandler.go
  go.mod
  go.sum
  integrationTests/interface.go
  integrationTests/testProcessorNodeWithTestWebServer.go
  node/external/blockAPI/apiBlockFactory_test.go
  node/external/blockAPI/baseBlock.go
  node/external/blockAPI/blockArgs.go
  node/external/blockAPI/check.go
  node/external/blockAPI/errors.go
  node/external/blockAPI/interface.go
  node/external/blockAPI/metaBlock.go
  node/external/blockAPI/metaBlock_test.go
  node/external/blockAPI/shardBlock.go
  node/external/blockAPI/shardBlock_test.go
  node/external/nodeApiResolver.go
  node/mock/apiBlockHandlerStub.go
  outport/process/alteredaccounts/alteredAccountsProvider.go
  outport/process/alteredaccounts/alteredAccountsProvider_test.go
  outport/process/alteredaccounts/shared/shared.go
  outport/process/interface.go
  outport/process/outportDataProvider.go
  testscommon/alteredAccountsProviderStub.go
  testscommon/logsFacadeStub.go
Labels: area:node-api, impact:low, complexity:medium

#4614 Renamed *Received* to *Processed* into sizeSyncStatistics interface
  factory/bootstrap/bootstrapComponents.go
  go.mod
  go.sum
  heartbeat/interface.go
  heartbeat/sender/disabled/trieSyncStatisticsProvider.go
  heartbeat/sender/heartbeatSender.go
  heartbeat/sender/heartbeatSender_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  state/syncer/baseAccountsSyncer.go
  testscommon/sizeSyncStatisticsHandlerStub.go
  trie/depthFirstSync.go
  trie/doubleListSync.go
  trie/statistics/trieSyncStatistics.go
  trie/statistics/trieSyncStatistics_test.go
  trie/sync.go
Labels: ignore-for-release-notes

#4588 propagate getNodeFromDb err
  errors/missingTrieNodeError.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/rewardTxPreProcessor_test.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactionsV2.go
  process/block/preprocess/transactionsV2_test.go
  process/block/preprocess/transactions_test.go
  process/rewardTransaction/process.go
  process/rewardTransaction/process_test.go
  process/smartContract/process.go
  process/sync/metablock.go
  process/sync/shardblock.go
  process/transaction/shardProcess.go
  state/accountsDB.go
  state/errors.go
  trie/patriciaMerkleTrie.go
Labels: area:sync, area:processing, area:trie, impact:medium, interested:protocol, size:medium, type:improvement, complexity:medium

#4619 Merge pseudo slashing consensus into blacklist invalid singers
  consensus/mock/consensusDataContainerMock.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/consensusCore.go
  consensus/spos/interface.go
Labels: ignore-for-release-notes

#4618 Fix empty trie root hash
  common/trie.go
  common/trie_test.go
  state/accountsDB.go
  trie/depthFirstSync.go
  trie/depthFirstSync_test.go
  trie/doubleListSync.go
  trie/doubleListSync_test.go
  trie/patriciaMerkleTrie.go
  trie/sync.go
  trie/trieStorageManager.go
  update/genesis/import.go
Labels: type:bug, area:trie, complexity:trivial, impact:low, interested:tools, size:small

#4625 Change contributing and pr template
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, type:docs, ignore-for-release-notes

#4605 Added operation mode cli flag
  cmd/node/flags.go
  common/operationmodes/operationmodes.go
  common/operationmodes/operationmodes_test.go
  config/contextFlagsConfig.go
Labels: area:processing, impact:low, interested:protocol, complexity:medium

#4626 Heartbeat v2 monitor better filtering
  heartbeat/monitor/errors.go
  heartbeat/monitor/heartbeatMessage.go
  heartbeat/monitor/monitor.go
  heartbeat/monitor/monitor_test.go
Labels: type:bug, area:node-api, area:heartbeat, impact:medium, interested:protocol, interested:validator, size:medium, type:refactoring, priority:3-!I&U, complexity:medium

#4609 Backward compatibility fixes on rc/v1.4.0
  cmd/node/config/enableEpochs.toml
  cmd/node/config/gasSchedules/gasScheduleV7.toml
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  process/smartContract/process.go
Labels: type:bug, area:processing, config, impact:medium, interested:protocol, size:small

#4635 Fixed transaction simulator data concurrency issue
  process/txsimulator/txSimulator.go
  process/txsimulator/txSimulator_test.go
Labels: type:bug, area:node-api, area:processing, impact:low, interested:protocol, size:small, complexity:medium

#4613 Compressed configs for v1.3.44-dev-config
  cmd/node/config/enableEpochs.toml
Labels: ignore-for-release-notes

#4634 New metric erd_accounts_snapshot_num_nodes
  common/constants.go
  common/interface.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  node/metrics/metrics.go
  node/metrics/metrics_test.go
  process/sync/storageBootstrap/metricsLoader/loadPersistentMetrics.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/snapshotStatistics.go
  statusHandler/persister/persistentHandler.go
  testscommon/statusMetricsStub.go
  trie/statistics/trieStatisticsCollector.go
  trie/statistics/trieStatisticsCollector_test.go
  update/factory/accountDBSyncerContainerFactory.go
Labels: low prio, area:node-api, area:sync, complexity:trivial, impact:low, interested:api-elrond-com, interested:protocol, type:improvement

#4644 Merge rc into feat trie nodes synced on hb 2022.10.25
  cmd/node/config/enableEpochs.toml
  cmd/node/config/gasSchedules/gasScheduleV7.toml
  cmd/node/flags.go
  common/operationmodes/operationmodes.go
  common/operationmodes/operationmodes_test.go
  config/contextFlagsConfig.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  go.mod
  go.sum
  process/smartContract/process.go
  scripts/testnet/include/config.sh
  scripts/testnet/variables.sh
  trie/statistics/trieSyncStatistics.go
Labels: ignore-for-release-notes

#4639 Merge master 2022.10.25
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  cmd/node/config/enableEpochs.toml
  heartbeat/monitor/errors.go
  heartbeat/monitor/heartbeatMessage.go
  heartbeat/monitor/monitor.go
  heartbeat/monitor/monitor_test.go
  process/txsimulator/txSimulator.go
  process/txsimulator/txSimulator_test.go
Labels: ignore-for-release-notes

#4612 Retrieve value with trie depth
  common/interface.go
  epochStart/metachain/baseRewards.go
  epochStart/metachain/baseRewards_test.go
  epochStart/metachain/systemSCs_test.go
  genesis/mock/userAccountMock.go
  go.mod
  go.sum
  integrationTests/mock/oneSCExecutorMockVM.go
  integrationTests/multiShard/relayedTx/relayedTx_test.go
  integrationTests/multiShard/smartContract/dns/dns_test.go
  integrationTests/multiShard/smartContract/polynetworkbridge/bridge_test.go
  integrationTests/multiShard/validatorToDelegation/validatorToDelegation_test.go
  integrationTests/state/stateTrie/stateTrie_test.go
  integrationTests/vm/arwen/arwenvm/mandosConverter/mandosConverterUtils.go
  integrationTests/vm/esdt/localFuncs/esdtLocalFunsSC_test.go
  integrationTests/vm/esdt/process/esdtProcess_test.go
  integrationTests/vm/testInitializer.go
  node/node.go
  node/node_test.go
  process/interface.go
  process/rewardTransaction/process.go
  process/rewardTransaction/process_test.go
  process/scToProtocol/stakingToPeer.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/blockChainHook_test.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/baseAccount.go
  state/interface.go
  state/journalEntries_test.go
  state/trackableDataTrie.go
  state/trackableDataTrie_test.go
  testscommon/blockChainHookStub.go
  testscommon/state/accountWrapperMock.go
  testscommon/state/userAccountStub.go
  testscommon/trie/dataTrieTrackerStub.go
  testscommon/trie/trieStub.go
  trie/branchNode.go
  trie/branchNode_test.go
  trie/depthFirstSync_test.go
  trie/doubleListSync_test.go
  trie/extensionNode.go
  trie/extensionNode_test.go
  trie/interface.go
  trie/leafNode.go
  trie/leafNode_test.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
  vm/interface.go
  vm/mock/blockChainHookStub.go
  vm/systemSmartContracts/eei.go
  vm/systemSmartContracts/staking_test.go
Labels: area:system-vm, area:trie, area:vm, impact:low, interested:wasm, interested:protocol, size:medium, type:improvement, complexity:medium

#4597 EN-13311: fix delegation contract's owner delegation logs
  vm/systemSmartContracts/delegation.go
  vm/systemSmartContracts/delegation_test.go
  vm/systemSmartContracts/logs.go
  vm/systemSmartContracts/logs_test.go
Labels: area:indexer, impact:low, size:small

#4650 Merge rc into feat nodes synced on hb 2022.10.27 2
  vm/systemSmartContracts/delegation.go
  vm/systemSmartContracts/delegation_test.go
  vm/systemSmartContracts/logs.go
  vm/systemSmartContracts/logs_test.go
Labels: ignore-for-release-notes

#4624 EN-13328: overridable config fields
  cmd/node/config/prefs.toml
  cmd/node/main.go
  common/reflectcommon/errors.go
  common/reflectcommon/structFieldsUpdate.go
  common/reflectcommon/structFieldsUpdate_test.go
  config/prefsConfig.go
Labels: impact:low, interested:protocol, complexity:medium

#4642 fix custom meta DB remover
  storage/factory/pruningStorerFactory.go
Labels: type:bug, area:storage, impact:low, size:small

#4596 Protocol tx fields
  go.mod
  go.sum
  integrationTests/testProcessorNodeWithTestWebServer.go
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/errors.go
  node/external/transactionAPI/unmarshaller.go
  node/external/transactionAPI/unmarshaller_test.go
Labels: area:node-api, area:proxy-api, complexity:trivial, impact:medium, interested:api-elrond-com, interested:protocol, size:small, interested:rosetta
