Repository multiversx/mx-chain-go, pull requests merged in 2022-11, with the labels that each got.

#4664 fix contributing URL
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type:bug, ignore-for-release-notes

#4671 Merge master rc v1 4 0 nov7
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release-notes

#4566 Fix missing storage resolver for validator info
  dataRetriever/factory/storageResolversContainer/baseResolversContainerFactory.go
  dataRetriever/factory/storageResolversContainer/metaResolversContainerFactory.go
  dataRetriever/factory/storageResolversContainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/storageResolversContainer/shardResolversContainerFactory.go
  dataRetriever/factory/storageResolversContainer/shardResolversContainerFactory_test.go
  dataRetriever/resolvers/disabled/validatorInfoResolver.go
  dataRetriever/resolvers/disabled/validatorInfoResolver_test.go
  dataRetriever/storageResolvers/sliceResolver.go
  epochStart/shardchain/peerMiniBlocksSyncer.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/validatorInfoPreProcessor.go
  process/block/preprocess/validatorInfoPreProcessor_test.go
Labels: type:bug, area:processing, complexity:trivial, impact:low, interested:protocol

#4673 fix tx value for altered accounts tx pool
  node/external/blockAPI/baseBlock.go
Labels: type:bug

#4658 Termui trie sync status
  api/gin/common_test.go
  cmd/termui/presenter/chainInfoGetters.go
  cmd/termui/view/interface.go
  cmd/termui/view/termuic/termuiRenders/widgetsRender.go
  common/constants.go
  epochStart/bootstrap/process.go
  facade/errors.go
  facade/initial/disabledStatusMetrics.go
  facade/initial/disabledStatusMetrics_test.go
  facade/initial/initialNodeFacade.go
  facade/initial/initialNodeFacade_test.go
  factory/consensus/consensusComponents.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  node/errors.go
  node/metrics/metrics.go
  node/metrics/metrics_test.go
  node/nodeRunner.go
  state/syncer/baseAccountsSyncer.go
  state/syncer/userAccountsSyncer.go
  state/syncer/validatorAccountsSyncer.go
  update/factory/accountDBSyncerContainerFactory.go
Labels: low prio, area:node-api, complexity:trivial, impact:low, interested:protocol, type:improvement

#4680 Enable epochs handler to data trie
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  epochStart/metachain/baseRewards_test.go
  epochStart/metachain/systemSCs_test.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/processComponents.go
  factory/state/stateComponents.go
  genesis/process/genesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  integrationTests/state/stateTrie/stateTrie_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/systemVM/stakingSC_test.go
  integrationTests/vm/testInitializer.go
  node/nodeLoadAccounts_test.go
  node/node_test.go
  node/trieIterators/delegatedListProcessor_test.go
  node/trieIterators/directStakedListProcessor_test.go
  node/trieIterators/stakeValuesProcessor_test.go
  process/block/baseProcess.go
  process/dataValidators/txValidator_test.go
  process/peer/process_test.go
  process/rewardTransaction/process_test.go
  process/scToProtocol/stakingToPeer_test.go
  process/smartContract/hooks/blockChainHook_test.go
  process/smartContract/process_test.go
  process/transaction/metaProcess_test.go
  process/transaction/shardProcess_test.go
  sharding/mock/enableEpochsHandlerMock.go
  state/accountsDB.go
  state/accountsDBApiWithHistory_test.go
  state/accountsDBApi_test.go
  state/accountsDB_test.go
  state/disabled/disabledDataTrieHandler.go
  state/disabled/disabledDataTrieHandler_test.go
  state/disabled/disabledTrackableDataTrie.go
  state/disabled/disabledTrackableDataTrie_test.go
  state/errors.go
  state/factory/accountCreator.go
  state/factory/accountCreator_test.go
  state/factory/peerAccountCreator.go
  state/factory/peerAccountCreator_test.go
  state/interface.go
  state/journalEntries_test.go
  state/peerAccount.go
  state/peerAccount_test.go
  state/storagePruningManager/storagePruningManager_test.go
  state/userAccount.go
  state/userAccount_test.go
  testscommon/enableEpochsHandlerStub.go
  testscommon/state/accountFactoryStub.go
  update/genesis/base.go
  update/genesis/import.go
  update/genesis/import_test.go
  vm/mock/blockChainHookStub.go
  vm/systemSmartContracts/eei_test.go
Labels: ignore-for-release-notes

#4575 Consensus and factories for sovereign chain
  cmd/node/main.go
  consensus/constants.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/errors.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlockV2.go
  consensus/spos/bls/subroundBlockV2_test.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/sposFactory/sposFactory.go
  consensus/spos/sposFactory/sposFactory_test.go
  factory/consensus/consensusComponents.go
  integrationTests/consensus/consensus_test.go
  node/nodeRunner.go
  process/block/preprocess/transactions.go
  testscommon/components/components.go
Labels: type:feature, area:consensus, impact:medium, interested:protocol, size:small, complexity:medium

#4646 fix full archive operation mode
  cmd/node/flags.go
Labels: type:bug, area:storage

#4675 EN-13395: extended overridable config for other config files
  cmd/node/config/prefs.toml
  cmd/node/flags.go
  cmd/node/main.go
  common/operationmodes/operationmodes.go
  common/operationmodes/operationmodes_test.go
  common/reflectcommon/structFieldsUpdate.go
  config/overridableConfig/configOverriding.go
  config/overridableConfig/configOverriding_test.go
  config/prefsConfig.go
Labels: complexity:trivial, impact:low, interested:protocol, size:large, type:improvement

#4691 Refactored the blocks syncers component construction
  cmd/node/main.go
  common/constants.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/errors.go
  consensus/spos/sposFactory/errors.go
  errors/errors.go
  factory/consensus/consensusComponents.go
  factory/consensus/consensusComponentsHandler_test.go
  factory/consensus/consensusComponentsV2.go
  factory/consensus/consensusComponents_test.go
  factory/processing/processComponents.go
  factory/processing/processComponentsHandler_test.go
  factory/processing/sovereignChainProcessComponents.go
  factory/processing/sovereignChainProcessComponentsHandler.go
  factory/processing/sovereignChainProcessComponentsHandler_test.go
  factory/processing/sovereignChainProcessComponents_test.go
  integrationTests/consensus/consensus_test.go
  node/nodeRunner.go
  node/sovereignChainNodeRunner.go
  testscommon/components/components.go
Labels: ignore-for-release-notes

#4686 Data trie value
  common/interface.go
  epochStart/bootstrap/disabled/disabledAccountsAdapter.go
  epochStart/metachain/systemSCs.go
  factory/processing/processComponents.go
  integrationTests/state/stateTrieClose/stateTrieClose_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/testProcessorNode.go
  node/node.go
  node/node_test.go
  node/trieIterators/delegatedListProcessor.go
  node/trieIterators/directStakedListProcessor.go
  node/trieIterators/directStakedListProcessor_test.go
  node/trieIterators/stakeValuesProcessor.go
  node/trieIterators/stakeValuesProcessor_test.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/peer/process.go
  process/peer/process_test.go
  process/txsimulator/wrappedAccountsDB.go
  process/txsimulator/wrappedAccountsDB_test.go
  state/accountsDB.go
  state/accountsDBApi.go
  state/accountsDBApiWithHistory.go
  state/accountsDBApiWithHistory_test.go
  state/accountsDBApi_test.go
  state/accountsDB_test.go
  state/dataTrieValue/dataTrieValue.go
  state/dataTrieValue/dataTrieValue.pb.go
  state/dataTrieValue/dataTrieValue.proto
  state/disabled/disabledDataTrieHandler.go
  state/disabled/disabledDataTrieHandler_test.go
  state/interface.go
  state/parsers/trieLeafParserV1.go
  state/parsers/trieLeafParserV1_test.go
  state/syncer/userAccountsSyncer.go
  testscommon/state/accountsAdapterStub.go
  testscommon/trie/trieStub.go
  trie/errors.go
  trie/keyBuilder/disabledKeyBuilder.go
  trie/keyBuilder/keyBuilder.go
  trie/mock/keyBuilderStub.go
  trie/node_test.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
  update/genesis/export.go
  update/genesis/export_test.go
Labels: ignore-for-release-notes

#4683 Move request handlers to new components for each resolver
  dataRetriever/requestHandlers/requesters/baseRequester.go
  dataRetriever/requestHandlers/requesters/baseRequester_test.go
  dataRetriever/requestHandlers/requesters/headerRequester.go
  dataRetriever/requestHandlers/requesters/headerRequester_test.go
  dataRetriever/requestHandlers/requesters/miniblockRequester.go
  dataRetriever/requestHandlers/requesters/peerAuthenticationRequester.go
  dataRetriever/requestHandlers/requesters/requesters_test.go
  dataRetriever/requestHandlers/requesters/transactionRequester.go
  dataRetriever/requestHandlers/requesters/trieNodeRequester.go
  dataRetriever/requestHandlers/requesters/validatorInfoRequester.go
Labels: low prio, area:processing, impact:low, interested:protocol, type:refactoring, complexity:medium

#4591 Syncer and factories for sovereign chain
  common/constants.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/errors.go
  errors/errors.go
  factory/consensus/consensusComponents.go
  factory/consensus/consensusComponentsHandler_test.go
  factory/consensus/consensusComponents_test.go
  factory/processing/processComponents.go
  factory/processing/processComponentsHandler.go
  factory/processing/processComponentsHandler_test.go
  integrationTests/consensus/consensus_test.go
  node/nodeRunner.go
  process/errors.go
  process/sync/baseSync.go
  process/sync/metablock.go
  process/sync/shardblock.go
  process/sync/sovereignChainBaseSync.go
  process/sync/sovereignChainBaseSync_test.go
  process/sync/sovereignChainShardBlock.go
  process/sync/sovereignChainShardBlock_test.go
  process/sync/sovereignChainShardForkDetector.go
  process/sync/sovereignChainShardForkDetector_test.go
  process/track/export_test.go
  process/track/sovereignChainBlockProcessor.go
  process/track/sovereignChainBlockProcessor_test.go
  process/track/sovereignChainShardBlockTrack.go
  process/track/sovereignChainShardBlockTrack_test.go
  testscommon/components/components.go
Labels: type:feature, area:sync, area:processing, impact:medium, interested:dapp-sdks, interested:protocol, size:medium, complexity:medium

#4696 Missing trie err fix
  state/accountsDB.go
  state/errors.go
Labels: area:logs, complexity:trivial, impact:low, size:small, type:improvement

#4710 fix consensus message pubkey in log trace
  consensus/spos/bls/subroundEndRound.go
Labels: ignore-for-release-notes

#4705 Unittests for topicRequestSender and requestersContainer
  dataRetriever/factory/containers/export_test.go
  dataRetriever/factory/containers/requestersContainer.go
  dataRetriever/factory/containers/requestersContainer_test.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go
  dataRetriever/topicSender/topicRequestSender.go
  dataRetriever/topicSender/topicRequestSender_test.go
  testscommon/dataRetriever/requesterStub.go
Labels: low prio, complexity:trivial, interested:protocol, ignore-for-release-notes

#4703 fix account query options for altered accounts
  api/errors/errors.go
  api/groups/blockGroup.go
  factory/api/apiResolverFactory.go
  go.mod
  go.sum
  integrationTests/testProcessorNodeWithTestWebServer.go
  node/external/blockAPI/apiBlockFactory_test.go
  node/external/blockAPI/baseBlock.go
  node/external/blockAPI/blockArgs.go
  node/external/blockAPI/check.go
  node/external/blockAPI/metaBlock.go
  node/external/blockAPI/metaBlock_test.go
  node/external/blockAPI/shardBlock.go
  node/external/blockAPI/shardBlock_test.go
Labels: type:bug, area:node-api, complexity:trivial, impact:low, interested:tools, size:small

#4681 Warm wasmer fixes
  go.mod
  go.sum
  integrationTests/vm/arwen/testdata/buyNFTCall/code.wasm
  integrationTests/vm/arwen/testdata/buyNFTCall/data.hex
  integrationTests/vm/testInitializer.go
  integrationTests/vm/txsFee/scCalls_test.go
  integrationTests/vm/txsFee/utils/utils.go
Labels: type:bug, area:sc-processing, area:vm, complexity:high, impact:high, interested:wasm, interested:protocol, size:medium, priority:1-I&U

#4723 Merge master rc v1.4.0 2022.11.21
  README.md
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/rewardTxPreProcessor.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/common.go
  process/common_test.go
Labels: ignore-for-release-notes

#4699 Bootstrap from storage or from epoch start for sovereign chain
  epochStart/bootstrap/process.go
  epochStart/bootstrap/sovereignChainProcess.go
  epochStart/bootstrap/sovereignChainProcess_test.go
  epochStart/bootstrap/storageProcess.go
  epochStart/bootstrap/storageProcess_test.go
  factory/bootstrap/bootstrapComponents.go
  factory/bootstrap/bootstrapComponents_test.go
  factory/consensus/consensusComponents.go
  factory/consensus/consensusComponents_test.go
  node/nodeRunner.go
  process/errors.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
  process/sync/storageBootstrap/metaStorageBootstrapper.go
  process/sync/storageBootstrap/shardStorageBootstrapper.go
  process/sync/storageBootstrap/sovereignChainBaseStorageBootstrapper.go
  process/sync/storageBootstrap/sovereignChainBaseStorageBootstrapper_test.go
  process/sync/storageBootstrap/sovereignChainShardStorageBootstrapper.go
  process/sync/storageBootstrap/sovereignChainShardStorageBootstrapper_test.go
  testscommon/components/components.go
Labels: type:feature, area:storage, area:sync, impact:medium, interested:dapp-sdks, interested:protocol, size:medium, complexity:medium

#4713 use bech32 address in trie statistics
  common/interface.go
  epochStart/metachain/systemSCs_test.go
  factory/processing/blockProcessorCreator_test.go
  factory/state/stateComponents.go
  genesis/process/genesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/memoryComponents.go
  integrationTests/state/stateTrie/stateTrie_test.go
  integrationTests/testInitializer.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/errors.go
  state/factory/accountsAdapterAPICreator_test.go
  state/peerAccountsDB.go
  state/peerAccountsDB_test.go
  state/storagePruningManager/storagePruningManager_test.go
  testscommon/integrationtests/factory.go
  testscommon/storageManagerStub.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
  trie/statistics/trieStatistics.go
  trie/statistics/trieStatistics_test.go
  trie/trieStorageManager.go
  trie/trieStorageManagerFactory_test.go
  trie/trieStorageManagerWithoutSnapshot.go
  trie/trieStorageManagerWithoutSnapshot_test.go
  trie/trieStorageManager_test.go
  update/errors.go
  update/genesis/import.go
  update/genesis/import_test.go
Labels: area:trie, area:logs, complexity:trivial, impact:low, size:small

#4729 remove key size from total leaf size computation
  state/trackableDataTrie.go
Labels: ignore-for-release-notes

#4725 index only non empty genesis miniblocks
  genesis/parsing/accountsParser.go
  genesis/parsing/accountsParser_test.go
Labels: area:indexer, complexity:trivial, impact:low, interested:protocol

#4736 Integrate new elrond-go-storage (less verbose logs)
  go.mod
  go.sum
Labels: area:logs, complexity:trivial, size:small

#4727 Hardfork exclusion handler
  cmd/node/config/config.toml
  common/errors.go
  common/hardfork/hardforkExclusionHandler.go
  common/hardfork/hardforkExclusionHandler_test.go
  common/interface.go
  config/config.go
  go.mod
  go.sum
  node/nodeRunner.go
  testscommon/hardforkExclusionHandlerStub.go
Labels: type:feature, low prio, area:processing, interested:protocol, complexity:medium

#4734 HardforkExclusionHandler into header interceptor
  epochStart/bootstrap/common.go
  epochStart/bootstrap/factory/epochStartInterceptorsContainerFactory.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/errors.go
  errors/errors.go
  factory/bootstrap/bootstrapComponents.go
  factory/processing/processComponents.go
  integrationTests/factory/bootstrapComponents/bootstrapComponents_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/dataComponents/dataComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/stateComponents/stateComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testProcessorNode.go
  node/nodeRunner.go
  process/errors.go
  process/factory/interceptorscontainer/args.go
  process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  process/interceptors/processor/argHdrInterceptorProcessor.go
  process/interceptors/processor/hdrInterceptorProcessor.go
  process/interceptors/processor/hdrInterceptorProcessor_test.go
  testscommon/components/components.go
  testscommon/headerHandlerStub.go
  update/errors.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncInterceptors.go
Labels: low prio, area:processing, impact:medium, interested:protocol, type:refactoring, complexity:medium

#4738 HardforkExclusionHandler into shouldAllowRollback
  common/hardfork/hardforkExclusionHandler.go
  common/interface.go
  factory/consensus/consensusComponents.go
  factory/consensus/consensusComponents_test.go
  go.mod
  go.sum
  integrationTests/consensus/consensus_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/testSyncNode.go
  node/nodeRunner.go
  process/sync/argBootstrapper.go
  process/sync/baseSync.go
  process/sync/baseSync_test.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
  testscommon/components/components.go
  testscommon/hardforkExclusionHandlerStub.go
Labels: low prio, area:processing, impact:medium, interested:protocol, type:refactoring, complexity:medium
