Repository multiversx/mx-chain-go, pull requests merged in 2022-12, with the labels that each got.

#4620 Integration test multi key
  integrationTests/consensus/consensus_test.go
  integrationTests/testConsensusNode.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  keysManagement/peerInfo.go
Labels: type:feature, area:consensus, impact:low, interested:protocol, interested:validator, size:small, complexity:medium, area:multikey

#4751 HardforkExclusionHandler into consensus
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/bls/subroundStartRound_test.go
  consensus/spos/errors.go
  consensus/spos/sposFactory/sposFactory.go
  consensus/spos/sposFactory/sposFactory_test.go
  factory/consensus/consensusComponents.go
Labels: low prio, area:processing, impact:medium, interested:protocol, type:refactoring, complexity:medium

#4719 Hbv2 config variables better namings
  cmd/node/config/config.toml
  common/reflectcommon/structFieldsUpdate_test.go
  config/config.go
  epochStart/bootstrap/process.go
  factory/heartbeat/heartbeatV2Components.go
  factory/heartbeat/heartbeatV2Components_test.go
  heartbeat/processor/peerAuthenticationRequestsProcessor.go
  heartbeat/processor/peerAuthenticationRequestsProcessor_test.go
  heartbeat/sender/bootstrapSender.go
  heartbeat/sender/bootstrapSender_test.go
  heartbeat/sender/peerShardSender.go
  heartbeat/sender/peerShardSender_test.go
  heartbeat/sender/sender.go
  heartbeat/sender/sender_test.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNode.go
  testscommon/generalConfig.go
Labels: low prio, area:heartbeat, complexity:trivial, impact:low, interested:protocol, ignore-for-release-notes

#4758 Refactored private keys usage in consensus
  consensus/interface.go
  consensus/mock/consensusDataContainerMock.go
  consensus/mock/mockTestInitializer.go
  consensus/mock/signatureHandlerStub.go
  consensus/signing/errors.go
  consensus/signing/signing.go
  consensus/signing/signing_test.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/consensusCore_test.go
  consensus/spos/interface.go
  consensus/spos/subround.go
  factory/consensus/consensusComponents.go
Labels: area:consensus, impact:low, interested:protocol, size:small, type:refactoring, complexity:medium, area:multikey

#4764 fixes after review: fix indentation + use timer in blacklist
  consensus/blacklist/blacklist.go
  consensus/message.proto
  consensus/spos/bls/subroundEndRound.go
Labels: ignore-for-release-notes

#4766 Merge 1.5.0 feat optimize consensus
  cmd/node/config/config.toml
  common/reflectcommon/structFieldsUpdate_test.go
  config/config.go
  epochStart/bootstrap/process.go
  factory/heartbeat/heartbeatV2Components.go
  factory/heartbeat/heartbeatV2Components_test.go
  heartbeat/processor/peerAuthenticationRequestsProcessor.go
  heartbeat/processor/peerAuthenticationRequestsProcessor_test.go
  heartbeat/sender/bootstrapSender.go
  heartbeat/sender/bootstrapSender_test.go
  heartbeat/sender/peerShardSender.go
  heartbeat/sender/peerShardSender_test.go
  heartbeat/sender/sender.go
  heartbeat/sender/sender_test.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNode.go
  testscommon/generalConfig.go
Labels: ignore-for-release-notes

#4768 Fix integration tests
  integrationTests/consensus/consensusSigning_test.go
  integrationTests/consensus/consensus_test.go
Labels: ignore-for-release-notes

#4771 Merge rcv1.5.0 2022.12.07
  cmd/node/config/config.toml
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  common/reflectcommon/structFieldsUpdate_test.go
  config/config.go
  config/epochConfig.go
  epochStart/bootstrap/process.go
  factory/heartbeat/heartbeatV2Components.go
  factory/heartbeat/heartbeatV2Components_test.go
  go.mod
  go.sum
  heartbeat/processor/peerAuthenticationRequestsProcessor.go
  heartbeat/processor/peerAuthenticationRequestsProcessor_test.go
  heartbeat/sender/bootstrapSender.go
  heartbeat/sender/bootstrapSender_test.go
  heartbeat/sender/peerShardSender.go
  heartbeat/sender/peerShardSender_test.go
  heartbeat/sender/sender.go
  heartbeat/sender/sender_test.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/txsFee/scCalls_test.go
  node/nodeRunner.go
  outport/notifier/eventNotifier.go
  outport/notifier/eventNotifier_test.go
  outport/notifier/export_test.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerStub.go
  testscommon/generalConfig.go
Labels: ignore-for-release-notes

#4656 use dfs instead of bfs in trie iterator
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  trie/baseIterator.go
  trie/baseIterator_test.go
  trie/branchNode_test.go
  trie/dfsIterator.go
  trie/dfsIterator_test.go
  trie/export_test.go
  trie/interceptedNode_test.go
  trie/iterator_test.go
  trie/patriciaMerkleTrie.go
Labels: area:trie, interested:protocol, type:improvement

#4776 Merge rc/v1.5.0 2022.12.07 2
  common/constants.go
  consensus/blacklist/blacklist.go
  consensus/blacklist/blacklist_test.go
  consensus/broadcast/commonMessenger.go
  consensus/interface.go
  consensus/message.go
  consensus/message.pb.go
  consensus/message.proto
  consensus/message_test.go
  consensus/mock/consensusDataContainerMock.go
  consensus/mock/keyGenMock.go
  consensus/mock/messageSigningHandlerMock.go
  consensus/mock/messageSigningHandlerStub.go
  consensus/mock/mockTestInitializer.go
  consensus/mock/peerBlackListCacher.go
  consensus/mock/peerBlacklistHandlerStub.go
  consensus/mock/signingHandlerStub.go
  consensus/mock/singleSigMock.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsWorker.go
  consensus/spos/bls/blsWorker_test.go
  consensus/spos/bls/constants.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/consensusCore_test.go
  consensus/spos/consensusMessageValidator.go
  consensus/spos/consensusMessageValidator_test.go
  consensus/spos/consensusState.go
  consensus/spos/errors.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  factory/consensus/consensusComponents.go
  factory/crypto/cryptoComponents.go
  factory/crypto/cryptoComponentsHandler.go
  factory/crypto/errors.go
  factory/crypto/signingHandler.go
  factory/crypto/signingHandler_test.go
  factory/disabled/p2pMessageSigner.go
  factory/interface.go
  factory/mock/cryptoComponentsMock.go
  heartbeat/interface.go
  integrationTests/consensus/consensusSigning_test.go
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/cryptoComponentsStub.go
  integrationTests/testConsensusNode.go
  node/mock/factory/cryptoComponentsStub.go
  p2p/factory/factory.go
  p2p/interface.go
  p2p/mock/p2pSignerStub.go
  testscommon/components/default.go
Labels: ignore-for-release-notes

#4765 EN-13529: get token with custom system account
  go.mod
  go.sum
  node/node.go
  node/nodeLoadAccounts.go
  node/node_test.go
  testscommon/esdtStorageHandlerStub.go
Labels: type:bug, area:node-api, size:small

#4755 Add missing call to DecreaseRating on peersRatingHandler
  dataRetriever/resolvers/topicResolverSender/topicResolverSender.go
  dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go
Labels: type:bug, low prio, area:processing, complexity:trivial, impact:low, interested:protocol

#4779 Trie load benchmarks
  integrationTests/benchmarks/loadFromTrie_test.go
Labels: size:medium, complexity:medium, area:integration-tests

#4742 EN-13432 consensus group size by epoch
  cmd/node/config/config.toml
  cmd/node/config/nodesSetup.json
  cmd/node/main.go
  config/config.go
  config/tomlConfig_test.go
  epochStart/mock/nodesSetupStub.go
  factory/core/coreComponents.go
  factory/mock/nodesSetupStub.go
  factory/mock/testdata/nodesSetupMock.json
  factory/mock/testdata/nodesSetupMockInvalidRound.json
  factory/status/statusComponents_test.go
  integrationTests/factory/componentsHelper.go
  integrationTests/factory/testdata/nodesSetup.json
  integrationTests/mock/nodesSetupStub.go
  integrationTests/testProcessorNode.go
  node/nodeRunner.go
  process/errors.go
  process/interface.go
  process/mock/nodesSetupStub.go
  process/rating/ratingsData.go
  process/rating/ratingsData_test.go
  sharding/chainParametersHolder.go
  sharding/chainParametersHolder_test.go
  sharding/dtos.go
  sharding/errors.go
  sharding/interface.go
  sharding/mock/testdata/invalidNodesSetupMock.json
  sharding/mock/testdata/nodesSetupMock.json
  sharding/nodesSetup.go
  sharding/nodesSetup_test.go
  testscommon/components/components.go
  testscommon/components/configs.go
  testscommon/nodesSetupMock.go
  testscommon/shardingmock/chainParametersHolderMock.go
  testscommon/shardingmock/chainParametersHolderStub.go
  update/genesis/export.go
  update/interface.go
  update/mock/nodesSetupHandlerStub.go
Labels: area:consensus, complexity:medium

#4793 Merge rc/1.5.0 into feat/pubkeyconverter refactor 2022.12.12
  integrationTests/benchmarks/loadFromTrie_test.go
Labels: ignore-for-release-notes

#4775 Refactor and more fixes for feat/chain-go-sdk
  factory/processing/blockProcessorCreator.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/export_test.go
  factory/processing/processComponents.go
  factory/processing/processComponents_test.go
  genesis/errors.go
  genesis/process/disabled/scheduledTxsExecutionHandler.go
  genesis/process/shardGenesisBlockCreator.go
  process/block/sovereignblock.go
Labels: type:feature, area:processing, impact:medium, interested:dapp-sdks, interested:protocol, size:medium, type:refactoring, complexity:medium

#4791 Disable in-epoch trie pruning
  cmd/node/config/config.toml
Labels: ignore-for-release-notes

#4780 Fix missing call to decrease rating into peers rating handler
  dataRetriever/topicSender/topicRequestSender.go
  dataRetriever/topicSender/topicRequestSender_test.go
Labels: type:bug, low prio, area:processing, interested:protocol, complexity:medium

#4781 Peers rating handler integration test
  cmd/node/config/config.toml
  common/constants.go
  config/config.go
  dataRetriever/interface.go
  epochStart/bootstrap/disabled/disabledPeersRatingHandler.go
  errors/errors.go
  factory/network/networkComponents.go
  factory/network/networkComponentsHandler.go
  go.mod
  go.sum
  integrationTests/p2p/peersRating/peersRating_test.go
  integrationTests/testProcessorNode.go
  node/metrics/metrics.go
  node/metrics/metrics_test.go
  p2p/constants.go
  p2p/interface.go
  testscommon/components/components.go
  testscommon/components/configs.go
  testscommon/generalConfig.go
  testscommon/p2pmocks/peersRatingHandlerStub.go
Labels: low prio, impact:low, interested:protocol, type:improvement, complexity:medium, area:integration-tests

#4794 Blockchainhook counters refactor
  process/interface.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/blockChainHook_test.go
  process/smartContract/hooks/counters/disabledCounter.go
  process/smartContract/hooks/counters/usageCounter.go
  process/smartContract/hooks/counters/usageCounter_test.go
  process/smartContract/hooks/interface.go
  process/smartContract/process.go
  testscommon/blockChainHookCounterStub.go
  testscommon/blockChainHookStub.go
Labels: area:sc-processing, complexity:trivial, impact:low, interested:protocol, interested:validator, size:small, type:refactoring

#4795 Save nodes config per epoch separately into storage
  cmd/node/config/config.toml
  config/config.go
  epochStart/bootstrap/baseStorageHandler.go
  epochStart/bootstrap/common.go
  epochStart/bootstrap/disabled/disabledNodesCoordinator.go
  epochStart/bootstrap/epochStartMetaBlockProcessor.go
  epochStart/bootstrap/fromLocalStorage.go
  epochStart/bootstrap/fromLocalStorage_test.go
  epochStart/bootstrap/metaStorageHandler.go
  epochStart/bootstrap/metaStorageHandler_test.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/shardStorageHandler.go
  epochStart/bootstrap/storageProcess.go
  epochStart/bootstrap/syncValidatorStatus.go
  epochStart/bootstrap/syncValidatorStatus_test.go
  epochStart/errors.go
  epochStart/metachain/baseRewards_test.go
  epochStart/metachain/systemSCs_test.go
  factory/bootstrap/shardingFactory.go
  factory/processing/blockProcessorCreator_test.go
  genesis/process/genesisBlockCreator_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/longTests/storage/storage_test.go
  node/nodeRunner.go
  process/sync/storageBootstrap/baseStorageBootstrapper.go
  sharding/nodesCoordinator/errors.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorLite.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorLite_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorRegistry.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorRegistry_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorWithRater.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorWithRater_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
  sharding/nodesCoordinator/interface.go
  sharding/nodesCoordinator/shardingArgs.go
  testscommon/components/configs.go
  testscommon/generalConfig.go
  testscommon/shardingMocks/nodesCoordinatorMock.go
  testscommon/shardingMocks/nodesCoordinatorStub.go
  testscommon/storageManager/storageManagerArgs.go
Labels: area:storage, impact:medium, interested:protocol, type:improvement, complexity:medium

#4815 Fixed the `keygenerator` binary
  cmd/keygenerator/converter/directStringPubkeyConverter.go
  cmd/keygenerator/converter/directStringPubkeyConverter_test.go
  cmd/keygenerator/converter/errors.go
  cmd/keygenerator/converter/pidPubkeyConverter.go
  cmd/keygenerator/converter/pidPubkeyConverter_test.go
  cmd/keygenerator/main.go
  go.mod
  go.sum
  p2p/factory/factory.go
Labels: type:bug, area:libp2p, complexity:trivial, impact:medium, interested:protocol, size:small, type:refactoring

#4773 Transaction execution order
  factory/processing/blockProcessorCreator.go
  go.mod
  go.sum
  outport/mock/executionOrderHandlerStub.go
  outport/process/errors.go
  outport/process/executionOrder/dtos.go
  outport/process/executionOrder/interface.go
  outport/process/executionOrder/miniBlocksGetter.go
  outport/process/executionOrder/miniBlocksGetter_test.go
  outport/process/executionOrder/scrs.go
  outport/process/executionOrder/scrs_test.go
  outport/process/executionOrder/transactionsExecutionOrder.go
  outport/process/executionOrder/transactionsExecutionOrder_test.go
  outport/process/factory/check.go
  outport/process/factory/check_test.go
  outport/process/factory/outportDataProviderFactory.go
  outport/process/interface.go
  outport/process/outportDataProvider.go
  outport/process/outportDataProvider_test.go
  process/block/metablock.go
  process/block/shardblock.go
Labels: type:feature, area:indexer, impact:medium, interested:protocol, size:medium, priority:2-I&!U, complexity:medium

#4821 Trie leaf data unmarshal
  state/parsers/dataTrieLeafParser.go
  state/parsers/dataTrieLeafParser_test.go
Labels: type:bug, area:trie, complexity:trivial, impact:medium, interested:protocol, size:small

#4825 Merge rc v140 into feat chain go sdk
  cmd/keygenerator/converter/directStringPubkeyConverter.go
  cmd/keygenerator/converter/directStringPubkeyConverter_test.go
  cmd/keygenerator/converter/errors.go
  cmd/keygenerator/converter/pidPubkeyConverter.go
  cmd/keygenerator/converter/pidPubkeyConverter_test.go
  cmd/keygenerator/main.go
  cmd/node/config/config.toml
  factory/processing/blockProcessorCreator.go
  go.mod
  go.sum
  outport/mock/executionOrderHandlerStub.go
  outport/process/errors.go
  outport/process/executionOrder/dtos.go
  outport/process/executionOrder/interface.go
  outport/process/executionOrder/miniBlocksGetter.go
  outport/process/executionOrder/miniBlocksGetter_test.go
  outport/process/executionOrder/scrs.go
  outport/process/executionOrder/scrs_test.go
  outport/process/executionOrder/transactionsExecutionOrder.go
  outport/process/executionOrder/transactionsExecutionOrder_test.go
  outport/process/factory/check.go
  outport/process/factory/check_test.go
  outport/process/factory/outportDataProviderFactory.go
  outport/process/interface.go
  outport/process/outportDataProvider.go
  outport/process/outportDataProvider_test.go
  p2p/factory/factory.go
  process/block/metablock.go
  process/block/shardblock.go
  process/interface.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/blockChainHook_test.go
  process/smartContract/hooks/counters/disabledCounter.go
  process/smartContract/hooks/counters/usageCounter.go
  process/smartContract/hooks/counters/usageCounter_test.go
  process/smartContract/hooks/interface.go
  process/smartContract/process.go
  testscommon/blockChainHookCounterStub.go
  testscommon/blockChainHookStub.go
Labels: type:feature, ignore-for-release-notes

#4806 EN-13432: update index hashed nodes coordinator
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/storageProcess.go
  epochStart/bootstrap/syncValidatorStatus.go
  epochStart/bootstrap/syncValidatorStatus_test.go
  epochStart/mock/coreComponentsMock.go
  errors/errors.go
  factory/bootstrap/shardingFactory.go
  factory/core/coreComponents.go
  factory/core/coreComponentsHandler.go
  factory/interface.go
  factory/mock/coreComponentsMock.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/mock/coreComponentsStub.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/nodesCoordinatorFactory.go
  integrationTests/testConsensusNode.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  node/mock/factory/coreComponentsStub.go
  node/nodeRunner.go
  process/interface.go
  process/mock/coreComponentsMock.go
  sharding/nodesCoordinator/errors.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorWithRater_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
  sharding/nodesCoordinator/shardingArgs.go
Labels: area:consensus, area:processing, impact:medium, complexity:medium

#4823 refactor trie stats
  trie/patriciaMerkleTrie_test.go
  trie/statistics/trieStatistics.go
  trie/statistics/trieStatisticsCollector.go
  trie/statistics/trieStatistics_test.go
Labels: area:trie, complexity:trivial, impact:low, interested:protocol, size:medium, type:refactoring

#4817 Epoch nodes config cacher
  epochStart/bootstrap/syncValidatorStatus.go
  factory/bootstrap/shardingFactory.go
  sharding/mock/nodesCoordinatorCacheMock.go
  sharding/nodesCoordinator/errors.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorLite.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorWithRater_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
  sharding/nodesCoordinator/interface.go
  sharding/nodesCoordinator/shardingArgs.go
Labels: area:consensus, area:storage, interested:protocol, type:improvement, complexity:medium

#4829 fix num rounds and nonces passed in epoch for prometheus
  statusHandler/statusMetricsProvider.go
  statusHandler/statusMetricsProvider_test.go
Labels: type:bug, area:node-api, impact:low, interested:tools, complexity:medium

#4834 Merge rc/1.4.0 to rc/1.5.0 22.12.2022
  cmd/keygenerator/converter/directStringPubkeyConverter.go
  cmd/keygenerator/converter/directStringPubkeyConverter_test.go
  cmd/keygenerator/converter/errors.go
  cmd/keygenerator/converter/pidPubkeyConverter.go
  cmd/keygenerator/converter/pidPubkeyConverter_test.go
  cmd/keygenerator/main.go
  cmd/node/config/config.toml
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  factory/processing/blockProcessorCreator.go
  go.mod
  go.sum
  integrationTests/vm/txsFee/multiShard/esdtLiquidity_test.go
  integrationTests/vm/txsFee/utils/utilsESDT.go
  outport/mock/executionOrderHandlerStub.go
  outport/process/errors.go
  outport/process/executionOrder/dtos.go
  outport/process/executionOrder/interface.go
  outport/process/executionOrder/miniBlocksGetter.go
  outport/process/executionOrder/miniBlocksGetter_test.go
  outport/process/executionOrder/scrs.go
  outport/process/executionOrder/scrs_test.go
  outport/process/executionOrder/transactionsExecutionOrder.go
  outport/process/executionOrder/transactionsExecutionOrder_test.go
  outport/process/factory/check.go
  outport/process/factory/check_test.go
  outport/process/factory/outportDataProviderFactory.go
  outport/process/interface.go
  outport/process/outportDataProvider.go
  outport/process/outportDataProvider_test.go
  p2p/factory/factory.go
  process/block/metablock.go
  process/block/shardblock.go
  process/interface.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/blockChainHook_test.go
  process/smartContract/hooks/counters/disabledCounter.go
  process/smartContract/hooks/counters/usageCounter.go
  process/smartContract/hooks/counters/usageCounter_test.go
  process/smartContract/hooks/interface.go
  process/smartContract/process.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/blockChainHookCounterStub.go
  testscommon/blockChainHookStub.go
  testscommon/enableEpochsHandlerStub.go
  trie/patriciaMerkleTrie_test.go
  trie/statistics/trieStatistics.go
  trie/statistics/trieStatisticsCollector.go
  trie/statistics/trieStatistics_test.go
Labels: ignore-for-release-notes

#4831 Fix `MetricReceivedProposedBlock` overflow
  consensus/spos/worker.go
  consensus/spos/worker_test.go
Labels: type:bug, area:consensus, complexity:trivial, impact:low, interested:protocol, size:small

#4827 Added os-level memory statistics
  common/statistics/osLevel/errors.go
  common/statistics/osLevel/export_test.go
  common/statistics/osLevel/memStats.go
  common/statistics/osLevel/memStats_test.go
  common/statistics/resourceMonitor.go
  common/statistics/resourceMonitor_test.go
Labels: type:feature, area:logs, complexity:trivial, impact:low, interested:protocol, size:small
