Repository multiversx/mx-chain-go, pull requests merged in 2022-07, with the labels that each got.

#4319 EN-12514: github community standards
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#4293 [FIX]Active db markup exception on master
  common/interface.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/export_test.go
  state/peerAccountsDB.go
  state/peerAccountsDB_test.go
  testscommon/storageManagerStub.go
  trie/export_test.go
  trie/patriciaMerkleTrie_test.go
  trie/trieStorageManager.go
  trie/trieStorageManagerWithoutCheckpoints.go
  trie/trieStorageManagerWithoutCheckpoints_test.go
  trie/trieStorageManagerWithoutPruning.go
  trie/trieStorageManagerWithoutPruning_test.go
  trie/trieStorageManager_test.go
Labels: bug

#4321 Customized automated release note
  .github/release.yml
Labels: documentation, config, interested:protocol, size:small, type:docs, status:categorize

#4325 [FIX]Added a disabled peer authentication resolver in import-db mode
  dataRetriever/factory/storageResolversContainer/baseResolversContainerFactory.go
  dataRetriever/factory/storageResolversContainer/metaResolversContainerFactory.go
  dataRetriever/factory/storageResolversContainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/storageResolversContainer/shardResolversContainerFactory.go
  dataRetriever/factory/storageResolversContainer/shardResolversContainerFactory_test.go
  dataRetriever/resolvers/disabled/peerAuthenticationResolver.go
  dataRetriever/resolvers/disabled/peerAuthenticatorResolver_test.go
Labels: type:bug, low prio, area:heartbeat, complexity:trivial, impact:low, interested:protocol, size:small

#4324 Refactor TestProcessorNode
  integrationTests/frontend/wallet/txInterception_test.go
  integrationTests/multiShard/block/interceptedBlocks/interceptedBlocks_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/softfork/scDeploy_test.go
  integrationTests/multiShard/transaction/interceptedResolvedBulkTx/interceptedResolvedBulkTx_test.go
  integrationTests/resolvers/testInitializer.go
  integrationTests/singleShard/block/executingMiniblocks/executingMiniblocks_test.go
  integrationTests/singleShard/block/executingMiniblocksSc/executingMiniblocksSc_test.go
  integrationTests/singleShard/block/interceptedRequestHdr/interceptedRequestHdr_test.go
  integrationTests/singleShard/block/interceptedRequestTxBlockBody/interceptedRequestTxBlockBody_test.go
  integrationTests/singleShard/transaction/interceptedBulkTx/interceptedBulkTx_test.go
  integrationTests/singleShard/transaction/interceptedBulkUnsignedTx/interceptedBulkUnsignedTx_test.go
  integrationTests/singleShard/transaction/interceptedResolvedTx/interceptedResolvedTx_test.go
  integrationTests/singleShard/transaction/interceptedResolvedUnsignedTx/interceptedResolvedUnsignedTx_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/sync/basicSync/basicSync_test.go
  integrationTests/sync/edgeCases/edgeCases_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/testProcessorNodeWithStateCheckpointModulus.go
  integrationTests/testProcessorNodeWithTestWebServer.go
  integrationTests/testSyncNode.go
  integrationTests/vm/arwen/delegation/testRunner.go
  integrationTests/vm/delegation/delegationScenarios_test.go
  integrationTests/vm/esdt/process/esdtProcess_test.go
  integrationTests/wrappers.go
  node/node_test.go
  sharding/multiShardCoordinator_test.go
Labels: low prio, status:work-in-progress, impact:low, complexity:medium, area:integration-tests
