Repository multiversx/mx-chain-go, pull requests merged in 2023-01, with the labels that each got.

#4840 Merge rc into feat fix peers rating 2022.12.29
  cmd/keygenerator/converter/directStringPubkeyConverter.go
  cmd/keygenerator/converter/directStringPubkeyConverter_test.go
  cmd/keygenerator/converter/errors.go
  cmd/keygenerator/converter/pidPubkeyConverter.go
  cmd/keygenerator/converter/pidPubkeyConverter_test.go
  cmd/keygenerator/main.go
  cmd/node/config/config.toml
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  factory/processing/blockProcessorCreator.go
  go.mod
  go.sum
  integrationTests/vm/txsFee/multiShard/esdtLiquidity_test.go
  integrationTests/vm/txsFee/utils/utilsESDT.go
  outport/mock/executionOrderHandlerStub.go
  outport/process/errors.go
  outport/process/executionOrder/dtos.go
  outport/process/executionOrder/interface.go
  outport/process/executionOrder/miniBlocksGetter.go
  outport/process/executionOrder/miniBlocksGetter_test.go
  outport/process/executionOrder/scrs.go
  outport/process/executionOrder/scrs_test.go
  outport/process/executionOrder/transactionsExecutionOrder.go
  outport/process/executionOrder/transactionsExecutionOrder_test.go
  outport/process/factory/check.go
  outport/process/factory/check_test.go
  outport/process/factory/outportDataProviderFactory.go
  outport/process/interface.go
  outport/process/outportDataProvider.go
  outport/process/outportDataProvider_test.go
  p2p/factory/factory.go
  process/block/metablock.go
  process/block/shardblock.go
  process/interface.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/blockChainHook_test.go
  process/smartContract/hooks/counters/disabledCounter.go
  process/smartContract/hooks/counters/usageCounter.go
  process/smartContract/hooks/counters/usageCounter_test.go
  process/smartContract/hooks/interface.go
  process/smartContract/process.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/blockChainHookCounterStub.go
  testscommon/blockChainHookStub.go
  testscommon/enableEpochsHandlerStub.go
  trie/patriciaMerkleTrie_test.go
  trie/statistics/trieStatistics.go
  trie/statistics/trieStatisticsCollector.go
  trie/statistics/trieStatistics_test.go
Labels: ignore-for-release-notes

#4819 EN-13432: fixes for nodes coordinator with chain parameters
  epochStart/bootstrap/disabled/disabledNodesCoordinator.go
  epochStart/interface.go
  epochStart/metachain/baseRewards.go
  epochStart/metachain/baseRewards_test.go
  epochStart/metachain/rewards.go
  epochStart/metachain/rewardsV2.go
  epochStart/metachain/rewardsV2_test.go
  epochStart/metachain/rewards_test.go
  epochStart/metachain/systemSCs.go
  epochStart/metachain/systemSCs_test.go
  factory/consensus/consensusComponents.go
  factory/core/coreComponents.go
  integrationTests/nodesCoordinatorFactory.go
  integrationTests/testConsensusNode.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  process/peer/process.go
  process/peer/process_test.go
  sharding/chainParametersHolder.go
  sharding/nodesCoordinator/dtos.go
  sharding/nodesCoordinator/hashValidatorShuffler.go
  sharding/nodesCoordinator/hashValidatorShuffler_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorLite.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorLite_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorWithRater_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
  sharding/nodesCoordinator/interface.go
  testscommon/shardingMocks/nodesCoordinatorMock.go
  testscommon/shardingMocks/nodesCoordinatorStub.go
Labels: area:consensus, impact:medium, complexity:medium

#4838 Removed trie state pruning queue for increased performance
  cmd/node/config/config.toml
  config/config.go
  epochStart/metachain/systemSCs_test.go
  integrationTests/state/stateTrie/stateTrie_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/shardblock.go
  state/accountsDB_test.go
  state/storagePruningManager/evictionWaitingList/benchmark_test.go
  state/storagePruningManager/evictionWaitingList/evictionWaitingList.go
  state/storagePruningManager/evictionWaitingList/evictionWaitingList_test.go
  state/storagePruningManager/evictionWaitingList/memoryEvictionWaitingList.go
  state/storagePruningManager/evictionWaitingList/memoryEvictionWaitingList_test.go
  state/storagePruningManager/storagePruningManager.go
  state/storagePruningManager/storagePruningManager_test.go
  testscommon/integrationtests/factory.go
  testscommon/state/evictionWaitingListMock.go
Labels: area:processing, area:trie, complexity:high, impact:low, interested:protocol, size:small, type:performance

#4871 Add missing mut locks
  process/guardian/guardedAccount.go
  process/guardian/guardedAccount_test.go
Labels: ignore-for-release-notes

#4872 added tokens keys test examples
  examples/tokenKeys_test.go
Labels: ignore-for-release-notes

#4877 Update feat rebranding 2023.01.16
  examples/tokenKeys_test.go
Labels: ignore-for-release-notes

#4884 Fixed create release workflow
  .github/workflows/create_release.yml
Labels: type:bug, ignore-for-release-notes

#4878 Fix old nft storage
  cmd/node/config/enableEpochs.toml
  cmd/node/config/gasSchedules/gasScheduleV1.toml
  cmd/node/config/gasSchedules/gasScheduleV2.toml
  cmd/node/config/gasSchedules/gasScheduleV3.toml
  cmd/node/config/gasSchedules/gasScheduleV4.toml
  cmd/node/config/gasSchedules/gasScheduleV5.toml
  cmd/node/config/gasSchedules/gasScheduleV6.toml
  cmd/node/config/gasSchedules/gasScheduleV7.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  go.mod
  go.sum
  integrationTests/vm/testInitializer.go
  integrationTests/vm/txsFee/multiShard/nftTransferUpdate_test.go
  integrationTests/vm/txsFee/utils/utils.go
  integrationTests/vm/txsFee/utils/utilsESDT.go
  integrationTests/vm/wasm/wasmvm/scenariosConverter/scenariosConverter.go
  integrationTests/vm/wasm/wasmvm/scenariosConverter/scenariosConverterUtils.go
  process/factory/shard/vmContainerFactory.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerStub.go
Labels: type:bug, area:processing, config, impact:low, interested:protocol, size:small, complexity:medium

#4888 Fix termui node URL
  cmd/termui/provider/metricsProvider.go
Labels: ignore-for-release-notes

#4885 En 13697 bootstrap metrics
  api/groups/nodeGroup.go
  api/groups/nodeGroup_test.go
  cmd/node/config/api.toml
  cmd/termui/provider/metricsProvider.go
  facade/initial/initialNodeFacade.go
  facade/initial/initialStatusMetricsProvider.go
  facade/initial/initialStatusMetricsProvider_test.go
  integrationTests/testProcessorNodeWithTestWebServer.go
  node/external/interface.go
  statusHandler/statusMetricsProvider.go
  statusHandler/statusMetricsProvider_test.go
  testscommon/statusMetricsStub.go
Labels: type:bug, area:node-api, impact:low, interested:protocol, complexity:medium

#4887 Update prefs.toml
  cmd/node/config/prefs.toml
Labels: ignore-for-release-notes

#4876 Fix /transaction/pool with nonce-gaps
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  node/external/interface.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/fieldsHandler.go
  node/external/transactionAPI/fieldsHandler_test.go
  node/mock/apiTransactionHandlerStub.go
Labels: type:bug, area:node-api, complexity:trivial, impact:low, interested:protocol

#4809 add unit tests for trie nodes versioning
  trie/node_test.go
Labels: ignore-for-release-notes

#4897 Time between heartbeats at bootstrap
  cmd/node/config/config.toml
  config/config.go
  epochStart/bootstrap/process.go
  factory/heartbeat/heartbeatV2Components_test.go
  integrationTests/testProcessorNode.go
  testscommon/generalConfig.go
Labels: low prio, area:node-api, area:heartbeat, complexity:trivial, impact:low, interested:protocol, type:improvement

#4909 Merge rc 1 4 into rc 1 5
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/dependabot.yml
  README.md
  elrond_logo_01.svg
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  go.mod
  go.sum
  multiversx-logo.svg
  node/external/interface.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/fieldsHandler.go
  node/external/transactionAPI/fieldsHandler_test.go
  node/mock/apiTransactionHandlerStub.go
  outport/process/alteredaccounts/alteredAccountsProvider.go
  outport/process/alteredaccounts/alteredAccountsProvider_test.go
  outport/process/alteredaccounts/tokensProcessor.go
  vm/systemSmartContracts/esdt.go
  vm/systemSmartContracts/esdt_test.go
Labels: ignore-for-release-notes

#4904 Save `synced` miniblocks at bootstrap
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/shardStorageHandler.go
  epochStart/bootstrap/shardStorageHandler_test.go
  epochStart/bootstrap/startInEpochScheduled.go
  epochStart/bootstrap/startInEpochScheduled_test.go
  epochStart/bootstrap/types/scheduledDataSyncerTypes.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  testscommon/scheduledDataSyncer/dataSyncerStub.go
Labels: type:bug, area:storage, area:sync, impact:low, interested:protocol, size:small, complexity:medium

#4907 Fix txhash encoding
  go.mod
  go.sum
  outport/notifier/eventNotifier.go
  outport/notifier/eventNotifier_test.go
Labels: type:bug, area:indexer, interested:validator, complexity:medium

#4886 Move sovereign implementation from separated repository to feat/chain-go-sdk
  factory/processing/blockProcessorCreator.go
  factory/processing/processComponents.go
  genesis/process/argGenesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  process/block/preprocess/export.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/sovereignChainTransactions.go
  process/block/preprocess/sovereignChainTransactions_test.go
  process/block/preprocess/transactions_test.go
  process/block/shardblock_test.go
  process/coordinator/process_test.go
  process/factory/metachain/preProcessorsContainerFactory.go
  process/factory/metachain/preProcessorsContainerFactory_test.go
  process/factory/shard/preProcessorsContainerFactory.go
  process/factory/shard/preProcessorsContainerFactory_test.go
  testscommon/txCacherStub.go
Labels: type:feature, ignore-for-release-notes

#4920 Merge rc v1.4.0 into feat chain go sdk 30.01.2023
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/shardStorageHandler.go
  epochStart/bootstrap/shardStorageHandler_test.go
  epochStart/bootstrap/startInEpochScheduled.go
  epochStart/bootstrap/startInEpochScheduled_test.go
  epochStart/bootstrap/types/scheduledDataSyncerTypes.go
  go.mod
  go.sum
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  outport/notifier/eventNotifier.go
  outport/notifier/eventNotifier_test.go
  testscommon/scheduledDataSyncer/dataSyncerStub.go
  vm/systemSmartContracts/delegation.go
  vm/systemSmartContracts/logs.go
  vm/systemSmartContracts/logs_test.go
Labels: type:feature, ignore-for-release-notes

#4911 Integrate p2p feat/refactor_net_messenger
  cmd/seednode/main.go
  consensus/broadcast/commonMessenger_test.go
  consensus/broadcast/metaChainMessenger_test.go
  consensus/broadcast/shardChainMessenger_test.go
  consensus/mock/messengerStub.go
  consensus/spos/sposFactory/sposFactory_test.go
  dataRetriever/interface.go
  dataRetriever/mock/messengerStub.go
  dataRetriever/storageRequesters/headerRequester_test.go
  dataRetriever/storageRequesters/sliceRequester_test.go
  dataRetriever/storageRequesters/trieNodeRequester_test.go
  epochStart/bootstrap/interface.go
  epochStart/bootstrap/process.go
  factory/network/networkComponents.go
  go.mod
  go.sum
  integrationTests/p2p/antiflood/common.go
  integrationTests/singleShard/transaction/interceptedBulkUnsignedTx/interceptedBulkUnsignedTx_test.go
  integrationTests/testInitializer.go
  node/interface.go
  node/nodeTesting.go
  node/nodeTesting_test.go
  process/interceptors/epochStartMetaBlockInterceptor_test.go
  process/mock/messengerStub.go
  process/txsSender/interface.go
  process/txsSender/txsSender.go
  process/txsSender/txsSender_test.go
  redundancy/mock/messengerStub.go
  redundancy/redundnacy_test.go
  testscommon/p2pmocks/messengerStub.go
Labels: low prio, area:libp2p, area:processing, impact:low, interested:protocol, type:refactoring, complexity:medium

#4923 Merge rc v1.4.0 into feat chain go sdk 30.01.2023 2
  .github/ISSUE_TEMPLATE/question.yml
  common/constants.go
  examples/tokenKeys_test.go
  integrationTests/factory/bootstrapComponents/bootstrapComponents_test.go
  integrationTests/factory/componentsHelper.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/constants.go
  integrationTests/factory/coreComponents/coreComponents_test.go
  integrationTests/factory/cryptoComponents/cryptoComponents_test.go
  integrationTests/factory/dataComponents/dataComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/networkComponents/networkComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/stateComponents/stateComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/factory/statusCoreComponents/statusCoreComponents_test.go
  integrationTests/vm/esdt/process/esdtProcess_test.go
  integrationTests/vm/txsFee/scCalls_test.go
  process/smartContract/process_test.go
  vm/process/systemVM.go
  vm/process/systemVM_test.go
Labels: type:feature, ignore-for-release-notes

#4906 Fixed net statistics early exit
  common/statistics/machine/netStatistics.go
  common/statistics/machine/netStatistics_test.go
Labels: ignore-for-release-notes
