Repository multiversx/mx-chain-go, pull requests merged in 2023-10, with the labels that each got.

#5617 proper tags
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5601 Node redundancy system fixes
  cmd/node/CLI.md
  cmd/node/config/config.toml
  cmd/node/flags.go
  common/interface.go
  config/config.go
  config/contextFlagsConfig.go
  config/tomlConfig_test.go
  consensus/interface.go
  consensus/mock/sentSignatureTrackerStub.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/bls/subroundStartRound_test.go
  consensus/spos/consensusState.go
  consensus/spos/errors.go
  consensus/spos/interface.go
  consensus/spos/sentSignaturesTracker.go
  consensus/spos/sentSignaturesTracker_test.go
  consensus/spos/sposFactory/sposFactory.go
  consensus/spos/sposFactory/sposFactory_test.go
  consensus/spos/subround.go
  consensus/spos/worker.go
  factory/consensus/consensusComponents.go
  factory/crypto/cryptoComponents.go
  factory/crypto/cryptoComponentsHandler_test.go
  factory/crypto/cryptoComponents_test.go
  factory/processing/processComponents.go
  heartbeat/interface.go
  heartbeat/sender/heartbeatSender.go
  heartbeat/sender/multikeyHeartbeatSender.go
  integrationTests/realcomponents/processorRunner.go
  integrationTests/testConsensusNode.go
  integrationTests/testHeartbeatNode.go
  keysManagement/export_test.go
  keysManagement/keysHandler.go
  keysManagement/keysHandler_test.go
  keysManagement/managedPeersHolder.go
  keysManagement/managedPeersHolder_test.go
  keysManagement/peerInfo.go
  node/nodeRunner.go
  redundancy/common/redundancyHandler.go
  redundancy/common/redundancyHandler_test.go
  redundancy/export_test.go
  redundancy/redundancy.go
  redundancy/redundancy_test.go
  testscommon/keysHandlerSingleSignerMock.go
  testscommon/keysHandlerStub.go
  testscommon/managedPeersHolderStub.go
  testscommon/realConfigsHandling.go
Labels: type:bug, area:consensus, area:heartbeat, complexity:high, impact:medium, interested:protocol, interested:validator, size:small, area:multikey

#5605 Fixed tx removal from inner tx pool
  dataRetriever/factory/dataPoolFactory.go
  dataRetriever/txpool/shardedTxPool.go
  dataRetriever/txpool/shardedTxPool_test.go
Labels: ignore-for-release-notes

#5604 Added fallback on topicRequestSender in case requests on full archive nodes fail
  dataRetriever/mock/peerListCreatorStub.go
  dataRetriever/topicSender/topicRequestSender.go
  dataRetriever/topicSender/topicRequestSender_test.go
Labels: area:processing, impact:low, interested:protocol, type:improvement, complexity:medium

#5611 Revert tx that migrates data bugfix
  state/accountsDB_test.go
  state/trackableDataTrie/trackableDataTrie.go
  state/trackableDataTrie/trackableDataTrie_test.go
  trie/branchNode.go
  trie/branchNode_test.go
Labels: type:bug, area:trie, complexity:high, impact:medium, interested:protocol, size:small

#5636 Fix test contracts (part 2)
  integrationTests/vm/wasm/testdata/deployer-custom/deployer-custom.c
  integrationTests/vm/wasm/testdata/deployer-custom/output/deployer-custom.wasm
  integrationTests/vm/wasm/testdata/misc/cpucalculate_wasm/cpucalculate.c
  integrationTests/vm/wasm/testdata/misc/cpucalculate_wasm/cpucalculate.export
  integrationTests/vm/wasm/testdata/misc/cpucalculate_wasm/output/cpucalculate.wasm
  integrationTests/vm/wasm/testdata/mxvm/context.h
  integrationTests/vm/wasm/upgrades/upgrades_test.go
  integrationTests/vm/wasm/wasmvm/wasmVM_test.go
Labels: ignore-for-release-notes

#5637 Fix contracts tests (part 3)
  integrationTests/multiShard/smartContract/testdata/first/first.export
  integrationTests/multiShard/smartContract/testdata/first/first.wasm
  integrationTests/multiShard/smartContract/testdata/first/output/first.wasm
  integrationTests/vm/txsFee/asyncCall_multi_test.go
  integrationTests/vm/txsFee/multiShard/relayedScDeploy_test.go
  integrationTests/vm/txsFee/relayedAsyncCall_test.go
  integrationTests/vm/txsFee/relayedScDeploy_test.go
  integrationTests/vm/txsFee/scDeploy_test.go
  integrationTests/vm/txsFee/testdata/first/first.export
  integrationTests/vm/txsFee/testdata/first/first.wasm
  integrationTests/vm/txsFee/testdata/first/output/first.wasm
  integrationTests/vm/wasm/delegation/delegation_test.go
  integrationTests/vm/wasm/wasmvm/wasmVM_test.go
Labels: ignore-for-release-notes

#5284 Tests for hyperblock partial miniblock
  integrationTests/node/dblookupext/partialMiniblockSave_test.go
  testscommon/dblookupext/suppliesHandlerStub.go
Labels: type:bug, area:storage, area:processing, impact:medium, interested:protocol, size:medium, complexity:medium

#5639 Fix contracts (parts 4)
  integrationTests/vm/txsFee/asyncCall_test.go
  integrationTests/vm/txsFee/dynamicGasCost_test.go
  integrationTests/vm/txsFee/relayedScDeploy_test.go
  integrationTests/vm/wasm/testdata/delegation/delegation_vA.wasm
  integrationTests/vm/wasm/testdata/delegation/delegation_vB.wasm
  integrationTests/vm/wasm/testdata/storage100/output/storage100.wasm
  integrationTests/vm/wasm/testdata/storage100/storage100.c
  integrationTests/vm/wasm/testdata/storage100/storage100.export
  integrationTests/vm/wasm/testdata/trieStoreAndLoad/output/storage.wasm
  integrationTests/vm/wasm/testdata/trieStoreAndLoad/storage.c
  integrationTests/vm/wasm/testdata/trieStoreAndLoad/storage.export
  integrationTests/vm/wasm/testdata/trieStoreAndLoad/storage.wasm
Labels: ignore-for-release-notes

#5641 Fix contracts tests (part 5)
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/vm/txsFee/apiTransactionEvaluator_test.go
  integrationTests/vm/txsFee/multiShard/asyncCall_test.go
Labels: ignore-for-release-notes

#5646 Fix remaining tests (part 6)
  cmd/assessment/testdata/fibonacci.wasm
  cmd/assessment/testdata/fibonacci.wat
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multiShard/smartContract/testdata/callBuiltin/callBuiltin.c
  integrationTests/multiShard/smartContract/testdata/callBuiltin/callBuiltin.export
  integrationTests/multiShard/smartContract/testdata/callBuiltin/output/callBuiltin.hex
  integrationTests/multiShard/smartContract/testdata/callBuiltin/output/callBuiltin.wasm
  integrationTests/multiShard/smartContract/testdata/second/output/second.wasm
  integrationTests/multiShard/smartContract/testdata/second/second.c
  integrationTests/multiShard/smartContract/testdata/second/second.export
  integrationTests/multiShard/smartContract/testdata/second/second.wasm
Labels: ignore-for-release-notes

#5647 Fix remaining test (part 7)
  integrationTests/multiShard/smartContract/testdata/delegate-mock/delegate.c
  integrationTests/multiShard/smartContract/testdata/delegate-mock/delegate.export
  integrationTests/multiShard/smartContract/testdata/delegate-mock/delegate.wasm
  integrationTests/multiShard/smartContract/testdata/delegate-mock/output/delegate.wasm
Labels: ignore-for-release-notes

#5618 adjust `account not found` error when sending a transaction
  integrationTests/singleShard/transaction/interceptedBulkTx/interceptedBulkTx_test.go
  node/node.go
  node/node_test.go
Labels: area:node-api, area:trie, complexity:trivial, impact:low

#5651 tx hash test example with guardian
  examples/construction_test.go
Labels: ignore-for-release-notes

#5176 Improve requesting of missing mini blocks dest me
  factory/disabled/txCoordinator.go
  integrationTests/mock/transactionCoordinatorMock.go
  process/block/baseProcess.go
  process/block/shardblock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/interface.go
  testscommon/transactionCoordinatorMock.go
  update/mock/transactionCoordinatorMock.go
Labels: type:improvement

#5659 update guardians tx construction example
  examples/construction_test.go
Labels: ignore-for-release-notes

#5675 stubGenerator -> mockGenerator
  scripts/generators/mockGenerator.sh
Labels: ignore-for-release-notes
