Repository multiversx/mx-chain-go, pull requests merged in 2023-05, with the labels that each got.

#5178 Coverage for: blockGroup, hardforkGroup, internalBlockGroup
  api/groups/blockGroup.go
  api/groups/blockGroup_test.go
  api/groups/hardforkGroup_test.go
  api/groups/internalGroup_test.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5188 pass storageMarker as argument when SyncAccounts() is called
  common/interface.go
  dataRetriever/storageRequesters/trieNodeRequester_test.go
  epochStart/bootstrap/process.go
  epochStart/interface.go
  factory/consensus/consensusComponents.go
  factory/state/stateComponentsHandler_test.go
  integrationTests/mock/accountsDBSyncerStub.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/testProcessorNode.go
  node/nodeRunner.go
  node/nodeTesting_test.go
  node/node_test.go
  process/interface.go
  process/mock/accountsDBSyncerStub.go
  process/sync/baseSync.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/factory/accountsAdapterAPICreator_test.go
  state/interface.go
  state/peerAccountsDB_test.go
  state/syncer/baseAccountsSyncer.go
  state/syncer/errors.go
  state/syncer/userAccountSyncer_test.go
  state/syncer/userAccountsSyncer.go
  state/syncer/validatorAccountsSyncer.go
  state/syncer/validatorAccountsSyncer_test.go
  testscommon/components/default.go
  testscommon/storageManager/storageManagerStub.go
  trie/export_test.go
  trie/interface.go
  trie/storageMarker/disabledStorageMarker.go
  trie/storageMarker/trieStorageMarker.go
  trie/storageMarker/trieStorageMarker_test.go
  trie/trieStorageManagerFactory_test.go
  trie/trieStorageManagerInEpoch_test.go
  trie/trieStorageManagerWithoutPruning_test.go
  update/container/accountDBSyncers_test.go
  update/factory/accountDBSyncerContainerFactory.go
  update/genesis/import_test.go
  update/interface.go
  update/mock/accountsDBSyncerStub.go
  update/sync/coordinator_test.go
  update/sync/syncAccountsDBs.go
Labels: ignore-for-release-notes

#5214 termui: display if the node is full archive
  cmd/termui/view/termuic/termuiRenders/widgetsRender.go
  node/nodeRunner.go
Labels: complexity:trivial, impact:low, interested:protocol, size:small

#5173 Coverage for: factory/processing
  cmd/keygenerator/converter/pidPubkeyConverter.go
  errors/errors.go
  factory/consensus/consensusComponents_test.go
  factory/interface.go
  factory/mock/stateComponentsHolderStub.go
  factory/processing/blockProcessorCreator.go
  factory/processing/export_test.go
  factory/processing/processComponents.go
  factory/processing/processComponentsHandler_test.go
  factory/processing/processComponents_test.go
  genesis/errors.go
  genesis/process/genesisBlockCreator.go
  integrationTests/mock/p2pAntifloodHandlerStub.go
  integrationTests/testProcessorNode.go
  node/nodeTesting_test.go
  process/factory/metachain/vmContainerFactory.go
  process/factory/metachain/vmContainerFactory_test.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  testscommon/components/default.go
  testscommon/factory/stateComponentsMock.go
  testscommon/mainFactoryMocks/bootstrapComponentsStub.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5217 sync missing data trie node
  common/errors.go
  common/interface.go
  epochStart/metachain/systemSCs_test.go
  errors/errors.go
  errors/missingTrieNodeError.go
  factory/api/apiResolverFactory.go
  factory/consensus/consensusComponents.go
  factory/interface.go
  factory/mock/stateComponentsHolderStub.go
  factory/processing/blockProcessorCreator.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/export_test.go
  factory/processing/processComponents.go
  factory/state/stateComponents.go
  factory/state/stateComponentsHandler.go
  factory/state/stateComponentsHandler_test.go
  genesis/process/genesisBlockCreator.go
  genesis/process/metaGenesisBlockCreator.go
  genesis/process/shardGenesisBlockCreator.go
  go.mod
  go.sum
  integrationTests/testProcessorNode.go
  integrationTests/vm/testInitializer.go
  integrationTests/vm/wasm/utils.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/blockChainHook_test.go
  process/smartContract/hooks/errors.go
  process/sync/export_test.go
  process/sync/interface.go
  process/sync/metablock.go
  process/sync/metablock_test.go
  process/sync/shardblock.go
  process/sync/shardblock_test.go
  state/syncer/export_test.go
  state/syncer/missingTrieNodesNotifier.go
  state/syncer/missingTrieNodesNotifier_test.go
  state/syncer/userAccountSyncer_test.go
  state/syncer/userAccountsSyncer.go
  testscommon/components/default.go
  testscommon/missingTrieNodesNotifierStub.go
  testscommon/stateComponentsMock.go
  testscommon/stateSyncNotifierSubscriberStub.go
  trie/node.go
Labels: ignore-for-release-notes

#5235 Coverage for: trie
  testscommon/trie/snapshotPruningStorerStub.go
  trie/dfsIterator_test.go
  trie/factory/trieCreator_test.go
  trie/keyBuilder/disabledKeyBuilder_test.go
  trie/snapshotTrieStorageManager_test.go
  trie/statistics/trieStatisticsCollector_test.go
  trie/statistics/trieStatistics_test.go
  trie/storageMarker/trieStorageMarker_test.go
  trie/syncTrieStorageManager_test.go
  trie/sync_test.go
  trie/trieNodesHandler_test.go
  trie/trieStorageManagerInEpoch_test.go
  trie/trieStorageManagerWithoutCheckpoints_test.go
  trie/trieStorageManagerWithoutSnapshot_test.go
  trie/trieStorageManager_test.go
  update/container/accountDBSyncers_test.go
  update/container/export_test.go
  update/container/trieSyncers_test.go
Labels: impact:low, interested:protocol, size:medium, type:improvement, area:testing

#5237 Coverage for facade
  facade/initial/initialNodeFacade_test.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
Labels: impact:low, interested:protocol, size:medium, type:improvement, area:testing

#5243 Merge rc/1.6.0 in feat/sync missing trie nodes 16 may
  facade/initial/initialNodeFacade_test.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  go.mod
  go.sum
  testscommon/trie/snapshotPruningStorerStub.go
  trie/dfsIterator_test.go
  trie/factory/trieCreator_test.go
  trie/keyBuilder/disabledKeyBuilder_test.go
  trie/snapshotTrieStorageManager_test.go
  trie/statistics/trieStatisticsCollector_test.go
  trie/statistics/trieStatistics_test.go
  trie/storageMarker/trieStorageMarker_test.go
  trie/syncTrieStorageManager_test.go
  trie/sync_test.go
  trie/trieNodesHandler_test.go
  trie/trieStorageManagerInEpoch_test.go
  trie/trieStorageManagerWithoutCheckpoints_test.go
  trie/trieStorageManagerWithoutSnapshot_test.go
  trie/trieStorageManager_test.go
  update/container/accountDBSyncers_test.go
  update/container/export_test.go
  update/container/trieSyncers_test.go
Labels: ignore-for-release-notes

#5244 proper core release
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5201 Refactored transaction simulation construction
  api/middleware/responseLogger.go
  factory/processing/blockProcessorCreator.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/export_test.go
  factory/processing/processComponents.go
  factory/processing/txSimulatorProcessComponents.go
  factory/processing/txSimulatorProcessComponents_test.go
  integrationTests/realcomponents/processorRunner.go
  integrationTests/realcomponents/processorRunner_test.go
  integrationTests/realcomponents/testdata/adder/adder.abi.json
  integrationTests/realcomponents/testdata/adder/adder.wasm
  integrationTests/realcomponents/txsimulator/componentConstruction_test.go
  integrationTests/testProcessorNode.go
  node/nodeRunner_test.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
  testscommon/realConfigsHandling.go
  vm/systemSmartContracts/eei.go
Labels: type:bug, area:node-api, area:processing, area:sc-processing, impact:medium, interested:protocol, size:medium, complexity:medium

#5242 update trie stats
  common/interface.go
  go.mod
  go.sum
  integrationTests/vm/txsFee/migrateDataTrie_test.go
  state/accountsDB.go
  state/snapshotStatistics.go
  state/snapshotStatistics_test.go
  testscommon/trie/statisticsMock.go
  trie/statistics/trieStatistics.go
  trie/statistics/trieStatisticsCollector.go
  trie/statistics/trieStatisticsCollector_test.go
  trie/statistics/trieStatistics_test.go
  trie/trieStorageManager.go
Labels: ignore-for-release-notes

#5229 Mx 13965 block processing cutoff
  cmd/node/config/prefs.toml
  cmd/node/flags.go
  common/constants.go
  config/prefsConfig.go
  config/tomlConfig_test.go
  factory/core/coreComponents.go
  factory/processing/blockProcessorCreator.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/export_test.go
  factory/processing/processComponents.go
  factory/processing/processComponents_test.go
  integrationTests/realcomponents/processorRunner.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/nodeRunner.go
  process/block/argProcessor.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/cutoff/blockProcessingCutoffFactory.go
  process/block/cutoff/blockProcessingCutoffFactory_test.go
  process/block/cutoff/blockProcessingCutoffHandler.go
  process/block/cutoff/blockProcessingCutoffHandler_test.go
  process/block/cutoff/disabledBlockProcessingCutoff.go
  process/block/cutoff/disabledBlockProcessingCutoff_test.go
  process/block/cutoff/errors.go
  process/block/cutoff/interface.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/shardblock.go
  process/errors.go
  testscommon/blockProcessingCutoffStub.go
Labels: area:processing, impact:low, interested:protocol

#5265 Fixed the indexer creation
  factory/status/statusComponents.go
Labels: type:bug, ignore-for-release-notes

#5273 proper release
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5276 update vm versions in go mod
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5245 Mx 13962 consistent tokens values length checks
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  go.mod
  go.sum
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerStub.go
Labels: area:processing, area:system-vm, impact:low, type:improvement, complexity:medium

#5177 added semi-integration test for relayed v2 multi nft transfers
  integrationTests/vm/txsFee/multiShard/esdt_test.go
  integrationTests/vm/txsFee/utils/utilsESDT.go
Labels: ignore-for-release-notes

#5213 Coverage for: dataRetriever
  dataRetriever/blockchain/blockchain_test.go
  dataRetriever/blockchain/metachain_test.go
  dataRetriever/chainStorer_test.go
  dataRetriever/dataPool/dataPool_test.go
  dataRetriever/dataPool/headersCache/headersCache.go
  dataRetriever/dataPool/headersCache/headersPool_test.go
  dataRetriever/factory/containers/resolversContainer_test.go
  dataRetriever/factory/epochProviders/currentEpochProvidersFactory_test.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go
  dataRetriever/interface.go
  dataRetriever/mock/marshalizerMock.go
  dataRetriever/provider/miniBlocks_test.go
  dataRetriever/requestHandlers/requestHandler_test.go
  dataRetriever/resolvers/epochproviders/disabled/disabledEpochProvider_test.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/messageProcessor_test.go
  dataRetriever/resolvers/miniblockResolver_test.go
  dataRetriever/resolvers/peerAuthenticationResolver_test.go
  dataRetriever/resolvers/transactionResolver_test.go
  dataRetriever/resolvers/trieNodeResolver_test.go
  dataRetriever/resolvers/validatorInfoResolver_test.go
  dataRetriever/shardedData/shardedData_test.go
  dataRetriever/storageRequesters/headerRequester_test.go
  dataRetriever/storageRequesters/sliceRequester_test.go
  dataRetriever/storageRequesters/trieNodeRequester_test.go
  dataRetriever/topicSender/diffPeerListCreator_test.go
  dataRetriever/txpool/shardedTxPool_test.go
  dataRetriever/unitType_test.go
  testscommon/storageManager/storageManagerStub.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5287 Update feat/balance data tries 29may
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  dataRetriever/blockchain/blockchain_test.go
  dataRetriever/blockchain/metachain_test.go
  dataRetriever/chainStorer_test.go
  dataRetriever/dataPool/dataPool_test.go
  dataRetriever/dataPool/headersCache/headersCache.go
  dataRetriever/dataPool/headersCache/headersPool_test.go
  dataRetriever/factory/containers/resolversContainer_test.go
  dataRetriever/factory/epochProviders/currentEpochProvidersFactory_test.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go
  dataRetriever/interface.go
  dataRetriever/mock/marshalizerMock.go
  dataRetriever/provider/miniBlocks_test.go
  dataRetriever/requestHandlers/requestHandler_test.go
  dataRetriever/resolvers/epochproviders/disabled/disabledEpochProvider_test.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/messageProcessor_test.go
  dataRetriever/resolvers/miniblockResolver_test.go
  dataRetriever/resolvers/peerAuthenticationResolver_test.go
  dataRetriever/resolvers/transactionResolver_test.go
  dataRetriever/resolvers/trieNodeResolver_test.go
  dataRetriever/resolvers/validatorInfoResolver_test.go
  dataRetriever/shardedData/shardedData_test.go
  dataRetriever/storageRequesters/headerRequester_test.go
  dataRetriever/storageRequesters/sliceRequester_test.go
  dataRetriever/storageRequesters/trieNodeRequester_test.go
  dataRetriever/topicSender/diffPeerListCreator_test.go
  dataRetriever/txpool/shardedTxPool_test.go
  dataRetriever/unitType_test.go
  go.mod
  go.sum
  integrationTests/vm/txsFee/multiShard/esdt_test.go
  integrationTests/vm/txsFee/utils/utilsESDT.go
  outport/process/transactionsfee/dataHolders.go
  outport/process/transactionsfee/dataHolders_test.go
  outport/process/transactionsfee/transactionChecker.go
  outport/process/transactionsfee/transactionsFeeProcessor.go
  outport/process/transactionsfee/transactionsFeeProcessor_test.go
  p2p/config/config.go
  p2p/constants.go
  p2p/errors.go
  p2p/factory/factory.go
  p2p/interface.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerMock/enableEpochsHandlerStub.go
  testscommon/storageManager/storageManagerStub.go
Labels: ignore-for-release-notes

#5292 update go mod
  go.mod
  go.sum
  trie/statistics/trieStatistics.go
  trie/statistics/trieStatistics_test.go
Labels: ignore-for-release-notes

#5298 add proper releases
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5296 Merge master rc/v1.5.0 2023.05.29
  common/enablers/epochFlags.go
  config/epochConfig.go
  integrationTests/multiShard/relayedTx/edgecases/edgecases_test.go
  integrationTests/vm/txsFee/relayedAsyncCall_test.go
  integrationTests/vm/txsFee/relayedBuiltInFunctions_test.go
  integrationTests/vm/txsFee/relayedMoveBalance_test.go
  integrationTests/vm/txsFee/relayedScCalls_test.go
Labels: ignore-for-release-notes

#5010 Feat/sharded persister
  config/config.go
  epochStart/bootstrap/process.go
  go.mod
  go.sum
  integrationTests/vm/wasm/delegation/testRunner.go
  storage/database/db.go
  storage/disabled/shardIDProvider.go
  storage/disabled/shardIDProvider_test.go
  storage/errors.go
  storage/factory/dbConfigHandler.go
  storage/factory/dbConfigHandler_test.go
  storage/factory/export_test.go
  storage/factory/openStorage.go
  storage/factory/openStorage_test.go
  storage/factory/persisterCreator.go
  storage/factory/persisterCreator_test.go
  storage/factory/persisterFactory.go
  storage/factory/persisterFactory_test.go
  storage/factory/storageServiceFactory.go
  storage/interface.go
  storage/latestData/latestDataProvider.go
  storage/pruning/fullHistoryPruningStorer_test.go
  storage/pruning/pruningStorer_test.go
  storage/storageunit/constants.go
  storage/storageunit/storageunit.go
  testscommon/integrationtests/factory.go
Labels: type:feature, area:storage, impact:medium, interested:protocol, size:medium

#5291 Feat/trie sync optimizations
  common/channels.go
  common/constants.go
  state/syncer/baseAccountsSyncer.go
  state/syncer/baseAccoutnsSyncer_test.go
  state/syncer/export_test.go
  state/syncer/userAccountsSyncer.go
  state/syncer/userAccountsSyncer_test.go
  state/syncer/validatorAccountsSyncer.go
  state/syncer/validatorAccountsSyncer_test.go
  trie/depthFirstSync.go
  trie/depthFirstSync_test.go
  trie/doubleListSync.go
  trie/doubleListSync_test.go
  trie/sync.go
  trie/sync_test.go
  trie/trieStorageManager.go
  trie/trieStorageManagerWithoutCheckpoints.go
  trie/trieStorageManagerWithoutSnapshot.go
Labels: area:trie, impact:high, interested:protocol, size:medium, type:improvement, complexity:medium

#5310 Merge rc v1.5.0 rc v1.6.0 2023.05.30
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  go.mod
  go.sum
  integrationTests/multiShard/relayedTx/edgecases/edgecases_test.go
  integrationTests/vm/txsFee/common.go
  integrationTests/vm/txsFee/guardAccount_test.go
  integrationTests/vm/txsFee/migrateDataTrie_test.go
  integrationTests/vm/txsFee/relayedAsyncCall_test.go
  integrationTests/vm/txsFee/relayedBuiltInFunctions_test.go
  integrationTests/vm/txsFee/relayedMoveBalance_test.go
  integrationTests/vm/txsFee/relayedScCalls_test.go
  process/errors.go
  process/guardian/guardedAccount.go
  process/guardian/guardedAccount_test.go
  process/interface.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/transaction/baseProcess.go
  process/transaction/baseProcess_test.go
  process/transaction/export_test.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerMock/enableEpochsHandlerStub.go
  testscommon/goroutines/filter.go
  testscommon/scProcessorMock.go
  testscommon/vmcommonMocks/builtInFunctionExecutableStub.go
Labels: ignore-for-release-notes
