Repository multiversx/mx-chain-go, pull requests merged in 2023-12, with the labels that each got.

#5761 Fixed forgotten mutexes Unlock calls
  process/block/metablock.go
  process/block/shardblock.go
Labels: type:bug, area:sc-processing, complexity:trivial, impact:low, interested:protocol, size:small

#5738 Move ValidatorAPIResponse structure to mx-chain-core-go
  api/groups/validatorGroup.go
  api/groups/validatorGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  facade/initial/initialNodeFacade.go
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  factory/mock/validatorsProviderStub.go
  go.mod
  go.sum
  integrationTests/interface.go
  integrationTests/mock/validatorsProviderStub.go
  node/mock/validatorsProviderStub.go
  node/node.go
  node/node_test.go
  process/interface.go
  process/mock/validatorsProviderStub.go
  process/peer/export_test.go
  process/peer/validatorsProvider.go
  process/peer/validatorsProvider_test.go
  state/accounts/peerAccountData.pb.go
  state/accounts/peerAccountData.proto
Labels: area:node-api, complexity:trivial, impact:low, interested:protocol, type:refactoring

#5765 Updated vms
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5764 Fix snapshots manager
  common/interface.go
  state/snapshotsManager.go
  state/snapshotsManager_test.go
  state/storagePruningManager/evictionWaitingList/memoryEvictionWaitingList.go
  testscommon/storageManager/storageManagerStub.go
  trie/trieStorageManager.go
  trie/trieStorageManagerWithoutSnapshot.go
  trie/trieStorageManagerWithoutSnapshot_test.go
  trie/trieStorageManager_test.go
Labels: type:bug, area:trie, complexity:high, impact:medium, interested:protocol, size:small

#5666 Equivalent messages filter on consensus topic
  cmd/node/config/enableEpochs.toml
  common/constants.go
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  config/epochConfig.go
  config/tomlConfig_test.go
  consensus/message.go
  consensus/mock/equivalentMessagesDebuggerStub.go
  consensus/spos/debug/equivalentMessagesDebugger.go
  consensus/spos/debug/equivalentMessagesDebugger_test.go
  consensus/spos/errors.go
  consensus/spos/export_test.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  factory/consensus/consensusComponents.go
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithMultisigner.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  sharding/mock/enableEpochsHandlerMock.go
Labels: type:feature, area:processing, impact:low, interested:protocol, complexity:medium

#5793 Merge rc160 into rc170 2023.12.28
  cmd/node/config/systemSmartContractsConfig.toml
  common/interface.go
  dataRetriever/factory/dataPoolFactory.go
  epochStart/metachain/systemSCs_test.go
  genesis/process/genesisBlockCreator.go
  go.mod
  go.sum
  keysManagement/managedPeersHolder.go
  keysManagement/managedPeersHolder_test.go
  node/external/blockAPI/metaBlock.go
  node/external/blockAPI/shardBlock.go
  outport/notifier/eventNotifier.go
  outport/notifier/eventNotifier_test.go
  process/block/metablock.go
  process/block/shardblock.go
  process/smartContract/hooks/blockChainHook.go
  state/snapshotsManager.go
  state/snapshotsManager_test.go
  state/storagePruningManager/evictionWaitingList/memoryEvictionWaitingList.go
  storage/factory/persisterCreator.go
  storage/factory/storageServiceFactory.go
  storage/interface.go
  storage/storageunit/storageunit.go
  storage/storageunit/storageunit_test.go
  testscommon/dataRetriever/poolFactory.go
  testscommon/storageManager/storageManagerStub.go
  trie/trieStorageManager.go
  trie/trieStorageManagerWithoutSnapshot.go
  trie/trieStorageManagerWithoutSnapshot_test.go
  trie/trieStorageManager_test.go
  update/factory/dataTrieFactory.go
  update/factory/exportHandlerFactory.go
  vm/systemSmartContracts/esdt.go
  vm/systemSmartContracts/governance.go
  vm/systemSmartContracts/governance_test.go
Labels: ignore-for-release-notes
