Repository multiversx/mx-chain-go, pull requests merged in 2023-03, with the labels that each got.

#4585 moved snapshots enabled field from config to cli params
  cmd/node/config/config.toml
  cmd/node/flags.go
  config/config.go
  config/contextFlagsConfig.go
  dataRetriever/factory/storageRequestersContainer/args.go
  dataRetriever/factory/storageRequestersContainer/baseRequestersContainerFactory.go
  dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory.go
  dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory_test.go
  dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory.go
  dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory_test.go
  epochStart/bootstrap/fromLocalStorage.go
  epochStart/bootstrap/metaStorageHandler.go
  epochStart/bootstrap/metaStorageHandler_test.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/shardStorageHandler.go
  epochStart/bootstrap/shardStorageHandler_test.go
  epochStart/bootstrap/storageProcess.go
  factory/data/dataComponents.go
  factory/processing/processComponents.go
  factory/state/stateComponents.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/nodeRunner.go
  storage/factory/pruningStorerFactory.go
  testscommon/components/components.go
  testscommon/generalConfig.go
  trie/factory/trieCreator.go
  trie/factory/trieCreator_test.go
Labels: area:storage, interested:protocol

#5037 Update mx-chain-p2p-go
  cmd/keygenerator/converter/pidPubkeyConverter.go
  go.mod
  go.sum
  p2p/factory/factory.go
  p2p/interface.go
Labels: ignore-for-release-notes

#5043 Bug-fix outport data provider
  outport/process/transactionsfee/transactionsFeeProcessor.go
  outport/process/transactionsfee/transactionsFeeProcessor_test.go
  process/block/metablock.go
  process/block/shardblock.go
Labels: type:bug, area:indexer, interested:explorer, size:small, priority:1-I&U

#5057 Proper release for feat multikey
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5059 Bug-fix `gasUsed` and `fee` transasctionsFeeProcessor
  node/external/transactionAPI/gasUsedAndFeeProcessor.go
  node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
  outport/process/transactionsfee/transactionsFeeProcessor.go
  outport/process/transactionsfee/transactionsFeeProcessor_test.go
Labels: type:bug, area:indexer, impact:low, interested:explorer, size:small, priority:1-I&U, complexity:medium

#5062 Snapshot get test point
  trie/node_extension.go
  trie/node_test.go
  trie/snapshotTrieStorageManager.go
Labels: ignore-for-release-notes

#4962 Migrate data trie
  cmd/node/config/gasSchedules/gasScheduleV1.toml
  cmd/node/config/gasSchedules/gasScheduleV2.toml
  cmd/node/config/gasSchedules/gasScheduleV3.toml
  cmd/node/config/gasSchedules/gasScheduleV4.toml
  cmd/node/config/gasSchedules/gasScheduleV5.toml
  cmd/node/config/gasSchedules/gasScheduleV6.toml
  cmd/node/config/gasSchedules/gasScheduleV7.toml
  common/interface.go
  common/trie.go
  errors/errors.go
  genesis/mock/userAccountMock.go
  go.mod
  go.sum
  node/node_test.go
  process/gasCost.go
  process/smartContract/builtInFunctions/factory_test.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/baseAccount.go
  state/disabled/disabledTrackableDataTrie.go
  state/export_test.go
  state/interface.go
  state/journalEntries.go
  state/journalEntries_test.go
  state/parsers/dataTrieLeafParser.go
  state/parsers/dataTrieLeafParser_test.go
  state/parsers/mainTrieLeafParser.go
  state/parsers/mainTrieLeafParser_test.go
  state/trackableDataTrie.go
  state/trackableDataTrie_test.go
  testscommon/state/accountWrapperMock.go
  testscommon/state/userAccountStub.go
  testscommon/trie/dataTrieMigratorStub.go
  testscommon/trie/dataTrieTrackerStub.go
  testscommon/trie/trieStub.go
  trie/branchNode.go
  trie/branchNode_test.go
  trie/extensionNode.go
  trie/extensionNode_test.go
  trie/interface.go
  trie/leafNode.go
  trie/leafNode_test.go
  trie/node.go
  trie/node_test.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
  vm/gasCost.go
  vm/systemSmartContracts/defaults/gasMap.go
Labels: area:trie, complexity:high, impact:medium, interested:protocol, size:large, type:improvement

#5028 Bugfixing for scheduled transactions in feat sovereign
  cmd/sovereignnode/config/economics.toml
  cmd/sovereignnode/config/enableEpochs.toml
  factory/disabled/txProcessor.go
  process/block/preprocess/accountsTracker.go
  process/block/preprocess/accountsTracker_test.go
  process/block/preprocess/sovereignChainTransactions.go
  process/block/preprocess/sovereignChainTransactions_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactionsV2.go
  process/interface.go
  process/transaction/baseProcess.go
  process/transaction/metaProcess.go
  process/txsimulator/interface.go
  scripts/testnet/include/config.sh
  scripts/testnet/include/observers.sh
  scripts/testnet/sovereign-txgen-basic.sh
  scripts/testnet/sovereign-txgen-erc20.sh
  scripts/testnet/sovereign-txgen-esdt.sh
  scripts/testnet/sovereignStart.sh
  testscommon/state/userAccountStub.go
  testscommon/txProcessorMock.go
  testscommon/txProcessorStub.go
Labels: type:feature, ignore-for-release-notes

#5050 Update mx-chain-p2p-go with latest peers rating handler fixes
  config/overridableConfig/configOverriding_test.go
  consensus/mock/messageSigningHandlerMock.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/worker_test.go
  dataRetriever/mock/p2pMessageMock.go
  dataRetriever/requestData_test.go
  dataRetriever/resolvers/common_test.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/messageProcessor_test.go
  dataRetriever/resolvers/transactionResolver_test.go
  dataRetriever/resolvers/trieNodeResolver_test.go
  dataRetriever/topicSender/baseTopicSender.go
  dataRetriever/topicSender/export_test.go
  dataRetriever/topicSender/topicRequestSender.go
  dataRetriever/topicSender/topicResolverSender_test.go
  go.mod
  go.sum
  integrationTests/p2p/peersRating/peersRating_test.go
  integrationTests/testProcessorNode.go
  p2p/constants.go
  process/interceptors/baseDataInterceptor_test.go
  process/interceptors/epochStartMetaBlockInterceptor_test.go
  process/interceptors/multiDataInterceptor_test.go
  process/interceptors/singleDataInterceptor_test.go
  process/mock/p2pMessageMock.go
  process/throttle/antiflood/p2pAntiflood_test.go
  testscommon/p2pmocks/p2pMessageMock.go
Labels: ignore-for-release-notes

#4969 Extra info on enableEpochsHandler log
  common/enablers/enableEpochsHandler.go
Labels: ignore-for-release-notes

#5072 Merge rc v1.6.0 into feat chain go sdk 09.03.2023
  common/enablers/enableEpochsHandler.go
Labels: type:feature, ignore-for-release-notes

#5084 Merge rc v1.6.0 feat pubkey conv 2023.03.10
  common/enablers/enableEpochsHandler.go
  integrationTests/consensus/consensus_test.go
  node/external/transactionAPI/apiTransactionProcessor.go
Labels: ignore-for-release-notes

#5090 always return empty responses when accounts are not found
  node/node.go
  node/node_test.go
Labels: area:node-api, type:breaking-change

#5056 add migration stats when collecting statistics about the trie
  common/interface.go
  go.mod
  go.sum
  state/snapshotStatistics.go
  state/snapshotStatistics_test.go
  testscommon/trie/statisticsMock.go
  trie/leafNode.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
  trie/statistics/trieStatistics.go
  trie/statistics/trieStatisticsCollector.go
  trie/statistics/trieStatisticsCollector_test.go
  trie/statistics/trieStatistics_test.go
  trie/trieStorageManager.go
Labels: area:trie, complexity:trivial, impact:low, interested:protocol, size:small

#5071 extracted configuration value for vm-queries delay
  cmd/node/config/config.toml
  config/config.go
  node/nodeRunner.go
Labels: area:node-api, type:improvement, priority:4-!i&!u

#5094 Merge rc v1.6.0 into feat consensus model v2 14.03.2023
  cmd/node/config/config.toml
  config/config.go
  node/nodeRunner.go
Labels: type:feature, ignore-for-release-notes

#5096 Merge feat consensus model v2 into feat chain go sdk 14.03.2023
  cmd/node/config/config.toml
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/config.go
  config/epochConfig.go
  config/tomlConfig_test.go
  consensus/message.go
  consensus/message.pb.go
  consensus/message.proto
  consensus/message_test.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/bls/subroundStartRound_test.go
  consensus/spos/consensusMessageValidator.go
  consensus/spos/consensusMessageValidator_test.go
  consensus/spos/consensusState.go
  consensus/spos/consensusState_test.go
  consensus/spos/errors.go
  consensus/spos/export_test.go
  consensus/spos/sposFactory/sposFactory.go
  consensus/spos/sposFactory/sposFactory_test.go
  consensus/spos/subround.go
  consensus/spos/subround_test.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  factory/consensus/consensusComponents.go
  node/nodeRunner.go
  process/block/metablock.go
  process/block/shardblock.go
  process/sync/metablock_test.go
  process/sync/shardblock_test.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerStub.go
Labels: type:feature, ignore-for-release-notes

#5085 Merge rc v1.5.0 in rc v1.6.0 2023.03.10
  go.mod
  go.sum
  node/external/transactionAPI/gasUsedAndFeeProcessor.go
  node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
  outport/process/transactionsfee/transactionsFeeProcessor.go
  outport/process/transactionsfee/transactionsFeeProcessor_test.go
  process/block/metablock.go
  process/block/shardblock.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/peerAccountsDB.go
  testscommon/memDbMock.go
  trie/node_extension.go
  trie/node_test.go
  trie/snapshotTrieStorageManager.go
Labels: ignore-for-release-notes

#5107 Update master rc v1.5.0 2023.03.20
  go.mod
  go.sum
  node/node.go
  node/node_test.go
  vm/systemSmartContracts/esdt.go
Labels: ignore-for-release-notes

#5117 Update rc v1.5.0 proper releases 2023.03.21
  go.mod
  go.sum
  node/node.go
  node/node_test.go
  vm/systemSmartContracts/esdt.go
Labels: ignore-for-release-notes

#5115 add migrateDataTrie semi integration tests
  integrationTests/vm/txsFee/migrateDataTrie_test.go
  testscommon/integrationtests/factory.go
Labels: ignore-for-release-notes

#5110 v1.4.14-dev-config
  cmd/node/config/enableEpochs.toml
Labels: ignore-for-release-notes

#5106 Block tracker implementation for extended shard headers
  dataRetriever/requestHandlers/requestHandler.go
  factory/mock/blockTrackerStub.go
  genesis/process/disabled/requestHandler.go
  go.mod
  go.sum
  integrationTests/mock/blockTrackerStub.go
  node/mock/blockTrackerStub.go
  process/block/sovereignblock.go
  process/common.go
  process/interface.go
  process/mock/blockTrackerMock.go
  process/track/baseBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockProcessor.go
  process/track/blockProcessor_test.go
  process/track/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
  process/track/sovereignChainBlockProcessor.go
  process/track/sovereignChainBlockProcessor_test.go
  process/track/sovereignChainShardBlockTrack.go
  process/track/sovereignChainShardBlockTrack_test.go
  testscommon/requestHandlerStub.go
Labels: type:feature, ignore-for-release-notes
