Repository multiversx/mx-chain-go, pull requests merged in 2023-07, with the labels that each got.

#5393 Merge rc/v1.6.0 in feat/state refactor 4jul
  api/groups/transactionGroup.go
  api/groups/transactionGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  facade/initial/initialNodeFacade.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/mock/txExecutionSimulatorStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  factory/api/apiResolverFactory.go
  factory/interface.go
  factory/mock/processComponentsStub.go
  factory/processing/export_test.go
  factory/processing/processComponents.go
  factory/processing/processComponentsHandler.go
  factory/processing/processComponentsHandler_test.go
  factory/processing/txSimulatorProcessComponents.go
  factory/processing/txSimulatorProcessComponents_test.go
  go.mod
  go.sum
  integrationTests/interface.go
  integrationTests/mock/processComponentsStub.go
  integrationTests/mock/transactionSimulatorStub.go
  integrationTests/realcomponents/txsimulator/componentConstruction_test.go
  integrationTests/testProcessorNodeWithTestWebServer.go
  integrationTests/vm/testInitializer.go
  integrationTests/vm/txsFee/apiTransactionEvaluator_test.go
  node/external/errors.go
  node/external/interface.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionResults.go
  node/external/transactionAPI/gasUsedAndFeeProcessor.go
  node/external/transactionAPI/refundDetector.go
  node/external/transactionAPI/refundDetector_test.go
  node/mock/transactionCostEstimatorMock.go
  node/nodeRunner.go
  process/mock/transactionSimulatorStub.go
  process/smartContract/process.go
  process/transaction/transactionCostEstimator.go
  process/transactionEvaluator/data/data.go
  process/transactionEvaluator/errors.go
  process/transactionEvaluator/interface.go
  process/transactionEvaluator/simulationAccountsDB.go
  process/transactionEvaluator/simulationAccountsDB_test.go
  process/transactionEvaluator/transactionEvaluator.go
  process/transactionEvaluator/transactionEvaluator_test.go
  process/transactionEvaluator/transactionSimulator.go
  process/transactionEvaluator/transactionSimulator_test.go
  process/txsimulator/data/data.go
  process/txsimulator/wrappedAccountsDB.go
  state/interface.go
  testscommon/state/accountsAdapterStub.go
Labels: ignore-for-release-notes

#5392 Fix the logviewer CLI commands
  .github/workflows/check-cli-md.yml
  Makefile
  cmd/CLI.md.sh
  cmd/assessment/CLI.md
  cmd/keygenerator/CLI.md
  cmd/logviewer/CLI.md
  cmd/node/CLI.md
  cmd/seednode/CLI.md
  cmd/termui/CLI.md
Labels: impact:low, interested:protocol, interested:validator, size:small, type:docs

#5402 Fixed race condition in test
  process/transaction/shardProcess_test.go
Labels: type:bug, ignore-for-release-notes

#5403 Compressed flags
  cmd/node/config/enableEpochs.toml
Labels: ignore-for-release-notes

#5416 Merge rc160 into feat multiple p2p messengers 2023.07.10
  .github/workflows/check-cli-md.yml
  .github/workflows/deploy-docker.yml
  Makefile
  cmd/CLI.md.sh
  cmd/assessment/CLI.md
  cmd/keygenerator/CLI.md
  cmd/logviewer/CLI.md
  cmd/node/CLI.md
  cmd/node/config/enableEpochs.toml
  cmd/seednode/CLI.md
  cmd/termui/CLI.md
  docker-compose.yml
  docker/elasticsearch/elasticsearch.yml
  docker/filebeat/Dockerfile
  docker/filebeat/filebeat.yml
  docker/filebeat/logstash-beats.crt
  docker/filebeat/start.sh
  docker/keygenerator/Dockerfile
  docker/multiversx/Dockerfile
  docker/seednode/Dockerfile
  process/transaction/shardProcess_test.go
Labels: ignore-for-release-notes

#5414 Merge rc160 into feat multikey metrics 2023.07.10
  .github/workflows/check-cli-md.yml
  .github/workflows/deploy-docker.yml
  Makefile
  cmd/CLI.md.sh
  cmd/assessment/CLI.md
  cmd/keygenerator/CLI.md
  cmd/logviewer/CLI.md
  cmd/node/CLI.md
  cmd/node/config/enableEpochs.toml
  cmd/seednode/CLI.md
  cmd/termui/CLI.md
  docker-compose.yml
  docker/elasticsearch/elasticsearch.yml
  docker/filebeat/Dockerfile
  docker/filebeat/filebeat.yml
  docker/filebeat/logstash-beats.crt
  docker/filebeat/start.sh
  docker/keygenerator/Dockerfile
  docker/multiversx/Dockerfile
  docker/seednode/Dockerfile
  process/transaction/shardProcess_test.go
Labels: ignore-for-release-notes

#5417 New enable epochs handler functionality
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/interface.go
Labels: area:processing, complexity:trivial, impact:low, interested:protocol, type:refactoring

#5409 Deterministic sort on validators info
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  epochStart/metachain/testdata/expected-deterministic.data
  epochStart/metachain/testdata/expected-legacy.data
  epochStart/metachain/validators.go
  epochStart/metachain/validators_test.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerStub.go
Labels: area:processing, impact:low, interested:protocol, size:small, type:improvement, complexity:medium

#5420 Merge rc160 into feat multikey metrics 2023.05.11
  go.mod
  go.sum
  integrationTests/vm/txsFee/multiShard/scCallWithValueTransfer_test.go
  integrationTests/vm/txsFee/testdata/transferValueContract/transferValue.wasm
  integrationTests/vm/txsFee/utils/utils.go
  process/smartContract/process.go
  process/smartContract/processorV2/processV2.go
Labels: ignore-for-release-notes

#5428 Put back snapshot-less config in config.toml
  cmd/node/config/config.toml
  cmd/node/flags.go
  config/config.go
  config/contextFlagsConfig.go
  config/tomlConfig_test.go
  dataRetriever/factory/storageRequestersContainer/args.go
  dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory.go
  dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory_test.go
  dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory.go
  dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory_test.go
  epochStart/bootstrap/fromLocalStorage.go
  epochStart/bootstrap/metaStorageHandler.go
  epochStart/bootstrap/metaStorageHandler_test.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/shardStorageHandler.go
  epochStart/bootstrap/shardStorageHandler_test.go
  epochStart/bootstrap/storageProcess.go
  factory/data/dataComponents.go
  factory/processing/processComponents.go
  factory/state/stateComponents.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/realcomponents/processorRunner.go
  node/nodeRunner.go
  storage/factory/storageServiceFactory.go
  trie/factory/trieCreator.go
  trie/factory/trieCreator_test.go
Labels: ignore-for-release-notes

#5424 Update vm-common and vms + remove old methods part 1
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/enablers/epochFlags_test.go
  common/interface.go
  epochStart/metachain/systemSCs.go
  go.mod
  go.sum
  integrationTests/nodesCoordinatorFactory.go
  process/block/preprocess/gasComputation.go
  process/block/preprocess/gasComputation_test.go
  process/economics/economicsData.go
  process/economics/economicsData_test.go
  process/factory/metachain/vmContainerFactory_test.go
  process/factory/shard/vmContainerFactory.go
  process/interceptors/factory/interceptedTxDataFactory.go
  process/peer/process.go
  process/peer/process_test.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
  process/smartContract/backwardsCompatibility.go
  process/smartContract/process.go
  process/smartContract/processProxy/processProxy_test.go
  process/smartContract/process_test.go
  process/smartContract/processorV2/process_test.go
  process/smartContract/vmInput.go
  process/transaction/baseProcess.go
  process/transaction/baseProcess_test.go
  process/transaction/metaProcess.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerMock/enableEpochsHandlerStub.go
  vm/systemSmartContracts/delegation.go
  vm/systemSmartContracts/delegation_test.go
  vm/systemSmartContracts/staking.go
  vm/systemSmartContracts/stakingSaveLoad.go
  vm/systemSmartContracts/staking_test.go
  vm/systemSmartContracts/validator.go
  vm/systemSmartContracts/validatorSaveLoad.go
  vm/systemSmartContracts/validator_test.go
Labels: ignore-for-release-notes

#5435 Updated mx-chain-communication-go with NetworkType
  cmd/seednode/main.go
  factory/network/networkComponents.go
  go.mod
  go.sum
  p2p/constants.go
Labels: ignore-for-release-notes

#5431 Update enableEpochsHandler methods part 2
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  epochStart/metachain/systemSCs.go
  integrationTests/nodesCoordinatorFactory.go
  integrationTests/testConsensusNode.go
  outport/process/executionOrder/transactionsExecutionOrder.go
  outport/process/executionOrder/transactionsExecutionOrder_test.go
  process/block/preprocess/basePreProcess.go
  process/block/preprocess/smartContractResults.go
  process/block/preprocess/smartContractResults_test.go
  process/block/preprocess/transactions.go
  process/block/preprocess/transactions_test.go
  process/peer/process.go
  process/peer/process_test.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
  process/smartContract/hooks/blockChainHook.go
  process/smartContract/hooks/blockChainHook_test.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/smartContract/processorV2/processV2.go
  process/smartContract/processorV2/process_test.go
  process/smartContract/testScProcessor.go
  process/transaction/metaProcess.go
  process/transaction/metaProcess_test.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
  process/transactionEvaluator/transactionEvaluator.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerMock/enableEpochsHandlerStub.go
  vm/systemSmartContracts/delegation.go
  vm/systemSmartContracts/delegationManager.go
  vm/systemSmartContracts/delegationManager_test.go
  vm/systemSmartContracts/delegation_test.go
  vm/systemSmartContracts/esdt.go
  vm/systemSmartContracts/esdt_test.go
  vm/systemSmartContracts/governance.go
  vm/systemSmartContracts/governance_test.go
  vm/systemSmartContracts/staking.go
  vm/systemSmartContracts/staking_test.go
  vm/systemSmartContracts/validator.go
  vm/systemSmartContracts/validator_test.go
Labels: ignore-for-release-notes

#5441 update mx chain communication go
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5446 Update mx-chain-communication-go tag
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5448 Copy fullArchiveP2P.toml
  scripts/testnet/include/config.sh
Labels: ignore-for-release-notes
