Repository multiversx/mx-chain-go, pull requests merged in 2023-04, with the labels that each got.

#5144 Update master rc/v1.5.0 2023.04.03
  cmd/node/config/enableEpochs.toml
  factory/api/apiResolverFactory_test.go
  factory/bootstrap/bootstrapComponentsHandler_test.go
  factory/bootstrap/bootstrapComponents_test.go
  factory/consensus/consensusComponentsHandler_test.go
  factory/consensus/consensusComponents_test.go
  factory/core/coreComponentsHandler_test.go
  factory/core/coreComponents_test.go
  factory/crypto/cryptoComponentsHandler_test.go
  factory/crypto/cryptoComponents_test.go
  factory/crypto/multiSignerContainer_test.go
  factory/data/dataComponentsHandler_test.go
  factory/data/dataComponents_test.go
  factory/network/networkComponentsHandler_test.go
  factory/network/networkComponents_test.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/processComponentsHandler_test.go
  factory/processing/processComponents_test.go
  factory/state/stateComponentsHandler_test.go
  factory/state/stateComponents_test.go
  factory/status/statusComponentsHandler_test.go
  factory/status/statusComponents_test.go
  factory/statusCore/statusCoreComponentsHandler_test.go
  factory/statusCore/statusCoreComponents_test.go
  genesis/process/genesisBlockCreator_test.go
  integrationTests/vm/txsFee/asyncESDT_test.go
  integrationTests/vm/txsFee/testdata/third/third.wasm
  state/accountsDB.go
  state/accountsDB_test.go
  state/dataTriesHolder.go
  state/export_test.go
  state/storagePruningManager/storagePruningManager.go
  trie/node.go
  trie/node_test.go
  trie/patriciaMerkleTrie.go
Labels: ignore-for-release-notes

#5140 Refactor usage of common interfaces in sovereign
  dataRetriever/requestHandlers/requestHandler.go
  dataRetriever/requestHandlers/sovereignRequestHandler.go
  dataRetriever/requestHandlers/sovereignRequestHandler_test.go
  epochStart/bootstrap/storageProcess.go
  epochStart/bootstrap/storageProcess_test.go
  factory/mock/blockTrackerStub.go
  factory/mock/extendedShardHeaderTrackerStub.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/processComponents.go
  genesis/process/disabled/requestHandler.go
  integrationTests/mock/blockTrackerStub.go
  node/mock/blockTrackerStub.go
  process/block/sovereignblock.go
  process/block/sovereignblock_test.go
  process/interface.go
  process/mock/blockTrackerMock.go
  process/track/baseBlockTrack.go
  process/track/sovereignChainBlockProcessor.go
  process/track/sovereignChainBlockProcessor_test.go
  process/track/sovereignChainShardBlockTrack_test.go
  testscommon/extendedShardHeaderRequestHandlerStub.go
  testscommon/requestHandlerStub.go
Labels: type:feature, ignore-for-release-notes

#5091 use normal PersisterTracker if processing mode is import db
  common/configParser.go
  epochStart/bootstrap/metaStorageHandler.go
  epochStart/bootstrap/metaStorageHandler_test.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/shardStorageHandler.go
  epochStart/bootstrap/shardStorageHandler_test.go
  factory/bootstrap/bootstrapComponents.go
  factory/data/dataComponents.go
  factory/processing/processComponents.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  node/nodeRunner.go
  storage/factory/pruningStorerFactory.go
  testscommon/components/components.go
Labels: area:storage, complexity:trivial, impact:low, interested:protocol, size:small, type:improvement

#5088 Bump library versions
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5068 create a new errChan struct that wraps an err chan
  common/channels.go
  common/channels_test.go
  common/errChan/errChan.go
  common/errChan/errChan_test.go
  common/interface.go
  debug/process/stateExport.go
  epochStart/metachain/systemSCs.go
  factory/processing/processComponents.go
  integrationTests/state/stateTrieClose/stateTrieClose_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/txsFee/asyncESDT_test.go
  node/node.go
  node/node_test.go
  node/trieIterators/delegatedListProcessor.go
  node/trieIterators/delegatedListProcessor_test.go
  node/trieIterators/directStakedListProcessor.go
  node/trieIterators/directStakedListProcessor_test.go
  node/trieIterators/stakeValuesProcessor.go
  node/trieIterators/stakeValuesProcessor_test.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/peer/process.go
  process/peer/process_test.go
  process/txsimulator/wrappedAccountsDB_test.go
  state/accountsDB.go
  state/accountsDB_test.go
  state/peerAccountsDB.go
  state/syncer/userAccountsSyncer.go
  trie/export_test.go
  trie/node_test.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
  trie/trieStorageManager.go
  trie/trieStorageManagerFactory_test.go
  trie/trieStorageManagerWithoutCheckpoints_test.go
  trie/trieStorageManagerWithoutSnapshot_test.go
  trie/trieStorageManager_test.go
  update/genesis/common.go
  update/genesis/export.go
  update/genesis/export_test.go
Labels: type:bug, area:trie, impact:medium, interested:protocol, size:medium, type:refactoring, complexity:medium

#5132 Unit tests for `node` package + small refactoring & fixes
  node/external/logs/logsFacade_test.go
  node/external/nodeApiResolver_test.go
  node/external/timemachine/fee/feeComputer_test.go
  node/metrics/metrics.go
  node/metrics/metrics_test.go
  node/mock/applicationRunningTrigger.go
  node/nodeRunner.go
  node/nodeRunner_test.go
  node/node_test.go
  node/trieIterators/delegatedListProcessor_test.go
  node/trieIterators/directStakedListProcessor_test.go
  testscommon/api/upgradeableHttpServerHandlerStub.go
Labels: impact:low, interested:protocol, size:small, type:refactoring, complexity:medium, area:testing

#5138 Fixes and unittests for factory api
  factory/api/apiResolverFactory.go
  factory/api/apiResolverFactory_test.go
  factory/api/export_test.go
  process/errors.go
  statusHandler/errors.go
  testscommon/factory/coreComponentsHolderStub.go
  update/errors.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5148 updated mx-chain-core-go to latest
  api/groups/transactionGroup_test.go
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5141 Added unit tests for `storage` package
  factory/bootstrap/bootstrapComponents.go
  storage/cache/cache_test.go
  storage/clean/oldDataCleanerProvider_test.go
  storage/clean/oldDatabaseCleaner_test.go
  storage/database/db_test.go
  storage/databaseremover/customDatabaseRemover_test.go
  storage/directoryhandler/directoryReader_test.go
  storage/disabled/errorDisabledPersister.go
  storage/disabled/errorDisabledPersister_test.go
  storage/disabled/persister_test.go
  storage/disabled/storer_test.go
  storage/factory/bootstrapDataProvider_test.go
  storage/factory/disabledPersister.go
  storage/factory/openStorage.go
  storage/factory/openStorage_test.go
  storage/factory/persisterFactory.go
  storage/factory/persisterFactory_test.go
  storage/factory/storageServiceFactory.go
  storage/factory/storageServiceFactory_test.go
  storage/latestData/latestDataProvider_test.go
  storage/pathmanager/pathManager_test.go
  storage/pruning/fullHistoryPruningStorer_test.go
  storage/pruning/fullHistoryTriePruningStorer.go
  storage/pruning/fullHistoryTriePruningStorer_test.go
  storage/pruning/persistersTracker_test.go
  storage/pruning/pruningStorer_test.go
  storage/pruning/triePersistersTracker_test.go
  storage/pruning/triePruningStorer_test.go
  storage/storageunit/storageunit_test.go
  storage/txcache/txcache_test.go
  testscommon/storage/storedDataFactoryStub.go
Labels: area:storage, complexity:trivial, impact:low, interested:protocol, size:small, type:refactoring, area:testing

#5164 wrap invalid guardian signature error
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
Labels: area:node-api, area:processing, impact:low, interested:protocol

#4927 chain parameters notifier
  common/chainparametersnotifier/chainParametersNotifier.go
  common/chainparametersnotifier/chainParametersNotifier_test.go
  common/constants.go
  common/forking/genericEpochNotifier_test.go
  common/interface.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/roundConsensus.go
  epochStart/bootstrap/disabled/disabledAntiFloodHandler.go
  epochStart/mock/coreComponentsMock.go
  factory/consensus/consensusComponents.go
  factory/consensus/consensusComponentsHandler.go
  factory/core/coreComponents.go
  factory/core/coreComponentsHandler.go
  factory/interface.go
  factory/mock/coreComponentsMock.go
  factory/mock/p2pAntifloodHandlerStub.go
  integrationTests/mock/coreComponentsStub.go
  integrationTests/mock/nilAntifloodHandler.go
  integrationTests/mock/p2pAntifloodHandlerStub.go
  integrationTests/testConsensusNode.go
  node/interface.go
  node/mock/factory/coreComponentsStub.go
  node/mock/p2pAntifloodHandlerStub.go
  node/node.go
  node/nodeHelper.go
  node/options.go
  node/options_test.go
  process/interface.go
  process/mock/coreComponentsMock.go
  process/mock/floodPreventerStub.go
  process/mock/p2pAntifloodHandlerStub.go
  process/throttle/antiflood/disabled/antiflood.go
  process/throttle/antiflood/disabled/antiflood_test.go
  process/throttle/antiflood/export_test.go
  process/throttle/antiflood/p2pAntiflood.go
  process/throttle/antiflood/p2pAntiflood_test.go
  sharding/chainParametersHolder.go
  sharding/chainParametersHolder_test.go
  sharding/errors.go
  sharding/interface.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
  testscommon/commonmocks/chainParametersNotifierStub.go
Labels: area:processing, complexity:medium

#4944 MX-13760: improve handlers sorting on epoch change subscriber
  epochStart/notifier/epochStartSubscriptionHandler.go
  epochStart/notifier/epochStartSubscriptionHandler_test.go
  state/syncer/userAccountsSyncer.go
Labels: area:processing, type:improvement

#5180 update go mod
  go.mod
  go.sum
  state/disabled/disabledTrackableDataTrie.go
  state/interface.go
  state/trackableDataTrie.go
  state/trackableDataTrie_test.go
  testscommon/trie/dataTrieTrackerStub.go
  testscommon/trie/trieStub.go
  trie/branchNode.go
  trie/extensionNode.go
  trie/interface.go
  trie/leafNode.go
  trie/node.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
Labels: ignore-for-release-notes

#5139 Coverage for: factory/bootstrap
  errors/errors.go
  factory/bootstrap/bootstrapComponents.go
  factory/bootstrap/bootstrapComponentsHandler_test.go
  factory/bootstrap/bootstrapComponents_test.go
  factory/bootstrap/shardingFactory.go
  factory/bootstrap/shardingFactory_test.go
  storage/errors.go
  storage/factory/openStorage.go
  storage/factory/openStorage_test.go
  storage/latestData/latestDataProvider.go
  storage/latestData/latestDataProvider_test.go
  testscommon/shuffleOutCloserStub.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5145 Coverage for: factory/data, factory/core, factory/crypto
  factory/bootstrap/bootstrapComponentsHandler_test.go
  factory/bootstrap/bootstrapComponents_test.go
  factory/consensus/consensusComponents_test.go
  factory/core/coreComponentsHandler_test.go
  factory/core/coreComponents_test.go
  factory/crypto/cryptoComponents.go
  factory/crypto/cryptoComponentsHandler.go
  factory/crypto/cryptoComponentsHandler_test.go
  factory/crypto/cryptoComponents_test.go
  factory/data/dataComponents.go
  factory/data/dataComponentsHandler.go
  factory/data/dataComponentsHandler_test.go
  factory/data/dataComponents_test.go
  factory/interface.go
  factory/mock/cryptoComponentsMock.go
  factory/mock/dataComponentsMock.go
  genesis/mock/dataComponentsMock.go
  genesis/process/argGenesisBlockCreator.go
  genesis/process/genesisBlockCreator.go
  integrationTests/mock/cryptoComponentsStub.go
  integrationTests/mock/dataComponentsStub.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  node/mock/factory/cryptoComponentsStub.go
  node/mock/factory/dataComponentsStub.go
  node/nodeTesting_test.go
  testscommon/components/default.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5152 Coverage for: factory/heartbeat, factory/network, factory/state
  factory/api/apiResolverFactory_test.go
  factory/constants.go
  factory/heartbeat/heartbeatV2Components.go
  factory/heartbeat/heartbeatV2ComponentsHandler.go
  factory/heartbeat/heartbeatV2ComponentsHandler_test.go
  factory/heartbeat/heartbeatV2Components_test.go
  factory/network/networkComponentsHandler_test.go
  factory/network/networkComponents_test.go
  factory/processing/processComponentsHandler_test.go
  factory/state/stateComponents.go
  factory/state/stateComponentsHandler_test.go
  factory/state/stateComponents_test.go
  factory/status/statusComponents_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/stateComponents/stateComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/mock/peerShardMapperStub.go
  integrationTests/mock/processComponentsStub.go
  node/nodeRunner.go
  testscommon/components/components.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5166 Coverage for: factory/status, factory/statusCore
  common/statistics/softwareVersion/factory/softwareVersionFactory.go
  errors/errors.go
  factory/interface.go
  factory/status/export_test.go
  factory/status/statusComponents.go
  factory/status/statusComponentsHandler.go
  factory/status/statusComponentsHandler_test.go
  factory/status/statusComponents_test.go
  factory/statusCore/statusCoreComponents.go
  factory/statusCore/statusCoreComponentsHandler.go
  factory/statusCore/statusCoreComponentsHandler_test.go
  factory/statusCore/statusCoreComponents_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  node/nodeRunner.go
  testscommon/components/components.go
  testscommon/generalConfig.go
  testscommon/networkStatisticsProviderStub.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5168 Coverage for: factory/consensus
  consensus/mock/mockTestInitializer.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/consensusCoreValidator_test.go
  factory/consensus/consensusComponents.go
  factory/consensus/consensusComponentsHandler_test.go
  factory/consensus/consensusComponents_test.go
  factory/mock/forkDetectorMock.go
  integrationTests/mock/cryptoComponentsStub.go
  integrationTests/mock/headersCacherStub.go
  integrationTests/mock/networkComponentsMock.go
  integrationTests/mock/processComponentsStub.go
  integrationTests/mock/statusComponentsStub.go
  integrationTests/testProcessorNode.go
  testscommon/components/default.go
  testscommon/consensus/signingHandlerStub.go
  testscommon/factory/statusCoreComponentsStub.go
  testscommon/roundHandlerMock.go
  testscommon/shardingMocks/nodesCoordinatorStub.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5175 Coverage for: api/gin + addressGroup
  api/errors/errors.go
  api/gin/common.go
  api/gin/common_test.go
  api/gin/httpServer.go
  api/gin/httpServer_test.go
  api/gin/interface.go
  api/gin/webServer.go
  api/gin/webServer_test.go
  api/gin/writers_test.go
  api/groups/addressGroup.go
  api/groups/addressGroupOptions_test.go
  api/groups/addressGroup_test.go
  api/mock/facadeStub.go
  testscommon/api/groupHandlerStub.go
  testscommon/api/serverStub.go
Labels: impact:low, interested:protocol, type:improvement, complexity:medium, area:testing

#5184 Coverage for: networkGroup, nodeGroup, proofGroup, transactionGroup, validatorGroup, vmValuesGroup
  api/groups/addressGroup_test.go
  api/groups/networkGroup_test.go
  api/groups/nodeGroup_test.go
  api/groups/proofGroup.go
  api/groups/proofGroup_test.go
  api/groups/transactionGroup_test.go
  api/groups/validatorGroup_test.go
  api/groups/vmValuesGroup_test.go
  api/mock/facadeStub.go
Labels: impact:low, interested:protocol, size:medium, type:improvement, area:testing
