Repository multiversx/mx-chain-go, pull requests merged in 2023-11, with the labels that each got.

#5686 reference core version with removed omitempty for guarded api field
  go.mod
  go.sum
Labels: area:node-api

#5703 Fixed return value in the `MaxGasPriceSetGuardian` method on the disabled fee handler
  epochStart/bootstrap/process_test.go
  genesis/process/disabled/feeHandler.go
  testscommon/cryptoMocks/signerStub.go
Labels: type:bug

#5713 Fix out of gas save key value
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  go.mod
  go.sum
  integrationTests/vm/txsFee/builtInFunctions_test.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerMock/enableEpochsHandlerStub.go
Labels: type:bug, area:processing, impact:low, interested:protocol, interested:validator, size:small, complexity:medium

#5724 Merge master rc v1.6.0 2023.11.20
  cmd/node/config/config.toml
  cmd/node/config/enableRounds.toml
  epochStart/bootstrap/process_test.go
  genesis/process/disabled/disabled_test.go
  genesis/process/disabled/feeHandler.go
  testscommon/cryptoMocks/signerStub.go
Labels: ignore-for-release-notes

#5707 Added new flag + readme for starting p2p prometheus dashboards
  README.md
  api/gin/common_test.go
  api/gin/webServer.go
  api/mock/facadeStub.go
  api/shared/interface.go
  cmd/node/CLI.md
  cmd/node/flags.go
  cmd/seednode/CLI.md
  cmd/seednode/api/api.go
  cmd/seednode/main.go
  config/config.go
  config/contextFlagsConfig.go
  facade/initial/initialNodeFacade.go
  facade/initial/initialNodeFacade_test.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  go.mod
  node/nodeRunner.go
Labels: area:node-api, area:libp2p, impact:low, interested:protocol, type:improvement, complexity:medium

#5714 New endpoint /node/waiting-epochs-left/:key
  api/errors/errors.go
  api/groups/nodeGroup.go
  api/groups/nodeGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  cmd/node/config/api.toml
  epochStart/bootstrap/disabled/disabledNodesCoordinator.go
  epochStart/bootstrap/syncValidatorStatus.go
  epochStart/mock/nodesSetupStub.go
  facade/initial/initialNodeFacade.go
  facade/initial/initialNodeFacade_test.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  factory/api/apiResolverFactory.go
  factory/bootstrap/shardingFactory.go
  integrationTests/interface.go
  integrationTests/mock/nodesSetupStub.go
  integrationTests/nodesCoordinatorFactory.go
  integrationTests/testConsensusNode.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNodeWithCoordinator.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/testProcessorNodeWithTestWebServer.go
  node/external/errors.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  process/mock/nodesSetupStub.go
  sharding/interface.go
  sharding/mock/enableEpochsHandlerMock.go
  sharding/mock/nodesSetupMock.go
  sharding/nodesCoordinator/errors.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorWithRater_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
  sharding/nodesCoordinator/interface.go
  sharding/nodesCoordinator/shardingArgs.go
  testscommon/nodesSetupMock.go
  testscommon/shardingMocks/nodesCoordinatorMock.go
  testscommon/shardingMocks/nodesCoordinatorStub.go
Labels: type:feature, area:node-api, impact:low, interested:explorer, interested:api-multiversx-com, interested:protocol, interested:validator, complexity:medium

#5735 Merge rc/v1.6.0 in rc/v1.7.0 23nov
  api/gin/webServer.go
  api/gin/webServer_test.go
  cmd/node/config/config.toml
  cmd/node/config/enableEpochs.toml
  cmd/node/config/enableRounds.toml
  cmd/node/config/fullArchiveP2P.toml
  cmd/node/config/p2p.toml
  cmd/seednode/config/p2p.toml
  common/constants.go
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/reflectcommon/structFieldsUpdate.go
  common/reflectcommon/structFieldsUpdate_test.go
  config/epochConfig.go
  config/tomlConfig_test.go
  epochStart/bootstrap/process_test.go
  genesis/process/disabled/disabled_test.go
  genesis/process/disabled/feeHandler.go
  go.mod
  go.sum
  integrationTests/p2p/networkSharding-hbv2/networkSharding_test.go
  integrationTests/testInitializer.go
  integrationTests/vm/txsFee/builtInFunctions_test.go
  integrationTests/vm/txsFee/multiShard/asyncCallWithChangeOwner_test.go
  integrationTests/vm/txsFee/testdata/changeOwner/contract.wasm
  integrationTests/vm/wasm/testdata/hello-v1/answer.c
  integrationTests/vm/wasm/testdata/hello-v1/answer.export
  integrationTests/vm/wasm/testdata/hello-v1/output/answer.wasm
  p2p/config/config.go
  p2p/constants.go
  process/errors.go
  process/smartContract/processorV2/process_test.go
  process/smartContract/processorV2/vmInputV2.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/components/components.go
  testscommon/cryptoMocks/signerStub.go
  testscommon/enableEpochsHandlerMock/enableEpochsHandlerStub.go
Labels: ignore-for-release-notes
