Repository multiversx/mx-chain-go, pull requests merged in 2023-02, with the labels that each got.

#4931 Integrated new VMs
  cmd/node/config/gasSchedules/gasScheduleV1.toml
  cmd/node/config/gasSchedules/gasScheduleV2.toml
  cmd/node/config/gasSchedules/gasScheduleV3.toml
  cmd/node/config/gasSchedules/gasScheduleV4.toml
  cmd/node/config/gasSchedules/gasScheduleV5.toml
  cmd/node/config/gasSchedules/gasScheduleV6.toml
  cmd/node/config/gasSchedules/gasScheduleV7.toml
  common/constants.go
  go.mod
  go.sum
  integrationTests/vm/txsFee/scCalls_test.go
  integrationTests/vm/wasm/wasmvm/scenariosConverter/scenariosConverter.go
  integrationTests/vm/wasm/wasmvm/scenariosConverter/scenariosConverterUtils.go
  process/factory/shard/vmContainerFactory.go
  process/factory/shard/vmContainerFactory_test.go
  process/smartContract/process_test.go
  vm/process/systemVM.go
  vm/process/systemVM_test.go
Labels: ignore-for-release-notes

#4939 Merge rc v1.5.0 2023.02.01
  .github/ISSUE_TEMPLATE/question.yml
  cmd/node/config/config.toml
  cmd/node/config/gasSchedules/gasScheduleV1.toml
  cmd/node/config/gasSchedules/gasScheduleV2.toml
  cmd/node/config/gasSchedules/gasScheduleV3.toml
  cmd/node/config/gasSchedules/gasScheduleV4.toml
  cmd/node/config/gasSchedules/gasScheduleV5.toml
  cmd/node/config/gasSchedules/gasScheduleV6.toml
  cmd/node/config/gasSchedules/gasScheduleV7.toml
  common/constants.go
  common/statistics/machine/netStatistics.go
  common/statistics/machine/netStatistics_test.go
  config/config.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/shardStorageHandler.go
  epochStart/bootstrap/shardStorageHandler_test.go
  epochStart/bootstrap/startInEpochScheduled.go
  epochStart/bootstrap/startInEpochScheduled_test.go
  epochStart/bootstrap/types/scheduledDataSyncerTypes.go
  examples/tokenKeys_test.go
  factory/heartbeat/heartbeatV2Components_test.go
  go.mod
  go.sum
  integrationTests/factory/bootstrapComponents/bootstrapComponents_test.go
  integrationTests/factory/componentsHelper.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/constants.go
  integrationTests/factory/coreComponents/coreComponents_test.go
  integrationTests/factory/cryptoComponents/cryptoComponents_test.go
  integrationTests/factory/dataComponents/dataComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/networkComponents/networkComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/stateComponents/stateComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/factory/statusCoreComponents/statusCoreComponents_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/esdt/process/esdtProcess_test.go
  integrationTests/vm/txsFee/scCalls_test.go
  integrationTests/vm/wasm/wasmvm/scenariosConverter/scenariosConverter.go
  integrationTests/vm/wasm/wasmvm/scenariosConverter/scenariosConverterUtils.go
  outport/notifier/eventNotifier.go
  outport/notifier/eventNotifier_test.go
  process/factory/shard/vmContainerFactory.go
  process/factory/shard/vmContainerFactory_test.go
  process/smartContract/process_test.go
  scripts/testnet/variables.sh
  testscommon/generalConfig.go
  testscommon/scheduledDataSyncer/dataSyncerStub.go
  vm/process/systemVM.go
  vm/process/systemVM_test.go
  vm/systemSmartContracts/delegation.go
  vm/systemSmartContracts/logs.go
  vm/systemSmartContracts/logs_test.go
Labels: ignore-for-release-notes

#4930 Extend transaction structure new fields
  go.mod
  go.sum
  node/external/timemachine/fee/feeComputer.go
  node/external/timemachine/fee/feeComputer_test.go
  node/external/timemachine/fee/interface.go
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/gasUsedAndFeeProcessor.go
  node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
  node/external/transactionAPI/interface.go
  testscommon/feeComputerStub.go
Labels: type:feature, area:node-api, impact:low, interested:api-elrond-com, size:medium, priority:2-I&!U, complexity:medium

#4941 Merge master 2023.02.01
  docker/termui/Dockerfile
Labels: ignore-for-release-notes

#4903 adjust operation modes flags
  cmd/node/flags.go
  common/operationmodes/operationmodes.go
  common/operationmodes/operationmodes_test.go
Labels: impact:low, size:small, ignore-for-release-notes

#4945 fix arbitrary failing test
  update/sync/syncTransactions_test.go
Labels: ignore-for-release-notes

#4929 Merge rc v1.4.0 into feat chain go sdk 02.02.2023
  cmd/node/config/gasSchedules/gasScheduleV1.toml
  cmd/node/config/gasSchedules/gasScheduleV2.toml
  cmd/node/config/gasSchedules/gasScheduleV3.toml
  cmd/node/config/gasSchedules/gasScheduleV4.toml
  cmd/node/config/gasSchedules/gasScheduleV5.toml
  cmd/node/config/gasSchedules/gasScheduleV6.toml
  cmd/node/config/gasSchedules/gasScheduleV7.toml
  cmd/node/flags.go
  common/constants.go
  common/operationmodes/operationmodes.go
  common/operationmodes/operationmodes_test.go
  common/statistics/machine/netStatistics.go
  common/statistics/machine/netStatistics_test.go
  docker/termui/Dockerfile
  go.mod
  go.sum
  integrationTests/vm/txsFee/scCalls_test.go
  integrationTests/vm/wasm/wasmvm/scenariosConverter/scenariosConverter.go
  integrationTests/vm/wasm/wasmvm/scenariosConverter/scenariosConverterUtils.go
  node/external/timemachine/fee/feeComputer.go
  node/external/timemachine/fee/feeComputer_test.go
  node/external/timemachine/fee/interface.go
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/gasUsedAndFeeProcessor.go
  node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
  node/external/transactionAPI/interface.go
  node/node.go
  process/block/metablock.go
  process/factory/shard/vmContainerFactory.go
  process/factory/shard/vmContainerFactory_test.go
  process/peer/process.go
  process/smartContract/process_test.go
  scripts/testnet/variables.sh
  testscommon/feeComputerStub.go
  update/sync/syncTransactions_test.go
  vm/process/systemVM.go
  vm/process/systemVM_test.go
Labels: type:feature, ignore-for-release-notes

#4951 add delay after UpdateRound in integration tests
  integrationTests/testInitializer.go
Labels: type:bug, complexity:trivial, impact:low, interested:protocol, size:small, area:integration-tests

#4952 Merge rc v1.4.0 into feat chain go sdk 03.02.2023
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/testConsensusNode.go
  integrationTests/testInitializer.go
Labels: type:feature, ignore-for-release-notes

#4953 remove StartInEpoch integration test db
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
Labels: ignore-for-release-notes

#4916 Node runner, configs and factories for sovereign chain
  cmd/sovereignnode/CLI.md
  cmd/sovereignnode/flags.go
  cmd/sovereignnode/main.go
  config/contextFlagsConfig.go
  node/errors.go
  node/nodeRunner.go
  node/sovereignNodeRunner.go
Labels: type:feature, ignore-for-release-notes

#4964 Fix inconsistent computation of "initiallyPaidFee" on concurrent requests
  node/external/timemachine/fee/feeComputer.go
  node/external/timemachine/fee/feeComputer_test.go
  node/external/timemachine/fee/memoryFootprint/memory_test.go
Labels: area:node-api

#4973 Merge rc v1.4.0 into chain go sdk 08.02.2023
  cmd/node/config/config.toml
  cmd/node/config/external.toml
  common/constants.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlockV2_test.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  go.mod
  go.sum
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/databaseWritterMock.go
  integrationTests/multiShard/block/interceptedBlocks/interceptedBlocks_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multisig/blsMultisig_bench_test.go
  integrationTests/multisig/blsMultisig_test.go
  integrationTests/resolvers/testInitializer.go
  integrationTests/singleShard/block/interceptedRequestHdr/interceptedRequestHdr_test.go
  integrationTests/testConsensusNode.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/external/timemachine/fee/feeComputer.go
  node/external/timemachine/fee/feeComputer_test.go
  node/external/timemachine/fee/memoryFootprint/memory_test.go
  node/metrics/metrics.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/metrics.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  testscommon/headerHandlerStub.go
  trie/branchNode.go
  trie/extensionNode.go
  trie/leafNode.go
  trie/node.go
  trie/node_test.go
Labels: type:feature, ignore-for-release-notes

#4974 Node setup and configs for sovereign chain
  factory/processing/processComponents.go
  process/peer/export_test.go
  process/peer/process.go
  process/peer/sovereignChainProcess.go
  process/peer/sovereignChainProcess_test.go
  scripts/testnet/include/build.sh
  scripts/testnet/include/validators.sh
  scripts/testnet/sovereignStart.sh
  scripts/testnet/variables.sh
Labels: type:feature, ignore-for-release-notes

#4982 Merge rc v1.4.0 to rc v1.5.0 2023.01.13
  cmd/node/config/config.toml
  cmd/node/config/external.toml
  cmd/node/flags.go
  common/constants.go
  common/operationmodes/operationmodes.go
  common/operationmodes/operationmodes_test.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  go.mod
  go.sum
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/databaseWritterMock.go
  integrationTests/multiShard/block/interceptedBlocks/interceptedBlocks_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multisig/blsMultisig_bench_test.go
  integrationTests/multisig/blsMultisig_test.go
  integrationTests/resolvers/testInitializer.go
  integrationTests/singleShard/block/interceptedRequestHdr/interceptedRequestHdr_test.go
  integrationTests/testConsensusNode.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/external/timemachine/fee/feeComputer.go
  node/external/timemachine/fee/feeComputer_test.go
  node/external/timemachine/fee/memoryFootprint/memory_test.go
  node/metrics/metrics.go
  node/node.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/metrics.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  testscommon/headerHandlerStub.go
  trie/branchNode.go
  trie/extensionNode.go
  trie/leafNode.go
  trie/node.go
  trie/node_test.go
  update/sync/syncTransactions_test.go
Labels: ignore-for-release-notes

#4990 Save `miniblocks` from prev header at epoch start
  epochStart/bootstrap/startInEpochScheduled.go
  epochStart/bootstrap/startInEpochScheduled_test.go
Labels: type:bug, area:storage, area:sync, impact:low, interested:protocol, size:small, priority:2-I&!U, complexity:medium

#5011 Merge 1.6.0 into feat sharded persister
  cmd/node/config/config.toml
  cmd/node/config/enableEpochs.toml
  cmd/node/config/external.toml
  cmd/node/flags.go
  common/constants.go
  common/operationmodes/operationmodes.go
  common/operationmodes/operationmodes_test.go
  consensus/mock/mockTestInitializer.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  go.mod
  go.sum
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/mock/databaseWritterMock.go
  integrationTests/multiShard/block/interceptedBlocks/interceptedBlocks_test.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/multisig/blsMultisig_bench_test.go
  integrationTests/multisig/blsMultisig_test.go
  integrationTests/resolvers/testInitializer.go
  integrationTests/singleShard/block/interceptedRequestHdr/interceptedRequestHdr_test.go
  integrationTests/testConsensusNode.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  node/external/timemachine/fee/feeComputer.go
  node/external/timemachine/fee/feeComputer_test.go
  node/external/timemachine/fee/memoryFootprint/memory_test.go
  node/metrics/metrics.go
  node/node.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/metrics.go
  process/block/shardblock.go
  process/block/shardblock_test.go
  testscommon/headerHandlerStub.go
  trie/branchNode.go
  trie/extensionNode.go
  trie/leafNode.go
  trie/node.go
  trie/node_test.go
  update/sync/syncTransactions_test.go
Labels: ignore-for-release-notes

#5015 Contributors badge
  README.md
Labels: ignore-for-release-notes

#4947 Fix storage pruning node type selection
  common/interface.go
  epochStart/bootstrap/common.go
  epochStart/bootstrap/metaStorageHandler.go
  epochStart/bootstrap/metaStorageHandler_test.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/process_test.go
  epochStart/bootstrap/shardStorageHandler.go
  epochStart/bootstrap/shardStorageHandler_test.go
  epochStart/errors.go
  epochStart/mock/cryptoComponentsMock.go
  factory/crypto/cryptoComponents.go
  factory/crypto/cryptoComponentsHandler.go
  factory/crypto/export_test.go
  factory/data/dataComponents.go
  factory/data/dataComponents_test.go
  factory/interface.go
  factory/mock/cryptoComponentsMock.go
  factory/processing/processComponents.go
  heartbeat/interface.go
  heartbeat/sender/heartbeatSenderFactory.go
  heartbeat/sender/heartbeatSenderFactory_test.go
  heartbeat/sender/peerAuthenticationSenderFactory_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/dataComponents/dataComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/stateComponents/stateComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/mock/cryptoComponentsStub.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  keysManagement/errors.go
  keysManagement/export_test.go
  keysManagement/interface.go
  keysManagement/keysHandler.go
  keysManagement/keysHandler_test.go
  keysManagement/managedPeersHolder.go
  keysManagement/managedPeersHolder_test.go
  node/mock/factory/cryptoComponentsStub.go
  node/nodeRunner.go
  process/interface.go
  process/mock/cryptoComponentsMock.go
  storage/clean/oldDataCleanerProvider.go
  storage/clean/oldDataCleanerProvider_test.go
  storage/errors.go
  storage/factory/pruningStorerFactory.go
  storage/interface.go
  testscommon/components/components.go
  testscommon/managedPeersHolderStub.go
Labels: type:bug, low prio, interested:protocol, complexity:medium, area:multikey

#4984 Trie mutex refactoring
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
Labels: type:bug, area:trie, impact:low, interested:protocol, size:small, complexity:medium

#4998 Bugfixing and stabilization for sovereign chain
  consensus/constants.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundBlockV2_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRoundV2.go
  consensus/spos/bls/subroundEndRoundV2_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignatureV2.go
  consensus/spos/bls/subroundSignatureV2_test.go
  consensus/spos/sposFactory/sposFactory.go
  consensus/spos/sposFactory/sposFactory_test.go
  errors/errors.go
  factory/consensus/consensusComponents.go
  factory/consensus/consensusComponentsHandler_test.go
  factory/consensus/consensusComponents_test.go
  go.mod
  go.sum
  integrationTests/consensus/consensus_test.go
  node/nodeRunner.go
  node/sovereignNodeRunner.go
  process/block/baseProcess.go
  process/block/interface.go
  process/block/sovereignblock.go
  process/common.go
  process/errors.go
  testscommon/components/components.go
Labels: type:feature, ignore-for-release-notes

#5021 Update rc v1.5.0 2023.02.23
  README.md
Labels: ignore-for-release-notes

#5016 Added complex scenario semi-integration test for guarded accounts feat
  integrationTests/vm/txsFee/guardAccount_test.go
Labels: impact:low, interested:protocol, size:small, complexity:medium, area:testing

#5029 Merge rc v1.6.0 into feat chain go sdk
  README.md
  cmd/node/config/config.toml
  cmd/node/config/enableEpochs.toml
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  common/enablers/epochFlags.go
  common/interface.go
  config/epochConfig.go
  config/tomlConfig_test.go
  epochStart/bootstrap/startInEpochScheduled.go
  epochStart/bootstrap/startInEpochScheduled_test.go
  go.mod
  go.sum
  integrationTests/testConsensusNode.go
  integrationTests/vm/testInitializer.go
  integrationTests/vm/txsFee/asyncCall_test.go
  integrationTests/vm/txsFee/testdata/asyncOnInit/asyncOnInit.wasm
  integrationTests/vm/txsFee/testdata/second/elrond.json
  integrationTests/vm/txsFee/utils/utils.go
  sharding/mock/enableEpochsHandlerMock.go
  testscommon/enableEpochsHandlerStub.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
Labels: type:feature, ignore-for-release-notes

#5018 Fix import db on rc v1.6.0
  dataRetriever/common.go
  dataRetriever/common_test.go
  dataRetriever/interface.go
  dataRetriever/mock/headerRequesterStub.go
  dataRetriever/mock/throttlerStub.go
  dataRetriever/requestHandlers/requesters/headerRequester.go
  dataRetriever/requestHandlers/requesters/headerRequester_test.go
  dataRetriever/resolvers/disabled/resolver.go
  dataRetriever/resolvers/headerResolver.go
  dataRetriever/resolvers/headerResolver_test.go
  dataRetriever/resolvers/miniblockResolver_test.go
  dataRetriever/resolvers/peerAuthenticationResolver_test.go
  dataRetriever/resolvers/transactionResolver_test.go
  dataRetriever/resolvers/trieNodeResolver_test.go
  dataRetriever/resolvers/validatorInfoResolver_test.go
  dataRetriever/storageRequesters/headerRequester.go
  factory/processing/processComponents.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  node/nodeDebugFactory/interceptedDebugHandler_test.go
  testscommon/components/default.go
  testscommon/dataRetriever/resolversContainerStub.go
Labels: type:bug, complexity:high, impact:low, interested:protocol, area:import-db

#5030 Aded consensus integration tests for consensus model v2
  integrationTests/consensus/consensusSigning_test.go
  integrationTests/consensus/consensus_test.go
Labels: ignore-for-release-notes

#5006 Fixed self-blacklisted event in consensus due to edge case when setting the epoch as proposer
  process/block/shardblock.go
  process/block/shardblock_test.go
Labels: type:bug, area:processing, impact:low, interested:protocol, complexity:medium

#5024 Remove `GetNumNodes` trie functionality
  common/interface.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  testscommon/trie/trieStub.go
  trie/branchNode.go
  trie/branchNode_test.go
  trie/extensionNode.go
  trie/extensionNode_test.go
  trie/interface.go
  trie/leafNode.go
  trie/patriciaMerkleTrie.go
  trie/patriciaMerkleTrie_test.go
Labels: area:trie, complexity:medium

#5038 Relayed guard accounts semi integration tests
  integrationTests/multiShard/relayedTx/common.go
  integrationTests/testInitializer.go
  integrationTests/vm/txsFee/asyncCall_test.go
  integrationTests/vm/txsFee/asyncESDT_test.go
  integrationTests/vm/txsFee/backwardsCompatibility_test.go
  integrationTests/vm/txsFee/builtInFunctions_test.go
  integrationTests/vm/txsFee/dns_test.go
  integrationTests/vm/txsFee/esdtLocalBurn_test.go
  integrationTests/vm/txsFee/esdtLocalMint_test.go
  integrationTests/vm/txsFee/esdt_test.go
  integrationTests/vm/txsFee/guardAccount_test.go
  integrationTests/vm/txsFee/moveBalance_test.go
  integrationTests/vm/txsFee/multiESDTTransfer_test.go
  integrationTests/vm/txsFee/multiShard/relayedBuiltInFunctions_test.go
  integrationTests/vm/txsFee/multiShard/relayedMoveBalance_test.go
  integrationTests/vm/txsFee/multiShard/relayedScDeploy_test.go
  integrationTests/vm/txsFee/multiShard/relayedTxScCalls_test.go
  integrationTests/vm/txsFee/relayedAsyncCall_test.go
  integrationTests/vm/txsFee/relayedAsyncESDT_test.go
  integrationTests/vm/txsFee/relayedBuiltInFunctions_test.go
  integrationTests/vm/txsFee/relayedDns_test.go
  integrationTests/vm/txsFee/relayedESDT_test.go
  integrationTests/vm/txsFee/relayedMoveBalance_test.go
  integrationTests/vm/txsFee/relayedScCalls_test.go
  integrationTests/vm/txsFee/relayedScDeploy_test.go
  integrationTests/vm/txsFee/scCalls_test.go
  integrationTests/vm/txsFee/scDeploy_test.go
  integrationTests/vm/txsFee/txCostEstimator_test.go
  integrationTests/vm/txsFee/utils/utils.go
  integrationTests/vm/txsFee/utils/utilsESDT.go
  integrationTests/vm/txsFee/validatorSC_test.go
Labels: impact:low, interested:protocol, size:small, area:testing
