Repository multiversx/mx-chain-go, pull requests merged in 2023-09, with the labels that each got.

#5555 Merge rc in feat exec 2
  epochStart/metachain/stakingDataProvider.go
  epochStart/metachain/systemSCs.go
  epochStart/metachain/systemSCs_test.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/intermediate/txExecutionProcessor.go
  genesis/process/metaGenesisBlockCreator.go
  go.mod
  go.sum
  integrationTests/multiShard/smartContract/scCallingSC_test.go
  integrationTests/vm/wasm/wasmvm/asyncMockContracts_test.go
  integrationTests/vm/wasm/wasmvm/mockContracts.go
  process/smartContract/scQueryService_test.go
Labels: ignore-for-release-notes

#5504 Mx 14448 sovereign managed runtype comp
  errors/errors.go
  factory/constants.go
  factory/interface.go
  factory/processing/processComponents.go
  factory/processing/processComponentsHandler.go
  factory/runType/runTypeComponents.go
  factory/runType/runTypeComponentsHandler.go
  factory/runType/runTypeComponentsHandler_test.go
  factory/runType/runTypeComponents_test.go
  factory/runType/sovereignRunTypeComponents.go
  factory/runType/sovereignRunTypeComponents_test.go
  factory/state/stateComponentsHandler.go
  factory/statusCore/statusCoreComponents.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock_test.go
  process/mock/statusCoreComponentsStub.go
  process/sync/storageBootstrap/shardBootstrapFactory_test.go
  process/sync/storageBootstrap/shardStorageBootstrapFactory_test.go
  statusHandler/persister/interface.go
  statusHandler/persister/persistentStatus.go
  statusHandler/persister/persistentStatus_test.go
  testscommon/components/components.go
  testscommon/factory/blockChainHookHandlerFactoryStub.go
  testscommon/factory/blockProcessorFactoryStub.go
  testscommon/factory/blockTrackerFactoryStub.go
  testscommon/factory/bootstrapperFromStorageFactoryStub.go
  testscommon/factory/epochStartBootstrapperFactoryStub.go
  testscommon/factory/forkDetectorFactoryStub.go
  testscommon/factory/headerValidatorFactoryStub.go
  testscommon/factory/requestHandlerFactoryStub.go
  testscommon/factory/scheduledTxsExecutionFactoryStub.go
  testscommon/factory/transactionCoordinatorFactoryStub.go
  testscommon/factory/validatorStatisticsProcessorFactoryStub.go
Labels: area:processing

#5521 GetActivationEpoch implementation + further refactor
  common/constants.go
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/syncValidatorStatus.go
  epochStart/metachain/epochStartData.go
  epochStart/metachain/epochStartData_test.go
  epochStart/metachain/rewards.go
  epochStart/metachain/rewardsCreatorProxy.go
  epochStart/metachain/rewardsCreatorProxy_test.go
  epochStart/metachain/rewardsV2.go
  epochStart/shardchain/trigger.go
  factory/processing/blockProcessorCreator.go
  node/external/blockAPI/internalBlock.go
  node/external/blockAPI/internalBlock_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  sharding/mock/enableEpochsHandlerMock.go
  sharding/nodesCoordinator/hashValidatorShuffler.go
  sharding/nodesCoordinator/hashValidatorShuffler_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
Labels: ignore-for-release-notes

#5574 Fixed heartbeat messages in multikey mode
  integrationTests/node/heartbeatV2/heartbeatV2_test.go
  integrationTests/testHeartbeatNode.go
  keysManagement/managedPeersHolder.go
  keysManagement/managedPeersHolder_test.go
  node/nodeRunner.go
  process/heartbeat/interceptedHeartbeat.go
Labels: type:bug, area:heartbeat, impact:high, interested:protocol, interested:validator, size:small, complexity:medium, area:multikey

#5597 Fixed managedPeersHolder for badly configured node
  keysManagement/managedPeersHolder.go
  keysManagement/managedPeersHolder_test.go
Labels: type:bug, complexity:trivial, impact:medium, interested:protocol, interested:validator, size:small, priority:1-I&U, area:multikey

#5587 Added p2p debugger setter
  cmd/seednode/main.go
  common/constants.go
  common/converters.go
  common/converters_test.go
  factory/network/networkComponents.go
  factory/status/export_test.go
  factory/status/statusComponentsHandler.go
  factory/status/statusComponentsHandler_test.go
  go.mod
  go.sum
  p2p/disabled/networkMessenger.go
  p2p/interface.go
  testscommon/p2pmocks/messengerStub.go
Labels: type:bug, area:libp2p, complexity:trivial, impact:low, interested:protocol
