Repository multiversx/mx-chain-go, pull requests merged in 2023-06, with the labels that each got.

#5294 Coverage for common package
  common/configParser_test.go
  common/converters_test.go
  common/enablers/enableEpochsHandler_test.go
  common/forking/gasSchedule_test.go
  common/holders/receiptsHolder_test.go
  common/holders/rootHashHolder_test.go
  common/logging/errorLogging_test.go
  common/pidQueue_test.go
  common/reflectcommon/structFieldsUpdate_test.go
  common/statistics/disabled/netStatistics_test.go
  common/statistics/machine/netStatistics_test.go
  common/statistics/resourceMonitor_test.go
  common/statistics/softwareVersion/factory/softwareVersionFactory.go
  common/statistics/softwareVersion/softwareVersion.go
  common/statistics/softwareVersion/softwareVersion_test.go
  common/statistics/softwareVersion/stableTagProvider_test.go
  common/trie_test.go
  common/validatorInfo/validatorInfoUtils.go
  common/validatorInfo/validatorInfoUtils_test.go
Labels: complexity:trivial, impact:low, interested:protocol, type:improvement, area:testing

#5301 Coverage for genesis package
  factory/processing/processComponents.go
  genesis/data/delegationData_test.go
  genesis/data/initialAccount_test.go
  genesis/parsing/accountsParser_test.go
  genesis/parsing/export_test.go
  genesis/process/argGenesisBlockCreator.go
  genesis/process/disabled/disabled_test.go
  genesis/process/disabled/messageSignVerifier_test.go
  genesis/process/genesisBlockCreator.go
  genesis/process/genesisBlockCreator_test.go
  genesis/process/intermediate/deployProcessor_test.go
  genesis/process/intermediate/txExecutionProcessor_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/testInitializer.go
Labels: complexity:trivial, impact:low, interested:protocol, type:improvement, area:testing

#5295 Refactor peer and user accounts
  epochStart/metachain/systemSCs.go
  epochStart/metachain/systemSCs_test.go
  process/mock/peerAccountHandlerMock.go
  process/peer/process.go
  process/peer/process_test.go
  process/scToProtocol/stakingToPeer.go
  process/scToProtocol/stakingToPeer_test.go
  state/baseAccount.go
  state/baseAccount_test.go
  state/disabled/disabledTrackableDataTrie.go
  state/disabled/disabledTrackableDataTrie_test.go
  state/export_test.go
  state/interface.go
  state/peerAccount.go
  state/peerAccount_test.go
  state/peerAccountsDB.go
  state/peerAccountsDB_test.go
  state/userAccount.go
  state/userAccount_test.go
  update/genesis/common.go
Labels: area:trie, impact:low, interested:protocol, size:medium, type:refactoring, complexity:medium

#5154 Sovereign block processing with shard headers notarization
  cmd/sovereignnode/go.mod
  cmd/sovereignnode/go.sum
  dataRetriever/requestHandlers/sovereignRequestHandler.go
  dataRetriever/unitType.go
  factory/processing/blockProcessorCreator.go
  factory/processing/blockProcessorCreator_test.go
  factory/processing/processComponents.go
  genesis/process/disabled/processedMiniBlocksTracker.go
  genesis/process/shardGenesisBlockCreator.go
  go.mod
  go.sum
  process/block/baseProcess.go
  process/block/displayBlock.go
  process/block/displayBlock_test.go
  process/block/export_test.go
  process/block/headerValidator.go
  process/block/interface.go
  process/block/metablock.go
  process/block/processedMb/processedMiniBlocks.go
  process/block/processedMb/processedMiniBlocks_test.go
  process/block/shardblock.go
  process/block/sovereignChainBlock.go
  process/block/sovereignChainBlock_test.go
  process/block/sovereignChainHeaderValidator.go
  process/block/sovereignChainHeaderValidator_test.go
  process/block/sovereignblock.go
  process/block/sovereignblock_test.go
  process/common.go
  process/coordinator/sovereignChainProcess.go
  process/coordinator/sovereignChainProcess_test.go
  process/errors.go
  process/interface.go
  process/sovereignConstants.go
  process/sync/baseSync.go
  process/sync/metablock.go
  process/sync/shardblock.go
  process/sync/sovereignChainBaseSync.go
  process/sync/sovereignChainShardBlock.go
  process/track/baseBlockTrack.go
  process/track/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
  process/track/sovereignChainBlockProcessor_test.go
  process/track/sovereignChainShardBlockTrack.go
  process/track/sovereignChainShardBlockTrack_test.go
  testscommon/extendedShardHeaderRequestHandlerStub.go
  testscommon/processedMiniBlocksTrackerStub.go
Labels: type:feature, ignore-for-release-notes

#5332 Full archive heartbeat sender + new data pools
  dataRetriever/dataPool/dataPool_test.go
  epochStart/bootstrap/process.go
  factory/heartbeat/heartbeatV2Components.go
  factory/heartbeat/heartbeatV2Components_test.go
  factory/interface.go
  factory/mock/networkComponentsMock.go
  factory/network/networkComponentsHandler.go
  heartbeat/sender/baseSender.go
  heartbeat/sender/baseSender_test.go
  heartbeat/sender/bootstrapSender.go
  heartbeat/sender/bootstrapSender_test.go
  heartbeat/sender/commonPeerAuthenticationSender.go
  heartbeat/sender/heartbeatSender.go
  heartbeat/sender/heartbeatSenderFactory.go
  heartbeat/sender/heartbeatSender_test.go
  heartbeat/sender/multikeyHeartbeatSender.go
  heartbeat/sender/multikeyHeartbeatSender_test.go
  heartbeat/sender/multikeyPeerAuthenticationSender.go
  heartbeat/sender/multikeyPeerAuthenticationSender_test.go
  heartbeat/sender/peerAuthenticationSender.go
  heartbeat/sender/peerAuthenticationSender_test.go
  heartbeat/sender/peerShardSender.go
  heartbeat/sender/peerShardSender_test.go
  heartbeat/sender/sender.go
  heartbeat/sender/sender_test.go
  integrationTests/mock/networkComponentsMock.go
  integrationTests/node/heartbeatV2/heartbeatV2_test.go
  integrationTests/p2p/networkSharding-hbv2/networkSharding_test.go
  integrationTests/testHeartbeatNode.go
  node/mock/factory/networkComponentsMock.go
  process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
Labels: area:processing, area:heartbeat, impact:medium, interested:protocol, type:improvement, complexity:medium

#5340 handle nodes config from storage
  sharding/nodesCoordinator/indexHashedNodesCoordinator.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
Labels: ignore-for-release-notes

#5361 Separate package for data trie tracker
  factory/processing/blockProcessorCreator_test.go
  genesis/process/genesisBlockCreator_test.go
  integrationTests/testInitializer.go
  node/node_test.go
  process/peer/process.go
  process/peer/process_test.go
  process/rewardTransaction/process_test.go
  process/scToProtocol/stakingToPeer_test.go
  process/sync/trieIterators/tokensSuppliesProcessor_test.go
  process/sync/trieIterators/trieAccountsIterator_test.go
  state/accounts/peerAccount.go
  state/accounts/peerAccount_test.go
  state/export_test.go
  state/factory/accountCreator.go
  state/interface.go
  state/journalEntries.go
  state/trackableDataTrie/export_test.go
  state/trackableDataTrie/trackableDataTrie.go
  state/trackableDataTrie/trackableDataTrie_test.go
  testscommon/state/accountWrapperMock.go
  update/genesis/common.go
  vm/systemSmartContracts/eei_test.go
  vm/systemSmartContracts/staking_test.go
Labels: ignore-for-release-notes

#5356 Managed peers monitor
  common/interface.go
  keysManagement/errors.go
  keysManagement/interface.go
  keysManagement/managedPeersMonitor.go
  keysManagement/managedPeersMonitor_test.go
Labels: impact:low, type:improvement, complexity:medium, area:multikey

#5357 New API endpoints for managed keys
  api/errors/errors.go
  api/groups/nodeGroup.go
  api/groups/nodeGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  cmd/node/config/api.toml
  common/interface.go
  errors/errors.go
  facade/initial/initialNodeFacade.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/nodeFacade.go
  factory/api/apiResolverFactory.go
  factory/api/apiResolverFactory_test.go
  factory/interface.go
  factory/status/statusComponents.go
  factory/status/statusComponentsHandler.go
  factory/status/statusComponentsHandler_test.go
  factory/status/statusComponents_test.go
  integrationTests/factory/consensusComponents/consensusComponents_test.go
  integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
  integrationTests/factory/processComponents/processComponents_test.go
  integrationTests/factory/statusComponents/statusComponents_test.go
  integrationTests/interface.go
  integrationTests/mock/statusComponentsStub.go
  integrationTests/realcomponents/processorRunner.go
  integrationTests/testProcessorNodeWithTestWebServer.go
  keysManagement/errors.go
  keysManagement/interface.go
  keysManagement/managedPeersMonitor.go
  keysManagement/managedPeersMonitor_test.go
  node/external/errors.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  node/nodeRunner.go
  testscommon/components/components.go
  testscommon/components/default.go
  testscommon/mainFactoryMocks/statusComponentsStub.go
  testscommon/managedPeersMonitorStub.go
Labels: area:node-api, impact:low, interested:protocol, type:improvement, complexity:medium, area:multikey

#5366 add test for stakingToValidatorStatistics
  epochStart/metachain/systemSCs.go
  epochStart/metachain/systemSCs_test.go
  errors/errors.go
Labels: ignore-for-release-notes

#5347 Update request-resolve mechanism for full archive network
  dataRetriever/factory/requestersContainer/args.go
  dataRetriever/factory/requestersContainer/baseRequestersContainerFactory.go
  dataRetriever/factory/requestersContainer/metaRequestersContainerFactory.go
  dataRetriever/factory/requestersContainer/metaRequestersContainerFactory_test.go
  dataRetriever/factory/requestersContainer/shardRequestersContainerFactory.go
  dataRetriever/factory/requestersContainer/shardRequestersContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/args.go
  dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go
  dataRetriever/interface.go
  dataRetriever/mock/messageHandlerStub.go
  dataRetriever/topicSender/baseTopicSender.go
  dataRetriever/topicSender/topicRequestSender.go
  dataRetriever/topicSender/topicRequestSender_test.go
  dataRetriever/topicSender/topicResolverSender.go
  dataRetriever/topicSender/topicResolverSender_test.go
  epochStart/bootstrap/process.go
  factory/disabled/preferredPeersHolder.go
  factory/interface.go
  factory/mock/networkComponentsMock.go
  factory/network/networkComponents.go
  factory/network/networkComponentsHandler.go
  factory/network/networkComponentsHandler_test.go
  factory/processing/processComponents.go
  factory/processing/processComponents_test.go
  integrationTests/consensus/consensusSigning_test.go
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/networkComponentsMock.go
  integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/node/heartbeatV2/heartbeatV2_test.go
  integrationTests/p2p/peersRating/peersRating_test.go
  integrationTests/singleShard/block/interceptedRequestHdr/interceptedRequestHdr_test.go
  integrationTests/singleShard/block/interceptedRequestTxBlockBody/interceptedRequestTxBlockBody_test.go
  integrationTests/singleShard/transaction/interceptedResolvedTx/interceptedResolvedTx_test.go
  integrationTests/singleShard/transaction/interceptedResolvedUnsignedTx/interceptedResolvedUnsignedTx_test.go
  integrationTests/state/stateTrieSync/stateTrieSync_test.go
  integrationTests/sync/edgeCases/edgeCases_test.go
  integrationTests/testConsensusNode.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  node/mock/factory/networkComponentsMock.go
  p2p/disabled/networkMessenger.go
  update/errors.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncRequestersContainerFactory.go
  update/factory/fullSyncResolversContainerFactory.go
Labels: area:processing, impact:medium, interested:protocol, type:improvement, complexity:medium

#5354 Update metrics for managed keys
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/bls/subroundStartRound_test.go
  factory/processing/blockProcessorCreator.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  outport/process/outportDataProvider.go
  process/block/argProcessor.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock.go
  process/block/metablock_test.go
  process/block/metrics.go
  process/block/metrics_test.go
  process/block/shardblock.go
  process/errors.go
  testscommon/shardingMocks/nodesCoordinatorStub.go
Labels: area:node-api, impact:low, interested:protocol, type:improvement, complexity:medium, area:multikey

#5369 Merge rc160 into feat multikey metrics 2023.06.22
  SECURITY.md
  cmd/node/config/enableEpochs.toml
  factory/processing/blockProcessorCreator.go
  factory/processing/txSimulatorProcessComponents.go
  genesis/process/shardGenesisBlockCreator.go
  go.mod
  go.sum
  integrationTests/singleShard/block/executingMiniblocks/executingMiniblocks_test.go
  integrationTests/testInitializer.go
  integrationTests/testProcessorNode.go
  integrationTests/vm/testInitializer.go
  integrationTests/vm/txsFee/relayedMoveBalance_test.go
  integrationTests/vm/wasm/utils.go
  integrationTests/vm/wasm/wasmvm/wasmVM_test.go
  process/transaction/export_test.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
  vm/systemSmartContracts/esdt.go
  vm/systemSmartContracts/esdt_test.go
Labels: ignore-for-release-notes

#5371 Fix managed peers holder initialization
  process/block/shardblock.go
Labels: ignore-for-release-notes

#5374 One peersRatingHandler for both networks
  api/groups/nodeGroup.go
  api/groups/nodeGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  dataRetriever/factory/requestersContainer/args.go
  dataRetriever/factory/requestersContainer/baseRequestersContainerFactory.go
  dataRetriever/factory/requestersContainer/metaRequestersContainerFactory.go
  dataRetriever/factory/requestersContainer/metaRequestersContainerFactory_test.go
  dataRetriever/factory/requestersContainer/shardRequestersContainerFactory.go
  dataRetriever/factory/requestersContainer/shardRequestersContainerFactory_test.go
  dataRetriever/topicSender/topicRequestSender.go
  dataRetriever/topicSender/topicRequestSender_test.go
  epochStart/bootstrap/process.go
  facade/initial/initialNodeFacade.go
  facade/initial/initialNodeFacade_test.go
  facade/interface.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  factory/disabled/peersRatingHandler.go
  factory/disabled/peersRatingMonitor.go
  factory/interface.go
  factory/mock/networkComponentsMock.go
  factory/network/networkComponents.go
  factory/network/networkComponentsHandler.go
  factory/network/networkComponentsHandler_test.go
  factory/processing/processComponents.go
  factory/processing/processComponents_test.go
  go.mod
  go.sum
  integrationTests/interface.go
  integrationTests/mock/networkComponentsMock.go
  integrationTests/multiShard/hardFork/hardFork_test.go
  integrationTests/p2p/peersRating/peersRating_test.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNode.go
  node/mock/factory/networkComponentsMock.go
  node/node.go
  p2p/interface.go
  testscommon/p2pmocks/peersRatingMonitorStub.go
  update/factory/exportHandlerFactory.go
  update/factory/fullSyncRequestersContainerFactory.go
Labels: ignore-for-release-notes

#5379 fix race in tests
  process/transaction/shardProcess_test.go
Labels: ignore-for-release-notes

#5387 Merge rc/v1.6.0 in feat/state refactor 30jun
  cmd/node/config/external.toml
  config/externalConfig.go
  factory/status/export_test.go
  factory/status/statusComponents.go
  factory/status/statusComponents_test.go
  outport/factory/hostDriverFactory.go
  outport/factory/hostDriverFactory_test.go
  outport/factory/outportFactory.go
  outport/factory/outportFactory_test.go
  testscommon/components/components.go
Labels: ignore-for-release-notes
