Repository multiversx/mx-chain-go, pull requests merged in 2024-02, with the labels that each got.

#5940 Fix scripts for local testnet in multikey mode
  scripts/testnet/include/config.sh
  scripts/testnet/include/observers.sh
  scripts/testnet/variables.sh
Labels: type:bug, complexity:trivial, impact:low, interested:protocol, area:multikey, area:testing

#5943 New endpoint /node/loaded-keys
  api/groups/nodeGroup.go
  api/groups/nodeGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  cmd/node/config/api.toml
  common/interface.go
  facade/initial/initialNodeFacade.go
  facade/initial/initialNodeFacade_test.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  factory/api/apiResolverFactory.go
  heartbeat/interface.go
  integrationTests/interface.go
  integrationTests/testProcessorNodeWithTestWebServer.go
  keysManagement/managedPeersHolder.go
  keysManagement/managedPeersHolder_test.go
  keysManagement/managedPeersMonitor.go
  keysManagement/managedPeersMonitor_test.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  testscommon/managedPeersHolderStub.go
  testscommon/managedPeersMonitorStub.go
Labels: type:feature, area:node-api, impact:low, interested:api-multiversx-com, interested:protocol, interested:validator, complexity:medium, area:multikey

#5899 Performance degradation for v1.6.15 fix
  cmd/node/config/config.toml
  config/config.go
  dataRetriever/factory/resolverscontainer/args.go
  dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go
  dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go
  dataRetriever/resolvers/trieNodeResolver.go
  epochStart/bootstrap/process.go
  factory/processing/processComponents.go
  integrationTests/testHeartbeatNode.go
  integrationTests/testProcessorNode.go
  testscommon/generalConfig.go
Labels: type:bug, area:sync, area:trie, impact:medium, interested:protocol, interested:validator, size:small, type:performance, complexity:medium

#5942 Removed unnecessary heartbeat components
  factory/heartbeat/heartbeatV2Components.go
  factory/heartbeat/heartbeatV2Components_test.go
  heartbeat/monitor/crossShardPeerTopicNotifier.go
  heartbeat/monitor/crossShardPeerTopicNotifier_test.go
  integrationTests/testHeartbeatNode.go
Labels: type:bug, area:libp2p, area:heartbeat, complexity:high, impact:medium, interested:protocol, size:small

#5964 Chain simulator processor tests
  integrationTests/testProcessorNode.go
  node/chainSimulator/process/errors.go
  node/chainSimulator/process/processor.go
  node/chainSimulator/process/processor_test.go
  testscommon/chainSimulator/nodeHandlerMock.go
  testscommon/headerHandlerStub.go
  testscommon/roundHandlerMock.go
  testscommon/shardingMocks/nodesCoordinatorStub.go
Labels: ignore-for-release-notes

#5965 Chain simulator test only processing node tests
  node/chainSimulator/components/testOnlyProcessingNode.go
  node/chainSimulator/components/testOnlyProcessingNode_test.go
  testscommon/state/userAccountStub.go
Labels: ignore-for-release-notes

#5974 Proper DelegationSmartContractFlag flag
  epochStart/metachain/legacySystemSCs.go
Labels: ignore-for-release-notes

#5979 Process proxy fix
  process/smartContract/processProxy/processProxy.go
  process/smartContract/processProxy/processProxy_test.go
  process/smartContract/processProxy/testProcessProxy.go
Labels: ignore-for-release-notes

#5971 More chain simulator tests
  node/chainSimulator/components/bootstrapComponents.go
  node/chainSimulator/components/bootstrapComponents_test.go
  node/chainSimulator/components/coreComponents.go
  node/chainSimulator/components/coreComponents_test.go
  node/chainSimulator/components/cryptoComponents.go
  node/chainSimulator/components/cryptoComponents_test.go
Labels: ignore-for-release-notes

#5992 Merge rc170 into feat staking v4 2024.02.23
  cmd/node/config/config.toml
  common/interface.go
  common/statistics/disabled/stateStatistics.go
  common/statistics/disabled/stateStatistics_test.go
  common/statistics/stateStatistics.go
  common/statistics/stateStatistics_test.go
  factory/bootstrap/bootstrapComponents.go
  factory/bootstrap/bootstrapComponents_test.go
  node/chainSimulator/components/bootstrapComponents.go
  node/chainSimulator/components/bootstrapComponents_test.go
  node/chainSimulator/components/coreComponents.go
  node/chainSimulator/components/coreComponents_test.go
  node/chainSimulator/components/cryptoComponents.go
  node/chainSimulator/components/cryptoComponents_test.go
  process/smartContract/scQueryService.go
  process/smartContract/scQueryServiceDispatcher.go
  process/smartContract/scQueryService_test.go
  state/accountsDB.go
  state/accountsDBApi.go
  state/accountsDBApi_test.go
  state/errors.go
  storage/interface.go
  storage/pruning/pruningStorer.go
  storage/pruning/triePruningStorer.go
  storage/pruning/triePruningStorer_test.go
  testscommon/stateStatisticsHandlerStub.go
  trie/node.go
Labels: ignore-for-release-notes

#5985 More chain simulator tests part 2
  factory/api/apiResolverFactory_test.go
  factory/processing/processComponents_test.go
  factory/state/stateComponentsHandler_test.go
  factory/state/stateComponents_test.go
  node/chainSimulator/components/dataComponents.go
  node/chainSimulator/components/dataComponents_test.go
  node/chainSimulator/components/instantBroadcastMessenger_test.go
  node/chainSimulator/components/manualRoundHandler_test.go
  node/chainSimulator/components/memoryComponents.go
  node/chainSimulator/components/memoryComponents_test.go
  node/chainSimulator/components/networkComponents.go
  node/chainSimulator/components/networkComponents_test.go
  node/chainSimulator/components/processComponents.go
  node/chainSimulator/components/processComponents_test.go
  testscommon/components/components.go
Labels: ignore-for-release-notes

#5990 More chain simulator tests part 3
  node/chainSimulator/components/api/fixedAPIInterface_test.go
  node/chainSimulator/components/api/freeAPIInterface_test.go
  node/chainSimulator/components/api/noApiInterface_test.go
  node/chainSimulator/components/closeHandler_test.go
  node/chainSimulator/components/stateComponents.go
  node/chainSimulator/components/stateComponents_test.go
  node/chainSimulator/components/statusComponents.go
  node/chainSimulator/components/statusComponents_test.go
  node/chainSimulator/components/statusCoreComponents.go
  node/chainSimulator/components/statusCoreComponents_test.go
  node/chainSimulator/components/storageService_test.go
  node/chainSimulator/facade_test.go
  testscommon/chainSimulator/chainSimulatorMock.go
  testscommon/generalConfig.go
Labels: ignore-for-release-notes
