Repository multiversx/mx-chain-go, pull requests merged in 2024-08, with the labels that each got.

#6380 Merge master into rc17next1 2024.08.08
  .github/workflows/build_and_test.yml
  .github/workflows/create_release.yml
  go.mod
  go.sum
Labels: ignore-for-release-notes

#5781 SubroundEndRound changes
  consensus/mock/sposWorkerMock.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/errors.go
  consensus/spos/export_test.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  dataRetriever/blockchain/baseBlockchain.go
  factory/interface.go
Labels: ignore-for-release-notes

#6387 fix gh action
  .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
Labels: github-workflow

#6390 Switch log level to trace for tractions.processTransaction log
  process/block/preprocess/transactionsV2.go
Labels: ignore-for-release-notes

#6382 Added fix for relayed move balance to non payables
  cmd/node/config/enableEpochs.toml
  common/constants.go
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  config/epochConfig.go
  config/tomlConfig_test.go
  integrationTests/chainSimulator/relayedTx/relayedTx_test.go
  integrationTests/chainSimulator/vm/esdtImprovements_test.go
  integrationTests/multiShard/relayedTx/common.go
  integrationTests/testProcessorNode.go
  node/metrics/metrics.go
  node/metrics/metrics_test.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
  statusHandler/statusMetricsProvider.go
  statusHandler/statusMetricsProvider_test.go
Labels: type:bug, area:processing, impact:medium, interested:protocol, complexity:medium

#6392 Delayed broadcaster mock
  consensus/broadcast/commonMessenger.go
  consensus/broadcast/delayedBroadcast.go
  consensus/broadcast/delayedBroadcast_test.go
  consensus/broadcast/errors.go
  consensus/broadcast/export.go
  consensus/broadcast/interface.go
  consensus/broadcast/metaChainMessenger.go
  consensus/broadcast/metaChainMessenger_test.go
  consensus/broadcast/shardChainMessenger.go
  consensus/broadcast/shardChainMessenger_test.go
  consensus/broadcast/shared/types.go
  consensus/mock/delayedBroadcasterMock.go
  consensus/spos/sposFactory/sposFactory.go
Labels: ignore-for-release-notes

#6397 Master into feat/mempool-plus-plus (2024-08=20)
  cmd/node/config/enableEpochs.toml
  common/constants.go
  common/enablers/enableEpochsHandler.go
  common/enablers/enableEpochsHandler_test.go
  config/epochConfig.go
  config/tomlConfig_test.go
  go.mod
  go.sum
  integrationTests/vm/wasm/wasmvm/mockcontracts/simpleChildSC.go
  integrationTests/vm/wasm/wasmvm/mockcontracts/simpleParentSC.go
Labels: ignore-for-release-notes

#6388 increase coverage for subroundStartRound
  consensus/broadcast/shardChainMessenger_test.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundStartRound_test.go
  testscommon/outport/outportStub.go
  testscommon/shardingMocks/nodesCoordinatorStub.go
Labels: ignore-for-release-notes

#5790 Gradual broadcast mechanism
  cmd/node/config/config.toml
  config/config.go
  config/tomlConfig_test.go
  consensus/broadcast/commonMessenger.go
  consensus/broadcast/delayedBroadcast.go
  consensus/broadcast/delayedBroadcast_test.go
  consensus/broadcast/interface.go
  consensus/broadcast/metaChainMessenger.go
  consensus/broadcast/shardChainMessenger.go
  consensus/broadcast/shardChainMessenger_test.go
  consensus/interface.go
  consensus/mock/broadcastMessangerMock.go
  consensus/mock/delayedBroadcasterMock.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/errors.go
  consensus/spos/sposFactory/sposFactory.go
  consensus/spos/sposFactory/sposFactory_test.go
  factory/consensus/consensusComponents.go
  integrationTests/consensus/consensusSigning_test.go
  integrationTests/consensus/consensus_test.go
  integrationTests/mock/blockProcessorMock.go
  integrationTests/testConsensusNode.go
  integrationTests/testProcessorNode.go
  node/chainSimulator/components/testOnlyProcessingNode.go
Labels: ignore-for-release-notes

#5855 Fixes after tests
  cmd/node/config/enableEpochs.toml
  consensus/mock/sposWorkerMock.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundStartRound.go
  consensus/spos/bls/subroundStartRound_test.go
  consensus/spos/consensusMessageValidator.go
  consensus/spos/errors.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  factory/interface.go
  factory/processing/processComponents.go
  integrationTests/state/stateTrie/stateTrie_test.go
  integrationTests/testProcessorNodeWithMultisigner.go
  integrationTests/vm/staking/componentsHolderCreator.go
  node/chainSimulator/components/testOnlyProcessingNode.go
  process/block/baseProcess.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/interceptedBlockHeader.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/metablock.go
  process/headerCheck/headerSignatureVerify.go
  process/headerCheck/headerSignatureVerify_test.go
  process/peer/process.go
Labels: ignore-for-release-notes
