Repository multiversx/mx-chain-go, pull requests merged in 2024-09, with the labels that each got.

#6426 fixed missing scrs when multiple inner tx fail with the same error, caused by hash collision
  integrationTests/chainSimulator/relayedTx/relayedTx_test.go
  process/transaction/export_test.go
  process/transaction/shardProcess.go
Labels: type:bug, area:processing, complexity:trivial, impact:low, interested:protocol

#6405 throttler-management
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundSignature.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/errors.go
  consensus/spos/sposFactory/sposFactory.go
  consensus/spos/sposFactory/sposFactory_test.go
  factory/consensus/consensusComponents.go
Labels: area:consensus, impact:low, interested:protocol, type:improvement, complexity:medium, area:multikey

#6403 Benchmark test
  consensus/spos/bls/benchmark_test.go
  consensus/spos/bls/blsWorker_test.go
Labels: ignore-for-release-notes

#6411 moving/removing consensus package mocks to testscommon
  consensus/broadcast/delayedBroadcast_test.go
  consensus/broadcast/metaChainMessenger_test.go
  consensus/broadcast/shardChainMessenger_test.go
  consensus/mock/alarmSchedulerStub.go
  consensus/mock/epochStartNotifierStub.go
  consensus/mock/forkDetectorMock.go
  consensus/mock/headerIntegrityVerifierStub.go
  consensus/mock/headersCacherStub.go
  consensus/spos/bls/benchmark_test.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/bls/subroundSignature_test.go
  consensus/spos/bls/subroundStartRound_test.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/consensusCore_test.go
  consensus/spos/consensusMessageValidator_test.go
  consensus/spos/sposFactory/sposFactory_test.go
  consensus/spos/subround_test.go
  consensus/spos/worker_test.go
  node/chainSimulator/components/coreComponents.go
  node/chainSimulator/components/instantBroadcastMessenger_test.go
  node/chainSimulator/process/processor_test.go
  sharding/chainParametersHolder_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinatorWithRater_test.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
  testscommon/bootstrapperStubs/bootstrapperStub.go
  testscommon/consensus/broadcastMessangerMock.go
  testscommon/consensus/chronologyHandlerMock.go
  testscommon/consensus/consensusDataContainerMock.go
  testscommon/consensus/consensusStateMock.go
  testscommon/consensus/delayedBroadcasterMock.go
  testscommon/consensus/equivalentMessagesDebuggerStub.go
  testscommon/consensus/hasherStub.go
  testscommon/consensus/mockTestInitializer.go
  testscommon/epochstartmock/epochStartNotifierStub.go
Labels: ignore-for-release-notes

#6415 increase coverage for nodesSetup
  sharding/errors.go
  sharding/mock/pubkeyConverterMock.go
  sharding/nodesCoordinator/common_test.go
  sharding/nodesSetup_test.go
  sharding/oneShardCoordinator_test.go
Labels: ignore-for-release-notes

#6401 Increase test coverage for metaChainMessenger and chronology.
  consensus/broadcast/export_test.go
  consensus/broadcast/metaChainMessenger_test.go
  consensus/chronology/chronology.go
  consensus/chronology/chronology_test.go
  consensus/chronology/export_test.go
  consensus/mock/contextMock.go
  consensus/mock/watchdogMock.go
Labels: ignore-for-release-notes

#6443 New tags
  go.mod
  go.sum
Labels: ignore-for-release-notes

#6454 Proper fix for fee/initially paid fee for relayed after fix
  node/external/transactionAPI/gasUsedAndFeeProcessor.go
  node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
  node/external/transactionAPI/testData/failedRelayedV1.json
  outport/process/transactionsfee/transactionsFeeProcessor.go
Labels: type:bug, area:node-api, area:proxy-api, complexity:trivial, impact:low, interested:protocol

#6424 benchmark_signature_verification
  consensus/spos/bls/benchmark_verify_signatures_test.go
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/blsSubroundsFactory_test.go
  consensus/spos/bls/blsWorker_test.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/sposFactory/sposFactory_test.go
  factory/consensus/consensusComponents.go
Labels: type:question

#6437 Broadcast header on subroundBlock, on the shard_meta topic
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundEndRound.go
Labels: area:consensus, impact:medium, interested:protocol, interested:validator, type:improvement, complexity:medium, ignore-for-release-notes

#6467 updated deps to tags
  go.mod
  go.sum
Labels: ignore-for-release-notes

#6457 equivalentProofsTopic + interceptor
  cmd/node/factory/interface.go
  common/constants.go
  consensus/interface.go
  consensus/spos/interface.go
  epochStart/bootstrap/disabled/disabledHeaderSigVerifier.go
  epochStart/bootstrap/disabled/disabledNodesCoordinator.go
  epochStart/bootstrap/process.go
  epochStart/bootstrap/storageProcess.go
  go.mod
  go.sum
  process/block/interceptedBlocks/errors.go
  process/block/interceptedBlocks/interceptedEquivalentProof.go
  process/block/interceptedBlocks/interceptedEquivalentProof_test.go
  process/errors.go
  process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
  process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
  process/headerCheck/headerSignatureVerify.go
  process/headerCheck/headerSignatureVerify_test.go
  process/interceptors/factory/interceptedEquivalentProofsFactory.go
  process/interceptors/factory/interceptedEquivalentProofsFactory_test.go
  process/interceptors/processor/equivalentProofsInterceptorProcessor.go
  process/interceptors/processor/equivalentProofsInterceptorProcessor_test.go
  process/interceptors/processor/interface.go
  process/interface.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator.go
  sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
  sharding/nodesCoordinator/interface.go
  testscommon/consensus/headerSigVerifierStub.go
  testscommon/processMocks/equivalentProofsPoolMock.go
  testscommon/shardingMocks/nodesCoordinatorMock.go
  testscommon/shardingMocks/nodesCoordinatorStub.go
Labels: area:consensus, impact:low, interested:protocol, type:improvement, complexity:medium

#6470 crypto ei signature hooks errors
  go.mod
  go.sum
Labels: ignore-for-release-notes

#6472 new vm go tag
  go.mod
  go.sum
Labels: ignore-for-release-notes

#6456 Equivalent proofs tracker
  consensus/broadcast/delayedBroadcast.go
  consensus/broadcast/delayedBroadcast_test.go
  consensus/interface.go
  consensus/message.go
  consensus/mock/sposWorkerMock.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundEndRound_test.go
  consensus/spos/consensusCore.go
  consensus/spos/consensusCoreValidator.go
  consensus/spos/consensusCoreValidator_test.go
  consensus/spos/consensusCore_test.go
  consensus/spos/debug/equivalentMessagesDebugger.go
  consensus/spos/debug/equivalentMessagesDebugger_test.go
  consensus/spos/errors.go
  consensus/spos/export_test.go
  consensus/spos/interface.go
  consensus/spos/worker.go
  consensus/spos/worker_test.go
  dataRetriever/blockchain/baseBlockchain.go
  dataRetriever/blockchain/baseBlockchain_test.go
  dataRetriever/dataPool/dataPool.go
  dataRetriever/dataPool/dataPool_test.go
  dataRetriever/dataPool/proofsCache/errors.go
  dataRetriever/dataPool/proofsCache/proofsCache.go
  dataRetriever/dataPool/proofsCache/proofsPool.go
  dataRetriever/dataPool/proofsCache/proofsPool_test.go
  dataRetriever/errors.go
  dataRetriever/factory/dataPoolFactory.go
  dataRetriever/interface.go
  factory/consensus/consensusComponents.go
  factory/consensus/consensusComponents_test.go
  factory/interface.go
  go.mod
  go.sum
  integrationTests/consensus/consensusSigning_test.go
  integrationTests/consensus/consensus_test.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/interceptedBlocks/interceptedBlockHeader_test.go
  process/block/metablock.go
  process/headerCheck/headerSignatureVerify.go
  process/headerCheck/headerSignatureVerify_test.go
  process/peer/process.go
  testscommon/chainHandlerMock.go
  testscommon/chainHandlerStub.go
  testscommon/consensus/consensusDataContainerMock.go
  testscommon/consensus/equivalentMessagesDebuggerStub.go
  testscommon/consensus/mockTestInitializer.go
  testscommon/dataRetriever/poolFactory.go
  testscommon/dataRetriever/poolsHolderMock.go
  testscommon/dataRetriever/poolsHolderStub.go
  testscommon/dataRetriever/proofsPoolMock.go
  testscommon/headerHandlerStub.go
Labels: type:feature, area:consensus, interested:protocol, complexity:medium

#6479 Register consensus received header handler
  consensus/spos/bls/blsSubroundsFactory.go
  consensus/spos/bls/export_test.go
  consensus/spos/bls/subroundBlock.go
  consensus/spos/bls/subroundBlock_test.go
  consensus/spos/bls/subroundEndRound.go
  consensus/spos/bls/subroundSignature.go
Labels: ignore-for-release-notes

#6492 Merge master into Spica
  .github/workflows/build_and_test.yml
  .github/workflows/create_release.yml
Labels: ignore-for-release-notes

#6489 upgrade wasmer executor version
  go.mod
  go.sum
Labels: ignore-for-release-notes
