Repository multiversx/mx-chain-go, pull requests merged in 2024-12, with the labels that each got.

#6639 RelayedV3 fixes
  common/common.go
  common/common_test.go
  factory/disabled/txCoordinator.go
  integrationTests/chainSimulator/relayedTx/relayedTx_test.go
  integrationTests/mock/transactionCoordinatorMock.go
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/node.go
  node/node_test.go
  outport/process/transactionsfee/transactionsFeeProcessor.go
  process/block/preprocess/gasComputation.go
  process/block/preprocess/gasComputation_test.go
  process/block/preprocess/transactionsV2.go
  process/block/preprocess/transactionsV2_test.go
  process/coordinator/process.go
  process/coordinator/process_test.go
  process/coordinator/transactionType.go
  process/coordinator/transactionType_test.go
  process/dataValidators/txValidator.go
  process/disabled/txTypeHandler.go
  process/economics/economicsData.go
  process/errors.go
  process/interceptors/factory/interceptedTxDataFactory.go
  process/interface.go
  process/mock/multipleShardsCoordinatorMock.go
  process/smartContract/process.go
  process/smartContract/process_test.go
  process/smartContract/processorV2/processV2.go
  process/smartContract/processorV2/process_test.go
  process/smartContract/processorV2/vmInputV2.go
  process/transaction/baseProcess.go
  process/transaction/export_test.go
  process/transaction/interceptedTransaction.go
  process/transaction/interceptedTransaction_test.go
  process/transaction/metaProcess.go
  process/transaction/metaProcess_test.go
  process/transaction/shardProcess.go
  process/transaction/shardProcess_test.go
  process/transactionEvaluator/transactionEvaluator.go
  process/transactionEvaluator/transactionEvaluator_test.go
  testscommon/scProcessorMock.go
  testscommon/transactionCoordinatorMock.go
  testscommon/txTypeHandlerMock.go
Labels: ignore-for-release-notes

#6649 use proper prevTxHash in case of relayed v1 and v2
  process/smartContract/processorV2/processV2.go
Labels: ignore-for-release-notes

#6647 Fix get non fungible tokens list
  api/groups/networkGroup.go
  node/node.go
  node/node_test.go
Labels: type:bug, area:node-api, area:proxy-api, impact:low, complexity:medium

#6653 Proper tag for storage go
  go.mod
  go.sum
Labels: ignore-for-release-notes

#6651 Fix transaction/pool endpoint issues
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/fieldsHandler.go
  node/external/transactionAPI/fieldsHandler_test.go
Labels: type:bug, area:node-api, complexity:trivial, impact:low, interested:api-multiversx-com, interested:protocol

#6513 Metachain notarizez based on equivalent proofs
  common/common.go
  consensus/spos/bls/v2/subroundBlock.go
  consensus/spos/bls/v2/subroundBlock_test.go
  factory/processing/processComponents.go
  go.mod
  go.sum
  integrationTests/consensus/consensusSigning_test.go
  integrationTests/consensus/consensus_test.go
  integrationTests/testNetwork.go
  integrationTests/testProcessorNode.go
  process/block/baseProcess.go
  process/block/headerValidator.go
  process/block/interceptedBlocks/common.go
  process/block/interceptedBlocks/common_test.go
  process/block/interceptedBlocks/interceptedMetaBlockHeader.go
  process/block/metablock.go
  process/block/shardblock.go
  process/errors.go
  process/interface.go
  process/track/argBlockProcessor.go
  process/track/argBlockTrack.go
  process/track/baseBlockTrack_test.go
  process/track/blockProcessor.go
  process/track/blockProcessor_test.go
  process/track/errors.go
  process/track/export_test.go
  process/track/metaBlockTrack.go
  process/track/shardBlockTrack.go
Labels: type:feature, area:processing, impact:medium, interested:protocol, complexity:medium

#6659 Fix header verification after equivalent proofs
  process/headerCheck/headerSignatureVerify.go
Labels: ignore-for-release-notes

#6677 Accept relayed tx v3 with sender account non-existent
  integrationTests/chainSimulator/relayedTx/relayedTx_test.go
  process/dataValidators/txValidator.go
  process/dataValidators/txValidator_test.go
Labels: area:processing, impact:low, interested:protocol, type:improvement, complexity:medium

#6678 Merge rc spica patch rv3 into feat rv3 2024.12.16
  common/reflectcommon/structFieldsUpdate.go
  common/reflectcommon/structFieldsUpdate_test.go
  testscommon/toml/config.go
  testscommon/toml/config.toml
  testscommon/toml/overwrite.toml
Labels: ignore-for-release-notes

#6682 Merge rc spica patch rv3 into feat rv3 2024.12.18
  storage/pruning/fullHistoryPruningStorer.go
  storage/pruning/fullHistoryPruningStorer_test.go
  storage/pruning/pruningStorer.go
Labels: ignore-for-release-notes

#6687 Fix receipts hash mismatch
  integrationTests/chainSimulator/relayedTx/relayedTx_test.go
  process/transaction/shardProcess.go
Labels: ignore-for-release-notes
