Repository multiversx/mx-chain-go, pull requests merged in 2025-06, with the labels that each got.

#6961 UnBondPeriodInEpochs to 3
  cmd/node/config/systemSmartContractsConfig.toml
Labels: ignore-for-release-notes

#7049 Merge master into rc barnard 2025.06.13
  go.mod
  go.sum
Labels: ignore-for-release-notes

#7028 Fix internal testing suite report storage
  .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
Labels: github_actions

#7068 Update Index of Reports
  .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
  .github/workflows/build_and_test_on_macos.yml
  .github/workflows/code-coverage.yml
Labels: github-workflow, github_actions

#7077 config update as per master
  cmd/node/config/config.toml
  cmd/node/config/ratings.toml
Labels: ignore-for-release-notes
