Repository multiversx/mx-chain-go, pull requests merged in 2025-09, with the labels that each got.

#7233 Merge master into rc supernova 2025.09.09
  factory/processing/txSimulatorProcessComponents.go
  integrationTests/chainSimulator/simulate/simulate_test.go
Labels: ignore-for-release-notes

#7236 Merge rc/teegarden in feat/state changes 9sep
  factory/processing/txSimulatorProcessComponents.go
  go.mod
  go.sum
  integrationTests/chainSimulator/simulate/simulate_test.go
Labels: ignore-for-release-notes

#7241 Supernova TxPool: GetVirtualNonce Endpoint
  api/errors/errors.go
  api/groups/transactionGroup.go
  api/groups/transactionGroup_test.go
  api/mock/facadeStub.go
  api/shared/interface.go
  cmd/node/config/api.toml
  common/dtos.go
  facade/errors.go
  facade/initial/initialNodeFacade.go
  facade/interface.go
  facade/mock/apiResolverStub.go
  facade/mock/nodeStub.go
  facade/nodeFacade.go
  facade/nodeFacade_test.go
  integrationTests/interface.go
  node/external/interface.go
  node/external/nodeApiResolver.go
  node/external/nodeApiResolver_test.go
  node/external/transactionAPI/apiTransactionProcessor.go
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/errors.go
  node/mock/apiTransactionHandlerStub.go
  process/block/preprocess/interfaces.go
  testscommon/pubkeyConverterMock.go
  testscommon/state/accountWrapperMock.go
  txcache/errors.go
  txcache/txCache.go
  txcache/txCache_test.go
Labels: interested:protocol, type:improvement

#7250 Extra tests for disabled relayed
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
  outport/process/transactionsfee/transactionsFeeProcessor_test.go
  process/coordinator/transactionType_test.go
  process/transaction/interceptedTransaction_test.go
Labels: ignore-for-release-notes

#7245 Supernova Txpool: Improvements-09-12
  txcache/accountBreadcrumbsValidator.go
  txcache/accountBreadcrumbsValidator_test.go
  txcache/blocks.go
  txcache/blocks_test.go
  txcache/diagnosis.go
  txcache/selectionTracker.go
  txcache/selectionTracker_test.go
  txcache/txCache.go
  txcache/virtualSessionComputer.go
  txcache/virtualSessionComputer_test.go
  txcache/virtualSessionProvider.go
Labels: interested:protocol, type:improvement

#7253 Supernova TxPool: Improvements-09-15
  dataRetriever/txpool/shardedTxPool_test.go
  txcache/accountBreadcrumb.go
  txcache/accountBreadcrumb_test.go
  txcache/accountBreadcrumbsValidator.go
  txcache/accountBreadcrumbsValidator_test.go
  txcache/errors.go
  txcache/selectionTracker.go
  txcache/selectionTracker_test.go
  txcache/virtualAccountBalance.go
  txcache/virtualAccountBalance_test.go
  txcache/virtualAccountRecord.go
  txcache/virtualAccountRecord_test.go
  txcache/virtualSelectionSession.go
  txcache/virtualSessionComputer.go
  txcache/virtualSessionComputer_test.go
Labels: interested:protocol, type:improvement

#7255 Teegarden into txpool-ci (2025-09-16)
  node/external/transactionAPI/apiTransactionProcessor_test.go
  node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
  outport/process/transactionsfee/transactionsFeeProcessor_test.go
  process/coordinator/transactionType_test.go
  process/transaction/interceptedTransaction_test.go
Labels: ignore-for-release-notes

#7263 fix executionResultsVerifier_test and improve coverage on process/common.go
  process/block/executionResultsVerifier_test.go
  process/common_test.go
Labels: ignore-for-release-notes

#7261 Supernova TxPool: Improvements-16-09
  txcache/accountBreadcrumb.go
  txcache/accountBreadcrumb_test.go
  txcache/accountBreadcrumbsValidator.go
  txcache/accountBreadcrumbsValidator_test.go
  txcache/selection.go
  txcache/selection_test.go
  txcache/trackedBlock.go
  txcache/trackedBlock_test.go
  txcache/transactionsHeapItem_test.go
  txcache/virtualAccountBalance.go
  txcache/virtualAccountRecord.go
  txcache/virtualAccountRecord_test.go
  txcache/virtualSelectionSession.go
  txcache/virtualSelectionSession_test.go
  txcache/virtualSessionComputer.go
  txcache/virtualSessionComputer_test.go
  txcache/wrappedTransaction.go
Labels: interested:protocol, type:improvement

#7264 Supernova TxPool: Fixed Failing Integration Test
  integrationTests/testProcessorNode.go
  integrationTests/testProcessorNodeWithTestWebServer.go
Labels: type:bug, interested:protocol

#7267 Create block proposal shard coverage
  factory/processing/blockProcessorCreator.go
  integrationTests/testFullNode.go
  integrationTests/testProcessorNode.go
  integrationTests/testSyncNode.go
  integrationTests/vm/staking/metaBlockProcessorCreator.go
  process/block/argProcessor.go
  process/block/baseProcess.go
  process/block/baseProcess_test.go
  process/block/export_test.go
  process/block/metablock_test.go
  process/block/shardblockProposal.go
  process/block/shardblockProposal_test.go
  process/errors.go
  process/mock/blockTrackerMock.go
  testscommon/headerHandlerStub.go
  testscommon/processMocks/executionResultsVerifierMock.go
  testscommon/processMocks/inclusionEstimatorMock.go
  testscommon/processMocks/missingDataResolverMock.go
Labels: impact:low, interested:protocol, size:medium, type:improvement, area:testing

#7280 Supernova TxPool Part2: Optimize the check for a tracked transaction
  txcache/autoClean.go
  txcache/errors.go
  txcache/eviction.go
  txcache/selectionTracker.go
  txcache/selectionTracker_test.go
  txcache/transactionsTracker.go
  txcache/transactionsTracker_test.go
  txcache/txByHashMap.go
  txcache/txByHashMap_test.go
  txcache/txCache.go
Labels: interested:protocol, type:improvement

#7278 Supernova TxPool Part2: Check if a transaction is still tracked
  txcache/autoClean.go
  txcache/eviction.go
  txcache/interface.go
  txcache/selectionTracker.go
  txcache/testutils_test.go
  txcache/transactionsTracker.go
  txcache/transactionsTracker_test.go
  txcache/txByHashMap.go
  txcache/txByHashMap_test.go
  txcache/txCache.go
Labels: interested:protocol, type:improvement

#7284 Supernova TxPool Part2: Check Tracked Txs Fixes
  txcache/autoClean.go
  txcache/eviction.go
  txcache/interface.go
  txcache/selectionTracker.go
  txcache/transactionsTracker.go
  txcache/transactionsTracker_test.go
  txcache/txByHashMap.go
  txcache/txByHashMap_test.go
  txcache/txCache.go
Labels: interested:protocol, type:improvement
